### ISSUE TITLE
TypeError: Cannot read property 'pipes' of undefined [on master]

### ISSUE THREAD

**Issue by imatlopez** [mscdex/ssh2#1013]
I am using a customized VS Code SFTP extension which uses the latest code from this package (pulling from master). I seem to be having issues with the stream closing on me and piping not working.

The code in question looks like this:

```ts
  function _put(
    input: NodeJS.ReadableStream,
    path,
    option?: {
      flags?: string;
      encoding?: string;
      mode?: number;
      autoClose?: boolean;
      handle?: FileHandle;
    }
  ): Promise<void> {
    return new Promise<void>((resolve, reject) => {
      const writer: NodeJS.WritableStream = this.sftp.createWriteStream(
        path,
        option
      );
      writer.once("error", reject).once("finish", resolve); // transffered

      input.once("error", (err) => {
        reject(err);
        writer.end();
      });
      input.pipe(writer);
    });
  }
```

<details>
<summary>Logs from extension</summary>
<p>

```cs
[05-24 11:29:05] [debug] Custom crypto binding not available
[05-24 11:29:05] [debug] Client: Trying sftp.myserver.com on port 2222 ...
[05-24 11:29:05] [debug] Local ident: 'SSH-2.0-ssh2js1.0.0-beta.0'
[05-24 11:29:06] [debug] Socket connected
[05-24 11:29:06] [debug] Remote ident: 'SSH-2.0-OpenSSH_6.2'
[05-24 11:29:06] [debug] Outbound: Sending KEXINIT
[05-24 11:29:06] [debug] Inbound: Handshake in progress
[05-24 11:29:06] [debug] Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
[05-24 11:29:06] [debug] Handshake: (remote) KEX method: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
[05-24 11:29:06] [debug] Handshake: KEX algorithm: ecdh-sha2-nistp256
[05-24 11:29:06] [debug] Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
[05-24 11:29:06] [debug] Handshake: (remote) Host key format: ssh-rsa
[05-24 11:29:06] [debug] Handshake: Host key format: ssh-rsa
[05-24 11:29:06] [debug] Handshake: (local) C->S cipher: aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
[05-24 11:29:06] [debug] Handshake: (remote) C->S cipher: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
[05-24 11:29:06] [debug] Handshake: C->S Cipher: aes128-gcm@openssh.com
[05-24 11:29:06] [debug] Handshake: (local) S->C cipher: aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
[05-24 11:29:06] [debug] Handshake: (remote) S->C cipher: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
[05-24 11:29:06] [debug] Handshake: S->C cipher: aes128-gcm@openssh.com
[05-24 11:29:06] [debug] Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[05-24 11:29:06] [debug] Handshake: (remote) C->S MAC: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
[05-24 11:29:06] [debug] Handshake: C->S MAC: <implicit>
[05-24 11:29:06] [debug] Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[05-24 11:29:06] [debug] Handshake: (remote) S->C MAC: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
[05-24 11:29:06] [debug] Handshake: S->C MAC: <implicit>
[05-24 11:29:06] [debug] Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
[05-24 11:29:06] [debug] Handshake: (remote) C->S compression: none,zlib@openssh.com
[05-24 11:29:06] [debug] Handshake: C->S compression: none
[05-24 11:29:06] [debug] Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
[05-24 11:29:06] [debug] Handshake: (remote) S->C compression: none,zlib@openssh.com
[05-24 11:29:06] [debug] Handshake: S->C compression: none
[05-24 11:29:06] [debug] Outbound: Sending KEXECDH_INIT
[05-24 11:29:06] [debug] Received DH Reply
[05-24 11:29:06] [debug] Host accepted by default (no verification)
[05-24 11:29:06] [debug] Host accepted (verified)
[05-24 11:29:06] [debug] Inbound: NEWKEYS
[05-24 11:29:06] [debug] Verifying signature ...
[05-24 11:29:06] [debug] Verified signature
[05-24 11:29:06] [debug] Outbound: Sending NEWKEYS
[05-24 11:29:06] [debug] Handshake completed
[05-24 11:29:06] [debug] Outbound: Sending SERVICE_REQUEST (ssh-userauth)
[05-24 11:29:06] [debug] Inbound: Received SERVICE_ACCEPT (ssh-userauth)
[05-24 11:29:06] [debug] Outbound: Sending USERAUTH_REQUEST (none)
[05-24 11:29:07] [debug] Inbound: Received USERAUTH_FAILURE (publickey)
[05-24 11:29:07] [debug] Client: none auth failed
[05-24 11:29:07] [debug] Outbound: Sending USERAUTH_REQUEST (publickey -- check)
[05-24 11:29:07] [debug] Inbound: Received USERAUTH_PK_OK
[05-24 11:29:07] [debug] Outbound: Sending USERAUTH_REQUEST (publickey)
[05-24 11:29:07] [debug] Inbound: Received USERAUTH_SUCCESS
[05-24 11:29:07] [debug] Outbound: Sending CHANNEL_OPEN (r:0, session)
[05-24 11:29:07] [debug] Inbound: CHANNEL_OPEN_CONFIRMATION (r:0, s:0)
[05-24 11:29:07] [debug] Outbound: Sending CHANNEL_REQUEST (r:0, subsystem: sftp)
[05-24 11:29:07] [debug] Inbound: CHANNEL_WINDOW_ADJUST (r:0, 2097152)
[05-24 11:29:07] [debug] Inbound: CHANNEL_SUCCESS (r:0)
[05-24 11:29:07] [debug] Outbound: Sending CHANNEL_DATA (r:0, 9)
[05-24 11:29:07] [debug] Inbound: CHANNEL_DATA (r:0, 128)
[05-24 11:29:07] [debug] SFTP: Inbound: Received VERSION (v3, exts:posix-rename@openssh.com,statvfs@openssh.com,fstatvfs@openssh.com,hardlink@openssh.com)
[05-24 11:29:07] [debug] Outbound: Sending CHANNEL_DATA (r:0, 78)
[05-24 11:29:07] [debug] SFTP: Outbound: Buffered MKDIR
[05-24 11:29:07] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[05-24 11:29:07] [debug] SFTP: Inbound: Received STATUS (id:0, 4, "Failure")
[05-24 11:29:07] [debug] Outbound: Sending CHANNEL_DATA (r:0, 74)
[05-24 11:29:07] [debug] SFTP: Outbound: Buffered LSTAT
[05-24 11:29:07] [debug] Inbound: CHANNEL_DATA (r:0, 41)
[05-24 11:29:07] [debug] SFTP: Inbound: Received ATTRS (id:1)
[05-24 11:29:07] [debug] Outbound: Sending CHANNEL_DATA (r:0, 98)
[05-24 11:29:07] [debug] SFTP: Outbound: Buffered OPEN
[05-24 11:29:07] [debug] Inbound: CHANNEL_DATA (r:0, 17)
[05-24 11:29:07] [debug] SFTP: Inbound: Received HANDLE (id:2)
[05-24 11:29:07] [debug] Outbound: Sending CHANNEL_DATA (r:0, 17)
[05-24 11:29:07] [debug] SFTP: Outbound: Buffered FSTAT
[05-24 11:29:08] [debug] Inbound: CHANNEL_DATA (r:0, 41)
[05-24 11:29:08] [debug] SFTP: Inbound: Received ATTRS (id:3)
[05-24 11:29:08] [debug] Outbound: Sending CHANNEL_DATA (r:0, 25)
[05-24 11:29:08] [debug] SFTP: Outbound: Buffered FSETSTAT
[05-24 11:29:08] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[05-24 11:29:08] [debug] SFTP: Inbound: Received STATUS (id:4, 0, "Success")
[05-24 11:29:08] [debug] Outbound: Sending CHANNEL_DATA (r:0, 17)
[05-24 11:29:08] [debug] SFTP: Outbound: Buffered CLOSE
[05-24 11:29:08] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[05-24 11:29:08] [debug] SFTP: Inbound: Received STATUS (id:5, 0, "Success")
[05-24 11:29:08] [error] TypeError: Cannot read property 'pipes' of undefined
	at F.Readable.pipe (internal/streams/readable.js:649:13)
	at /root/.vscode-server/extensions/imatlopez.sftp-1.0.8/dist/extension.js:2:313977
	at new Promise (<anonymous>)
	at o._put (/root/.vscode-server/extensions/imatlopez.sftp-1.0.8/dist/extension.js:2:313842)
	at o.put (/root/.vscode-server/extensions/imatlopez.sftp-1.0.8/dist/extension.js:2:312603)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async t.default._transferFile (/root/.vscode-server/extensions/imatlopez.sftp-1.0.8/dist/extension.js:2:326262)
	at async t.default.run (/root/.vscode-server/extensions/imatlopez.sftp-1.0.8/dist/extension.js:2:325502)
	at async t.default._runTask (/root/.vscode-server/extensions/imatlopez.sftp-1.0.8/dist/extension.js:2:324492) when local ➞ remote /workspace/integration_test/testFromJson.py
[05-24 11:29:09] [info] [file-save] /workspace/integration_test/testFromJson.py
[05-24 11:29:09] [trace] handle upload file for /workspace/integration_test/testFromJson.py
[05-24 11:29:09] [debug] Outbound: Sending CHANNEL_DATA (r:0, 78)
[05-24 11:29:09] [debug] SFTP: Outbound: Buffered MKDIR
[05-24 11:29:09] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[05-24 11:29:09] [debug] SFTP: Inbound: Received STATUS (id:6, 4, "Failure")
[05-24 11:29:09] [debug] Outbound: Sending CHANNEL_DATA (r:0, 74)
[05-24 11:29:09] [debug] SFTP: Outbound: Buffered LSTAT
[05-24 11:29:09] [debug] Inbound: CHANNEL_DATA (r:0, 41)
[05-24 11:29:09] [debug] SFTP: Inbound: Received ATTRS (id:7)
[05-24 11:29:09] [debug] Outbound: Sending CHANNEL_DATA (r:0, 98)
[05-24 11:29:09] [debug] SFTP: Outbound: Buffered OPEN
[05-24 11:29:09] [debug] Inbound: CHANNEL_DATA (r:0, 17)
[05-24 11:29:09] [debug] SFTP: Inbound: Received HANDLE (id:8)
[05-24 11:29:09] [debug] Outbound: Sending CHANNEL_DATA (r:0, 17)
[05-24 11:29:09] [debug] SFTP: Outbound: Buffered FSTAT
[05-24 11:29:09] [debug] Inbound: CHANNEL_DATA (r:0, 41)
[05-24 11:29:09] [debug] SFTP: Inbound: Received ATTRS (id:9)
[05-24 11:29:09] [debug] Outbound: Sending CHANNEL_DATA (r:0, 25)
[05-24 11:29:09] [debug] SFTP: Outbound: Buffered FSETSTAT
[05-24 11:29:09] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[05-24 11:29:09] [debug] SFTP: Inbound: Received STATUS (id:10, 0, "Success")
[05-24 11:29:09] [debug] Outbound: Sending CHANNEL_DATA (r:0, 17)
[05-24 11:29:09] [debug] SFTP: Outbound: Buffered CLOSE
[05-24 11:29:10] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[05-24 11:29:10] [debug] SFTP: Inbound: Received STATUS (id:11, 0, "Success")
[05-24 11:29:10] [error] TypeError: Cannot read property 'pipes' of undefined
	at F.Readable.pipe (internal/streams/readable.js:649:13)
	at /root/.vscode-server/extensions/imatlopez.sftp-1.0.8/dist/extension.js:2:313977
	at new Promise (<anonymous>)
	at o._put (/root/.vscode-server/extensions/imatlopez.sftp-1.0.8/dist/extension.js:2:313842)
	at o.put (/root/.vscode-server/extensions/imatlopez.sftp-1.0.8/dist/extension.js:2:312603)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async t.default._transferFile (/root/.vscode-server/extensions/imatlopez.sftp-1.0.8/dist/extension.js:2:326262)
	at async t.default.run (/root/.vscode-server/extensions/imatlopez.sftp-1.0.8/dist/extension.js:2:325502)
	at async t.default._runTask (/root/.vscode-server/extensions/imatlopez.sftp-1.0.8/dist/extension.js:2:324492) when local ➞ remote /workspace/integration_test/testFromJson.py
[05-24 11:29:37] [debug] Outbound: Sending ping (GLOBAL_REQUEST: keepalive@openssh.com)
[05-24 11:29:37] [debug] Inbound: Received REQUEST_FAILURE
[05-24 11:30:07] [debug] Outbound: Sending ping (GLOBAL_REQUEST: keepalive@openssh.com)
[05-24 11:30:07] [debug] Inbound: Received REQUEST_FAILURE
```

</p>
</details>

**Comment by mscdex** [comment]
What is `input` exactly? The pipes error is coming from node core and would only happen if the stream was either malformed or didn't have a `Readable` part to it (e.g. `Readable`, `Transform`, or `Duplex`).

**Comment by imatlopez** [comment]
so from `at async t.default._transferFile (/root/.vscode-server/extensions/imatlopez.sftp-1.0.8/dist/extension.js:2:326262)`

I can see it's coming from a `sftp.createWriteStream` call

**Comment by mscdex** [comment]
Which node version are you using?

**Comment by imatlopez** [comment]
So this if from vscode 1.56.2 which uses electron 12 which uses node 14.16: https://code.visualstudio.com/updates/v1_56#_electron-12-update

**Comment by mscdex** [comment]
Have you tried the same (vscode-agnostic) code outside of Electron/vscode, using just plain node v14.16? This would help narrow done any meddling Electron may be doing.

**Comment by imatlopez** [comment]
Personally I am unable to replicate it, what my users report is that it only occurs when using the Python/Jupyter extension as well as working with a docker container, so I'm guessing the stream gets closed due to so many hoops, and it's perhaps not handled?

Right before each error you see.

```
[05-24 11:29:08] [debug] SFTP: Outbound: Buffered CLOSE
```

**Comment by mscdex** [comment]
Somehow the `stream._readableState` is being unset or never initialized, but I don't see how that is ever possible either in node core or in `ssh2`. If you can find a way to duplicate this with just `ssh2` and plain node I can try to look into it further, but until then there's not much I can do/suggest.
