### ISSUE TITLE
npm i ssh2 error 

### ISSUE THREAD

**Issue by au-top** [mscdex/ssh2#1015]
my run `npm i ssh2`

error

```

PS D:\project\js\autossh> npm i ssh2

> cpu-features@0.0.2 install D:\project\js\autossh\node_modules\ssh2\node_modules\cpu-features
> node-gyp rebuild


D:\project\js\autossh\node_modules\ssh2\node_modules\cpu-features>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_mo
dules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“-m”开关。
  Configuring dependencies
  -- Building for: Visual Studio 16 2019
  -- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.17763.
  -- The C compiler identification is MSVC 19.28.29910.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Configuring done
  -- Generating done
  -- Build files have been written to: D:/project/js/autossh/node_modules/ssh2/node_modules/cpu-features/deps/cpu_features/build
  Building dependencies
  用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.9.0+57a23d249
  版权所有(C) Microsoft Corporation。保留所有权利。

    Checking Build System
    Building Custom Rule D:/project/js/autossh/node_modules/ssh2/node_modules/cpu-features/deps/cpu_features/CMakeLists.txt
    filesystem.c
    stack_line_reader.c
    string_view.c
    正在生成代码...
    utils.vcxproj -> D:\project\js\autossh\node_modules\ssh2\node_modules\cpu-features\deps\cpu_features\build\utils.dir\Release\utils.lib
    Building Custom Rule D:/project/js/autossh/node_modules/ssh2/node_modules/cpu-features/deps/cpu_features/CMakeLists.txt
    cpuinfo_x86.c
    cpu_features.vcxproj -> D:\project\js\autossh\node_modules\ssh2\node_modules\cpu-features\deps\cpu_features\build\Release\cpu_features.lib
    Building Custom Rule D:/project/js/autossh/node_modules/ssh2/node_modules/cpu-features/deps/cpu_features/CMakeLists.txt
    list_cpu_features.c
D:\project\js\autossh\node_modules\ssh2\node_modules\cpu-features\deps\cpu_features\src\utils\list_cpu_features.c(343): warning C4715: “GetCacheTypeString”: 不是所有的控件路径都返回值 [D:\project\js\autossh\node_modules\ssh2\node_modules\cpu-features\deps\cpu_features\build\list_cpu_featu
res.vcxproj]
 [D:\project\js\autossh\node_modules\ssh2\node_modules\cpu-features\build\build_deps.vcxproj]
    list_cpu_features.vcxproj -> D:\project\js\autossh\node_modules\ssh2\node_modules\cpu-features\deps\cpu_features\build\Release\list_cpu_features.exe
    Building Custom Rule D:/project/js/autossh/node_modules/ssh2/node_modules/cpu-features/deps/cpu_features/CMakeLists.txt
  binding.cc
  win_delay_load_hook.cc
    正在创建库 D:\project\js\autossh\node_modules\ssh2\node_modules\cpu-features\build\Release\cpufeatures.lib 和对象 D:\project\js\autossh\node_modules\ssh2\node_modules\cpu-features\build\Release\cpufeatures.exp
LINK : warning LNK4098: 默认库“MSVCRT”与其他库的使用冲突；请使用 /NODEFAULTLIB:library [D:\project\js\autossh\node_modules\ssh2\node_modules\cpu-features\build\cpufeatures.vcxproj]
  cpufeatures.vcxproj -> D:\project\js\autossh\node_modules\ssh2\node_modules\cpu-features\build\Release\\cpufeatures.node

> ssh2@1.1.0 install D:\project\js\autossh\node_modules\ssh2
> node install.js


D:\project\js\autossh\node_modules\ssh2\lib\protocol\crypto>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" --target=v12.16.3 rebuild )  else (node "C:\Program Files\no
dejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" --target=v12.16.3 rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“-m”开关。
  binding.cc
  win_delay_load_hook.cc
D:\project\js\autossh\node_modules\ssh2\lib\protocol\crypto\src\binding.cc(1718,28): error C2131: 表达式的计算结果不是常数 [D:\project\js\autossh\node_modules\ssh2\lib\protocol\crypto\build\sshcrypto.vcxproj]
D:\project\js\autossh\node_modules\ssh2\lib\protocol\crypto\src\binding.cc(1718,28): message : 因读取超过生命周期的变量而失败 [D:\project\js\autossh\node_modules\ssh2\lib\protocol\crypto\build\sshcrypto.vcxproj]
D:\project\js\autossh\node_modules\ssh2\lib\protocol\crypto\src\binding.cc(1718,28): message : 请参见“this”的用法 [D:\project\js\autossh\node_modules\ssh2\lib\protocol\crypto\build\sshcrypto.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "--target=v12.16.3" "rebuild"
gyp ERR! cwd D:\project\js\autossh\node_modules\ssh2\lib\protocol\crypto
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
Failed to build optional crypto binding
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN autossh@1.0.0 No description
npm WARN autossh@1.0.0 No repository field.

+ ssh2@1.1.0
added 7 packages from 16 contributors in 10.298s

```

**Comment by au-top** [comment]
The key seems to be
`D:\project\js\autossh\node_modules\ssh2\lib\protocol\crypto\src\binding.cc(1718,28): error C2131: 表达式的计算结果不是常数 `
``` 
D:\project\js\autossh\node_modules\ssh2\lib\protocol\crypto\src\binding.cc(1718,28): error C2131: 表达式的计算结果不是常数 [D:\project\js\autossh\node_modules\ssh2\lib\protocol\crypto\build\sshcrypto.vcxproj]
D:\project\js\autossh\node_modules\ssh2\lib\protocol\crypto\src\binding.cc(1718,28): message : 因读取超过生命周期的变量而失败 [D:\project\js\autossh\node_modules\ssh2\lib\protocol\crypto\build\sshcrypto.vcxproj]
D:\project\js\autossh\node_modules\ssh2\lib\protocol\crypto\src\binding.cc(1718,28): message : 请参见“this”的用法 [D:\project\js\autossh\node_modules\ssh2\lib\protocol\crypto\build\sshcrypto.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "--target=v12.16.3" "rebuild"
gyp ERR! cwd D:\project\js\autossh\node_modules\ssh2\lib\protocol\crypto
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
```

**Comment by mscdex** [comment]
Just FYI the module will still work, the crypto just won't be accelerated with the optional binding.

Can you try this patch and let me know if that solves the binding compilation issue though?:

```diff
diff --git a/lib/protocol/crypto/src/binding.cc b/lib/protocol/crypto/src/binding.cc
index 9012866..e5c39a1 100644
--- a/lib/protocol/crypto/src/binding.cc
+++ b/lib/protocol/crypto/src/binding.cc
@@ -37,6 +37,8 @@ enum ErrorType {
   kErrBadBlockLen
 };
 
+#define MAX_MAC_LEN 64
+
 #define POLY1305_KEYLEN   32
 #define POLY1305_TAGLEN   16
 class ChaChaPolyCipher : public ObjectWrap {
@@ -1715,8 +1717,7 @@ out:
     ErrorType r = kErrNone;
 
     int outlen;
-    unsigned char calc_mac[hmac_len_];
-    memset(calc_mac, 0, hmac_len_);
+    unsigned char calc_mac[MAX_MAC_LEN] = {0};
 
     uint8_t seqbuf[4] = {0};
     ((uint8_t*)(seqbuf))[0] = (seqno >> 24) & 0xff;
@@ -1749,7 +1750,7 @@ out:
         }
 
         // Compare MACs
-        if (CRYPTO_memcmp(mac, calc_mac, sizeof(calc_mac))) {
+        if (CRYPTO_memcmp(mac, calc_mac, hmac_len_)) {
           r = kErrInvalidMAC;
           goto out;
         }
```

**Comment by mscdex** [comment]
Looks like even with this fixed node is missing some OpenSSL exports for its Windows builds. Unfortunately that means the binding won't be available for Windows users (not sure about WSL) until the symbol is exported or the missing symbols are worked around in the `ssh2` binding.

**Comment by mscdex** [comment]
Ok that additional fix was easier than I realized. Please try the master branch and let me know if the optional binding builds successfully and the module works for you.

**Comment by Achder** [comment]
I just installed the latest version:

```
gyp ERR! build error
gyp ERR! stack Error: `C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Current\\Bin\\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\lib\\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"C:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"rebuild\"
gyp ERR! cwd C:\\Development\\anvajo-datalab\\node_modules\\cpu-features
gyp ERR! node -v v14.2.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok"
```

**Comment by mscdex** [comment]
@Achder Does the module still work though?

**Comment by Achder** [comment]
Yes. Next line is:
```
info This module is OPTIONAL, you can safely ignore this error
```
It's just a bit annoying, since I'm updating packages in my project. The error pops up each time I run yarn. It's no deal breaker. Just wanted to provide an update.

**Comment by mscdex** [comment]
@Achder Out of curiosity, can you include the actual build error that comes before

```
gyp ERR! build error
gyp ERR! stack Error: `C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Current\\Bin\\MSBuild.exe` failed with exit code: 1
```

?

**Comment by Achder** [comment]
```
warning Error running install script for optional dependency: "C:\\Development\\***\\node_modules\\cpu-features: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\\Development\\***\\node_modules\\cpu-features
Output:
C:\\Development\\***\\node_modules\\cpu-features>if not defined npm_config_node_gyp (node \"C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" rebuild )  else (node \"\" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.2.0 | win32 | x64
gyp info find Python using Python version 3.9.1 found at \"C:\\Users\\***\\AppData\\Local\\Programs\\Python\\Python39\\python.exe\"
gyp info find VS using VS2019 (16.9.31112.23) found at:
gyp info find VS \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\\Users\\***\\AppData\\Local\\Programs\\Python\\Python39\\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\gyp\\\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Development\\\\***\\\\node_modules\\\\cpu-features\\\\build\\\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Users\\\\***\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\14.2.0\\\\include\\\\node\\\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\\\Users\\\\***\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\14.2.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\\\\\Users\\\\\\\\***\\\\\\\\AppData\\\\\\\\Local\\\\\\\\node-gyp\\\\\\\\Cache\\\\\\\\14.2.0\\\\\\\\<(target_arch)\\\\\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\\\Development\\\\***\\\\node_modules\\\\cpu-features',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\\\Development\\\\***\\\\node_modules\\\\cpu-features\\\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Current\\Bin\\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu erm�glichen, m�ssen Sie den Schalter \"-m\" hinzuf�gen.
  Configuring dependencies
  Der Befehl \"cmake\" ist entweder falsch geschrieben oder
  konnte nicht gefunden werden.
C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Microsoft\\VC\\v160\\Microsoft.CppCommon.targets(240,5): error MSB8066: Der benutzerdefinierte Build f�r \"C:\\Development\\***\\node_modules\\cpu-features\\deps\\cpu_features\\CMakeLists.txt\" wurde mit dem Code 9009 beendet. [C:\\Development\\***\\node_modules\\cpu-features\\build\\config_deps.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Current\\Bin\\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\lib\\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"C:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"rebuild\"
gyp ERR! cwd C:\\Development\\***\\node_modules\\cpu-features
```

**Comment by samtsai** [comment]
Another example failure log:

```
warning Error running install script for optional dependency: "REPO_DIR/node_modules/cpu-features: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: REPO_DIR/node_modules/cpu-features
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.17.1 | darwin | x64
gyp info find Python using Python version 2.7.16 found at \"/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python\"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   'HOME_PATH/.nvm/versions/node/v14.17.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   'REPO_DIR/node_modules/cpu-features/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'HOME_PATH/.nvm/versions/node/v14.17.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'HOME_PATH/Library/Caches/node-gyp/14.17.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=HOME_PATH/Library/Caches/node-gyp/14.17.1',
gyp info spawn args   '-Dnode_gyp_dir=HOME_PATH/.nvm/versions/node/v14.17.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=HOME_PATH/Library/Caches/node-gyp/14.17.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=REPO_DIR/node_modules/cpu-features',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  ACTION Configuring dependencies REPO_DIR/node_modules/cpu-features/deps/cpu_features/build/Makefile
/bin/sh: cmake: command not found
make: *** [REPO_DIR/node_modules/cpu-features/deps/cpu_features/build/Makefile] Error 127
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (HOME_PATH/.nvm/versions/node/v14.17.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 20.5.0
gyp ERR! command \"HOME_PATH/.nvm/versions/node/v14.17.1/bin/node\" \"HOME_PATH/.nvm/versions/node/v14.17.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd REPO_DIR/node_modules/cpu-features
gyp ERR! node -v v14.17.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error
```

**Comment by mscdex** [comment]
Closing this as the original issue should be resolved already.

As for the separated issues reported here, they can be ignored since it's about an optional dependency. If you want to fix the error anyway, you will need to look at the output to find what's wrong (e.g. missing cmake installation).

**Comment by PaulMest** [comment]
I received the same `node-gyp` failures on macOS. I resolved them by adding `cmake` via Homebrew.

```sh
$ brew install cmake
$ yarn install
```

**Comment by ayu-praja** [comment]
> I received the same `node-gyp` failures on macOS. I resolved them by adding `cmake` via Homebrew.
> 
> ```shell
> $ brew install cmake
> $ yarn install
> ```

It was fixed by brew install cmake but how to solve this error while deploying code in jenkins i am getting same error on jenkins

**Comment by bettafish15** [comment]
@mscdex can you give more information on the accelerating crypto with optional binding ? I'm curious about this but I don't know where to read

**Comment by mscdex** [comment]
@bettafish15 The optional bundled binding encrypts/decrypts in place, provides native poly1305, combines both encryption/decryption and hmac/authentication in one step, and has reduced overhead in the API itself. All of these are things node's built-in `crypto` module does not currently support.
