### ISSUE TITLE
Runtime issue after latest upgrade

### ISSUE THREAD

**Issue by rk-servian** [mscdex/ssh2#1016]
TypeError: Cannot read property 'FAILURE' of undefined
    at SFTP.FileSystem.readdir (/opt/estb/src/modules/server/FileSystem.ts:259:37)
    at SFTP.emit (events.js:315:20)
    at SFTP.EventEmitter.emit (domain.js:467:12)
    at 12 (/opt/estb/node_modules/ssh2/lib/protocol/SFTP.js:2942:15)
    at SFTP.push (/opt/estb/node_modules/ssh2/lib/protocol/SFTP.js:271:11)
    at CHANNEL_DATA (/opt/estb/node_modules/ssh2/lib/server.js:743:23)
    at 94 (/opt/estb/node_modules/ssh2/lib/protocol/handlers.misc.js:841:16)
    at Protocol.onPayload (/opt/estb/node_modules/ssh2/lib/protocol/Protocol.js:1974:10)
    at AESGCMDecipherBinding.decrypt (/opt/estb/node_modules/ssh2/lib/protocol/crypto.js:1091:26)
    at Protocol.parsePacket [as _parse] (/opt/estb/node_modules/ssh2/lib/protocol/Protocol.js:1943:25)
    at Protocol.parse (/opt/estb/node_modules/ssh2/lib/protocol/Protocol.js:281:16)
    at Socket.<anonymous> (/opt/estb/node_modules/ssh2/lib/server.js:1199:17)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)

/opt/estb/node_modules/ssh2/lib/protocol/crypto/poly1305.js:20
function J(a){if(b.onAbort)b.onAbort(a);L(a);O=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.")

**Comment by mscdex** [comment]
and what is at FileSystem.ts:259 ?

**Comment by P4sca1** [comment]
I have the same issue. The problem is that `SFTP_STATUS_CODE` is no longer exported from `ssh2`.

**Comment by mscdex** [comment]
@P4sca1 The actual fix for v1.x is to use the new location instead of reaching into internals. For example:

```js
const { utils: { sftp: {
  OPEN_MODE: SFTP_OPEN_MODE,
  STATUS_CODE: SFTP_STATUS_CODE,
} } } = require('ssh2');
```

**Comment by samuelgoldenbaum** [comment]
```javascript
const { utils: { sftp: {
  OPEN_MODE: SFTP_OPEN_MODE,
  STATUS_CODE: SFTP_STATUS_CODE,
} } } = require('ssh2');
```

How would one `import` this? @P4sca1 what did your import statement look like here?
