### ISSUE TITLE
npm install ssh2 error 

### ISSUE THREAD

**Issue by AshramC** [mscdex/ssh2#1024]
```
../src/binding.cc: In member function ‘void ChaChaPolyCipher::clear()’:
../src/binding.cc:86:30: error: ‘EVP_MD_CTX_free’ was not declared in this scope
       EVP_MD_CTX_free(md_ctx_);
                              ^
../src/binding.cc: In member function ‘ErrorType ChaChaPolyCipher::init(unsigned char*, size_t)’:
../src/binding.cc:103:38: error: ‘EVP_MD_CTX_new’ was not declared in this scope
         || (md_ctx_ = EVP_MD_CTX_new()) == nullptr
                                      ^
../src/binding.cc:105:44: error: ‘EVP_chacha20’ was not declared in this scope
                               EVP_chacha20(),
                                            ^
../src/binding.cc: In member function ‘ErrorType ChaChaPolyCipher::encrypt(unsigned char*, uint32_t, uint32_t)’:
../src/binding.cc:212:47: error: ‘EVP_PKEY_POLY1305’ was not declared in this scope
       polykey_ = EVP_PKEY_new_raw_private_key(EVP_PKEY_POLY1305,
                                               ^
../src/binding.cc:215:62: error: ‘EVP_PKEY_new_raw_private_key’ was not declared in this scope
                                               sizeof(polykey));
                                                              ^
../src/binding.cc:236:32: error: ‘EVP_DigestSign’ was not declared in this scope
                        data_len) != 1) {
                                ^
../src/binding.cc: In member function ‘ErrorType AESGCMCipher::init(const char*, unsigned char*, size_t, unsigned char*, size_t)’:
../src/binding.cc:384:36: error: ‘EVP_CTRL_AEAD_SET_IVLEN’ was not declared in this scope
     if (!EVP_CIPHER_CTX_ctrl(ctx_, EVP_CTRL_AEAD_SET_IVLEN, iv_len, nullptr)) {
                                    ^
../src/binding.cc: In member function ‘ErrorType AESGCMCipher::encrypt(unsigned char*, uint32_t)’:
../src/binding.cc:466:29: error: ‘EVP_CTRL_AEAD_GET_TAG’ was not declared in this scope
                             EVP_CTRL_AEAD_GET_TAG,
                             ^
../src/binding.cc: In member function ‘void GenericCipher::clear()’:
../src/binding.cc:606:30: error: ‘HMAC_CTX_free’ was not declared in this scope
       HMAC_CTX_free(ctx_hmac_);
                              ^
../src/binding.cc: In member function ‘ErrorType GenericCipher::init(const char*, unsigned char*, size_t, unsigned char*, size_t, const char*, unsigned char*, size_t, int)’:
../src/binding.cc:686:35: error: ‘HMAC_CTX_new’ was not declared in this scope
     if ((ctx_hmac_ = HMAC_CTX_new()) == nullptr
                                   ^
../src/binding.cc: In member function ‘void ChaChaPolyDecipher::clear()’:
../src/binding.cc:948:30: error: ‘EVP_MD_CTX_free’ was not declared in this scope
       EVP_MD_CTX_free(md_ctx_);
                              ^
../src/binding.cc: In member function ‘ErrorType ChaChaPolyDecipher::init(unsigned char*, size_t)’:
../src/binding.cc:965:38: error: ‘EVP_MD_CTX_new’ was not declared in this scope
         || (md_ctx_ = EVP_MD_CTX_new()) == nullptr
                                      ^
../src/binding.cc:967:44: error: ‘EVP_chacha20’ was not declared in this scope
                               EVP_chacha20(),
                                            ^
../src/binding.cc: In member function ‘ErrorType ChaChaPolyDecipher::decrypt(unsigned char*, uint32_t, unsigned char*, uint32_t)’:
../src/binding.cc:1083:47: error: ‘EVP_PKEY_POLY1305’ was not declared in this scope
       polykey_ = EVP_PKEY_new_raw_private_key(EVP_PKEY_POLY1305,
                                               ^
../src/binding.cc:1086:62: error: ‘EVP_PKEY_new_raw_private_key’ was not declared in this scope
                                               sizeof(polykey));
                                                              ^
../src/binding.cc: In member function ‘ErrorType AESGCMDecipher::init(const char*, unsigned char*, size_t, unsigned char*, size_t)’:
../src/binding.cc:1339:36: error: ‘EVP_CTRL_AEAD_SET_IVLEN’ was not declared in this scope
     if (!EVP_CIPHER_CTX_ctrl(ctx_, EVP_CTRL_AEAD_SET_IVLEN, iv_len, nullptr)) {
                                    ^
../src/binding.cc: In member function ‘ErrorType AESGCMDecipher::decrypt(unsigned char*, uint32_t, unsigned char*, unsigned char*)’:
../src/binding.cc:1412:35: error: ‘EVP_CTRL_AEAD_SET_TAG’ was not declared in this scope
     if (EVP_CIPHER_CTX_ctrl(ctx_, EVP_CTRL_AEAD_SET_TAG, 16, tag) != 1) {
                                   ^
../src/binding.cc: In member function ‘void GenericDecipher::clear()’:
../src/binding.cc:1572:30: error: ‘HMAC_CTX_free’ was not declared in this scope
       HMAC_CTX_free(ctx_hmac_);
                              ^
../src/binding.cc: In member function ‘ErrorType GenericDecipher::init(const char*, unsigned char*, size_t, unsigned char*, size_t, const char*, unsigned char*, size_t, int, size_t)’:
../src/binding.cc:1653:35: error: ‘HMAC_CTX_new’ was not declared in this scope
     if ((ctx_hmac_ = HMAC_CTX_new()) == nullptr
                                   ^
make: *** [Release/obj.target/sshcrypto/src/binding.o] Error 1
```

**Comment by AshramC** [comment]
my OpenSSL version is OpenSSL 1.1.1k  25 Mar 2021
my Cmake version is cmake version 3.20.2
thx a lot

**Comment by mscdex** [comment]
What version of node are you attempting to install with?

Also, the binding is optional, so the module should still be usable as it will fallback to using the node core crypto API and such.

**Comment by gagan-bansal** [comment]
I also got similar error.
OS: CentOS Linux release 7.0.1406 (Core) 
Node: v14.16.1

Here is error log: 

```sh
$ npm i ssh2
> cpu-features@0.0.2 install /home/gaganb/cvs_prod_repo/rpa/home/webdoc/rpa/node_modules/cpu-features
> node-gyp rebuild

make: Entering directory `/home/gaganb/cvs_prod_repo/rpa/home/webdoc/rpa/node_modules/cpu-features/build'
  ACTION Configuring dependencies /home/gaganb/cvs_prod_repo/rpa/home/webdoc/rpa/node_modules/cpu-features/deps/cpu_features/build/Makefile
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.0 or higher is required.  You are running version 2.8.11


-- Configuring incomplete, errors occurred!
make: *** [/home/gaganb/cvs_prod_repo/rpa/home/webdoc/rpa/node_modules/cpu-features/deps/cpu_features/build/Makefile] Error 1
make: Leaving directory `/home/gaganb/cvs_prod_repo/rpa/home/webdoc/rpa/node_modules/cpu-features/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/gaganb/.nvm/versions/node/v14.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 3.10.0-123.el7.x86_64
gyp ERR! command "/home/gaganb/.nvm/versions/node/v14.16.1/bin/node" "/home/gaganb/.nvm/versions/node/v14.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/gaganb/cvs_prod_repo/rpa/home/webdoc/rpa/node_modules/cpu-features
gyp ERR! node -v v14.16.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

> ssh2@1.1.0 install /home/gaganb/cvs_prod_repo/rpa/home/webdoc/rpa/node_modules/ssh2
> node install.js

make: Entering directory `/home/gaganb/cvs_prod_repo/rpa/home/webdoc/rpa/node_modules/ssh2/lib/protocol/crypto/build'
  CXX(target) Release/obj.target/sshcrypto/src/binding.o
In file included from /home/gaganb/.cache/node-gyp/14.16.1/include/node/node.h:67:0,
                 from ../src/binding.cc:6:
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:1585:58: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
                                 Local<Value> export_value);
                                                          ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:3359:23: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   Local<Value> Name() const { return Description(); }
                       ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:5178:76: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
       ArrayBufferCreationMode mode = ArrayBufferCreationMode::kExternalized);
                                                                            ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:5225:21: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   bool IsExternal() const;
                     ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:5252:24: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   Contents Externalize();
                        ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:5262:70: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   void Externalize(const std::shared_ptr<BackingStore>& backing_store);
                                                                      ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:5273:24: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   Contents GetContents();
                        ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:5660:76: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
       ArrayBufferCreationMode mode = ArrayBufferCreationMode::kExternalized);
                                                                            ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:5709:76: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
       ArrayBufferCreationMode mode = ArrayBufferCreationMode::kExternalized);
                                                                            ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:5718:21: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   bool IsExternal() const;
                     ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:5734:24: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   Contents Externalize();
                        ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:5744:70: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   void Externalize(const std::shared_ptr<BackingStore>& backing_store);
                                                                      ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:5759:24: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   Contents GetContents();
                        ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:5984:50: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
       Local<FinalizationGroup> finalization_group);
                                                  ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:7135:28: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   size_t code_range_size() const { return code_range_size_ / kMB; }
                            ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:7137:46: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   void set_code_range_size(size_t limit_in_mb) {
                                              ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:7141:38: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   size_t max_semi_space_size_in_kb() const;
                                      ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:7143:56: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   void set_max_semi_space_size_in_kb(size_t limit_in_kb);
                                                        ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:7145:31: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   size_t max_old_space_size() const { return max_old_generation_size_ / kMB; }
                               ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:7147:49: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   void set_max_old_space_size(size_t limit_in_mb) {
                                                 ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:7151:31: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   size_t max_zone_pool_size() const { return max_zone_pool_size_; }
                               ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:7153:43: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   void set_max_zone_pool_size(size_t bytes) { max_zone_pool_size_ = bytes; }
                                           ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:8601:52: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
       HostCleanupFinalizationGroupCallback callback);
                                                    ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:8765:59: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
                                     MeasureMemoryMode mode);
                                                           ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:8829:36: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   Local<Context> GetEnteredContext();
                                    ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:9106:22: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   void RunMicrotasks() { PerformMicrotaskCheckpoint(); }
                      ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:9150:75: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   void AddMicrotasksCompletedCallback(MicrotasksCompletedCallback callback);
                                                                           ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:9158:78: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   void RemoveMicrotasksCompletedCallback(MicrotasksCompletedCallback callback);
                                                                              ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:9330:30: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   UnwindState GetUnwindState();
                              ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:9393:54: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
       AllowCodeGenerationFromStringsCallback callback);
                                                      ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:9750:75: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   static bool TryHandleSignal(int signal_number, void* info, void* context);
                                                                           ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:10711:55: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
                                 const void* stack_base);
                                                       ^
/home/gaganb/.cache/node-gyp/14.16.1/include/node/v8.h:10737:65: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   static bool PCIsInV8(const UnwindState& unwind_state, void* pc);
                                                                 ^
  SOLINK_MODULE(target) Release/obj.target/sshcrypto.node
  COPY Release/sshcrypto.node
make: Leaving directory `/home/gaganb/cvs_prod_repo/rpa/home/webdoc/rpa/node_modules/ssh2/lib/protocol/crypto/build'
Succeeded in building optional crypto binding
npm WARN ical-generator@1.8.1 requires a peer of @types/node@>= 8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN rpa@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: cpu-features@0.0.2 (node_modules/cpu-features):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: cpu-features@0.0.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ ssh2@1.1.0
updated 1 package and audited 193 packages in 9.126s

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

```

**Comment by mscdex** [comment]
@gagan-bansal In your case the binding compiled just fine. The `cpu-features` optional dependency failed to compile however for the reason stated in the output:

> CMake 3.0 or higher is required.  You are running version 2.8.11

**Comment by gagan-bansal** [comment]
@mscdex  Thank you for pointing out, I should have read carefully. I'll update the CMake.
