### ISSUE TITLE
Cannot connect to PWD with publickey

### ISSUE THREAD

**Issue by OmgImAlexis** [mscdex/ssh2#1045]
I believe this is the same issue as #989 but I wanted to open a separate issue in case it's not.

```
xo@ALEXIS-TOWER:~/code/OmgImAlexis/deploy$ node ./dist/index.js --path=./deploy.config.json 
Custom crypto binding not available
Client: Trying direct.labs.play-with-docker.com on port 22 ...
Local ident: 'SSH-2.0-ssh2js1.2.0'
Socket connected
Remote ident: 'SSH-2.0-Go'
Outbound: Sending KEXINIT
Inbound: Handshake in progress
Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
Handshake: (remote) KEX method: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
Handshake: KEX algorithm: curve25519-sha256@libssh.org
Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
Handshake: (remote) Host key format: ssh-rsa
Handshake: Host key format: ssh-rsa
Handshake: (local) C->S cipher: aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
Handshake: (remote) C->S cipher: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,arcfour256,arcfour128
Handshake: C->S Cipher: aes128-gcm@openssh.com
Handshake: (local) S->C cipher: aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
Handshake: (remote) S->C cipher: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,arcfour256,arcfour128
Handshake: S->C cipher: aes128-gcm@openssh.com
Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
Handshake: (remote) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-256,hmac-sha1,hmac-sha1-96
Handshake: C->S MAC: <implicit>
Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
Handshake: (remote) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-256,hmac-sha1,hmac-sha1-96
Handshake: S->C MAC: <implicit>
Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
Handshake: (remote) C->S compression: none
Handshake: C->S compression: none
Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
Handshake: (remote) S->C compression: none
Handshake: S->C compression: none
Outbound: Sending KEXECDH_INIT
Received DH Reply
Host accepted by default (no verification)
Host accepted (verified)
Inbound: NEWKEYS
Verifying signature ...
Verified signature
Outbound: Sending NEWKEYS
Handshake completed
Outbound: Sending SERVICE_REQUEST (ssh-userauth)
Inbound: Received SERVICE_ACCEPT (ssh-userauth)
Outbound: Sending USERAUTH_REQUEST (none)
Inbound: Received USERAUTH_FAILURE (publickey)
Client: none auth failed
Outbound: Sending DISCONNECT (11)
/home/xo/code/OmgImAlexis/deploy/node_modules/ssh2/lib/client.js:802
        const err = new Error('All configured authentication methods failed');
                    ^

Error: All configured authentication methods failed
    at doNextAuth (/home/xo/code/OmgImAlexis/deploy/node_modules/ssh2/lib/client.js:802:21)
    at tryNextAuth (/home/xo/code/OmgImAlexis/deploy/node_modules/ssh2/lib/client.js:992:7)
    at USERAUTH_FAILURE (/home/xo/code/OmgImAlexis/deploy/node_modules/ssh2/lib/client.js:373:11)
    at 51 (/home/xo/code/OmgImAlexis/deploy/node_modules/ssh2/lib/protocol/handlers.misc.js:337:16)
    at Protocol.onPayload (/home/xo/code/OmgImAlexis/deploy/node_modules/ssh2/lib/protocol/Protocol.js:2021:10)
    at AESGCMDecipherNative.decrypt (/home/xo/code/OmgImAlexis/deploy/node_modules/ssh2/lib/protocol/crypto.js:992:26)
    at Protocol.parsePacket [as _parse] (/home/xo/code/OmgImAlexis/deploy/node_modules/ssh2/lib/protocol/Protocol.js:1990:25)
    at Protocol.parse (/home/xo/code/OmgImAlexis/deploy/node_modules/ssh2/lib/protocol/Protocol.js:292:16)
    at Socket.<anonymous> (/home/xo/code/OmgImAlexis/deploy/node_modules/ssh2/lib/client.js:712:21)
    at Socket.emit (node:events:394:28) {
  level: 'client-authentication'
}
```

```
xo@ALEXIS-TOWER:~/code/OmgImAlexis/deploy$ ssh ip172-18-0-26-c47h5kvnjsv00099psm0@direct.labs.play-with-docker.com -v
OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1f  31 Mar 2020
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Connecting to direct.labs.play-with-docker.com [40.76.55.146] port 22.

debug1: Connection established.
debug1: identity file /home/xo/.ssh/id_rsa type 0
debug1: identity file /home/xo/.ssh/id_rsa-cert type -1
debug1: identity file /home/xo/.ssh/id_dsa type -1
debug1: identity file /home/xo/.ssh/id_dsa-cert type -1
debug1: identity file /home/xo/.ssh/id_ecdsa type -1
debug1: identity file /home/xo/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/xo/.ssh/id_ecdsa_sk type -1
debug1: identity file /home/xo/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /home/xo/.ssh/id_ed25519 type -1
debug1: identity file /home/xo/.ssh/id_ed25519-cert type -1
debug1: identity file /home/xo/.ssh/id_ed25519_sk type -1
debug1: identity file /home/xo/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /home/xo/.ssh/id_xmss type -1
debug1: identity file /home/xo/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.2
debug1: Remote protocol version 2.0, remote software version Go
debug1: no match: Go
debug1: Authenticating to direct.labs.play-with-docker.com:22 as 'ip172-18-0-26-c47h5kvnjsv00099psm0'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ssh-rsa
debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha2-256-etm@openssh.com compression: none
debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha2-256-etm@openssh.com compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ssh-rsa SHA256:UyqFRi42lglohSOPKn6Hh9M83Y5Ic9IQn1PTHYqOjEA
debug1: Host 'direct.labs.play-with-docker.com' is known and matches the RSA host key.
debug1: Found key in /home/xo/.ssh/known_hosts:1
debug1: rekey out after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 4294967296 blocks
debug1: Will attempt key: /home/xo/.ssh/id_rsa RSA SHA256:c5qyJjyXLVSVB1j9aWNNLhEF7lSUYvE4DuL3gl3StzY
debug1: Will attempt key: /home/xo/.ssh/id_dsa 
debug1: Will attempt key: /home/xo/.ssh/id_ecdsa 
debug1: Will attempt key: /home/xo/.ssh/id_ecdsa_sk 
debug1: Will attempt key: /home/xo/.ssh/id_ed25519 
debug1: Will attempt key: /home/xo/.ssh/id_ed25519_sk 
debug1: Will attempt key: /home/xo/.ssh/id_xmss 
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: /home/xo/.ssh/id_rsa RSA SHA256:c5qyJjyXLVSVB1j9aWNNLhEF7lSUYvE4DuL3gl3StzY
debug1: Server accepts key: /home/xo/.ssh/id_rsa RSA SHA256:c5qyJjyXLVSVB1j9aWNNLhEF7lSUYvE4DuL3gl3StzY
debug1: Authentication succeeded (publickey).
Authenticated to direct.labs.play-with-docker.com ([40.76.55.146]:22).
debug1: channel 0: new [client-session]
debug1: Entering interactive session.
debug1: pledge: network
debug1: Sending environment.
debug1: Sending env LANG = C.UTF-8
Connecting to 52.149.144.189:8022

###############################################################
#                          WARNING!!!!                        #
# This is a sandbox environment. Using personal credentials   #
# is HIGHLY! discouraged. Any consequences of doing so are    #
# completely the user's responsibilites.                      #
#                                                             #
# The PWD team.                                               #
###############################################################
[node1] (local) root@192.168.0.8 ~
$ 
```

**Comment by OmgImAlexis** [comment]
Looks like this is the SSH server https://github.com/gliderlabs/ssh

**Comment by mscdex** [comment]
You'll need to include higher debug output levels for OpenSSH to be sure.

**Comment by OmgImAlexis** [comment]
Would level 3 be enough?

<details>
<summary><code>-vvv logs</code></summary>

```
xo@ALEXIS-TOWER:~/code/OmgImAlexis/deploy$ ssh ip172-18-0-26-c47h5kvnjsv00099psm0@direct.labs.play-with-docker.com -vvv
OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1f  31 Mar 2020
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug2: resolving "direct.labs.play-with-docker.com" port 22
debug2: ssh_connect_direct
debug1: Connecting to direct.labs.play-with-docker.com [40.76.55.146] port 22.
debug1: Connection established.
debug1: identity file /home/xo/.ssh/id_rsa type 0
debug1: identity file /home/xo/.ssh/id_rsa-cert type -1
debug1: identity file /home/xo/.ssh/id_dsa type -1
debug1: identity file /home/xo/.ssh/id_dsa-cert type -1
debug1: identity file /home/xo/.ssh/id_ecdsa type -1
debug1: identity file /home/xo/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/xo/.ssh/id_ecdsa_sk type -1
debug1: identity file /home/xo/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /home/xo/.ssh/id_ed25519 type -1
debug1: identity file /home/xo/.ssh/id_ed25519-cert type -1
debug1: identity file /home/xo/.ssh/id_ed25519_sk type -1
debug1: identity file /home/xo/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /home/xo/.ssh/id_xmss type -1
debug1: identity file /home/xo/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.2
debug1: Remote protocol version 2.0, remote software version Go
debug1: no match: Go
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to direct.labs.play-with-docker.com:22 as 'ip172-18-0-26-c47h5kvnjsv00099psm0'
debug3: hostkeys_foreach: reading file "/home/xo/.ssh/known_hosts"
debug3: record_hostkey: found key type RSA in file /home/xo/.ssh/known_hosts:1
debug3: load_hostkeys: loaded 1 keys from direct.labs.play-with-docker.com
debug3: order_hostkeyalgs: prefer hostkeyalgs: rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-c
debug2: host key algorithms: rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,ssh-ed25519,sk-ssh-ed25519@openssh.com
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: host key algorithms: ssh-rsa
debug2: ciphers ctos: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,arcfour256,arcfour128
debug2: ciphers stoc: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,arcfour256,arcfour128
debug2: MACs ctos: hmac-sha2-256-etm@openssh.com,hmac-sha2-256,hmac-sha1,hmac-sha1-96
debug2: MACs stoc: hmac-sha2-256-etm@openssh.com,hmac-sha2-256,hmac-sha1,hmac-sha1-96
debug2: compression ctos: none
debug2: compression stoc: none
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ssh-rsa
debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha2-256-etm@openssh.com compression: none
debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha2-256-etm@openssh.com compression: none
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug3: receive packet: type 31
debug1: Server host key: ssh-rsa SHA256:UyqFRi42lglohSOPKn6Hh9M83Y5Ic9IQn1PTHYqOjEA
debug3: hostkeys_foreach: reading file "/home/xo/.ssh/known_hosts"
debug3: record_hostkey: found key type RSA in file /home/xo/.ssh/known_hosts:1
debug3: load_hostkeys: loaded 1 keys from direct.labs.play-with-docker.com
debug3: hostkeys_foreach: reading file "/home/xo/.ssh/known_hosts"
debug3: record_hostkey: found key type RSA in file /home/xo/.ssh/known_hosts:2
debug3: load_hostkeys: loaded 1 keys from 40.76.55.146
debug1: Host 'direct.labs.play-with-docker.com' is known and matches the RSA host key.
debug1: Found key in /home/xo/.ssh/known_hosts:1
debug3: send packet: type 21
debug2: set_newkeys: mode 1
debug1: rekey out after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug1: SSH2_MSG_NEWKEYS received
debug2: set_newkeys: mode 0
debug1: rekey in after 4294967296 blocks
debug1: Will attempt key: /home/xo/.ssh/id_rsa RSA SHA256:c5qyJjyXLVSVB1j9aWNNLhEF7lSUYvE4DuL3gl3StzY
debug1: Will attempt key: /home/xo/.ssh/id_dsa 
debug1: Will attempt key: /home/xo/.ssh/id_ecdsa 
debug1: Will attempt key: /home/xo/.ssh/id_ecdsa_sk 
debug1: Will attempt key: /home/xo/.ssh/id_ed25519 
debug1: Will attempt key: /home/xo/.ssh/id_ed25519_sk 
debug1: Will attempt key: /home/xo/.ssh/id_xmss 
debug2: pubkey_prepare: done
debug3: send packet: type 5
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey
debug3: start over, passed a different list publickey
debug3: preferred gssapi-with-mic,publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering public key: /home/xo/.ssh/id_rsa RSA SHA256:c5qyJjyXLVSVB1j9aWNNLhEF7lSUYvE4DuL3gl3StzY
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 60
debug1: Server accepts key: /home/xo/.ssh/id_rsa RSA SHA256:c5qyJjyXLVSVB1j9aWNNLhEF7lSUYvE4DuL3gl3StzY
debug3: sign_and_send_pubkey: RSA SHA256:c5qyJjyXLVSVB1j9aWNNLhEF7lSUYvE4DuL3gl3StzY
debug3: sign_and_send_pubkey: signing using ssh-rsa SHA256:c5qyJjyXLVSVB1j9aWNNLhEF7lSUYvE4DuL3gl3StzY
debug3: send packet: type 50
debug3: receive packet: type 52
debug1: Authentication succeeded (publickey).
Authenticated to direct.labs.play-with-docker.com ([40.76.55.146]:22).
debug1: channel 0: new [client-session]
debug3: ssh_session2_open: channel_new: 0
debug2: channel 0: send open
debug3: send packet: type 90
debug1: Entering interactive session.
debug1: pledge: network
debug3: receive packet: type 91
debug2: channel_input_open_confirmation: channel 0: callback start
debug2: fd 3 setting TCP_NODELAY
debug3: ssh_packet_set_tos: set IP_TOS 0x10
debug2: client_session2_setup: id 0
debug2: channel 0: request pty-req confirm 1
debug3: send packet: type 98
debug1: Sending environment.
debug3: Ignored env SHELL
debug3: Ignored env COLORTERM
debug3: Ignored env NVM_INC
debug3: Ignored env TERM_PROGRAM_VERSION
debug3: Ignored env WSL_DISTRO_NAME
debug3: Ignored env NAME
debug3: Ignored env PWD
debug3: Ignored env LOGNAME
debug3: Ignored env VSCODE_GIT_ASKPASS_NODE
debug3: Ignored env MOTD_SHOWN
debug3: Ignored env HOME
debug1: Sending env LANG = C.UTF-8
debug2: channel 0: request env confirm 0
debug3: send packet: type 98
debug3: Ignored env WSL_INTEROP
debug3: Ignored env LS_COLORS
debug3: Ignored env GIT_ASKPASS
debug3: Ignored env NVM_DIR
debug3: Ignored env LESSCLOSE
debug3: Ignored env TERM
debug3: Ignored env LESSOPEN
debug3: Ignored env USER
debug3: Ignored env VSCODE_GIT_IPC_HANDLE
debug3: Ignored env SHLVL
debug3: Ignored env NVM_CD_FLAGS
debug3: Ignored env WSLENV
debug3: Ignored env VSCODE_GIT_ASKPASS_MAIN
debug3: Ignored env XDG_DATA_DIRS
debug3: Ignored env PATH
debug3: Ignored env NVM_BIN
debug3: Ignored env HOSTTYPE
debug3: Ignored env TERM_PROGRAM
debug3: Ignored env VSCODE_IPC_HOOK_CLI
debug3: Ignored env _
debug2: channel 0: request shell confirm 1
debug3: send packet: type 98
debug2: channel_input_open_confirmation: channel 0: callback done
debug2: channel 0: open confirm rwindow 2097152 rmax 32768
debug2: channel 0: rcvd ext data 35
Connecting to 52.149.144.189:8022
debug2: channel 0: written 35 to efd 6
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: PTY allocation request accepted on channel 0
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: shell request accepted on channel 0
###############################################################
#                          WARNING!!!!                        #
# This is a sandbox environment. Using personal credentials   #
# is HIGHLY! discouraged. Any consequences of doing so are    #
# completely the user's responsibilites.                      #
#                                                             #
# The PWD team.                                               #
###############################################################
[node1] (local) root@192.168.0.8 ~
$ debug2: channel 0: rcvd adjust 1
debug2: channel 0: rcvd adjust 1
exdebug2: channel 0: rcvd adjust 1
debug2: channel 0: rcvd adjust 1
debug2: channel 0: rcvd adjust 1
debug3: receive packet: type 97
debug2: channel 0: rcvd close
debug2: channel 0: output open -> drain
debug2: channel 0: chan_shutdown_read (i0 o1 sock -1 wfd 4 efd 6 [write])
debug2: channel 0: input open -> closed
debug3: channel 0: will not send data after close
itdebug3: channel 0: will not send data after close
debug2: channel 0: obuf empty
debug2: channel 0: chan_shutdown_write (i3 o1 sock -1 wfd 5 efd 6 [write])
debug2: channel 0: output drain -> closed
debug2: channel 0: almost dead
debug2: channel 0: gc: notify user
debug2: channel 0: gc: user detached
debug2: channel 0: send close
debug3: send packet: type 97
debug2: channel 0: is dead
debug2: channel 0: garbage collecting
debug1: channel 0: free: client-session, nchannels 1
debug3: channel 0: status: The following connections are open:
  #0 client-session (t4 r0 i3/0 o3/0 e[write]/0 fd -1/-1/6 sock -1 cc -1)

debug3: send packet: type 1
debug3: fd 1 is not O_NONBLOCK
Connection to direct.labs.play-with-docker.com closed.
Transferred: sent 3764, received 2656 bytes, in 4.7 seconds
Bytes per second: sent 809.1, received 570.9
debug1: Exit status -1
```

</details>

**Comment by mscdex** [comment]
Doesn't look like the same issue. The client is sending ext-info-c but the server never sends an SSH2_MSG_EXT_INFO message, which would contain server-sig-algs.

**Comment by mscdex** [comment]
Can you post what you're passing to `connect()`? The `ssh2` debug output during the user authentication doesn't seem quite right.

**Comment by OmgImAlexis** [comment]
Yep this was a bug with the object being passed to connect on my end.
