### ISSUE TITLE
Connect to Cisco IOS doesn't work v1.4 vs 0.8.9

### ISSUE THREAD

**Issue by Kurtas** [mscdex/ssh2#1064]
Hi,

I tried to update today ssh2 from `0.8.9` to `1.4.0` thanks for your great work!
During testing, I find out that the connection to some vendors like Cisco IOS doesn't work.

See attached log from `1.4.0` version
```
[2021-09-14T19:31:26.228Z] Custom crypto binding available
[2021-09-14T19:31:26.230Z] Client: Trying 10.39.23.1 on port 22 ...
[2021-09-14T19:31:26.244Z] Local ident: 'SSH-2.0-ssh2js1.4.0'
[2021-09-14T19:31:26.363Z] Socket connected
[2021-09-14T19:31:26.386Z] Remote ident: 'SSH-2.0-Cisco-1.25'
[2021-09-14T19:31:26.386Z] Outbound: Sending KEXINIT
[2021-09-14T19:31:26.397Z] Inbound: Handshake in progress
[2021-09-14T19:31:26.397Z] Handshake: (local) KEX method: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512
[2021-09-14T19:31:26.397Z] Handshake: (remote) KEX method: diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
[2021-09-14T19:31:26.397Z] Handshake: KEX algorithm: diffie-hellman-group1-sha1
[2021-09-14T19:31:26.397Z] Handshake: (local) Host key format: ssh-ed25519,ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-dss
[2021-09-14T19:31:26.397Z] Handshake: (remote) Host key format: ssh-rsa
[2021-09-14T19:31:26.397Z] Handshake: Host key format: ssh-rsa
[2021-09-14T19:31:26.397Z] Handshake: (local) C->S cipher: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
[2021-09-14T19:31:26.397Z] Handshake: (remote) C->S cipher: aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc
[2021-09-14T19:31:26.398Z] Handshake: C->S Cipher: aes256-cbc
[2021-09-14T19:31:26.398Z] Handshake: (local) S->C cipher: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
[2021-09-14T19:31:26.398Z] Handshake: (remote) S->C cipher: aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc
[2021-09-14T19:31:26.398Z] Handshake: S->C cipher: aes256-cbc
[2021-09-14T19:31:26.398Z] Handshake: (local) C->S MAC: hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-md5,hmac-sha2-256-96,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
[2021-09-14T19:31:26.398Z] Handshake: (remote) C->S MAC: hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-96
[2021-09-14T19:31:26.398Z] Handshake: C->S MAC: hmac-sha1
[2021-09-14T19:31:26.398Z] Handshake: (local) S->C MAC: hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-md5,hmac-sha2-256-96,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
[2021-09-14T19:31:26.398Z] Handshake: (remote) S->C MAC: hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-96
[2021-09-14T19:31:26.398Z] Handshake: S->C MAC: hmac-sha1
[2021-09-14T19:31:26.398Z] Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
[2021-09-14T19:31:26.398Z] Handshake: (remote) C->S compression: none
[2021-09-14T19:31:26.398Z] Handshake: C->S compression: none
[2021-09-14T19:31:26.399Z] Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
[2021-09-14T19:31:26.399Z] Handshake: (remote) S->C compression: none
[2021-09-14T19:31:26.399Z] Handshake: S->C compression: none
[2021-09-14T19:31:26.399Z] Outbound: Sending KEXDH_INIT
[2021-09-14T19:31:26.497Z] Socket ended

```

vs version `0.8.9`
```
[2021-09-14T19:16:27.169Z] DEBUG: Local ident: 'SSH-2.0-ssh2js0.4.10'
[2021-09-14T19:16:27.172Z] DEBUG: Client: Trying 10.39.23.1 on port 22 ...
[2021-09-14T19:16:27.185Z] DEBUG: Client: Connected
[2021-09-14T19:16:27.209Z] DEBUG: Parser: IN_INIT
[2021-09-14T19:16:27.214Z] DEBUG: Parser: IN_GREETING
[2021-09-14T19:16:27.215Z] DEBUG: Parser: IN_HEADER
[2021-09-14T19:16:27.215Z] DEBUG: Remote ident: 'SSH-2.0-Cisco-1.25'
[2021-09-14T19:16:27.217Z] DEBUG: Outgoing: Writing KEXINIT
[2021-09-14T19:16:27.244Z] DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
[2021-09-14T19:16:27.244Z] DEBUG: Parser: IN_PACKET
[2021-09-14T19:16:27.245Z] DEBUG: Parser: pktLen:340,padLen:5,remainLen:336
[2021-09-14T19:16:27.245Z] DEBUG: Parser: IN_PACKETDATA
[2021-09-14T19:16:27.245Z] DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXINIT
[2021-09-14T19:16:27.247Z] DEBUG: Comparing KEXINITs ...
[2021-09-14T19:16:27.248Z] DEBUG: (local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512
[2021-09-14T19:16:27.248Z] DEBUG: (remote) KEX algorithms: diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
[2021-09-14T19:16:27.248Z] DEBUG: KEX algorithm: diffie-hellman-group1-sha1
[2021-09-14T19:16:27.248Z] DEBUG: (local) Host key formats: ssh-ed25519,ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-dss
[2021-09-14T19:16:27.248Z] DEBUG: (remote) Host key formats: ssh-rsa
[2021-09-14T19:16:27.248Z] DEBUG: Host key format: ssh-rsa
[2021-09-14T19:16:27.248Z] DEBUG: (local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
[2021-09-14T19:16:27.248Z] DEBUG: (remote) Client->Server ciphers: aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc
[2021-09-14T19:16:27.248Z] DEBUG: Client->Server Cipher: aes256-cbc
[2021-09-14T19:16:27.249Z] DEBUG: (local) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
[2021-09-14T19:16:27.249Z] DEBUG: (remote) Server->Client ciphers: aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc
[2021-09-14T19:16:27.249Z] DEBUG: Server->Client Cipher: aes256-cbc
[2021-09-14T19:16:27.249Z] DEBUG: (local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-md5,hmac-sha2-256-96,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
[2021-09-14T19:16:27.249Z] DEBUG: (remote) Client->Server HMAC algorithms: hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-96
[2021-09-14T19:16:27.249Z] DEBUG: Client->Server HMAC algorithm: hmac-sha1
[2021-09-14T19:16:27.249Z] DEBUG: (local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-md5,hmac-sha2-256-96,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
[2021-09-14T19:16:27.249Z] DEBUG: (remote) Server->Client HMAC algorithms: hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-96
[2021-09-14T19:16:27.249Z] DEBUG: Server->Client HMAC algorithm: hmac-sha1
[2021-09-14T19:16:27.249Z] DEBUG: (local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
[2021-09-14T19:16:27.250Z] DEBUG: (remote) Client->Server compression algorithms: none
[2021-09-14T19:16:27.250Z] DEBUG: Client->Server compression algorithm: none
[2021-09-14T19:16:27.250Z] DEBUG: (local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
[2021-09-14T19:16:27.250Z] DEBUG: (remote) Server->Client compression algorithms: none
[2021-09-14T19:16:27.250Z] DEBUG: Server->Client compression algorithm: none
[2021-09-14T19:16:27.315Z] DEBUG: Outgoing: Writing KEXDH_INIT
[2021-09-14T19:16:27.316Z] DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
[2021-09-14T19:16:27.624Z] DEBUG: Parser: IN_PACKET
[2021-09-14T19:16:27.624Z] DEBUG: Parser: pktLen:1212,padLen:7,remainLen:1208
[2021-09-14T19:16:27.637Z] DEBUG: Parser: IN_PACKETDATA
[2021-09-14T19:16:27.637Z] DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXDH_REPLY
[2021-09-14T19:16:27.638Z] DEBUG: Checking host key format
[2021-09-14T19:16:27.638Z] DEBUG: Checking signature format
[2021-09-14T19:16:27.638Z] DEBUG: Verifying host fingerprint
[2021-09-14T19:16:27.638Z] DEBUG: Host accepted by default (no verification)
[2021-09-14T19:16:27.642Z] DEBUG: Verifying signature
[2021-09-14T19:16:27.643Z] DEBUG: Outgoing: Writing NEWKEYS
[2021-09-14T19:16:27.644Z] DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
[2021-09-14T19:16:27.644Z] DEBUG: Parser: IN_PACKET
[2021-09-14T19:16:27.644Z] DEBUG: Parser: pktLen:12,padLen:10,remainLen:8
[2021-09-14T19:16:27.644Z] DEBUG: Parser: IN_PACKETDATA
[2021-09-14T19:16:27.644Z] DEBUG: Parser: IN_PACKETDATAAFTER, packet: NEWKEYS
[2021-09-14T19:16:27.646Z] DEBUG: Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
.....
```

The settings of `algorithms` in `Client` `connect` method is the same. 

Thanks

**Comment by mscdex** [comment]
The only bug I'm aware of with Cisco 1.x SSH implementations is their group-exchange implementation (which this library accounts for), but that's not being used/forced in this instance, so I don't know why there would be a problem. I don't have any Cisco equipment to test against, so unless there is some useful SSH-related debug output you can supply from the Cisco software, there's not much I can do.

**Comment by mscdex** [comment]
Also, does it happen every time?

**Comment by Kurtas** [comment]
Hi @mscdex 

we tried to collect some debug logs from Cisco. Let me know if it's worth it or not. And yes it happens every time - it works with 0.8.9 without a problem.

[cisco_log_old-ssh-lib.txt](https://github.com/mscdex/ssh2/files/7172086/cisco_log_old-ssh-lib.txt)
[cisco_log_new-ssh-lib.txt](https://github.com/mscdex/ssh2/files/7172087/cisco_log_new-ssh-lib.txt)

Thanks

**Comment by mscdex** [comment]
Unfortunately the logs don't help very much. Just as a wild shot in the dark..... what if you comment out [these lines](https://github.com/mscdex/ssh2/blob/0af296dbebdefc9d761d23395ec27b3d716fd3b3/lib/protocol/kex.js#L77-L108)? Does it work then?

**Comment by Kurtas** [comment]
No same result, debug log attached 

```
[2021-09-15T19:34:05.419Z] Custom crypto binding available
[2021-09-15T19:34:05.421Z] Client: Trying 10.39.23.1 on port 22 ...
[2021-09-15T19:34:05.423Z] Local ident: 'SSH-2.0-ssh2js1.4.0'
[2021-09-15T19:34:05.441Z] Socket connected
[2021-09-15T19:34:05.479Z] Remote ident: 'SSH-2.0-Cisco-1.25'
[2021-09-15T19:34:05.481Z] Outbound: Sending KEXINIT
[2021-09-15T19:34:05.547Z] Inbound: Handshake in progress
[2021-09-15T19:34:05.548Z] Handshake: (local) KEX method: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512
[2021-09-15T19:34:05.548Z] Handshake: (remote) KEX method: diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
[2021-09-15T19:34:05.549Z] Handshake: KEX algorithm: diffie-hellman-group1-sha1
[2021-09-15T19:34:05.549Z] Handshake: (local) Host key format: ssh-ed25519,ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-dss
[2021-09-15T19:34:05.549Z] Handshake: (remote) Host key format: ssh-rsa
[2021-09-15T19:34:05.549Z] Handshake: Host key format: ssh-rsa
[2021-09-15T19:34:05.549Z] Handshake: (local) C->S cipher: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
[2021-09-15T19:34:05.549Z] Handshake: (remote) C->S cipher: aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc
[2021-09-15T19:34:05.549Z] Handshake: C->S Cipher: aes256-cbc
[2021-09-15T19:34:05.550Z] Handshake: (local) S->C cipher: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
[2021-09-15T19:34:05.550Z] Handshake: (remote) S->C cipher: aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc
[2021-09-15T19:34:05.550Z] Handshake: S->C cipher: aes256-cbc
[2021-09-15T19:34:05.550Z] Handshake: (local) C->S MAC: hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-md5,hmac-sha2-256-96,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
[2021-09-15T19:34:05.550Z] Handshake: (remote) C->S MAC: hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-96
[2021-09-15T19:34:05.550Z] Handshake: C->S MAC: hmac-sha1
[2021-09-15T19:34:05.550Z] Handshake: (local) S->C MAC: hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-md5,hmac-sha2-256-96,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
[2021-09-15T19:34:05.551Z] Handshake: (remote) S->C MAC: hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-96
[2021-09-15T19:34:05.551Z] Handshake: S->C MAC: hmac-sha1
[2021-09-15T19:34:05.551Z] Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
[2021-09-15T19:34:05.551Z] Handshake: (remote) C->S compression: none
[2021-09-15T19:34:05.551Z] Handshake: C->S compression: none
[2021-09-15T19:34:05.551Z] Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
[2021-09-15T19:34:05.551Z] Handshake: (remote) S->C compression: none
[2021-09-15T19:34:05.551Z] Handshake: S->C compression: none
[2021-09-15T19:34:05.552Z] Outbound: Sending KEXDH_INIT
[2021-09-15T19:34:05.733Z] Socket ended
```

**Comment by mscdex** [comment]
I'm at a loss then as I don't have any other suggestions offhand. Without a Cisco implementation to do active debugging against myself, there's not much else I can really do at the moment.

**Comment by Kurtas** [comment]
I tried Cisco sandbox of latest IOS and I have same problem:

Host: sandbox-iosxe-latest-1.cisco.com
username: developer 
password: C1sco12345

**Comment by mscdex** [comment]
Can you try now with ea95de4221836ace5b6b8e5b8b9c238f445fbafa?

**Comment by Kurtas** [comment]
Thanks for your efforts!

I thought that it works, because I was able to successfully connect to Cisco sandbox several times. Then I tried to connect on our older Cisco IOS and it sometimes works but most of the time no. 

Anyway, I was able to reproduce the same problem on the Cisco sandbox too after several attempts. So it fails there sporadically now but not so often like on our older version.

The error is always the same `Received unexpected packet type <number>` where <number> is differed as you can see from logs, I saw 0, 97, 225, 181, 162, 175 ...



Out older Cisco IOS
```
[2021-09-17T17:10:16.496Z] Custom crypto binding available
[2021-09-17T17:10:16.499Z] Client: Trying 10.39.23.1 on port 22 ...
[2021-09-17T17:10:16.501Z] Local ident: 'SSH-2.0-ssh2js1.4.0'
[2021-09-17T17:10:16.513Z] Socket connected
[2021-09-17T17:10:16.531Z] Remote ident: 'SSH-2.0-Cisco-1.25'
[2021-09-17T17:10:16.532Z] Outbound: Sending KEXINIT
[2021-09-17T17:10:16.542Z] Inbound: Handshake in progress
[2021-09-17T17:10:16.542Z] Handshake: (local) KEX method: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512
[2021-09-17T17:10:16.542Z] Handshake: (remote) KEX method: diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
[2021-09-17T17:10:16.542Z] Handshake: KEX algorithm: diffie-hellman-group1-sha1
[2021-09-17T17:10:16.543Z] Handshake: (local) Host key format: ssh-ed25519,ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-dss
[2021-09-17T17:10:16.543Z] Handshake: (remote) Host key format: ssh-rsa
[2021-09-17T17:10:16.543Z] Handshake: Host key format: ssh-rsa
[2021-09-17T17:10:16.543Z] Handshake: (local) C->S cipher: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
[2021-09-17T17:10:16.543Z] Handshake: (remote) C->S cipher: aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc
[2021-09-17T17:10:16.543Z] Handshake: C->S Cipher: aes256-cbc
[2021-09-17T17:10:16.543Z] Handshake: (local) S->C cipher: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
[2021-09-17T17:10:16.543Z] Handshake: (remote) S->C cipher: aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc
[2021-09-17T17:10:16.543Z] Handshake: S->C cipher: aes256-cbc
[2021-09-17T17:10:16.543Z] Handshake: (local) C->S MAC: hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-md5,hmac-sha2-256-96,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
[2021-09-17T17:10:16.543Z] Handshake: (remote) C->S MAC: hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-96
[2021-09-17T17:10:16.543Z] Handshake: C->S MAC: hmac-sha1
[2021-09-17T17:10:16.543Z] Handshake: (local) S->C MAC: hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-md5,hmac-sha2-256-96,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
[2021-09-17T17:10:16.543Z] Handshake: (remote) S->C MAC: hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-96
[2021-09-17T17:10:16.544Z] Handshake: S->C MAC: hmac-sha1
[2021-09-17T17:10:16.544Z] Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
[2021-09-17T17:10:16.544Z] Handshake: (remote) C->S compression: none
[2021-09-17T17:10:16.544Z] Handshake: C->S compression: none
[2021-09-17T17:10:16.544Z] Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
[2021-09-17T17:10:16.544Z] Handshake: (remote) S->C compression: none
[2021-09-17T17:10:16.544Z] Handshake: S->C compression: none
[2021-09-17T17:10:16.544Z] Outbound: Sending KEXDH_INIT
[2021-09-17T17:10:16.892Z] Outbound: Sending DISCONNECT (3)
Error: Received unexpected packet type 8
    at makeError (/home/joe/discovery/node_modules/ssh2/lib/protocol/utils.js:142:15)
    at doFatalError (/home/joe/discovery/node_modules/ssh2/lib/protocol/utils.js:184:13)
    at Protocol.onKEXPayload (/home/joe/discovery/node_modules/ssh2/lib/protocol/kex.js:1758:16)
    at NullDecipher.decrypt (/home/joe/discovery/node_modules/ssh2/lib/protocol/crypto.js:617:26)
    at Protocol.parsePacket [as _parse] (/home/joe/discovery/node_modules/ssh2/lib/protocol/Protocol.js:1993:25)
    at Protocol.parse (/home/joe/discovery/node_modules/ssh2/lib/protocol/Protocol.js:292:16)
    at Socket.<anonymous> (/home/joe/discovery/node_modules/ssh2/lib/client.js:712:21)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9) {
  level: 'handshake',
  fatal: true
}
[2021-09-17T17:10:17.006Z] Socket ended
[2021-09-17T17:10:17.012Z] Socket closed
```

Cisco sandbox
```
autoboss@nimpee-dev:~/discovery$ node ssh
[2021-09-17T17:15:54.817Z] Custom crypto binding available
[2021-09-17T17:15:54.820Z] Client: Trying sandbox-iosxe-latest-1.cisco.com on port 22 ...
[2021-09-17T17:15:54.823Z] Local ident: 'SSH-2.0-ssh2js1.4.0'
[2021-09-17T17:15:55.002Z] Socket connected
[2021-09-17T17:15:55.166Z] Remote ident: 'SSH-2.0-Cisco-1.25'
[2021-09-17T17:15:55.167Z] Outbound: Sending KEXINIT
[2021-09-17T17:15:55.171Z] Inbound: Handshake in progress
[2021-09-17T17:15:55.172Z] Handshake: (local) KEX method: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512
[2021-09-17T17:15:55.172Z] Handshake: (remote) KEX method: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1
[2021-09-17T17:15:55.172Z] Handshake: KEX algorithm: ecdh-sha2-nistp256
[2021-09-17T17:15:55.173Z] Handshake: (local) Host key format: ssh-ed25519,ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-dss
[2021-09-17T17:15:55.173Z] Handshake: (remote) Host key format: rsa-sha2-512,rsa-sha2-256,ssh-rsa
[2021-09-17T17:15:55.173Z] Handshake: Host key format: ssh-rsa
[2021-09-17T17:15:55.173Z] Handshake: (local) C->S cipher: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
[2021-09-17T17:15:55.173Z] Handshake: (remote) C->S cipher: aes128-gcm,aes256-gcm,aes128-ctr,aes192-ctr,aes256-ctr
[2021-09-17T17:15:55.174Z] Handshake: C->S Cipher: aes128-ctr
[2021-09-17T17:15:55.174Z] Handshake: (local) S->C cipher: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
[2021-09-17T17:15:55.174Z] Handshake: (remote) S->C cipher: aes128-gcm,aes256-gcm,aes128-ctr,aes192-ctr,aes256-ctr
[2021-09-17T17:15:55.174Z] Handshake: S->C cipher: aes128-ctr
[2021-09-17T17:15:55.175Z] Handshake: (local) C->S MAC: hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-md5,hmac-sha2-256-96,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
[2021-09-17T17:15:55.175Z] Handshake: (remote) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha2-512
[2021-09-17T17:15:55.175Z] Handshake: C->S MAC: hmac-sha2-256
[2021-09-17T17:15:55.175Z] Handshake: (local) S->C MAC: hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-md5,hmac-sha2-256-96,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
[2021-09-17T17:15:55.175Z] Handshake: (remote) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha2-512
[2021-09-17T17:15:55.176Z] Handshake: S->C MAC: hmac-sha2-256
[2021-09-17T17:15:55.176Z] Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
[2021-09-17T17:15:55.176Z] Handshake: (remote) C->S compression: none
[2021-09-17T17:15:55.176Z] Handshake: C->S compression: none
[2021-09-17T17:15:55.176Z] Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
[2021-09-17T17:15:55.177Z] Handshake: (remote) S->C compression: none
[2021-09-17T17:15:55.177Z] Handshake: S->C compression: none
[2021-09-17T17:15:55.178Z] Outbound: Sending KEXECDH_INIT
[2021-09-17T17:15:55.555Z] Outbound: Sending DISCONNECT (3)
Error: Received unexpected packet type 107
    at makeError (/home/joe/discovery/node_modules/ssh2/lib/protocol/utils.js:142:15)
    at doFatalError (/home/joe/discovery/node_modules/ssh2/lib/protocol/utils.js:184:13)
    at Protocol.onKEXPayload (/home/joe/discovery/node_modules/ssh2/lib/protocol/kex.js:1758:16)
    at NullDecipher.decrypt (/home/joe/discovery/node_modules/ssh2/lib/protocol/crypto.js:617:26)
    at Protocol.parsePacket [as _parse] (/home/joe/discovery/node_modules/ssh2/lib/protocol/Protocol.js:1993:25)
    at Protocol.parse (/home/joe/discovery/node_modules/ssh2/lib/protocol/Protocol.js:292:16)
    at Socket.<anonymous> (/home/joe/discovery/node_modules/ssh2/lib/client.js:712:21)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9) {
  level: 'handshake',
  fatal: true
}
[2021-09-17T17:15:55.719Z] Socket ended
[2021-09-17T17:15:55.720Z] Socket closed
```

**Comment by mscdex** [comment]
Ok, please try again with the master branch. There were a couple of issues I discovered:

1. There was a bit of a bug in the null decipher when a packet was split across multiple chunks. This is now fixed.
2. It appears that Cisco's `aes*-gcm` ciphers are not functionally identical to OpenSSH's GCM extension ciphers (`aes*-gcm@openssh.com`) and according to the OpenSSH changelog [RFC 5647](https://datatracker.ietf.org/doc/html/rfc5647) *should* be functionally identical to the OpenSSH variety (the only difference being the name and how the cipher is selected during the handshake). So for now I'm just removing the non-OpenSSH GCM cipher names, since they're uncommon at this point anyway.

**Comment by Kurtas** [comment]
Hi @mscdex 

Thanks, man! Great job, everything works now. And it seems that better than 0.8.9 - I see fewer timeouts during connection.

BTW: I did testing with reverted changes in your last commit https://github.com/mscdex/ssh2/commit/f1b5ac3c81734c194740016eab79a699efae83d8 (to keep the same settings as with 0.8.9) and it doesn't have any effect on the result. So the question is if it really needs to remove.

**Comment by mscdex** [comment]
I dunno, that was my experience anyway with their sandbox. It could very well vary depending on the version of their software. I believe Cisco uses the same "Cisco-1.25" SSH ident string across different versions of their software, at least from what I've seen in the past.
