### ISSUE TITLE
Error: read ECONNRESET after exec comand ends

### ISSUE THREAD

**Issue by alangregory** [mscdex/ssh2#1067]
Trying to figure out if its a bug or feature. Getting a reset after the exec finish, same doesnt happen on shell request. Something different about this device, is the message send after login, direct on terminal data.
```js
2021-09-20 02:01:59 warn:switch=> Host accepted by default (no verification)
2021-09-20 02:01:59 warn:switch=> Host accepted (verified)
2021-09-20 02:01:59 warn:switch=> Outbound: Sending NEWKEYS
2021-09-20 02:01:59 warn:switch=> Inbound: NEWKEYS
2021-09-20 02:01:59 warn:switch=> Verifying signature ...
2021-09-20 02:01:59 warn:switch=> Verified signature
2021-09-20 02:01:59 warn:switch=> Handshake completed
2021-09-20 02:01:59 warn:switch=> Outbound: Sending SERVICE_REQUEST (ssh-userauth)
2021-09-20 02:01:59 warn:switch=> Inbound: Received SERVICE_ACCEPT (ssh-userauth)
2021-09-20 02:01:59 warn:switch=> Outbound: Sending USERAUTH_REQUEST (none)
2021-09-20 02:01:59 warn:switch=> Inbound: Received USERAUTH_FAILURE (publickey,keyboard-interactive,password)
2021-09-20 02:01:59 warn:switch=> Client: none auth failed
2021-09-20 02:01:59 warn:switch=> Outbound: Sending USERAUTH_REQUEST (password)
2021-09-20 02:01:59 warn:switch=> Inbound: Received USERAUTH_SUCCESS
2021-09-20 02:01:59 warn:switch=> Outbound: Sending CHANNEL_OPEN (r:0, session)
2021-09-20 02:01:59 warn:switch=> Inbound: CHANNEL_OPEN_CONFIRMATION (r:0, s:2)
2021-09-20 02:01:59 warn:switch=> Outbound: Sending CHANNEL_REQUEST (r:2, exec: display pwd)
2021-09-20 02:01:59 warn:switch=> Inbound: CHANNEL_SUCCESS (r:0)
2021-09-20 02:11:31 warn:switch=> Inbound: CHANNEL_DATA (r:0, 99)

Info: The max number of VTY users is 10, and the number
      of current VTY users on line is 2.
2021-09-20 02:11:31 warn:switch=> Inbound: CHANNEL_DATA (r:0, 60)

      The current login time is 2021-09-20 09:56:37+00:00.
2021-09-20 02:11:31 warn:switch=> Inbound: CHANNEL_DATA (r:0, 34)

 Total PW template number : 0 

2021-09-20 02:11:31 warn:switch=> Inbound: CHANNEL_DATA (r:0, 19)

<switch>
2021-09-20 02:11:31 warn:switch=> Socket error: read ECONNRESET
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read',
  level: 'client-socket'
}
2021-09-20 02:01:59 warn:switch=> Socket closed
```
Sample code
```js
client.exec("display pw", (err, stream) => {
    stream.on('data', (data: Buffer) => {
        console.log(data.toString());
    }).on('close', (code: string, signal: string) => {
        console.log('command end');
    });
})
```

**Comment by mscdex** [comment]
Out of curiosity, can you try the master branch?

It could be that's how the server behaves..... what happens when you try with the OpenSSH client (with `-vvv` added to the command-line flags)? Does OpenSSH receive the channel close message?

Also the log output you posted doesn't make sense. The timestamps seem out of order? How could the "Socket closed" come 10 minutes before the channel data log messages and the ECONNRESET?

**Comment by alangregory** [comment]
Sory, mixed some logs. Here is a clean run
```js
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Custom crypto binding not available
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Client: Trying 10.30.32.48 on port 22 ...
2021-09-21 21:25:12 info:sw-metro-mck-01=> init connect
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Local ident: 'SSH-2.0-ssh2js1.4.0'
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Socket connected
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Remote ident: 'SSH-2.0--'
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Outbound: Sending KEXINIT
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Inbound: Handshake in progress
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Handshake: (local) KEX method: diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Handshake: (remote) KEX method: diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Handshake: KEX algorithm: diffie-hellman-group14-sha1
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Handshake: (local) Host key format: ssh-rsa,ssh-dss
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Handshake: (remote) Host key format: ecdsa-sha2-nistp521,ssh-dss,ssh-rsa
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Handshake: Host key format: ssh-rsa
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Handshake: (local) C->S cipher: aes256-ctr
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Handshake: (remote) C->S cipher: aes256-ctr,aes128-ctr,aes256-cbc,aes128-cbc,3des-cbc
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Handshake: C->S Cipher: aes256-ctr
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Handshake: (local) S->C cipher: aes256-ctr
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Handshake: (remote) S->C cipher: aes256-ctr,aes128-ctr,aes256-cbc,aes128-cbc,3des-cbc
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Handshake: S->C cipher: aes256-ctr
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Handshake: (remote) C->S MAC: hmac-sha2-256,hmac-sha2-256-96,hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-96
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Handshake: C->S MAC: hmac-sha2-256
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Handshake: (remote) S->C MAC: hmac-sha2-256,hmac-sha2-256-96,hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-96
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Handshake: S->C MAC: hmac-sha2-256
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Handshake: (remote) C->S compression: none,zlib
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Handshake: C->S compression: none
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Handshake: (remote) S->C compression: none,zlib
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Handshake: S->C compression: none
2021-09-21 21:25:12 warn:sw-metro-mck-01=> debug => Outbound: Sending KEXDH_INIT
2021-09-21 21:25:13 warn:sw-metro-mck-01=> debug => Received DH Reply
2021-09-21 21:25:13 warn:sw-metro-mck-01=> debug => Host accepted by default (no verification)
2021-09-21 21:25:13 warn:sw-metro-mck-01=> debug => Host accepted (verified)
2021-09-21 21:25:13 warn:sw-metro-mck-01=> debug => Outbound: Sending NEWKEYS
2021-09-21 21:25:13 warn:sw-metro-mck-01=> debug => Inbound: NEWKEYS
2021-09-21 21:25:13 warn:sw-metro-mck-01=> debug => Verifying signature ...
2021-09-21 21:25:13 warn:sw-metro-mck-01=> debug => Verified signature
2021-09-21 21:25:13 warn:sw-metro-mck-01=> debug => Handshake completed
2021-09-21 21:25:13 warn:sw-metro-mck-01=> debug => Outbound: Sending SERVICE_REQUEST (ssh-userauth)
2021-09-21 21:25:13 warn:sw-metro-mck-01=> debug => Inbound: Received SERVICE_ACCEPT (ssh-userauth)
2021-09-21 21:25:13 warn:sw-metro-mck-01=> debug => Outbound: Sending USERAUTH_REQUEST (none)
2021-09-21 21:25:13 warn:sw-metro-mck-01=> debug => Inbound: Received USERAUTH_FAILURE (publickey,keyboard-interactive,password)
2021-09-21 21:25:13 warn:sw-metro-mck-01=> debug => Client: none auth failed
2021-09-21 21:25:13 warn:sw-metro-mck-01=> debug => Outbound: Sending USERAUTH_REQUEST (password)
2021-09-21 21:25:13 warn:sw-metro-mck-01=> debug => Inbound: Received USERAUTH_SUCCESS
2021-09-21 21:25:13 info:sw-metro-mck-01=> connection ready
2021-09-21 21:25:13 warn:sw-metro-mck-01=> debug => Outbound: Sending CHANNEL_OPEN (r:0, session)
2021-09-21 21:25:13 warn:sw-metro-mck-01=> debug => Inbound: CHANNEL_OPEN_CONFIRMATION (r:0, s:2)
2021-09-21 21:25:13 warn:sw-metro-mck-01=> debug => Outbound: Sending CHANNEL_REQUEST (r:2, exec: display pw
)
2021-09-21 21:25:13 warn:sw-metro-mck-01=> debug => Inbound: CHANNEL_SUCCESS (r:0)
2021-09-21 21:25:13 warn:sw-metro-mck-01=> debug => Inbound: CHANNEL_DATA (r:0, 99)
2021-09-21 21:25:13 warn:sw-metro-mck-01=> debug => Inbound: CHANNEL_DATA (r:0, 60)
2021-09-21 21:25:13 info:sw-metro-mck-01=> data => 
Info: The max number of VTY users is 10, and the number
      of current VTY users on line is 2.
2021-09-21 21:25:13 info:sw-metro-mck-01=> data => 
      The current login time is 2021-09-22 08:10:23+00:00.
2021-09-21 21:25:13 warn:sw-metro-mck-01=> debug => Inbound: CHANNEL_DATA (r:0, 34)
2021-09-21 21:25:13 info:sw-metro-mck-01=> data => 
 Total PW template number : 0 

2021-09-21 21:25:13 warn:sw-metro-mck-01=> debug => Inbound: CHANNEL_DATA (r:0, 19)
2021-09-21 21:25:13 info:sw-metro-mck-01=> data => 
<sw-metro-mck-01>
2021-09-21 21:25:13 warn:sw-metro-mck-01=> debug => Socket error: read ECONNRESET
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read',
  level: 'client-socket'
}
2021-09-21 21:25:13 warn:sw-metro-mck-01=> debug => Socket closed
```
A ssh debug run
```js
OpenSSH_8.2p1 Ubuntu-4ubuntu0.3, OpenSSL 1.1.1f  31 Mar 2020
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug2: resolve_canonicalize: hostname 10.30.32.48 is address
debug2: ssh_connect_direct
debug1: Connecting to 10.30.32.48 [10.30.32.48] port 22.
debug1: Connection established.
debug1: identity file /home/alangregory/.ssh/id_rsa type -1
debug1: identity file /home/alangregory/.ssh/id_rsa-cert type -1
debug1: identity file /home/alangregory/.ssh/id_dsa type -1
debug1: identity file /home/alangregory/.ssh/id_dsa-cert type -1
debug1: identity file /home/alangregory/.ssh/id_ecdsa type -1
debug1: identity file /home/alangregory/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/alangregory/.ssh/id_ecdsa_sk type -1
debug1: identity file /home/alangregory/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /home/alangregory/.ssh/id_ed25519 type -1
debug1: identity file /home/alangregory/.ssh/id_ed25519-cert type -1
debug1: identity file /home/alangregory/.ssh/id_ed25519_sk type -1
debug1: identity file /home/alangregory/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /home/alangregory/.ssh/id_xmss type -1
debug1: identity file /home/alangregory/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.3
debug1: Remote protocol version 2.0, remote software version -
debug1: no match: -
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to 10.30.32.48:22 as 'opcaotelecom'
debug3: hostkeys_foreach: reading file "/home/alangregory/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /home/alangregory/.ssh/known_hosts:1
debug3: load_hostkeys: loaded 1 keys from 10.30.32.48
debug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group-exchange-sha1,ext-info-c
debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,ssh-ed25519,sk-ssh-ed25519@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1
debug2: host key algorithms: ecdsa-sha2-nistp521,ssh-dss,ssh-rsa
debug2: ciphers ctos: aes256-ctr,aes128-ctr,aes256-cbc,aes128-cbc,3des-cbc
debug2: ciphers stoc: aes256-ctr,aes128-ctr,aes256-cbc,aes128-cbc,3des-cbc
debug2: MACs ctos: hmac-sha2-256,hmac-sha2-256-96,hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-96
debug2: MACs stoc: hmac-sha2-256,hmac-sha2-256-96,hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-96
debug2: compression ctos: none,zlib
debug2: compression stoc: none,zlib
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug1: kex: algorithm: diffie-hellman-group-exchange-sha1
debug1: kex: host key algorithm: ecdsa-sha2-nistp521
debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha2-256 compression: none
debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha2-256 compression: none
debug3: send packet: type 34
debug1: SSH2_MSG_KEX_DH_GEX_REQUEST(2048<8192<8192) sent
debug3: receive packet: type 31
debug1: got SSH2_MSG_KEX_DH_GEX_GROUP
debug2: bits set: 2020/4096
debug3: send packet: type 32
debug1: SSH2_MSG_KEX_DH_GEX_INIT sent
debug3: receive packet: type 33
debug1: got SSH2_MSG_KEX_DH_GEX_REPLY
debug1: Server host key: ecdsa-sha2-nistp521 SHA256:ylg8LwHxfzxq2nDDX5M6rPGqD/1UwdPLYLOmQRMrWT4
debug3: hostkeys_foreach: reading file "/home/alangregory/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /home/alangregory/.ssh/known_hosts:1
debug3: load_hostkeys: loaded 1 keys from 10.30.32.48
debug1: Host '10.30.32.48' is known and matches the ECDSA host key.
debug1: Found key in /home/alangregory/.ssh/known_hosts:1
debug2: bits set: 2088/4096
debug3: send packet: type 21
debug2: set_newkeys: mode 1
debug1: rekey out after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug1: SSH2_MSG_NEWKEYS received
debug2: set_newkeys: mode 0
debug1: rekey in after 4294967296 blocks
debug1: Will attempt key: /home/alangregory/.ssh/id_rsa 
debug1: Will attempt key: /home/alangregory/.ssh/id_dsa 
debug1: Will attempt key: /home/alangregory/.ssh/id_ecdsa 
debug1: Will attempt key: /home/alangregory/.ssh/id_ecdsa_sk 
debug1: Will attempt key: /home/alangregory/.ssh/id_ed25519 
debug1: Will attempt key: /home/alangregory/.ssh/id_ed25519_sk 
debug1: Will attempt key: /home/alangregory/.ssh/id_xmss 
debug2: pubkey_prepare: done
debug3: send packet: type 5
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,keyboard-interactive,password
debug3: start over, passed a different list publickey,keyboard-interactive,password
debug3: preferred gssapi-with-mic,publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Trying private key: /home/alangregory/.ssh/id_rsa
debug3: no such identity: /home/alangregory/.ssh/id_rsa: No such file or directory
debug1: Trying private key: /home/alangregory/.ssh/id_dsa
debug3: no such identity: /home/alangregory/.ssh/id_dsa: No such file or directory
debug1: Trying private key: /home/alangregory/.ssh/id_ecdsa
debug3: no such identity: /home/alangregory/.ssh/id_ecdsa: No such file or directory
debug1: Trying private key: /home/alangregory/.ssh/id_ecdsa_sk
debug3: no such identity: /home/alangregory/.ssh/id_ecdsa_sk: No such file or directory
debug1: Trying private key: /home/alangregory/.ssh/id_ed25519
debug3: no such identity: /home/alangregory/.ssh/id_ed25519: No such file or directory
debug1: Trying private key: /home/alangregory/.ssh/id_ed25519_sk
debug3: no such identity: /home/alangregory/.ssh/id_ed25519_sk: No such file or directory
debug1: Trying private key: /home/alangregory/.ssh/id_xmss
debug3: no such identity: /home/alangregory/.ssh/id_xmss: No such file or directory
debug2: we did not send a packet, disable method
debug3: authmethod_lookup keyboard-interactive
debug3: remaining preferred: password
debug3: authmethod_is_enabled keyboard-interactive
debug1: Next authentication method: keyboard-interactive
debug2: userauth_kbdint
debug3: send packet: type 50
debug2: we sent a keyboard-interactive packet, wait for reply
debug3: receive packet: type 60
debug2: input_userauth_info_req
User Authentication
debug2: input_userauth_info_req: num_prompts 1
Password: 
debug3: send packet: type 61
debug3: receive packet: type 52
debug1: Authentication succeeded (keyboard-interactive).
Authenticated to 10.30.32.48 ([10.30.32.48]:22).
debug1: channel 0: new [client-session]
debug3: ssh_session2_open: channel_new: 0
debug2: channel 0: send open
debug3: send packet: type 90
debug1: Entering interactive session.
debug1: pledge: network
debug3: receive packet: type 91
debug2: channel_input_open_confirmation: channel 0: callback start
debug2: fd 3 setting TCP_NODELAY
debug3: ssh_packet_set_tos: set IP_TOS 0x10
debug2: client_session2_setup: id 0
debug2: channel 0: request pty-req confirm 1
debug3: send packet: type 98
debug1: Sending environment.
debug3: Ignored env SHELL
debug3: Ignored env COLORTERM
debug3: Ignored env TERM_PROGRAM_VERSION
debug3: Ignored env WSL_DISTRO_NAME
debug3: Ignored env NAME
debug3: Ignored env PWD
debug3: Ignored env LOGNAME
debug3: Ignored env VSCODE_GIT_ASKPASS_NODE
debug3: Ignored env MOTD_SHOWN
debug3: Ignored env HOME
debug1: Sending env LANG = C.UTF-8
debug2: channel 0: request env confirm 0
debug3: send packet: type 98
debug3: Ignored env WSL_INTEROP
debug3: Ignored env LS_COLORS
debug3: Ignored env GIT_ASKPASS
debug3: Ignored env LESSCLOSE
debug3: Ignored env TERM
debug3: Ignored env LESSOPEN
debug3: Ignored env USER
debug3: Ignored env VSCODE_GIT_IPC_HANDLE
debug3: Ignored env SHLVL
debug3: Ignored env WSLENV
debug3: Ignored env VSCODE_GIT_ASKPASS_MAIN
debug3: Ignored env XDG_DATA_DIRS
debug3: Ignored env PATH
debug3: Ignored env HOSTTYPE
debug3: Ignored env TERM_PROGRAM
debug3: Ignored env VSCODE_IPC_HOOK_CLI
debug3: Ignored env _
debug2: channel 0: request shell confirm 1
debug3: send packet: type 98
debug2: channel_input_open_confirmation: channel 0: callback done
debug2: channel 0: open confirm rwindow 131072 rmax 32768
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: PTY allocation request accepted on channel 0
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: shell request accepted on channel 0

Info: The max number of VTY users is 10, and the number
      of current VTY users on line is 2.
      The current login time is 2021-09-22 08:12:00+00:00.
<sw-metro-mck-01>dis pw
 Total PW template number : 0 

<sw-metro-mck-01>dis pw
 Total PW template number : 0 

<sw-metro-mck-01>q
Info: The max number of VTY users is 10, and the number
      of current VTY users on line is 1.debug3: receive packet: type 97
debug2: channel 0: rcvd close
debug2: channel 0: output open -> drain
debug2: channel 0: chan_shutdown_read (i0 o1 sock -1 wfd 4 efd 6 [write])
debug2: channel 0: input open -> closed
debug3: channel 0: will not send data after close
debug2: channel 0: obuf empty
debug2: channel 0: chan_shutdown_write (i3 o1 sock -1 wfd 5 efd 6 [write])
debug2: channel 0: output drain -> closed
debug2: channel 0: almost dead
debug2: channel 0: gc: notify user
debug2: channel 0: gc: user detached
debug2: channel 0: send close
debug3: send packet: type 97
debug2: channel 0: is dead
debug2: channel 0: garbage collecting
debug1: channel 0: free: client-session, nchannels 1
debug3: channel 0: status: The following connections are open:
  #0 client-session (t4 r2 i3/0 o3/0 e[write]/0 fd -1/-1/6 sock -1 cc -1)

debug3: send packet: type 1
debug3: fd 1 is not O_NONBLOCK
Connection to 10.30.32.48 closed.
Transferred: sent 3392, received 3248 bytes, in 30.8 seconds
Bytes per second: sent 110.0, received 105.3
debug1: Exit status -1
```

**Comment by mscdex** [comment]
So I'm guessing in the OpenSSH case you started an interactive session and didn't specify the command to execute on the command line?

In `ssh2`, using `exec()` is equivalent to doing something like `ssh user@example.org 'display pw'` in OpenSSH.
Using `shell()` is equivalent to doing something like `ssh user@example.org` in OpenSSH and then manually typing `'display pw'` followed by enter.

I would suggest trying to do use the same type of action to make sure it's not a weird server quirk where it has issues specifically with commands executed via `exec()`. I know I've seen Cisco and other specialized systems that are buggy and really only support interactive sessions.

**Comment by alangregory** [comment]
Tested with exec on ssh client, looks like the server is not ending the exec gracefully. Going to check it directly with huawei.
```js
User Authentication
Password: 

Info: The max number of VTY users is 10, and the number
      of current VTY users on line is 1.
      The current login time is x
Info: Lastest accessed IP:x  Time: x  Failed: 0

<sw-metro-mck-01>display pw
 Total PW template number : 0 

<sw-metro-mck-01>client_loop: send disconnect: Broken pipe
```
