### ISSUE TITLE
Handshake failed: no matching host key format

### ISSUE THREAD

**Issue by aymaddi** [mscdex/ssh2#1069]
Node-scp, use to work with following configuration,
 It stopped working when host system got enabled rsa-sha2-256 and rsa-sha2-512. We tried keeping tryKeyboard: true as well.
Error: Handshake failed: no matching host key format

Do we required to do anything else here?
Node version: 8.9

Client({
			host: clinetHost
			port: 22,
			username: uName,
			password: uPass,
		});

**Comment by mscdex** [comment]
Are you using the latest version of `ssh2`?

What is displayed for the handshake in the debug output if you set `debug: console.log` in your connection config object?

**Comment by aymaddi** [comment]
@mscdex 
ssh2 version: 1.1.0

error: Error: Handshake failed: no matching host key format
    at makeError (/home/node/app/node_modules/ssh2/lib/protocol/utils.js:142:15)
    at doFatalError (/home/node/app/node_modules/ssh2/lib/protocol/utils.js:184:13)
    at handleKexInit (/home/node/app/node_modules/ssh2/lib/protocol/kex.js:274:12)
    at Protocol.onKEXPayload (/home/node/app/node_modules/ssh2/lib/protocol/kex.js:1755:14)
    at NullDecipher.decrypt (/home/node/app/node_modules/ssh2/lib/protocol/crypto.js:617:26)
    at Protocol.parsePacket [as _parse] (/home/node/app/node_modules/ssh2/lib/protocol/Protocol.js:1990:25)
    at Protocol.parse (/home/node/app/node_modules/ssh2/lib/protocol/Protocol.js:292:16)
    at Socket.sock.on (/home/node/app/node_modules/ssh2/lib/client.js:712:21)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by mscdex** [comment]
The error is pretty self-explanatory. The client and server couldn't agree on a server host key format.

One quick and easy way to see what the server is offering is to just set `debug: console.log` in your connection config object passed to `connect()` and it will show the handshake between the client and server and what each side offers.

**Comment by aymaddi** [comment]
@mscdex  It's working now, earlier i was using ssh2 version: 1.1.0.
Now I updated it to 1.4.0 then it started working. 
thank you so much for your assistance.
