### ISSUE TITLE
Error installing ssh2 v1.4.0 on CentOS 7

### ISSUE THREAD

**Issue by ovlad** [mscdex/ssh2#1074]
Environment:
- CentOS **7**
- Node.js **14.17.5**
- NPM **6.14.14**

Running the `npm install ssh2` command results in the following error:
```
> cpu-features@0.0.2 install /data/ovlad/testproj/node_modules/cpu-features
> node-gyp rebuild

make: Entering directory `/data/ovlad/testproj/node_modules/cpu-features/build'
  ACTION Configuring dependencies /data/ovlad/testproj/node_modules/cpu-features/deps/cpu_features/build/Makefile
/bin/sh: cmake: command not found
make: *** [/data/ovlad/testproj/node_modules/cpu-features/deps/cpu_features/build/Makefile] Error 127
make: Leaving directory `/data/ovlad/testproj/node_modules/cpu-features/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 3.10.0-1127.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/ovlad/testproj/node_modules/cpu-features
gyp ERR! node -v v14.17.5
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

> ssh2@1.4.0 install /data/ovlad/testproj/node_modules/ssh2
> node install.js

make: Entering directory `/data/ovlad/testproj/node_modules/ssh2/lib/protocol/crypto/build'
  CXX(target) Release/obj.target/sshcrypto/src/binding.o
make: g++: Command not found
make: *** [Release/obj.target/sshcrypto/src/binding.o] Error 127
make: Leaving directory `/data/ovlad/testproj/node_modules/ssh2/lib/protocol/crypto/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 3.10.0-1127.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "--target=v14.17.5" "rebuild"
gyp ERR! cwd /data/ovlad/testproj/node_modules/ssh2/lib/protocol/crypto
gyp ERR! node -v v14.17.5
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
Failed to build optional crypto binding
npm WARN saveError ENOENT: no such file or directory, open '/data/ovlad/testproj/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/data/ovlad/testproj/package.json'
npm WARN testproj No description
npm WARN testproj No repository field.
npm WARN testproj No README data
npm WARN testproj No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: cpu-features@0.0.2 (node_modules/cpu-features):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: cpu-features@0.0.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ ssh2@1.4.0
added 6 packages from 16 contributors and audited 7 packages in 2.072s
found 0 vulnerabilities

```

**Comment by mscdex** [comment]
The module installed fine, the only thing that didn't get installed were the *optional* dependencies. If you want to fix those, you need cmake (for `cpu-features`) and a proper build environment (e.g. `sudo apt install build-essential` on Ubuntu) (for both `cpu-features` and the built-in custom crypto binding).

**Comment by danmihai89** [comment]
@mscdex The problem is that we don't want an error message with each deploy and we don't need those optional dependencies.

We just want to get rid of that error message and not have to install `cmake` or any other system package in our env.
We just need the latest clean version of `ssh2`, without having to install anything else. We are currently using version `0.8.9`.

Thanks!

**Comment by mscdex** [comment]
That's an issue with npm, not `ssh2`. AFAIU npm v7+ is supposed to be more silent about optional dependency errors.

**Comment by ovlad** [comment]
Thank you for your answer!
Perhaps a small clarification in the documentation that the lack of a certain system utility will lead to an installation with the issuance of an error would better define the optionality of the `cpu-features` package.
Thanks again!

**Comment by mscdex** [comment]
@ovlad  I'm not sure what you're asking for that isn't already [in the readme](https://github.com/mscdex/ssh2#requirements).
