### ISSUE TITLE
fastGet not working with concurrency > 1

### ISSUE THREAD

**Issue by cah-andy-kim** [mscdex/ssh2#1078]
```
await sftpClient.fastGet(
    '/client/C/blah/blah.zip',
    process.cwd() + '/testZip.zip',
    {
        concurrency: 2,
    },
);
```
When I use a concurrency > 1, the fastGet returns a "No such file" exception. However, switching to concurrency = 1 succeeds. Is this a problem with my implementation? I am on Node 14, and I do a `exists()` call before this get, so I know it exists on the SFTP server.

**Comment by mscdex** [comment]
Can you post the debug output (at least up until/including one SFTP read) from both scenarios? Set `debug: console.log` in the connection config object to have debug output printed to the console.

**Comment by cah-andy-kim** [comment]
Concurrency = 1
```
CLIENT[sftp]: connect: Debugging turned on
CLIENT[sftp]: connect: Connect attempt 1
CLIENT[sftp]: getConnection: Adding temp event listeners
CLIENT[sftp]: getConnection: created promise
CLIENT[sftp]: Adding listener to ready event
Custom crypto binding available
Client: Trying *** on port 22 ...
Local ident: 'SSH-2.0-ssh2js1.3.0'
Socket connected
Remote ident: 'SSH-2.0-9.99 sshlib'
Outbound: Sending KEXINIT
Inbound: Handshake in progress
Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
Handshake: (remote) KEX method: diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
Handshake: KEX algorithm: diffie-hellman-group-exchange-sha256
Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
Handshake: (remote) Host key format: ssh-rsa
Handshake: Host key format: ssh-rsa
Handshake: (local) C->S cipher: aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
Handshake: (remote) C->S cipher: aes256-ctr,twofish256-ctr,twofish-ctr,aes128-ctr,twofish128-ctr,3des-ctr,cast128-ctr,aes256-cbc,twofish256-cbc,twofish-cbc,aes128-cbc,twofish128-cbc,blowfish-cbc,3des-cbc,arcfour,cast128-cbc
Handshake: C->S Cipher: aes128-ctr
Handshake: (local) S->C cipher: aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
Handshake: (remote) S->C cipher: aes256-ctr,twofish256-ctr,twofish-ctr,aes128-ctr,twofish128-ctr,3des-ctr,cast128-ctr,aes256-cbc,twofish256-cbc,twofish-cbc,aes128-cbc,twofish128-cbc,blowfish-cbc,3des-cbc,arcfour,cast128-cbc
Handshake: S->C cipher: aes128-ctr
Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
Handshake: (remote) C->S MAC: hmac-sha2-512,hmac-sha2-256,hmac-sha1,hmac-md5,hmac-sha1-96,hmac-md5-96
Handshake: C->S MAC: hmac-sha2-256
Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
Handshake: (remote) S->C MAC: hmac-sha2-512,hmac-sha2-256,hmac-sha1,hmac-md5,hmac-sha1-96,hmac-md5-96
Handshake: S->C MAC: hmac-sha2-256
Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
Handshake: (remote) C->S compression: zlib,none
Handshake: C->S compression: none
Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
Handshake: (remote) S->C compression: zlib,none
Handshake: S->C compression: none
Outbound: Sending KEXDH_GEX_REQUEST
Received DH GEX Group
Outbound: Sending KEXDH_GEX_INIT
Received DH GEX Reply
Received DH Reply
Host accepted by default (no verification)
Host accepted (verified)
Outbound: Sending NEWKEYS
Inbound: NEWKEYS
Verifying signature ...
Verified signature
Handshake completed
Outbound: Sending SERVICE_REQUEST (ssh-userauth)
Inbound: Received SERVICE_ACCEPT (ssh-userauth)
Outbound: Sending USERAUTH_REQUEST (none)
Inbound: Received USERAUTH_FAILURE (publickey,password)
Client: none auth failed
Outbound: Sending USERAUTH_REQUEST (password)
Inbound: Received USERAUTH_SUCCESS
CLIENT[sftp]: getConnection: got connection - promise resolved
CLIENT[sftp]: getConnection: finally clause fired
CLIENT[sftp]: Removing listener from ready event
CLIENT[sftp]: getConnection: Removing temp event listeners
CLIENT[sftp]: getSftpChannel: Adding temp event listeners
CLIENT[sftp]: getSftpChannel: created promise
Outbound: Sending CHANNEL_OPEN (r:0, session)
Inbound: CHANNEL_OPEN_CONFIRMATION (r:0, s:0)
Outbound: Sending CHANNEL_REQUEST (r:0, subsystem: sftp)
Inbound: CHANNEL_SUCCESS (r:0)
Outbound: Sending CHANNEL_DATA (r:0, 9)
Inbound: CHANNEL_DATA (r:0, 9)
SFTP: Inbound: Received VERSION (v3)
CLIENT[sftp]: getSftpChannel: SFTP channel established
CLIENT[sftp]: getSftpChannel: finally clause fired
CLIENT[sftp]: getSftpChannel: Removing temp event listeners
CLIENT[sftp]: exists: /client/C/Production/Active/blah-20211005.zip -> /client/C/Production/Active/blah-20211005.zip
CLIENT[sftp]: _stat: /client/C/Production/Active/blah-20211005.zip
CLIENT[sftp]: _stat: Adding temp event listeners
Outbound: Sending CHANNEL_DATA (r:0, 76)
SFTP: Outbound: Buffered STAT
Inbound: CHANNEL_DATA (r:0, 41)
SFTP: Inbound: Received ATTRS (id:0)
CLIENT[sftp]: _stat: stats <-  {
 "mode": 33279,
 "uid": 0,
 "gid": 0,
 "size": 340536667,
 "accessTime": 1633500055000,
 "modifyTime": 1633500055000,
 "isDirectory": false,
 "isFile": true,
 "isBlockDevice": false,
 "isCharacterDevice": false,
 "isSymbolicLink": false,
 "isFIFO": false,
 "isSocket": false
}
CLIENT[sftp]: stat: Removing temp event listeners
CLIENT[sftp]: exists: <-  {
 "mode": 33279,
 "uid": 0,
 "gid": 0,
 "size": 340536667,
 "accessTime": 1633500055000,
 "modifyTime": 1633500055000,
 "isDirectory": false,
 "isFile": true,
 "isBlockDevice": false,
 "isCharacterDevice": false,
 "isSymbolicLink": false,
 "isFIFO": false,
 "isSocket": false
}
CLIENT[sftp]: exists: /client/C/Production/Active/blah-20211005.zip = -
CLIENT[sftp]: exists: /client/C/Production/blah/blah-20211005.zip -> /client/C/Production/blah/blah-20211005.zip
CLIENT[sftp]: _stat: /client/C/Production/blah/blah-20211005.zip
CLIENT[sftp]: _stat: Adding temp event listeners
Outbound: Sending CHANNEL_DATA (r:0, 73)
SFTP: Outbound: Buffered STAT
Inbound: CHANNEL_DATA (r:0, 35)
SFTP: Inbound: Received STATUS (id:1, 2, "No such file")
CLIENT[sftp]: _stat: Error No such file code: 2
CLIENT[sftp]: stat: Removing temp event listeners
CLIENT[sftp]: exists: /client/C/Production/blah/blah-20211005.zip = false errorCode = ENOENT
CLIENT[sftp]: exists: /client/C/Production/Active/blah-20211005.zip -> /client/C/Production/Active/blah-20211005.zip
CLIENT[sftp]: _stat: /client/C/Production/Active/blah-20211005.zip
CLIENT[sftp]: _stat: Adding temp event listeners
Outbound: Sending CHANNEL_DATA (r:0, 76)
SFTP: Outbound: Buffered STAT
Inbound: CHANNEL_DATA (r:0, 41)
SFTP: Inbound: Received ATTRS (id:2)
CLIENT[sftp]: _stat: stats <-  {
 "mode": 33279,
 "uid": 0,
 "gid": 0,
 "size": 340536667,
 "accessTime": 1633500055000,
 "modifyTime": 1633500055000,
 "isDirectory": false,
 "isFile": true,
 "isBlockDevice": false,
 "isCharacterDevice": false,
 "isSymbolicLink": false,
 "isFIFO": false,
 "isSocket": false
}
CLIENT[sftp]: stat: Removing temp event listeners
CLIENT[sftp]: exists: <-  {
 "mode": 33279,
 "uid": 0,
 "gid": 0,
 "size": 340536667,
 "accessTime": 1633500055000,
 "modifyTime": 1633500055000,
 "isDirectory": false,
 "isFile": true,
 "isBlockDevice": false,
 "isCharacterDevice": false,
 "isSymbolicLink": false,
 "isFIFO": false,
 "isSocket": false
}
CLIENT[sftp]: exists: /client/C/Production/Active/blah-20211005.zip = -
CLIENT[sftp]: fastGet -> remote: /client/C/Production/Active/blah-20211005.zip local: /Users/asdfasd/Projects/late-service/testZip.zip  {
 "concurrency": 1
}
CLIENT[sftp]: fastGet: Adding temp event listeners
Outbound: Sending CHANNEL_DATA (r:0, 84)
SFTP: Outbound: Buffered OPEN
Inbound: CHANNEL_DATA (r:0, 31965)
SFTP: Inbound: Received DATA (id:5, 31952)
Outbound: Sending CHANNEL_DATA (r:0, 29)
SFTP: Outbound: Buffered READ
Inbound: CHANNEL_DATA (r:0, 829)
SFTP: Inbound: Received DATA (id:8, 816)
```

Concurrency = 2
```
CLIENT[sftp]: connect: Debugging turned on
CLIENT[sftp]: connect: Connect attempt 1
CLIENT[sftp]: getConnection: Adding temp event listeners
CLIENT[sftp]: getConnection: created promise
CLIENT[sftp]: Adding listener to ready event
Custom crypto binding available
Client: Trying *** on port 22 ...
Local ident: 'SSH-2.0-ssh2js1.3.0'
Socket connected
Remote ident: 'SSH-2.0-9.99 sshlib'
Outbound: Sending KEXINIT
Inbound: Handshake in progress
Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
Handshake: (remote) KEX method: diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
Handshake: KEX algorithm: diffie-hellman-group-exchange-sha256
Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
Handshake: (remote) Host key format: ssh-rsa
Handshake: Host key format: ssh-rsa
Handshake: (local) C->S cipher: aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
Handshake: (remote) C->S cipher: aes256-ctr,twofish256-ctr,twofish-ctr,aes128-ctr,twofish128-ctr,3des-ctr,cast128-ctr,aes256-cbc,twofish256-cbc,twofish-cbc,aes128-cbc,twofish128-cbc,blowfish-cbc,3des-cbc,arcfour,cast128-cbc
Handshake: C->S Cipher: aes128-ctr
Handshake: (local) S->C cipher: aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
Handshake: (remote) S->C cipher: aes256-ctr,twofish256-ctr,twofish-ctr,aes128-ctr,twofish128-ctr,3des-ctr,cast128-ctr,aes256-cbc,twofish256-cbc,twofish-cbc,aes128-cbc,twofish128-cbc,blowfish-cbc,3des-cbc,arcfour,cast128-cbc
Handshake: S->C cipher: aes128-ctr
Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
Handshake: (remote) C->S MAC: hmac-sha2-512,hmac-sha2-256,hmac-sha1,hmac-md5,hmac-sha1-96,hmac-md5-96
Handshake: C->S MAC: hmac-sha2-256
Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
Handshake: (remote) S->C MAC: hmac-sha2-512,hmac-sha2-256,hmac-sha1,hmac-md5,hmac-sha1-96,hmac-md5-96
Handshake: S->C MAC: hmac-sha2-256
Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
Handshake: (remote) C->S compression: zlib,none
Handshake: C->S compression: none
Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
Handshake: (remote) S->C compression: zlib,none
Handshake: S->C compression: none
Outbound: Sending KEXDH_GEX_REQUEST
Received DH GEX Group
Outbound: Sending KEXDH_GEX_INIT
Received DH GEX Reply
Received DH Reply
Host accepted by default (no verification)
Host accepted (verified)
Outbound: Sending NEWKEYS
Inbound: NEWKEYS
Verifying signature ...
Verified signature
Handshake completed
Outbound: Sending SERVICE_REQUEST (ssh-userauth)
Inbound: Received SERVICE_ACCEPT (ssh-userauth)
Outbound: Sending USERAUTH_REQUEST (none)
Inbound: Received USERAUTH_FAILURE (publickey,password)
Client: none auth failed
Outbound: Sending USERAUTH_REQUEST (password)
Inbound: Received USERAUTH_SUCCESS
CLIENT[sftp]: getConnection: got connection - promise resolved
CLIENT[sftp]: getConnection: finally clause fired
CLIENT[sftp]: Removing listener from ready event
CLIENT[sftp]: getConnection: Removing temp event listeners
CLIENT[sftp]: getSftpChannel: Adding temp event listeners
CLIENT[sftp]: getSftpChannel: created promise
Outbound: Sending CHANNEL_OPEN (r:0, session)
Inbound: CHANNEL_OPEN_CONFIRMATION (r:0, s:0)
Outbound: Sending CHANNEL_REQUEST (r:0, subsystem: sftp)
Inbound: CHANNEL_SUCCESS (r:0)
Outbound: Sending CHANNEL_DATA (r:0, 9)
Inbound: CHANNEL_DATA (r:0, 9)
SFTP: Inbound: Received VERSION (v3)
CLIENT[sftp]: getSftpChannel: SFTP channel established
CLIENT[sftp]: getSftpChannel: finally clause fired
CLIENT[sftp]: getSftpChannel: Removing temp event listeners
CLIENT[sftp]: exists: /client/C/Production/Active/blah-20211005.zip -> /client/C/Production/Active/blah-20211005.zip
CLIENT[sftp]: _stat: /client/C/Production/Active/blah-20211005.zip
CLIENT[sftp]: _stat: Adding temp event listeners
Outbound: Sending CHANNEL_DATA (r:0, 76)
SFTP: Outbound: Buffered STAT
Inbound: CHANNEL_DATA (r:0, 41)
SFTP: Inbound: Received ATTRS (id:0)
CLIENT[sftp]: _stat: stats <-  {
 "mode": 33279,
 "uid": 0,
 "gid": 0,
 "size": 340536667,
 "accessTime": 1633500055000,
 "modifyTime": 1633500055000,
 "isDirectory": false,
 "isFile": true,
 "isBlockDevice": false,
 "isCharacterDevice": false,
 "isSymbolicLink": false,
 "isFIFO": false,
 "isSocket": false
}
CLIENT[sftp]: stat: Removing temp event listeners
CLIENT[sftp]: exists: <-  {
 "mode": 33279,
 "uid": 0,
 "gid": 0,
 "size": 340536667,
 "accessTime": 1633500055000,
 "modifyTime": 1633500055000,
 "isDirectory": false,
 "isFile": true,
 "isBlockDevice": false,
 "isCharacterDevice": false,
 "isSymbolicLink": false,
 "isFIFO": false,
 "isSocket": false
}
CLIENT[sftp]: exists: /client/C/Production/Active/blah-20211005.zip = -
CLIENT[sftp]: exists: /client/C/Production/blah/blah-20211005.zip -> /client/C/Production/blah/blah-20211005.zip
CLIENT[sftp]: _stat: /client/C/Production/blah/blah-20211005.zip
CLIENT[sftp]: _stat: Adding temp event listeners
Outbound: Sending CHANNEL_DATA (r:0, 73)
SFTP: Outbound: Buffered STAT
Inbound: CHANNEL_DATA (r:0, 35)
SFTP: Inbound: Received STATUS (id:1, 2, "No such file")
CLIENT[sftp]: _stat: Error No such file code: 2
CLIENT[sftp]: stat: Removing temp event listeners
CLIENT[sftp]: exists: /client/C/Production/blah/blah-20211005.zip = false errorCode = ENOENT
CLIENT[sftp]: exists: /client/C/Production/Active/blah-20211005.zip -> /client/C/Production/Active/blah-20211005.zip
CLIENT[sftp]: _stat: /client/C/Production/Active/blah-20211005.zip
CLIENT[sftp]: _stat: Adding temp event listeners
Outbound: Sending CHANNEL_DATA (r:0, 76)
SFTP: Outbound: Buffered STAT
Inbound: CHANNEL_DATA (r:0, 41)
SFTP: Inbound: Received ATTRS (id:2)
CLIENT[sftp]: _stat: stats <-  {
 "mode": 33279,
 "uid": 0,
 "gid": 0,
 "size": 340536667,
 "accessTime": 1633500055000,
 "modifyTime": 1633500055000,
 "isDirectory": false,
 "isFile": true,
 "isBlockDevice": false,
 "isCharacterDevice": false,
 "isSymbolicLink": false,
 "isFIFO": false,
 "isSocket": false
}
CLIENT[sftp]: stat: Removing temp event listeners
CLIENT[sftp]: exists: <-  {
 "mode": 33279,
 "uid": 0,
 "gid": 0,
 "size": 340536667,
 "accessTime": 1633500055000,
 "modifyTime": 1633500055000,
 "isDirectory": false,
 "isFile": true,
 "isBlockDevice": false,
 "isCharacterDevice": false,
 "isSymbolicLink": false,
 "isFIFO": false,
 "isSocket": false
}
CLIENT[sftp]: exists: /client/C/Production/Active/blah-20211005.zip = -
CLIENT[sftp]: fastGet -> remote: /client/C/Production/Active/blah-20211005.zip local: /Users/asdfasd/Projects/late-service/testZip.zip  {
 "concurrency": 2
Inbound: CHANNEL_DATA (r:0, 41)
SFTP: Inbound: Received ATTRS (id:4)
Inbound: CHANNEL_DATA (r:0, 32768)
SFTP: Inbound: Received DATA (id:5, 31952)
Outbound: Sending CHANNEL_DATA (r:0, 29)
SFTP: Outbound: Buffered READ
Inbound: CHANNEL_DATA (r:0, 31162)
SFTP: Inbound: Received DATA (id:6, 31952)
Outbound: Sending CHANNEL_DATA (r:0, 29)
SFTP: Outbound: Buffered READ
Inbound: CHANNEL_DATA (r:0, 829)
SFTP: Inbound: Received DATA (id:8, 816)
Error: fastGet: No such file
    at fmtError (/Users/asdfasd/Projects/late-service/node_modules/ssh2-sftp-client/src/utils.js:55:18)
    at SftpClient.fastGet (/Users/asdfasd/Projects/late-service/node_modules/ssh2-sftp-client/src/index.js:598:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Task.task (file:///Users/asdfasd/Projects/late-service/dist/index.js:78:25) {
  code: 2,
  custom: true,
  context: [Object: null prototype] {}
}
```
