### ISSUE TITLE
Issue with diffie-hellman-group-exchange-sha256 on AWS

### ISSUE THREAD

**Issue by CodeZeno** [mscdex/ssh2#1097]
I am using ssh2-sftp-client however I have also tried ssh2 directly.

Not receiving anything after "Received DH GEX Group"

Using AWS Lambda Node.js 14.x
It does work on Windows 10 Node.js v14.8.0

Any ideas as to what it could be? I did find [Issue](https://github.com/mscdex/ssh2/issues/1031#issuecomment-876463339) which sounds related but was fixed.

```
'use strict';
const ftpClient = require('ssh2-sftp-client');
const sftp = new ftpClient();
exports.handler = (event) => {
  console.log('running');
  sftp.connect({
    host: 'xxx.yyy.zzz',
    port: '22',
    username: 'name',
    password: 'pass',
    debug: function(msg){console.error(msg)}
  }).then(() => {
    console.log('connected');
    return sftp.put(Buffer.from('Hello World'), '/tests/file.txt');
  }).then(data => {
    console.log(data);
    sftp.end();
    return;
  }).catch(err => {
    console.log(err, 'catch error');
    return;
  });
};
```

Not working (AWS Lambda Node.js v14.x):

```
2021-12-02T00:00:06.811Z	INFO	running
2021-12-02T00:00:06.812Z	ERROR	CLIENT[sftp]: connect: Debugging turned on
2021-12-02T00:00:06.812Z	ERROR	CLIENT[sftp]: connect: Connect attempt 1
2021-12-02T00:00:06.812Z	ERROR	CLIENT[sftp]: getConnection: Adding temp event listeners
2021-12-02T00:00:06.812Z	ERROR	CLIENT[sftp]: getConnection: created promise
2021-12-02T00:00:06.812Z	ERROR	CLIENT[sftp]: Adding listener to ready event
2021-12-02T00:00:06.819Z	ERROR	Custom crypto binding not available
2021-12-02T00:00:06.819Z	ERROR	Local ident: 'SSH-2.0-ssh2js1.5.0'
2021-12-02T00:00:06.820Z	ERROR	Client: Trying xxx.yyy.zzz on port 22 ...
2021-12-02T00:00:07.011Z	ERROR	Socket connected
2021-12-02T00:00:07.197Z	ERROR	Remote ident: 'SSH-2.0-7.9.0.0_openssh Globalscape'
2021-12-02T00:00:07.198Z	ERROR	Outbound: Sending KEXINIT
2021-12-02T00:00:07.379Z	ERROR	Inbound: Handshake in progress
2021-12-02T00:00:07.379Z	ERROR	Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
2021-12-02T00:00:07.379Z	ERROR	Handshake: (remote) KEX method: diffie-hellman-group16-sha512,diffie-hellman-group14-sha256,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
2021-12-02T00:00:07.379Z	ERROR	Handshake: KEX algorithm: diffie-hellman-group-exchange-sha256
2021-12-02T00:00:07.379Z	ERROR	Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
2021-12-02T00:00:07.379Z	ERROR	Handshake: (remote) Host key format: ssh-rsa
2021-12-02T00:00:07.379Z	ERROR	Handshake: Host key format: ssh-rsa
2021-12-02T00:00:07.379Z	ERROR	Handshake: (local) C->S cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
2021-12-02T00:00:07.379Z	ERROR	Handshake: (remote) C->S cipher: aes256-cbc,aes256-ctr,aes128-cbc,aes128-ctr
2021-12-02T00:00:07.380Z	ERROR	Handshake: C->S Cipher: aes128-ctr
2021-12-02T00:00:07.380Z	ERROR	Handshake: (local) S->C cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
2021-12-02T00:00:07.380Z	ERROR	Handshake: (remote) S->C cipher: aes256-cbc,aes256-ctr,aes128-cbc,aes128-ctr
2021-12-02T00:00:07.380Z	ERROR	Handshake: S->C cipher: aes128-ctr
2021-12-02T00:00:07.380Z	ERROR	Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
2021-12-02T00:00:07.380Z	ERROR	Handshake: (remote) C->S MAC: hmac-sha2-512,hmac-sha2-256,hmac-sha1
2021-12-02T00:00:07.380Z	ERROR	Handshake: C->S MAC: hmac-sha2-256
2021-12-02T00:00:07.380Z	ERROR	Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
2021-12-02T00:00:07.380Z	ERROR	Handshake: (remote) S->C MAC: hmac-sha2-512,hmac-sha2-256,hmac-sha1
2021-12-02T00:00:07.380Z	ERROR	Handshake: S->C MAC: hmac-sha2-256
2021-12-02T00:00:07.380Z	ERROR	Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
2021-12-02T00:00:07.380Z	ERROR	Handshake: (remote) C->S compression: zlib,none
2021-12-02T00:00:07.380Z	ERROR	Handshake: C->S compression: none
2021-12-02T00:00:07.380Z	ERROR	Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
2021-12-02T00:00:07.380Z	ERROR	Handshake: (remote) S->C compression: zlib,none
2021-12-02T00:00:07.380Z	ERROR	Handshake: S->C compression: none
2021-12-02T00:00:07.380Z	ERROR	Outbound: Sending KEXDH_GEX_REQUEST
2021-12-02T00:00:07.649Z	ERROR	Received DH GEX Group
REPORT RequestId: Duration: 30016.71 ms	Billed Duration: 30000 ms	Memory Size: 1536 MB	Max Memory Used: 70 MB	Init Duration: 279.49 ms	
2021-12-02T00:00:36.819Z Task timed out after 30.02 seconds
```

Working (Windows 10 Node.js v14.8.0):

```
running
CLIENT[sftp]: connect: Debugging turned on
CLIENT[sftp]: connect: Connect attempt 1
CLIENT[sftp]: getConnection: Adding temp event listeners
CLIENT[sftp]: getConnection: created promise
CLIENT[sftp]: Adding listener to ready event
Custom crypto binding available
Local ident: 'SSH-2.0-ssh2js1.5.0'
Client: Trying xxx.yyy.zzz on port 22 ...
Socket connected
Remote ident: 'SSH-2.0-7.9.0.0_openssh Globalscape'
Outbound: Sending KEXINIT
Inbound: Handshake in progress
Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
Handshake: (remote) KEX method: diffie-hellman-group16-sha512,diffie-hellman-group14-sha256,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
Handshake: KEX algorithm: diffie-hellman-group-exchange-sha256
Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
Handshake: (remote) Host key format: ssh-rsa
Handshake: Host key format: ssh-rsa
Handshake: (local) C->S cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
Handshake: (remote) C->S cipher: aes256-cbc,aes256-ctr,aes128-cbc,aes128-ctr
Handshake: C->S Cipher: aes128-ctr
Handshake: (local) S->C cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
Handshake: (remote) S->C cipher: aes256-cbc,aes256-ctr,aes128-cbc,aes128-ctr
Handshake: S->C cipher: aes128-ctr
Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
Handshake: (remote) C->S MAC: hmac-sha2-512,hmac-sha2-256,hmac-sha1
Handshake: C->S MAC: hmac-sha2-256
Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
Handshake: (remote) S->C MAC: hmac-sha2-512,hmac-sha2-256,hmac-sha1
Handshake: S->C MAC: hmac-sha2-256
Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
Handshake: (remote) C->S compression: zlib,none
Handshake: C->S compression: none
Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
Handshake: (remote) S->C compression: zlib,none
Handshake: S->C compression: none
Outbound: Sending KEXDH_GEX_REQUEST
Received DH GEX Group
Outbound: Sending KEXDH_GEX_INIT
Received DH GEX Reply
Received DH Reply
Host accepted by default (no verification)
Host accepted (verified)
Outbound: Sending NEWKEYS
Inbound: NEWKEYS
Verifying signature ...
Verified signature
Handshake completed
Outbound: Sending SERVICE_REQUEST (ssh-userauth)
Inbound: Received SERVICE_ACCEPT (ssh-userauth)
Outbound: Sending USERAUTH_REQUEST (none)
Inbound: Received USERAUTH_BANNER
Inbound: Received USERAUTH_FAILURE (password)
Client: none auth failed
Outbound: Sending USERAUTH_REQUEST (password)
Inbound: Received USERAUTH_SUCCESS
CLIENT[sftp]: getConnection: got connection - promise resolved
CLIENT[sftp]: getConnection: finally clause fired
CLIENT[sftp]: Removing listener from ready event
CLIENT[sftp]: getConnection: Removing temp event listeners
CLIENT[sftp]: getSftpChannel: Adding temp event listeners
CLIENT[sftp]: getSftpChannel: created promise
Outbound: Sending CHANNEL_OPEN (r:0, session)
Inbound: CHANNEL_OPEN_CONFIRMATION (r:0, s:0)
Outbound: Sending CHANNEL_REQUEST (r:0, subsystem: sftp)
Inbound: CHANNEL_WINDOW_ADJUST (r:0, 2097152)
Inbound: CHANNEL_SUCCESS (r:0)
Outbound: Sending CHANNEL_DATA (r:0, 9)
Inbound: CHANNEL_DATA (r:0, 9)
SFTP: Inbound: Received VERSION (v3)
CLIENT[sftp]: getSftpChannel: SFTP channel established
CLIENT[sftp]: getSftpChannel: finally clause fired
CLIENT[sftp]: getSftpChannel: Removing temp event listeners
connected
CLIENT[sftp]: put: Adding temp event listeners
Outbound: Sending CHANNEL_DATA (r:0, 52)
SFTP: Outbound: Buffered OPEN
CLIENT[sftp]: put source is a buffer
Inbound: CHANNEL_DATA (r:0, 14)
SFTP: Inbound: Received HANDLE (id:0)
Outbound: Sending CHANNEL_DATA (r:0, 22)
SFTP: Outbound: Buffered FSETSTAT
Inbound: CHANNEL_DATA (r:0, 28)
SFTP: Inbound: Received STATUS (id:1, 0, "Success")
Outbound: Sending CHANNEL_DATA (r:0, 40)
SFTP: Outbound: Sent WRITE (id:2)
Inbound: CHANNEL_DATA (r:0, 28)
SFTP: Inbound: Received STATUS (id:2, 0, "Success")
Outbound: Sending CHANNEL_DATA (r:0, 14)
SFTP: Outbound: Buffered CLOSE
Inbound: CHANNEL_DATA (r:0, 28)
SFTP: Inbound: Received STATUS (id:3, 0, "Success")
CLIENT[sftp]: put: promise resolved
CLIENT[sftp]: put: Removing temp event listeners
Uploaded data stream to /tests/file.txt
CLIENT[sftp]: end: Adding temp event listeners
CLIENT[sftp]: Adding listener to close event
CLIENT[sftp]: end: Have connection - calling end()
Outbound: Sending DISCONNECT (11)
Socket ended
CLIENT[sftp]: end: Ignoring expected end event
CLIENT[sftp]: Global: Ignoring hanlded end event
Socket closed
CLIENT[sftp]: end: Connection closed
CLIENT[sftp]: end: ignoring expected close event
CLIENT[sftp]: Global: Ignoring handled close event
CLIENT[sftp]: end: finally clause fired
CLIENT[sftp]: end: Removing temp event listeners
CLIENT[sftp]: Removing listener from close event
```

**Comment by CodeZeno** [comment]
Further to this, I just increase the script running time to 90 seconds and got some extra output:

```
2021-12-02T00:23:18.425Z	ERROR	Received DH GEX Group
2021-12-02T00:23:48.617Z	ERROR	Outbound: Sending KEXDH_GEX_INIT
2021-12-02T00:23:48.618Z	ERROR	CLIENT[sftp]: getConnection: Handling error: Timed out while waiting for handshake
2021-12-02T00:23:48.618Z	ERROR	CLIENT[sftp]: getConnection: handled error with reject
2021-12-02T00:23:48.618Z	ERROR	CLIENT[sftp]: Global: Ignoring handled error
2021-12-02T00:23:48.618Z	ERROR	CLIENT[sftp]: getConnection: finally clause fired
2021-12-02T00:23:48.618Z	ERROR	Socket closed
2021-12-02T00:23:48.618Z	ERROR	CLIENT[sftp]: getConnection: handling unexpected close event
2021-12-02T00:23:48.618Z	ERROR	CLIENT[sftp]: getConnection: handling close event with reject
2021-12-02T00:23:48.618Z	ERROR	CLIENT[sftp]: Global: Ignoring handled close event
2021-12-02T00:23:49.119Z	ERROR	CLIENT[sftp]: Removing listener from ready event
2021-12-02T00:23:49.119Z	ERROR	CLIENT[sftp]: getConnection: Removing temp event listeners
2021-12-02T00:23:49.119Z	ERROR	CLIENT[sftp]: getConnection retry catch
2021-12-02T00:23:49.119Z	ERROR	CLIENT[sftp]: connect: Error getConnection: Timed out while waiting for handshake
2021-12-02T00:23:49.122Z	INFO	Error: connect->getConnection: Timed out while waiting for handshake
    at fmtError (/var/task/node_modules/ssh2-sftp-client/src/utils.js:55:18)
    at SftpClient.connect (/var/task/node_modules/ssh2-sftp-client/src/index.js:211:13) {
  code: 'ERR_GENERIC_CLIENT',
  custom: true
} catch error
```

**Comment by mscdex** [comment]
Most of those "serverless" vendors give you pretty bad compute resources from what I've seen. Additionally, OpenSSL enforces some expensive checks of Diffie-Hellman parameters for security reasons. Since it seems the SSH server you're connecting to does not support curve25519 for key exchanges (which would avoid the aforementioned expensive checks), you could try using one of the non-group exchange key exchange algorithms, but I am thinking OpenSSL still performs the same (or similar) expensive checks even with the fixed Diffie-Hellman groups.

**Comment by CodeZeno** [comment]
> you could try using one of the non-group exchange key exchange algorithms

Thank you for the fast reply, absolute genius. Working instantly now.
Working code:

```
'use strict';
const ftpClient = require('ssh2-sftp-client');
const sftp = new ftpClient();
exports.handler = (event) => {
  console.log('running');
  sftp.connect({
    host: 'xxx.yyy.zzz',
    port: '22',
    username: 'name',
    password: 'pass',
    debug: function(msg){console.error(msg)},
    algorithms: {
      kex: ["diffie-hellman-group14-sha256"]
    }
  }).then(() => {
    console.log('connected');
    return sftp.put(Buffer.from('Hello World'), '/tests/file.txt');
  }).then(data => {
    console.log(data);
    sftp.end();
    return;
  }).catch(err => {
    console.log(err, 'catch error');
    return;
  });
};
```
