### ISSUE TITLE
Fatal error: "Handshake failed: no matching key exchange algorithm"

### ISSUE THREAD

**Issue by axkibe** [mscdex/ssh2#1143]
I just had following random occurring error.

```
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: Handshake failed: no matching key exchange algorithm
    at makeError (/home/axel/node/node_modules/ssh2/lib/protocol/utils.js:142:15)
    at doFatalError (/home/axel/node/node_modules/ssh2/lib/protocol/utils.js:184:13)
    at handleKexInit (/home/axel/node/node_modules/ssh2/lib/protocol/kex.js:239:12)
    at Protocol.onKEXPayload (/home/axel/node/node_modules/ssh2/lib/protocol/kex.js:1755:14)
    at NullDecipher.decrypt (/home/axel/node/node_modules/ssh2/lib/protocol/crypto.js:612:26)
    at Protocol.parsePacket [as _parse] (/home/axel/node/node_modules/ssh2/lib/protocol/Protocol.js:1994:25)
    at Protocol.parse (/home/axel/node/node_modules/ssh2/lib/protocol/Protocol.js:293:16)
    at Socket.<anonymous> (/home/axel/node/node_modules/ssh2/lib/server.js:1207:17)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
Emitted 'error' event on Client instance at:
    at Socket.<anonymous> (/home/axel/node/node_modules/ssh2/lib/server.js:1209:16)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23) {
  level: 'handshake',
  fatal: true
}
```
Unfortunally I cannot (yet) reproduce it. (what I did is a git server spawning git-upload-pack, git-receive-pack with ssh2 as required and if allowed). Second git pull on the same repository worked just fine.

Question a) any idea what could have been wrong here (client side everything was the same) (since it was a large git repository maybe some memory size issue?)

Question b) the error killed by node.js server (it does restart automatically) however I'd like to catch that. I added an client.on( 'error' ) handler, but can't test it out, and as far I understand it would still do the same, or? (unless I make a global error catcher for the whole node process which I don't want to do). Also in the traceback none of it is my code, it traces all through ssh2.

BTW: (Otherwise) great library.

PS: What might be a factor, on the client side, I do create a ssh control master connection to vastly improve speed of git operations on multiple repositories, I was positively surprised this rather less known feature is supported by your lib.

**Comment by axkibe** [comment]
Okay added
  ```client.on( 'error', ( err ) => { console.log( 'ssh client error', err ); } );```

This indeed seems to catch all kind or errors (didn't understand your code ;)

I do get a bunch of these in production now:

```ssh
client error TypeError: Cannot read properties of undefined (reading 'PROTOCOL_ERROR')
    at doFatalError (/home/axel/data/node_modules/ssh2/lib/protocol/utils.js:187:34)
    at 1 (/home/axel/data/node_modules/ssh2/lib/protocol/handlers.misc.js:42:14)
    at Protocol.onPayload (/home/axel/data/node_modules/ssh2/lib/protocol/Protocol.js:2025:10)
    at GenericDecipherNative.decrypt (/home/axel/data/node_modules/ssh2/lib/protocol/crypto.js:1269:26)
    at Protocol.parsePacket [as _parse] (/home/axel/data/node_modules/ssh2/lib/protocol/Protocol.js:1994:25)
    at Protocol.parse (/home/axel/data/node_modules/ssh2/lib/protocol/Protocol.js:293:16)
    at Socket.<anonymous> (/home/axel/data/node_modules/ssh2/lib/server.js:1207:17)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
```

But as far I can tell everything is working nevertheless.

**Comment by axkibe** [comment]
Okay, turned on ip logging, second error is from bots (the port is publicly open) looking for some weakness it seems, geolocations of offending ip's is almost certainly non of my users.

Closing this, may reopen if first error happens (agian) with real users.
