### ISSUE TITLE
Error in error handling

### ISSUE THREAD

**Issue by axkibe** [mscdex/ssh2#1144]
I'm getting following message
```
4.3.2022, 18:16:55 ssh client connected {
  ip: 'XXX.XXX.XXX.XXX',
  family: 'IPv4',
  port: 43264,
  header: {
    greeting: '',
    identRaw: 'SSH-2.0-libssh-0.6.3',
    versions: { protocol: '2.0', software: 'libssh-0.6.3' },
    comments: undefined
  }
}
4.3.2022, 18:16:57 ssh client error TypeError: Cannot read properties of undefined (reading 'PROTOCOL_ERROR')
    at doFatalError (/home/axel/node/node_modules/ssh2/lib/protocol/utils.js:187:34)
    at 1 (/home/axel/node/node_modules/ssh2/lib/protocol/handlers.misc.js:42:14)
    at Protocol.onPayload (/home/axel/node/node_modules/ssh2/lib/protocol/Protocol.js:2025:10)
    at GenericDecipherNative.decrypt (/home/axel/node/node_modules/ssh2/lib/protocol/crypto.js:1269:26)
    at Protocol.parsePacket [as _parse] (/home/axel/node/node_modules/ssh2/lib/protocol/Protocol.js:1994:25)
    at Protocol.parse (/home/axel/node/node_modules/ssh2/lib/protocol/Protocol.js:293:16)
    at Socket.<anonymous> (/home/axel/node/node_modules/ssh2/lib/server.js:1207:17)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
```

The client is actually some foreign botnet (I removed their ip in the log) I'm getting this kind of probes every 10 minutes or so (always different ip). So usually I guess no big deal as long they don't find a weakness.

The error handling is just a bit broken I guess, as DISCONNECT_REASON is undefined, in protocol/utils.js it is defined by requiring itself? Which I guess should work, since it's a defered require, but it doesn't define it in module.exports either, so it stays undefined.

**Comment by axkibe** [comment]
I guess line 174 of protocols/utils.js should say
```
      ({ DISCONNECT_REASON } = require('./constants.js'));
```

instead of utils.js (and maybe move the whole thing to the top? requires after setup phase are halting IO)

**Comment by mscdex** [comment]
Can you try v1.7.0?

**Comment by axkibe** [comment]
Ok, done, since it is triggered by that (or several botnets) I'll have to wait a while to see what happens.

**Comment by axkibe** [comment]
Looks better. (I guess not that the difference matters in practice, but it's nicer)

```
5.3.2022, 18:25:32 ssh client connected {
  ip: 'XXX.XXX.XXX.XXX',
  family: 'IPv4',
  port: 41610,
  header: {
    greeting: '',
    identRaw: 'SSH-2.0-libssh-0.6.3',
    versions: { protocol: '2.0', software: 'libssh-0.6.3' },
    comments: undefined
  }
}
5.3.2022, 18:25:33 ssh client error Error: Inbound: Malformed DISCONNECT packet
    at makeError (/home/axel/node/node_modules/ssh2/lib/protocol/utils.js:142:15)
    at doFatalError (/home/axel/node/node_modules/ssh2/lib/protocol/utils.js:184:13)
    at 1 (/home/axel/node/node_modules/ssh2/lib/protocol/handlers.misc.js:42:14)
    at Protocol.onPayload (/home/axel/node/node_modules/ssh2/lib/protocol/Protocol.js:2025:10)
    at GenericDecipherNative.decrypt (/home/axel/node/node_modules/ssh2/lib/protocol/crypto.js:1269:26)
    at Protocol.parsePacket [as _parse] (/home/axel/node/node_modules/ssh2/lib/protocol/Protocol.js:1994:25)
    at Protocol.parse (/home/axel/node/node_modules/ssh2/lib/protocol/Protocol.js:293:16)
    at Socket.<anonymous> (/home/axel/node/node_modules/ssh2/lib/server.js:1207:17)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12) {
  level: 'protocol',
  fatal: true
}
```

**Comment by mscdex** [comment]
Ah, I see. It's malformed because of the missing language tag in the packet. Some implementations randomly omit those.

**Comment by mscdex** [comment]
Also, FWIW it appears libssh ended up fixing that particular issue in later versions by adding the language tag in the disconnect packet.

**Comment by axkibe** [comment]
It are illegitimate connection attempts anyway.

I wouldn't be surprised if it's a deliberate protocol failure to probe finding some well known issue of some old code.. 

Strange tough I'm targeted with this (as said about once every 10 minutes) I always thought anyone in internet with an open 22 port will sooner or later be targeted.  (this btw. why I disabled password authentication, they were testing password lists as well)
