### ISSUE TITLE
Optional crypto binding build broken on Windows

### ISSUE THREAD

**Issue by bobvandevijver** [mscdex/ssh2#1147]
Looks like the latest release broke the optional crypto binding when using Windows on Node 12. Also visible in the [changelog](https://github.com/mscdex/ssh2/compare/v1.6.0...v1.7.0#diff-ad187f6733dd1ee19e640d0380a8a14a167c485205896b5f6af1c14ee29d7f89L2), with the same messages I see during install.

```
D:\projecten\drenso\group\project\node_modules\ssh2\lib\protocol\crypto>if not defined npm_config_node_gyp (node "C:\Users\bobva\AppData\Roaming\nvm\v12.22.1\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" --target=v12.22.1 rebuild )  else (node "C:\Users\bobva\AppData\Roaming\nvm\v12.22.1\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" --target=v12.22.1 rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  binding.cc
  win_delay_load_hook.cc
D:\projecten\drenso\group\project\node_modules\ssh2\lib\protocol\crypto\src\binding.cc(83,7): error C3861: 'EVP_CIPHER_CTX_cleanup': identifier not found [D:\projecten\drenso\group\project\node_modules\ssh2\lib\protocol\crypto\build\sshcrypto.vcxproj]
D:\projecten\drenso\group\project\node_modules\ssh2\lib\protocol\crypto\src\binding.cc(88,7): error C3861: 'EVP_CIPHER_CTX_cleanup': identifier not found [D:\projecten\drenso\group\project\node_modules\ssh2\lib\protocol\crypto\build\sshcrypto.vcxproj]
D:\projecten\drenso\group\project\node_modules\ssh2\lib\protocol\crypto\src\binding.cc(403,7): error C3861: 'EVP_CIPHER_CTX_cleanup': identifier not found [D:\projecten\drenso\group\project\node_modules\ssh2\lib\protocol\crypto\build\sshcrypto.vcxproj]
D:\projecten\drenso\group\project\node_modules\ssh2\lib\protocol\crypto\src\binding.cc(650,7): error C3861: 'EVP_CIPHER_CTX_cleanup': identifier not found [D:\projecten\drenso\group\project\node_modules\ssh2\lib\protocol\crypto\build\sshcrypto.vcxproj]
D:\projecten\drenso\group\project\node_modules\ssh2\lib\protocol\crypto\src\binding.cc(989,7): error C3861: 'EVP_CIPHER_CTX_cleanup': identifier not found [D:\projecten\drenso\group\project\node_modules\ssh2\lib\protocol\crypto\build\sshcrypto.vcxproj]
D:\projecten\drenso\group\project\node_modules\ssh2\lib\protocol\crypto\src\binding.cc(994,7): error C3861: 'EVP_CIPHER_CTX_cleanup': identifier not found [D:\projecten\drenso\group\project\node_modules\ssh2\lib\protocol\crypto\build\sshcrypto.vcxproj]
D:\projecten\drenso\group\project\node_modules\ssh2\lib\protocol\crypto\src\binding.cc(1403,7): error C3861: 'EVP_CIPHER_CTX_cleanup': identifier not found [D:\projecten\drenso\group\project\node_modules\ssh2\lib\protocol\crypto\build\sshcrypto.vcxproj]
D:\projecten\drenso\group\project\node_modules\ssh2\lib\protocol\crypto\src\binding.cc(1661,7): error C3861: 'EVP_CIPHER_CTX_cleanup': identifier not found [D:\projecten\drenso\group\project\node_modules\ssh2\lib\protocol\crypto\build\sshcrypto.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\bobva\AppData\Roaming\nvm\v12.22.1\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Windows_NT 10.0.22000
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\bobva\\AppData\\Roaming\\nvm\\v12.22.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "--target=v12.22.1" "rebuild"
gyp ERR! cwd D:\projecten\drenso\group\project\node_modules\ssh2\lib\protocol\crypto
gyp ERR! node -v v12.22.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
Failed to build optional crypto binding
```

Not sure if this needs to be solved as it is an optional binding, but it doesn't look that nice currently.

**Comment by GitMensch** [comment]
Likely solved by https://github.com/mscdex/ssh2/commit/5af3bc6dd2011fb14da22a0316d8dca0ea12fd1b - note: this issue also happens on Ubuntu 20.04, so I hope a new package version is published soon.

**Comment by mscdex** [comment]
Can you try the master branch? I want to make sure things are fixed there now.

**Comment by bobvandevijver** [comment]
Looks good to me 👍🏻

```
PS D:\projecten\drenso\group\project> npm install "https://github.com/mscdex/ssh2.git#master" --save

> ssh2@1.7.0 install D:\projecten\drenso\group\project\node_modules\ssh2
> node install.js


D:\projecten\drenso\group\project\node_modules\ssh2\lib\protocol\crypto>if not defined npm_config_node_gyp (node "C:\Users\bobva\AppData\Roaming\nvm\v12.22.1\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" --target=v12.22.1 --real_openssl_major=1 rebuild )  else (node "C:\Users\bobva\AppData\Roaming\nvm\v12.22.1\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" --target=v12.22.1 --real_openssl_major=1 rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  binding.cc
  win_delay_load_hook.cc
     Creating library D:\projecten\drenso\group\project\node_modules\ssh2\lib\protocol\crypto\build\Release\sshcrypto.lib and object D:\projecten\drenso\group\project\node_modules\ssh2\lib\protocol\crypto\build\Release\sshcrypto.exp
  sshcrypto.vcxproj -> D:\projecten\drenso\group\project\node_modules\ssh2\lib\protocol\crypto\build\Release\\sshcrypto.node
Succeeded in building optional crypto binding
npm WARN no.firefence@1.0.0 No repository field.
npm WARN no.firefence@1.0.0 No license field.

+ ssh2@1.7.0
updated 1 package in 18.716s

90 packages are looking for funding
  run `npm fund` for details
```

**Comment by GitMensch** [comment]
@mscdex Would be nice if you could drop a note here on release.
