### ISSUE TITLE
Error: Unable to start subsystem: sftp

### ISSUE THREAD

**Issue by eddiemonge** [mscdex/ssh2#115]
Why would the sftp subsystem be unable to start? SSH connects just fine.

**Comment by dschep** [comment]
Just a random note because I found this because I was having the same error. But in my case it was simply a matter of the ssh server prompting the user to reset a password, thus blocking sftp.

**Comment by marek-knappe** [comment]
Adding 
```Subsystem sftp /usr/lib/openssh/sftp-server```
helped me case :)

**Comment by zipper01** [comment]
No this is not solved. in the remote server sftp is fine (longin by other clients); and the line 'Subsystem sftp /usr/lib/openssh/sftp-server' in '/etc/ssh/sshd_config' is enabled. but still get the same problem:
`[06-12 22:09:30] [info] config at d:\OneDrive\website\n4@huawei01 {"remotePath":"/home/n4/express-webpack3","uploadOnSave":true,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"huawei01","host":"121.36.31.162","port":22,"username":"******","password":"******","algorithms":{"kex":["ecdh-sha2-nistp256","ecdh-sha2-nistp384","ecdh-sha2-nistp521","diffie-hellman-group-exchange-sha256","diffie-hellman-group14-sha1","diffie-hellman-group-exchange-sha1","diffie-hellman-group1-sha1"],"cipher":["3des-cbc","aes128-ctr","aes192-ctr","aes256-ctr","aes128-gcm","aes128-gcm@openssh.com","aes256-gcm","aes256-gcm@openssh.com"],"serverHostKey":["ssh-rsa","ecdsa-sha2-nistp256","ecdsa-sha2-nistp384","ecdsa-sha2-nistp521"],"hmac":["hmac-sha2-256","hmac-sha2-512","hmac-sha1"]},"passive":true,"watcher":{"files":"**/*","autoUpload":false,"autoDelete":false}}
[06-12 22:09:37] [warn] ENOENT: no such file or directory, open 'C:\Users\myself\.ssh\config' load C:\Users\myself\.ssh\config failed
[06-12 22:09:38] [error] Error: Unable to start subsystem: sftp
	at c:\Users\myself\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2\lib\client.js:1431:19
	at SSH2Stream.<anonymous> (c:\Users\myself\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2\lib\Channel.js:206:24)
	at SSH2Stream.emit (events.js:203:13)
	at parsePacket (c:\Users\myself\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\ssh.js:3352:10)
	at SSH2Stream._transform (c:\Users\myself\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\ssh.js:694:13)
	at SSH2Stream.Transform._read (_stream_transform.js:189:10)
	at SSH2Stream._read (c:\Users\myself\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\ssh.js:253:15)
	at SSH2Stream.Transform._write (_stream_transform.js:177:12)
	at doWrite (_stream_writable.js:418:12)
	at writeOrBuffer (_stream_writable.js:402:5)
	at SSH2Stream.Writable.write (_stream_writable.js:302:11)
	at Socket.ondata (_stream_readable.js:720:22)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:166:17) `
Extension version? I don't know. I just re-downloaded in VSCode today (6/12/2020).

**Comment by zipper01** [comment]
In my case the last line in the sshd_config file is (default): `Subsystem sftp /usr/lib/sftp-server` and the file is not there. Instead it is under /usr/lib/openssh.  I changed it to `Subsystem sftp /usr/lib/openssh/sftp-server` and solved the problem.

**Comment by Liao-junbo** [comment]
> In my case, the last line in the sshd_config file is (default): `Subsystem sftp /usr/lib/sftp-server` but the 'sftp-server' file is not in '/usr/lib/'. Instead it is in '/usr/lib/openssh'. I changed it to `Subsystem sftp /usr/lib/openssh/sftp-server` and solved the problem.

you'r right. that works!!!!

**Comment by SebastianAviles** [comment]
Hello, this not work for me, I already have  `Subsystem sftp /usr/lib/openssh/sftp-server` previsly.
