### ISSUE TITLE
node 18, sftp.createReadStream, Cannot set property closed of #<Readable> which has only a getter

### ISSUE THREAD

**Issue by rafipiccolo** [mscdex/ssh2#1172]
i previously opened a ticket here :
https://github.com/theophilusx/ssh2-sftp-client/issues/410
but it seems this package is the root cause.

following code throws an error when using node 18.

ps :
- works on node 17
- i use latest package versions (1.9.0)

```
import {Client} from 'ssh2';

const conn = new Client();
conn.on('ready', () => {
    console.log('Client :: ready');
    conn.sftp((err, sftp) => {
        if (err) throw err;

        let x = sftp.createReadStream('/xxx.xml');
        x.on('data', (data) => {
            console.log('data', data);
        })
    });
}).connect({
    host: '...',
    port: ...,
    username: '...',
    password: '...',
});
```

```
root@raphaelpiccolo:~/docker/push# node testssh2.js 
Client :: ready
node:events:505
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot set property closed of #<Readable> which has only a getter
    at new ReadStream (/root/docker/push/node_modules/ssh2/lib/protocol/SFTP.js:3389:15)
    at SFTP.createReadStream (/root/docker/push/node_modules/ssh2/lib/protocol/SFTP.js:305:12)
    at file:///root/docker/push/testssh2.js:9:22
    at SFTP.onReady (/root/docker/push/node_modules/ssh2/lib/client.js:1483:11)
    at SFTP.emit (node:events:527:28)
    at 2 (/root/docker/push/node_modules/ssh2/lib/protocol/SFTP.js:2584:10)
    at SFTP.push (/root/docker/push/node_modules/ssh2/lib/protocol/SFTP.js:278:11)
    at CHANNEL_DATA (/root/docker/push/node_modules/ssh2/lib/client.js:525:23)
    at 94 (/root/docker/push/node_modules/ssh2/lib/protocol/handlers.misc.js:859:16)
    at Protocol.onPayload (/root/docker/push/node_modules/ssh2/lib/protocol/Protocol.js:2025:10)
Emitted 'error' event on Client instance at:
    at Socket.<anonymous> (/root/docker/push/node_modules/ssh2/lib/client.js:715:20)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

Node.js v18.0.0
```

**Comment by mscdex** [comment]
The fix for this is already in master and will be included in the next release that should be out soon.

**Comment by trgwii** [comment]
Last release on npm was 7 months ago, when is the next release?

**Comment by mscdex** [comment]
@trgwii The fix for this particular issue should already exist in v1.11 on npm.

**Comment by trgwii** [comment]
Ahhh great, my setup was messed up, sorry :)
