### ISSUE TITLE
Unable to connect using ssh agent

### ISSUE THREAD

**Issue by jnordberg** [mscdex/ssh2#119]
This is what i'm trying:

test.js

``` javascript
var Connection = require('ssh2')

var c = new Connection()
c.on('ready', function() {
  console.log('ready')
})
c.on('end', function() {
  console.log('end')
})
c.on('error', function(error) {
  console.log('error')
  throw error
})

var opts = {
  host: 'localhost',
  username: process.env['USER'],
  agent: process.env['SSH_AUTH_SOCK']
}

console.log('connecting %j', opts)
c.connect(opts)
```

``` bash
$ echo $SSH_AUTH_SOCK
/var/folders/wr/57t6l73s1g9ds61ks72ndr7m0000gn/T//ssh-tEjy7uRGSn2k/agent.24993
$ ssh localhost uptime
18:13  up 21:15, 5 users, load averages: 1,10 1,11 1,19
 $ node test
connecting {"host":"localhost","username":"jnordberg","agent":"/var/folders/wr/57t6l73s1g9ds61ks72ndr7m0000gn/T//ssh-tEjy7uRGSn2k/agent.24993"}
error

/Users/jnordberg/Development/nsync/test.js:12
  throw error
        ^
Error: Authentication failure. Available authentication methods: publickey,keyboard-interactive
    at Connection._tryNextAuth (/Users/jnordberg/Development/nsync/node_modules/ssh2/lib/Connection.js:933:15)
    at Connection._authAgent (/Users/jnordberg/Development/nsync/node_modules/ssh2/lib/Connection.js:1223:10)
    at Connection._tryNextAuth (/Users/jnordberg/Development/nsync/node_modules/ssh2/lib/Connection.js:927:10)
    at onUSERAUTH_FAILURE (/Users/jnordberg/Development/nsync/node_modules/ssh2/lib/Connection.js:2315:8)
    at Parser.<anonymous> (/Users/jnordberg/Development/nsync/node_modules/ssh2/lib/Connection.js:133:5)
    at Parser.EventEmitter.emit (events.js:98:17)
    at Parser.parsePacket (/Users/jnordberg/Development/nsync/node_modules/ssh2/lib/Parser.js:488:12)
    at Parser.execute (/Users/jnordberg/Development/nsync/node_modules/ssh2/lib/Parser.js:249:14)
    at Socket.<anonymous> (/Users/jnordberg/Development/nsync/node_modules/ssh2/lib/Connection.js:506:18)
    at Socket.EventEmitter.emit (events.js:95:17)
```

``` bash
$ ssh-agent -d
SSH_AUTH_SOCK=/var/folders/wr/57t6l73s1g9ds61ks72ndr7m0000gn/T//ssh-tEjy7uRGSn2k/agent.24993; export SSH_AUTH_SOCK;
echo Agent pid 24993;
debug1: read PEM private key done: type RSA
debug1: read PEM private key done: type RSA
debug1: type 11                    < seeing this when running ssh localhost
debug1: XXX shrink: 3 < 4
debug1: type 11                    < and when running node test.js
debug1: XXX shrink: 3 < 4
```

on OS X 10.9.2 using node v0.10.26

**Comment by Brikkbaby87** [comment]
Need help
