### ISSUE TITLE
Error List? How to handle errors?

### ISSUE THREAD

**Issue by jvalrog** [mscdex/ssh2#1221]
I'm seeing different types of errors like these:

```
Error: connect EHOSTUNREACH 172.26.0.5:22
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '172.26.0.5',
  port: 22,
  level: 'client-socket'
}
```
or
```
Error: All configured authentication methods failed
    at doNextAuth (/home/javi/files/work/darecode/code/be-diagnostico-ftth/node_modules/ssh2/lib/client.js:803:21)
    at tryNextAuth (/home/javi/files/work/darecode/code/be-diagnostico-ftth/node_modules/ssh2/lib/client.js:993:7)
    at USERAUTH_FAILURE (/home/javi/files/work/darecode/code/be-diagnostico-ftth/node_modules/ssh2/lib/client.js:373:11)
    at 51 (/home/javi/files/work/darecode/code/be-diagnostico-ftth/node_modules/ssh2/lib/protocol/handlers.misc.js:337:16)
    at Protocol.onPayload (/home/javi/files/work/darecode/code/be-diagnostico-ftth/node_modules/ssh2/lib/protocol/Protocol.js:2025:10)
    at GenericDecipherNative.decrypt (/home/javi/files/work/darecode/code/be-diagnostico-ftth/node_modules/ssh2/lib/protocol/crypto.js:1269:26)
    at Protocol.parsePacket [as _parse] (/home/javi/files/work/darecode/code/be-diagnostico-ftth/node_modules/ssh2/lib/protocol/Protocol.js:1994:25)
    at Protocol.parse (/home/javi/files/work/darecode/code/be-diagnostico-ftth/node_modules/ssh2/lib/protocol/Protocol.js:293:16)
    at Socket.<anonymous> (/home/javi/files/work/darecode/code/be-diagnostico-ftth/node_modules/ssh2/lib/client.js:713:21)
    at Socket.emit (node:events:513:28) {
  level: 'client-authentication'
}
```

And both are wildly different. How do you handle that?

**Comment by mscdex** [comment]
I'm not quite sure what you're asking. Just listen for the `'error'` event on the client object like any normal node.js `EventEmitter`?
