### ISSUE TITLE
ssh server

### ISSUE THREAD

**Issue by StreamerYT** [mscdex/ssh2#1229]
How do I get the data that I write to the console? in ssh2.ServerChannel, the readable event is called without arguments, and that's it.

**Comment by StreamerYT** [comment]
```js
EventEmitter.listenerCount = function () { return 1 }
const Emit = EventEmitter.prototype.emit

EventEmitter.prototype.emit = function (eventName, ...args) {
   console.log(this.constructor.name, { eventName, args });
   return Emit.call(this, eventName, ...args)
}
```

```js
Server { eventName: 'listening', args: [] }
Server { eventName: 'listening', args: [] }
Server {
  eventName: 'connection',
  args: [
    Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: [Server],
      _server: [Server],
      [Symbol(async_id_symbol)]: 12,
      [Symbol(kHandle)]: [TCP],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: false,
      [Symbol(kSetKeepAliveInitialDelay)]: 0,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    }
  ]
}
Socket { eventName: 'pause', args: [] }
Socket { eventName: 'resume', args: [] }
Socket {
  eventName: 'data',
  args: [
    <Buffer 53 53 48 2d 32 2e 30 2d 39 2e 32 33 20 46 6c 6f 77 53 73 68 3a 20 42 69 74 76 69 73 65 20 53 53 48 20 43 6c 69 65 6e 74 20 28 54 75 6e 6e 65 6c 69 65 ... 913 more bytes>
  ]
}
Server {
  eventName: 'connection',
  args: [
    Client {
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      _sock: [Socket],
      _chanMgr: [ChannelManager],
      _debug: undefined,
      noMoreSessions: false,
      authenticated: false,
      _protocol: [Protocol],
      [Symbol(kCapture)]: false
    },
    { ip: '127.0.0.1', family: 'IPv4', port: 55957, header: [Object] }
  ]
}
Socket {
  eventName: 'data',
  args: [
    <Buffer 00 00 00 54 2e 1e 00 00 00 20 02 43 32 b8 55 b6 30 c0 a1 01 7b b2 67 ae c5 eb 7e 8f af 3e 05 e6 f8 56 0d 55 b4 ee 8d ff 7a 52 f3 a5 38 49 e8 db a2 c7 ... 38 more bytes>
  ]
}
Socket {
  eventName: 'data',
  args: [
    <Buffer 00 00 00 54 52 15 0c 7e 59 aa cf 13 2d 90 37 02 50 f7 d1 21 57 c6 df 64 0b 11 22 3a 6c 1a fe c2 d7 43 af 02 5b 94 ee 27 fb 60 20 f8 44 16 9e 86 01 2d ... 146 more bytes>
  ]
}
Client {
  eventName: 'handshake',
  args: [
    {
      kex: 'curve25519-sha256',
      serverHostKey: 'rsa-sha2-512',
      cs: [Object],
      sc: [Object]
    }
  ]
}
Socket {
  eventName: 'data',
  args: [
    <Buffer d7 3c 2b 38 23 58 6b ab 18 56 11 de 0c 99 1d bb 20 52 2f aa 0e af 06 a7 40 49 03 c0 4d 0e fc 1d 0b 7c 26 df 4c 79 eb 5e 90 fa bb b5 92 dc d4 7c d5 4e ... 58 more bytes>
  ]
}
Client {
  eventName: 'authentication',
  args: [
    PwdAuthContext {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      user: 'foo',
      username: 'foo',
      service: 'ssh-connection',
      method: 'password',
      _initialResponse: false,
      _finalResponse: false,
      _multistep: false,
      _cbfinal: [Function (anonymous)],
      _protocol: [Protocol],
      password: 'bar',
      _changeCb: undefined,
      [Symbol(kCapture)]: false
    }
  ]
}
Client { eventName: 'ready', args: [] }
Socket {
  eventName: 'data',
  args: [
    <Buffer 31 52 b7 9e e1 b5 13 15 4c 55 02 f8 c6 fc 58 ce c2 aa 78 00 fc df 79 20 99 a7 60 72 0a 4b 6a 1b d0 a5 f5 e9 48 b1 f3 15 b0 42 b9 2a 4f b2 3a eb 45 de ... 58 more bytes>
  ]
}
Client {
  eventName: 'session',
  args: [ [Function: accept], [Function: reject] ]
}
Socket {
  eventName: 'data',
  args: [
    <Buffer 9c de 43 a9 91 60 b9 49 89 ca dd 6d 32 ba f3 ca cc fe f5 21 a8 aa 06 b2 a0 9a 35 c0 da 8c ea fb ca 61 3e b4 17 fe 01 ee 3e 90 c4 77 03 98 c4 24 c6 24 ... 58 more bytes>
  ]
}
Session {
  eventName: 'pty',
  args: [
    [Function: accept],
    [Function: reject],
    {
      term: 'vt100',
      cols: 100,
      rows: 35,
      width: 0,
      height: 0,
      modes: {}
    }
  ]
}
Socket {
  eventName: 'data',
  args: [
    <Buffer db 65 ca cd 4e 67 bb 73 d6 4e 67 6c 15 c3 4e 5e 31 0d c2 e4 7c 1d 34 42 ae f6 e6 d7 4a 23 55 2e 93 73 f8 c3 7f ee 6a a5 93 66 3c 3b 75 15 e4 56 45 b2 ... 58 more bytes>
  ]
}
Session {
  eventName: 'shell',
  args: [ [Function: accept], [Function: reject] ]
}
Socket {
  eventName: 'data',
  args: [
    <Buffer d2 3b c3 c1 86 f2 9c 4c 70 4d 31 2f 80 7d 6b f4 d1 e1 56 99 d5 9f 33 47 d9 95 59 3b 7e b6 a1 9f 1a 04 df 89 a8 3e 63 55 a2 f7 f2 d0 61 33 82 6e c3 a8 ... 58 more bytes>
  ]
}
Session {
  eventName: 'window-change',
  args: [
    undefined,
    undefined,
    { cols: 100, rows: 35, width: 0, height: 0 }
  ]
}
Socket {
  eventName: 'data',
  args: [
    <Buffer 83 d7 e5 7f db 7d 8d a3 81 7a 76 1c 4d 58 cb 5c c6 d2 68 92 5a fc 2f 0f f3 6a 31 a1 bf ae e0 46 0e 23 f1 b5 b2 ce 53 b0 06 88 5c a3 e9 10 2c 28 58 80 ... 58 more bytes>
  ]
}
Socket {
  eventName: 'data',
  args: [
    <Buffer 0f 0e ac df 53 62 7e dc ab c0 9f cb 2e 5a f6 01 ab 04 17 e1 53 fd 82 91 93 15 f3 8e e3 b8 1a fb c8 a4 47 75 7f 1a b0 08 64 72 e5 53 d8 73 64 92 ed 7b ... 58 more bytes>
  ]
}
Channel { eventName: 'readable', args: [] }
```

**Comment by mscdex** [comment]
> How do I get the data that I write to the console?

I'm not sure what you mean here. Could you perhaps provide a minimal code example of what you're currently using and where exactly you're getting stuck?

**Comment by StreamerYT** [comment]
I do not know English and use a translator.
I need to create an ssh and sftp server. But I kind of started figuring it out using the tests files.

**Comment by StreamerYT** [comment]
The READDIR event is executed cyclically
```
_REALPATH /\
_OPENDIR \
_READDIR { str: 'node.js', buf: <Buffer 6e 6f 64 65 2e 6a 73> }
_READDIR { str: 'node.js', buf: <Buffer 6e 6f 64 65 2e 6a 73> }
_READDIR { str: 'node.js', buf: <Buffer 6e 6f 64 65 2e 6a 73> }
_READDIR { str: 'node.js', buf: <Buffer 6e 6f 64 65 2e 6a 73> }
....
```
```js
SFTPWrapper.on('REALPATH', (reqId, path) => {
            console.log(`_REALPATH`, path)
            SFTPWrapper.name(reqId, { filename: Path.normalize(path) } as any)
        }).on('OPENDIR', (reqId, path) => {
            console.log(`_OPENDIR`, path)
            SFTPWrapper.handle(reqId, Buffer.from('node.js'))
        }).on('READDIR', (reqId, handle) => {
            console.log(`_READDIR`, { str: handle.toString(), buf: handle })
            SFTPWrapper.name(reqId, [
                {
                    filename: '.',
                    longname: 'drwxr-xr-x  56 nodejs nodejs      4096 Nov 10 01:05 .',
                    attrs: new (ssh2.utils.sftp as any).Stats({
                        mode: 0o755 | fs.constants.S_IFDIR,
                        size: 4096,
                        uid: 9001,
                        gid: 8001,
                        atime: 1415599549,
                        mtime: 1415599590
                    })
                },
                {
                    filename: '..',
                    longname: 'drwxr-xr-x   4 root   root        4096 May 16  2013 ..',
                    attrs: new (ssh2.utils.sftp as any).Stats({
                        mode: 0o755 | fs.constants.S_IFDIR,
                        size: 4096,
                        uid: 0,
                        gid: 0,
                        atime: 1368729954,
                        mtime: 1368729999
                    })
                },
                {
                    filename: 'foo',
                    longname: 'drwxrwxrwx   2 nodejs nodejs      4096 Mar  8  2009 foo',
                    attrs: new (ssh2.utils.sftp as any).Stats({
                        mode: 0o777 | fs.constants.S_IFDIR,
                        size: 4096,
                        uid: 9001,
                        gid: 8001,
                        atime: 1368729954,
                        mtime: 1368729999
                    })
                },
                {
                    filename: 'bar',
                    longname: '-rw-r--r--   1 nodejs nodejs 513901992 Dec  4  2009 bar',
                    attrs: new (ssh2.utils.sftp as any).Stats({
                        mode: 0o644 | fs.constants.S_IFREG,
                        size: 513901992,
                        uid: 9001,
                        gid: 8001,
                        atime: 1259972199,
                        mtime: 1259972199
                    })
                }
            ])
        })
 ```

**Comment by mscdex** [comment]
If you look at the [SFTP documentation](https://github.com/mscdex/ssh2/blob/master/SFTP.md), you will see that for READDIR, you should respond appropriately with `status()` to indicate there are no more directory entries.

**Comment by StreamerYT** [comment]
```js
SFTPWrapper.status(reqId, ssh2.utils.sftp.STATUS_CODE.OK)
```
```js
Error: write ECONNABORTED
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:874:11)
    at Socket._write (node:net:886:8)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at Socket.Writable.write (node:internal/streams/writable:336:10)
    at onWrite (A:\Programming\Node.JS\node_modules\ssh2\lib\server.js:482:18)
    at ChaChaPolyCipherBinding.Protocol._onWrite (A:\Programming\Node.JS\node_modules\ssh2\lib\protocol\Protocol.js:116:33)
    at ChaChaPolyCipherBinding.encrypt (A:\Programming\Node.JS\node_modules\ssh2\lib\protocol\crypto.js:274:10) {
  errno: -4079,
  code: 'ECONNABORTED',
  syscall: 'write',
  level: 'socket'
}
```

**Comment by StreamerYT** [comment]
```js
SFTP { eventName: 'ready', args: [] }
_REALPATH /tmp/foo
_OPENDIR /tmp/foo
Session { eventName: 'close', args: [] }
SFTP { eventName: 'end', args: [] }
SFTP { eventName: 'close', args: [] }
Client {
  eventName: 'error',
  args: [
    Error: read ECONNRESET
        at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
      errno: -4077,
      code: 'ECONNRESET',
      syscall: 'read',
      level: 'socket'
    }
  ]
}
```
```js
SFTPWrapper.on('REALPATH', (reqId, path) => {
            console.log(`_REALPATH`, path)
            SFTPWrapper.name(reqId, { filename: '/tmp/foo' } as any)
            SFTPWrapper.status(reqId, ssh2.utils.sftp.STATUS_CODE.OK)
        }).on('OPENDIR', (reqId, path) => {
            console.log(`_OPENDIR`, path)
            SFTPWrapper.handle(reqId, Buffer.from('node.js'))
            SFTPWrapper.status(reqId, ssh2.utils.sftp.STATUS_CODE.OK)   
        }).on('READDIR', (reqId, handle) => {
            console.log(`_READDIR`, { str: handle.toString(), buf: handle })
            SFTPWrapper.name(reqId, [
                {
                    filename: '.',
                    longname: 'drwxr-xr-x  56 nodejs nodejs      4096 Nov 10 01:05 .',
                    attrs: new (ssh2.utils.sftp as any).Stats({
                        mode: 0o755 | fs.constants.S_IFDIR,
                        size: 4096,
                        uid: 9001,
                        gid: 8001,
                        atime: 1415599549,
                        mtime: 1415599590
                    })
                },
                {
                    filename: '..',
                    longname: 'drwxr-xr-x   4 root   root        4096 May 16  2013 ..',
                    attrs: new (ssh2.utils.sftp as any).Stats({
                        mode: 0o755 | fs.constants.S_IFDIR,
                        size: 4096,
                        uid: 0,
                        gid: 0,
                        atime: 1368729954,
                        mtime: 1368729999
                    })
                },
                {
                    filename: 'foo',
                    longname: 'drwxrwxrwx   2 nodejs nodejs      4096 Mar  8  2009 foo',
                    attrs: new (ssh2.utils.sftp as any).Stats({
                        mode: 0o777 | fs.constants.S_IFDIR,
                        size: 4096,
                        uid: 9001,
                        gid: 8001,
                        atime: 1368729954,
                        mtime: 1368729999
                    })
                },
                {
                    filename: 'bar',
                    longname: '-rw-r--r--   1 nodejs nodejs 513901992 Dec  4  2009 bar',
                    attrs: new (ssh2.utils.sftp as any).Stats({
                        mode: 0o644 | fs.constants.S_IFREG,
                        size: 513901992,
                        uid: 9001,
                        gid: 8001,
                        atime: 1259972199,
                        mtime: 1259972199
                    })
                }
            ])
            SFTPWrapper.status(reqId, ssh2.utils.sftp.STATUS_CODE.OK)
        })
```

**Comment by mscdex** [comment]
No, you should only respond once for a particular request. You're now responding twice (once with directory entries and then again with the status).

You should instead only respond with `name()` if you have entries to send back. If there are no more, you send the EOF status, as noted in the SFTP API documentation.

**Comment by StreamerYT** [comment]
I don't quite understand what I need to do.

**Comment by StreamerYT** [comment]
Why is the client trying to open the /tmp/foo folder when connecting to sftp? Is there any way to change this?
