### ISSUE TITLE
SSH2 Server with abitlity to treat Remote Forwarding

### ISSUE THREAD

**Issue by stefanwerfling** [mscdex/ssh2#1230]
I use this sample by https://github.com/mscdex/ssh2/issues/698,
now start and connect, when 
`socket.setEncoding('utf8');`
then can not use https, only http works.

When i remove this line then it works short (i see the index.html) and ssh server process is killed by error with:
```

node:events:491
2022-10-26T21:59:46.386628220Z       throw er; // Unhandled 'error' event
2022-10-26T21:59:46.386634302Z       ^
2022-10-26T21:59:46.386638775Z 
2022-10-26T21:59:46.386643065Z Error: This socket has been ended by the other party
2022-10-26T21:59:46.386647480Z     at Socket.writeAfterFIN [as write] (node:net:518:14)
2022-10-26T21:59:46.386651947Z     at Channel.ondata (node:internal/streams/readable:766:22)
2022-10-26T21:59:46.386656537Z     at Channel.emit (node:events:513:28)
2022-10-26T21:59:46.386660548Z     at addChunk (node:internal/streams/readable:324:12)
2022-10-26T21:59:46.386664798Z     at readableAddChunk (node:internal/streams/readable:297:9)
2022-10-26T21:59:46.386669403Z     at Readable.push (node:internal/streams/readable:234:10)
2022-10-26T21:59:46.386673720Z     at CHANNEL_DATA (/opt/app/node_modules/ssh2/lib/server.js:750:23)
2022-10-26T21:59:46.386677821Z     at 94 (/opt/app/node_modules/ssh2/lib/protocol/handlers.misc.js:859:16)
2022-10-26T21:59:46.386682173Z     at Protocol.onPayload (/opt/app/node_modules/ssh2/lib/protocol/Protocol.js:2025:10)
2022-10-26T21:59:46.386686529Z Emitted 'error' event on Socket instance at:
2022-10-26T21:59:46.386690932Z     at Socket.onerror (node:internal/streams/readable:785:14)
2022-10-26T21:59:46.386695361Z     at Socket.emit (node:events:513:28)
2022-10-26T21:59:46.386699220Z     at emitErrorNT (node:internal/streams/destroy:151:8)
2022-10-26T21:59:46.386703564Z     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
2022-10-26T21:59:46.386708139Z     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
2022-10-26T21:59:46.386712724Z   code: 'EPIPE'
2022-10-26T21:59:46.386716590Z }
```

How can I solve the problem for https?

**Comment by stefanwerfling** [comment]
@mscdex here is my code: https://github.com/stefanwerfling/flyingfish/blob/main/sshserver/src/inc/ssh/SshServer.ts

If I leave the utf8 encoding in, then of course http works, but https doesn't.

As soon as I remove utf8 (I thought I would leave the encoding on the stream in the original) https only works for a short time, see image in the attachment.

![ssh-https](https://user-images.githubusercontent.com/12471903/198232384-3dddfed6-2647-45b0-8fbc-33929fd4b7b6.png)

SSH-Client log:
```
debug1: channel 32: free: ::ffff:10.103.0.3, nchannels 3
debug3: channel 32: status: The following connections are open:
  #32 ::ffff:10.103.0.3 (t4 r33 i3/0 o0/0 e[closed]/0 fd 38/38/-1 sock 38 cc -1)
  #33 ::ffff:10.103.0.3 (t4 r34 i3/0 o0/0 e[closed]/0 fd 39/39/-1 sock 39 cc -1)
  #34 ::ffff:10.103.0.3 (t4 r35 i3/0 o0/0 e[closed]/0 fd 40/40/-1 sock 40 cc -1)

debug1: channel 33: free: ::ffff:10.103.0.3, nchannels 2
debug3: channel 33: status: The following connections are open:
  #33 ::ffff:10.103.0.3 (t4 r34 i3/0 o0/0 e[closed]/0 fd 39/39/-1 sock 39 cc -1)
  #34 ::ffff:10.103.0.3 (t4 r35 i3/0 o0/0 e[closed]/0 fd 40/40/-1 sock 40 cc -1)

debug1: channel 34: free: ::ffff:10.103.0.3, nchannels 1
debug3: channel 34: status: The following connections are open:
  #34 ::ffff:10.103.0.3 (t4 r35 i3/0 o0/0 e[closed]/0 fd 40/40/-1 sock 40 cc -1)

debug3: fd 1 is not O_NONBLOCK
Connection to ssh.in.flyingfish.msc-dns.de closed by remote host.
Connection to ssh.in.flyingfish.msc-dns.de closed.
Transferred: sent 200352, received 54028 bytes, in 5.0 seconds
Bytes per second: sent 40365.3, received 10885.1
debug1: Exit status -1

```

My Server Log:
```

Debugger listening on ws://0.0.0.0:9229/b57cf8a7-8d1b-42f6-928c-33bdaa63eee7
2022-10-27T08:22:03.097694385Z For help, see: https://nodejs.org/en/docs/inspector
2022-10-27T08:22:18.404827794Z Debugger attached.
2022-10-27T08:22:20.326698289Z Load json-file: /opt/app/config.json
2022-10-27T08:22:20.630290450Z Listening on port 22
2022-10-27T08:22:24.426577658Z Client connected!
2022-10-27T08:22:26.459844797Z Client authenticated!
2022-10-27T08:22:26.467145556Z Listening remote forward on port 3333->3000 by userid: 1
2022-10-27T08:22:31.185530038Z Waiting for the debugger to disconnect...
2022-10-27T08:22:31.338169518Z node:events:491
2022-10-27T08:22:31.338228898Z       throw er; // Unhandled 'error' event
2022-10-27T08:22:31.338242528Z       ^
2022-10-27T08:22:31.338249933Z 
2022-10-27T08:22:31.338258693Z Error: This socket has been ended by the other party
2022-10-27T08:22:31.338266373Z     at Socket.writeAfterFIN [as write] (node:net:518:14)
2022-10-27T08:22:31.338274623Z     at Channel.ondata (node:internal/streams/readable:766:22)
2022-10-27T08:22:31.338283758Z     at Channel.emit (node:events:513:28)
2022-10-27T08:22:31.338289957Z     at addChunk (node:internal/streams/readable:324:12)
2022-10-27T08:22:31.338296334Z     at readableAddChunk (node:internal/streams/readable:297:9)
2022-10-27T08:22:31.338302578Z     at Readable.push (node:internal/streams/readable:234:10)
2022-10-27T08:22:31.338308201Z     at CHANNEL_DATA (/opt/app/node_modules/ssh2/lib/server.js:750:23)
2022-10-27T08:22:31.338313454Z     at 94 (/opt/app/node_modules/ssh2/lib/protocol/handlers.misc.js:859:16)
2022-10-27T08:22:31.338318597Z     at Protocol.onPayload (/opt/app/node_modules/ssh2/lib/protocol/Protocol.js:2025:10)
2022-10-27T08:22:31.338324407Z Emitted 'error' event on Socket instance at:
2022-10-27T08:22:31.338329929Z     at Socket.onerror (node:internal/streams/readable:785:14)
2022-10-27T08:22:31.338335338Z     at Socket.emit (node:events:513:28)
2022-10-27T08:22:31.338340675Z     at emitErrorNT (node:internal/streams/destroy:151:8)
2022-10-27T08:22:31.338347130Z     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
2022-10-27T08:22:31.338352922Z     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
2022-10-27T08:22:31.338358430Z   code: 'EPIPE'
2022-10-27T08:22:31.338363576Z }
2022-10-27T08:22:31.338791733Z 
2022-10-27T08:22:31.338819401Z Node.js v19.0.0

```

can you see anything here?

Except for the login, I think I'm still very close to the original.

**Comment by mscdex** [comment]
It could be the remote HTTPS server closing the socket abruptly with a TCP RST vs. FIN, so you will need to handle the errors appropriately one way or another.

**Comment by stefanwerfling** [comment]
@mscdex I just did some tests, for example the socket from 'net.createServer' lives longer if I set 'proxy_ignore_client_abort on;' in nginx. force But only a little longer, it still comes to the same error.


Since the client 'Browser' as socket
'net.createServer((socket) => {' arrives, it will also be destroyed. But all this is taken over in 'client.forwardOut'. How can I now hold the forwardOut and if a new net.createServer((socket) = > {' does this come back passed?

**Comment by mscdex** [comment]
> Since the client 'Browser' as socket
> 'net.createServer((socket) => {' arrives, it will also be destroyed. But all this is taken over in 'client.forwardOut'. How can I now hold the forwardOut and if a new net.createServer((socket) = > {' does this come back passed?

I'm not sure what you're asking here.

**Comment by stefanwerfling** [comment]
How can I catch error when this one is thrown in /opt/app/node_modules/ssh2/lib/protocol/Protocol.js:2025:10? 

I am aware that my client can terminate the connection to my server. Nevertheless, the server would have to continue listening and forward it again with a new connection.

**Comment by mscdex** [comment]
You should attach `'error'` event handlers on both `socket` and `upstream`.

**Comment by stefanwerfling** [comment]
@mscdex now the error is actually caught and everything works! 

Many Thanks!


here the changes:
```
fserver = net.createServer((socket) => {
                        // socket.setEncoding('utf8');
                        socket.on('error', (err) => {
                            if (shellChannel) {
                                shellChannel.write(`Client::error: ${err.message}`);
                            }

                            console.log(`Server::error: ${err.message}`);
                        });

                        client.forwardOut(
                            info.bindAddr,
                            info.bindPort,
                            socket.remoteAddress!,
                            socket.remotePort!,
                            (
                                err,
                                upstream
                            ) => {
                                if (err) {
                                    socket.end();

                                    if (shellChannel) {
                                        shellChannel.stderr.write(`not working: ${err}\n`);
                                    }

                                    console.error(`not working: ${err}`);

                                    return;
                                }

                                upstream.pipe(socket).pipe(upstream);
                                upstream.on('error', (errUp: any) => {
                                    if (shellChannel) {
                                        shellChannel.write('Server::error: upstream');
                                    }

                                    console.error(errUp);
                                });
                            }
                        );
                    }).listen(sshPort!.port, () => {
...
```
