### ISSUE TITLE
sftp.fastPut fail

### ISSUE THREAD

**Issue by ljx2** [mscdex/ssh2#1232]
Hello:

There is the message:

```js
E:\cmdUpload2\file_update_server\deploy\index.js:106
          if (err) throw err
                   ^

Error: Failure
    at 101 (E:\cmdUpload2\file_update_server\deploy\node_modules\ssh2\lib\protocol\SFTP.js:2704:19)
    at SFTP.push (E:\cmdUpload2\file_update_server\deploy\node_modules\ssh2\lib\protocol\SFTP.js:278:11)
    at CHANNEL_DATA (E:\cmdUpload2\file_update_server\deploy\node_modules\ssh2\lib\client.js:525:23)
    at 94 (E:\cmdUpload2\file_update_server\deploy\node_modules\ssh2\lib\protocol\handlers.misc.js:859:16)
    at Protocol.onPayload (E:\cmdUpload2\file_update_server\deploy\node_modules\ssh2\lib\protocol\Protocol.js:2025:10)
    at AESGCMDecipherBinding.decrypt (E:\cmdUpload2\file_update_server\deploy\node_modules\ssh2\lib\protocol\crypto.js:1086:26)
    at Protocol.parsePacket [as _parse] (E:\cmdUpload2\file_update_server\deploy\node_modules\ssh2\lib\protocol\Protocol.js:1994:25)
    at Protocol.parse (E:\cmdUpload2\file_update_server\deploy\node_modules\ssh2\lib\protocol\Protocol.js:293:16)
    at Socket.<anonymous> (E:\cmdUpload2\file_update_server\deploy\node_modules\ssh2\lib\client.js:713:21)
    at Socket.emit (node:events:527:28) {
  code: 4
}
```

code:
```js
sftp.fastPut(sourceCodePath, '/home/centos/overseaFileServer2', {}, (err, result) => {
      if (err) throw err
 })
```

a few days ago is ok，buy now is fail

**Comment by ljx2** [comment]
"ssh2": "^1.11.0",

**Comment by mscdex** [comment]
It means the server failed one of the intermediary SFTP requests (e.g. open, stat, write, etc.) while transferring the file. Unfortunately, servers don't always provide useful error messages, so it's up to you to investigate why it's failing. Perhaps it's a permission issue, disk space issue, or something else. It could be anything really.

**Comment by mscdex** [comment]
You can set `debug: console.log` in your connection config object to get debug output and find which request is failing, but beyond that there's not much more that can be done. I supposed it would be interesting to compare with the SFTP requests mobaXterm is sending to achieve the same file transfer.

**Comment by ljx2** [comment]
Maybe it's beyond my ability, I will have a try

**Comment by ljx2** [comment]
The reason for the problem is that I have a directory with the same name.
