### ISSUE TITLE
Signature verification failed: Error: error:03000098:digital envelope routines::invalid digest

### ISSUE THREAD

**Issue by johnachli** [mscdex/ssh2#1273]
Hello,

i face the following issue while trying to connect to an SSH server using SSH2 (v1.11.0) library.

Notes:
 - The connection works fine in the local machine.
 - The same nodejs script was working fine before upgrading npm/nodejs (details below)

The code looks like:
```
var SSHClient = require("ssh2").Client;
var conn = new SSHClient();
conn.connect(...);
```

The software details are:
```
bash-5.1$ cat /etc/redhat-release; npm -v ; node -v
Red Hat Enterprise Linux release 9.0 (Plow)
8.15.0
v16.17.1
```

```
bash-5.1$ node -e "console.log(process.versions)"
{
  node: '16.17.1',
  v8: '9.4.146.26-node.22',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.9',
  openssl: '3.0.1',
  cldr: '41.0',
  icu: '71.1',
  tz: '2022a',
  unicode: '14.0'
}
```

The error is:
```
[Thu, 02 Feb 2023 16:44:42 GMT]  Custom crypto binding not available
[Thu, 02 Feb 2023 16:44:42 GMT]  Local ident: 'SSH-2.0-ssh2js1.11.0'
[Thu, 02 Feb 2023 16:44:42 GMT]  Client: Trying 10.17.0.100 on port 22 ...
[Thu, 02 Feb 2023 16:44:42 GMT]  Socket connected
[Thu, 02 Feb 2023 16:44:42 GMT]  Remote ident: 'SSH-2.0-OpenSSH_3.5p1'
[Thu, 02 Feb 2023 16:44:42 GMT]  Outbound: Sending KEXINIT
[Thu, 02 Feb 2023 16:44:42 GMT]  Inbound: Handshake in progress
[Thu, 02 Feb 2023 16:44:42 GMT]  Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
[Thu, 02 Feb 2023 16:44:42 GMT]  Handshake: (remote) KEX method: diffie-hellman-group16-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
[Thu, 02 Feb 2023 16:44:42 GMT]  Handshake: KEX algorithm: diffie-hellman-group14-sha256
[Thu, 02 Feb 2023 16:44:42 GMT]  Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
[Thu, 02 Feb 2023 16:44:42 GMT]  Handshake: (remote) Host key format: ssh-rsa,ssh-dss
[Thu, 02 Feb 2023 16:44:42 GMT]  Handshake: Host key format: ssh-rsa
[Thu, 02 Feb 2023 16:44:42 GMT]  Handshake: (local) C->S cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
[Thu, 02 Feb 2023 16:44:42 GMT]  Handshake: (remote) C->S cipher: aes256-ctr,aes192-ctr,aes128-ctr,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,arcfour,aes192-cbc,aes256-cbc,rijndael-cbc@lysator.liu.se
[Thu, 02 Feb 2023 16:44:42 GMT]  Handshake: C->S Cipher: aes128-ctr
[Thu, 02 Feb 2023 16:44:42 GMT]  Handshake: (local) S->C cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
[Thu, 02 Feb 2023 16:44:42 GMT]  Handshake: (remote) S->C cipher: aes256-ctr,aes192-ctr,aes128-ctr,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,arcfour,aes192-cbc,aes256-cbc,rijndael-cbc@lysator.liu.se
[Thu, 02 Feb 2023 16:44:42 GMT]  Handshake: S->C cipher: aes128-ctr
[Thu, 02 Feb 2023 16:44:42 GMT]  Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[Thu, 02 Feb 2023 16:44:42 GMT]  Handshake: (remote) C->S MAC: hmac-sha2-512,hmac-sha2-256,hmac-sha1,hmac-sha1-96,hmac-md5,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-md5-96
[Thu, 02 Feb 2023 16:44:42 GMT]  Handshake: C->S MAC: hmac-sha2-256
[Thu, 02 Feb 2023 16:44:42 GMT]  Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[Thu, 02 Feb 2023 16:44:42 GMT]  Handshake: (remote) S->C MAC: hmac-sha2-512,hmac-sha2-256,hmac-sha1,hmac-sha1-96,hmac-md5,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-md5-96
[Thu, 02 Feb 2023 16:44:42 GMT]  Handshake: S->C MAC: hmac-sha2-256
[Thu, 02 Feb 2023 16:44:42 GMT]  Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
[Thu, 02 Feb 2023 16:44:42 GMT]  Handshake: (remote) C->S compression: none
[Thu, 02 Feb 2023 16:44:42 GMT]  Handshake: C->S compression: none
[Thu, 02 Feb 2023 16:44:42 GMT]  Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
[Thu, 02 Feb 2023 16:44:42 GMT]  Handshake: (remote) S->C compression: none
[Thu, 02 Feb 2023 16:44:42 GMT]  Handshake: S->C compression: none
[Thu, 02 Feb 2023 16:44:42 GMT]  Outbound: Sending KEXDH_INIT
[Thu, 02 Feb 2023 16:44:42 GMT]  Received DH Reply
[Thu, 02 Feb 2023 16:44:42 GMT]  Host accepted by default (no verification)
[Thu, 02 Feb 2023 16:44:42 GMT]  Host accepted (verified)
[Thu, 02 Feb 2023 16:44:42 GMT]  Outbound: Sending NEWKEYS
[Thu, 02 Feb 2023 16:44:42 GMT]  Inbound: NEWKEYS
[Thu, 02 Feb 2023 16:44:42 GMT]  Verifying signature ...
[Thu, 02 Feb 2023 16:44:42 GMT]  Signature verification failed: Error: error:03000098:digital envelope routines::invalid digest
    at verifyOneShot (node:internal/crypto/sig:288:39)
    at OpenSSH_Public.verify (/var/ng-cmu/sshClient/node_modules/ssh2/lib/protocol/keyParser.js:408:18)
    at DHExchange.finish (/var/ng-cmu/sshClient/node_modules/ssh2/lib/protocol/kex.js:669:40)
    at DHExchange.parse (/var/ng-cmu/sshClient/node_modules/ssh2/lib/protocol/kex.js:1216:25)
    at Protocol.onKEXPayload (/var/ng-cmu/sshClient/node_modules/ssh2/lib/protocol/kex.js:1767:20)
    at NullDecipher.decrypt (/var/ng-cmu/sshClient/node_modules/ssh2/lib/protocol/crypto.js:612:26)
    at Protocol.parsePacket [as _parse] (/var/ng-cmu/sshClient/node_modules/ssh2/lib/protocol/Protocol.js:1994:25)
    at Protocol.parse (/var/ng-cmu/sshClient/node_modules/ssh2/lib/protocol/Protocol.js:293:16)
    at Socket.<anonymous> (/var/ng-cmu/sshClient/node_modules/ssh2/lib/client.js:713:21)
    at Socket.emit (node:events:513:28)
[Thu, 02 Feb 2023 16:44:42 GMT]  Outbound: Sending DISCONNECT (3)
[Thu, 02 Feb 2023 16:44:42 GMT]  Socket ended
[Thu, 02 Feb 2023 16:44:42 GMT]  Socket closed
```

As a workaround, i have tried to set the environmental variable `NODE_OPTIONS=--openssl-legacy-provider`, restart the script, but it doesn't work.

Here are the older nodejs version that the same script was working fine:
```
bash-5.1$ cat /etc/redhat-release; npm -v ; node -v
Red Hat Enterprise Linux release 9.0 (Plow)
8.3.1
v16.14.0
```

```
bash-5.1$ node -e "console.log(process.versions)"
{
  node: '16.14.0',
  v8: '9.4.146.24-node.20',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '3.0.1',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0'
}
```

I have found a similar issue reported @ [stack-overflow](https://stackoverflow.com/questions/75021434/signature-verification-failed-error-error03000098digital-envelope-routines)...

Please let me know if additional info is needed.
Any help will be appreciated!

**Comment by mscdex** [comment]
What does `node -pe 'crypto.getHashes().sort()'` output with the problematic version of node?

**Comment by johnachli** [comment]
Hi,
the output is:

bash-5.1$ node -pe 'crypto.getHashes().sort()'
```
[
  'RSA-MD5',
  'RSA-SHA1',
  'RSA-SHA1-2',
  'RSA-SHA224',
  'RSA-SHA256',
  'RSA-SHA3-224',
  'RSA-SHA3-256',
  'RSA-SHA3-384',
  'RSA-SHA3-512',
  'RSA-SHA384',
  'RSA-SHA512',
  'RSA-SHA512/224',
  'RSA-SHA512/256',
  'RSA-SM3',
  'blake2b512',
  'blake2s256',
  'id-rsassa-pkcs1-v1_5-with-sha3-224',
  'id-rsassa-pkcs1-v1_5-with-sha3-256',
  'id-rsassa-pkcs1-v1_5-with-sha3-384',
  'id-rsassa-pkcs1-v1_5-with-sha3-512',
  'md5',
  'md5-sha1',
  'md5WithRSAEncryption',
  'sha1',
  'sha1WithRSAEncryption',
  'sha224',
  'sha224WithRSAEncryption',
  'sha256',
  'sha256WithRSAEncryption',
  'sha3-224',
  'sha3-256',
  'sha3-384',
  'sha3-512',
  'sha384',
  'sha384WithRSAEncryption',
  'sha512',
  'sha512-224',
  'sha512-224WithRSAEncryption',
  'sha512-256',
  'sha512-256WithRSAEncryption',
  'sha512WithRSAEncryption',
  'shake128',
  'shake256',
  'sm3',
  'sm3WithRSAEncryption',
  'ssl3-md5',
  'ssl3-sha1'
]
```

**Comment by mscdex** [comment]
I don't see what could be wrong then.

Out of curiosity, could you log the value of `algo` on keyParser.js:408 so we can verify it is a supported digest algorithm?

**Comment by mscdex** [comment]
It also doesn't make sense that both versions seemingly use the same OpenSSL version yet only one of them has the error.

Is it possible that one of the node binaries had OpenSSL 3.x linked statically and the other is using a shared, system OpenSSL 3.x library?

**Comment by mscdex** [comment]
What happens when you try the [official compiled node binary for v16.17.1](https://nodejs.org/dist/v16.17.1/) instead of the (assumingly) Redhat-provided binary? The official compiled node binary would have OpenSSL compiled in statically and would be using OpenSSL 1.1.1.

**Comment by johnachli** [comment]
Hi,

the value of "algo" is "sha1" on both cases.

in the problematic scenario (node v16.17.1):

the shared libs...
\# node -v && ldd /usr/bin/node
```
v16.17.1
        linux-vdso.so.1 (0x00007ffefbb34000)
        libnode.so.93 => /lib64/libnode.so.93 (0x00007f3bdbbae000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f3bdb9a4000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f3bdb98a000)
        libbrotlidec.so.1 => /lib64/libbrotlidec.so.1 (0x00007f3bdb97c000)
        libbrotlienc.so.1 => /lib64/libbrotlienc.so.1 (0x00007f3bdb8eb000)
        libcrypto.so.3 => /lib64/libcrypto.so.3 (0x00007f3bdb4bf000)
        libssl.so.3 => /lib64/libssl.so.3 (0x00007f3bdb418000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f3bdb1f1000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f3bdb116000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f3bdb0fb000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f3bdf275000)
        libbrotlicommon.so.1 => /lib64/libbrotlicommon.so.1 (0x00007f3bdb0d8000)
```

Debug logs including algo's logging...
```
...
[Wed, 15 Feb 2023 14:01:06 GMT]  Verifying signature ...
[Wed, 15 Feb 2023 14:01:06 GMT]  The value of algo is sha1  <---
[Wed, 15 Feb 2023 14:01:06 GMT]  Signature verification failed: Error: error:03000098:digital envelope routines::invalid digest
    at verifyOneShot (node:internal/crypto/sig:288:39)
    at OpenSSH_Public.verify (/var/ng-cmu/sshClient/node_modules/ssh2/lib/protocol/keyParser.js:409:18)
    at DHExchange.finish (/var/ng-cmu/sshClient/node_modules/ssh2/lib/protocol/kex.js:669:40)
    at DHExchange.parse (/var/ng-cmu/sshClient/node_modules/ssh2/lib/protocol/kex.js:1216:25)
    at Protocol.onKEXPayload (/var/ng-cmu/sshClient/node_modules/ssh2/lib/protocol/kex.js:1767:20)
    at NullDecipher.decrypt (/var/ng-cmu/sshClient/node_modules/ssh2/lib/protocol/crypto.js:612:26)
    at Protocol.parsePacket [as _parse] (/var/ng-cmu/sshClient/node_modules/ssh2/lib/protocol/Protocol.js:1994:25)
    at Protocol.parse (/var/ng-cmu/sshClient/node_modules/ssh2/lib/protocol/Protocol.js:293:16)
    at Socket.<anonymous> (/var/ng-cmu/sshClient/node_modules/ssh2/lib/client.js:713:21)
    at Socket.emit (node:events:513:28)
[Wed, 15 Feb 2023 14:01:06 GMT]  Outbound: Sending DISCONNECT (3)
[Wed, 15 Feb 2023 14:01:06 GMT]  Socket ended
[Wed, 15 Feb 2023 14:01:06 GMT]  Socket closed
```

In the working scenario (node v16.14.0):

\# node -v && ldd /usr/bin/node
```
v16.14.0
        linux-vdso.so.1 (0x00007ffd08087000)
        libnode.so.93 => /lib64/libnode.so.93 (0x00007f614c4e3000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f614c2d9000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f614c2bf000)
        libbrotlidec.so.1 => /lib64/libbrotlidec.so.1 (0x00007f614c2b1000)
        libbrotlienc.so.1 => /lib64/libbrotlienc.so.1 (0x00007f614c220000)
        libcrypto.so.3 => /lib64/libcrypto.so.3 (0x00007f614bdf4000)
        libssl.so.3 => /lib64/libssl.so.3 (0x00007f614bd4d000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f614bb26000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f614ba4b000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f614ba30000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f614fabd000)
        libbrotlicommon.so.1 => /lib64/libbrotlicommon.so.1 (0x00007f614ba0d000)
```

the algo's values is also "sha1":
```
...
[Wed, 15 Feb 2023 13:48:58 GMT]  Verifying signature ...
[Wed, 15 Feb 2023 13:48:58 GMT]  The value of algo is sha1  <---
[Wed, 15 Feb 2023 13:48:58 GMT]  Verified signature
[Wed, 15 Feb 2023 13:48:58 GMT]  Handshake completed
...
```

The final goal is to use node v18.x (and openssl 3.x.x). I originally had the same issue there, so i started to downgrade in order to narrow down the possible release that introduced the issue.
Given the fact that both red-hat's provided node binaries use the same openSSL lib, maybe a node's change between 16.14.0 & 16.17.1 affects us? According to its changelog, there are some potential commits/changes but not sure if/how they could be responsible...
So, i guess that there is no added value to check with the official nodev16.17.1, right?

**Comment by johnachli** [comment]
I tried both, but nothing changed, i get the same error.
Thank you very much for your help and prompt response!

**Comment by mscdex** [comment]
I'm not sure beyond that then as I don't see any other changes that would affect something like this. I guess you could also compare the strace output of both the working and non-working versions to see if there is anything different with regard to OpenSSL (e.g. loading different config file or similar).

Additionally you might check if your system copy of openssl.cnf is configured to reject sha1 or something. It just doesn't make sense why OpenSSL would return sha1 as a valid digest only to reject its use later.

All official binaries from nodejs.org will have their dependencies compiled in, so 16.17.1 from nodejs.org will have OpenSSL 1.1.1 and 18.x will have OpenSSL 3.x. For fun it might be good to verify that the official 16.17.1 and 18.x binaries work.

**Comment by johnachli** [comment]
Hi,

Indeed, it works by installing 16.17.1 from nodejs.org!
The node v18.14.0 is also working...


Eg. for v16:
```
bash-5.1$ node -v
v16.17.1
bash-5.1$ ldd /usr/local/bin/node
        linux-vdso.so.1 (0x00007ffc69524000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f700c3e8000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f700c1c1000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f700c0e6000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f700c0cb000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f700c0c6000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f700bebd000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f700c3f1000)
```

Regarding SHA-1, i was using update-crypto-policies to enable it (default:sha1 or legacy)...
It was working with older node (v16.14.0), but not with the newer one(v16.17.1).

I will go this way at least for now.

Thank you once more for your help!

**Comment by mscdex** [comment]
Yeah the only thing I can think of that would have changed in node is the change that was made to the OpenSSL config section name (`openssl_conf` to `nodejs_conf`) in https://github.com/nodejs/node/commit/06c6bd377bd613d78cebf8b4ac5f3d71fd6cc507, so potentially different OpenSSL settings would be applied after that change was made depending on the contents of the used OpenSSL config file.

Maybe RHEL uses a different (default) section name other than `openssl_conf` when applying OpenSSL settings.

**Comment by mscdex** [comment]
Ok, I just realized I misspoke earlier, `OPENSSL_CONF`/`--openssl-config` should have pointed to the config *file* and *not* contained the desired section name. It seems the section name can *only* be set at compile time, something presumably the RHEL maintainers should be overriding for their build of node.js in order for the correct OpenSSL settings to be used (e.g. for enabling SHA-1).

**Comment by mscdex** [comment]
Closing this for now based on the assumption of this being a RHEL build/config issue.
