### ISSUE TITLE
server exit with error when enter "exit" to shell

### ISSUE THREAD

**Issue by yangsengui** [mscdex/ssh2#1286]
I use xhsell connect to the ssh serve, when want to exit and enter the "exit" command, the server exit with error.

```
Listening on port 8023
[540184.827275400] Custom crypto binding not available
[540184.827275400] Local ident: 'SSH-2.0-ssh2js1.11.0'
[540184.827275400] Remote ident: 'SSH-2.0-nsssh2_6.0.0037 NetSarang Computer, Inc.'
[540184.827275400] Outbound: Sending KEXINIT
[540184.827275400] Inbound: Handshake in progress
[540184.827275400] Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
[540184.827275400] Handshake: (remote) KEX method: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group18-sha512,diffie-hellman-group16-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
[540184.827275400] Handshake: KEX algorithm: curve25519-sha256@libssh.org
[540184.827275400] Handshake: (local) Host key format: rsa-sha2-512,rsa-sha2-256,ssh-rsa
[540184.827275400] Handshake: (remote) Host key format: ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519
[540184.827275400] Handshake: Host key format: ssh-rsa
[540184.827275400] Handshake: (local) C->S cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
[540184.827275400] Handshake: (remote) C->S cipher: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc,blowfish-cbc,cast128-cbc,arcfour,rijndael128-cbc,rijndael192-cbc,rijndael256-cbc,rijndael-cbc@lysator.liu.se,arcfour128,arcfour256
[540184.827275400] Handshake: C->S Cipher: chacha20-poly1305@openssh.com
[540184.827275400] Handshake: (local) S->C cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
[540184.827275400] Handshake: (remote) S->C cipher: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc,blowfish-cbc,cast128-cbc,arcfour,rijndael128-cbc,rijndael192-cbc,rijndael256-cbc,rijndael-cbc@lysator.liu.se,arcfour128,arcfour256
[540184.827275400] Handshake: S->C cipher: chacha20-poly1305@openssh.com
[540184.827275400] Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[540184.827275400] Handshake: (remote) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-96,hmac-ripemd160,hmac-ripemd160@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-etm@openssh.com,hmac-md5-96-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,none
[540184.827275400] Handshake: C->S MAC: <implicit>
[540184.827275400] Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[540184.827275400] Handshake: (remote) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-96,hmac-ripemd160,hmac-ripemd160@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-etm@openssh.com,hmac-md5-96-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,none
[540184.827275400] Handshake: S->C MAC: <implicit>
[540184.827275400] Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
[540184.827275400] Handshake: (remote) C->S compression: none
[540184.827275400] Handshake: C->S compression: none
[540184.827275400] Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
[540184.827275400] Handshake: (remote) S->C compression: none
[540184.827275400] Handshake: S->C compression: none
[540184.827275400] Received DH Init
[540184.827275400] Generating signature ...
[540184.827275400] Outbound: Sending KEXECDH_REPLY
[540184.827275400] Outbound: Sending NEWKEYS
[540184.827275400] Inbound: NEWKEYS
[540184.827275400] Handshake completed
[540184.827275400] Inbound: Received SERVICE_REQUEST (ssh-userauth)
[540184.827275400] Outbound: Sending SERVICE_ACCEPT (ssh-userauth)
[540184.827275400] Inbound: Received USERAUTH_REQUEST (none)
[540184.827275400] Outbound: Sending USERAUTH_SUCCESS
[540184.827275400] Inbound: CHANNEL_OPEN (s:0, session)
[540184.827275400] Outbound: Sending CHANNEL_OPEN_CONFIRMATION (r:0, l:0)
[540184.827275400] Inbound: CHANNEL_REQUEST (r:0, x11-req)
[540184.827275400] Automatic rejection of incoming channel request: x11-req
[540184.827275400] Outbound: Sending CHANNEL_FAILURE (r:0)
[540184.827275400] Inbound: CHANNEL_REQUEST (r:0, pty-req)
[540184.827275400] Inbound: CHANNEL_REQUEST (r:0, shell)
[540184.827275400] Outbound: Sending CHANNEL_DATA (r:0, 507)
[540184.827275400] Outbound: Sending CHANNEL_DATA (r:0, 29)
[540184.827275400] Inbound: CHANNEL_DATA (r:0, 1)
[540184.827275400] Outbound: Sending CHANNEL_DATA (r:0, 1)
[540184.827275400] Inbound: CHANNEL_DATA (r:0, 1)
[540184.827275400] Outbound: Sending CHANNEL_DATA (r:0, 1)
[540184.827275400] Inbound: CHANNEL_DATA (r:0, 1)
[540184.827275400] Outbound: Sending CHANNEL_DATA (r:0, 1)
[540184.827275400] Inbound: CHANNEL_DATA (r:0, 1)
[540184.827275400] Outbound: Sending CHANNEL_DATA (r:0, 1)
[540184.827275400] Inbound: CHANNEL_DATA (r:0, 1)
[540184.827275400] Outbound: Sending CHANNEL_DATA (r:0, 19)
[540184.827275400] Outbound: Sending CHANNEL_EOF (r:0)
[540184.827275400] Outbound: Sending CHANNEL_CLOSE (r:0)
[540184.827275400] Inbound: CHANNEL_EOF (r:0)
[540184.827275400] Inbound: CHANNEL_CLOSE (r:0)
[540184.827275400] Outbound: Sending DISCONNECT (11)
[540184.827275400] Inbound: Received DISCONNECT (0, "")
Error: Unexpected disconnection reason: 0
    at DISCONNECT (E:\PycharmProjects\2023-03\asyncssh-test\untitled1\node_modules\ssh2\lib\server.js:526:25)
    at 1 (E:\PycharmProjects\2023-03\asyncssh-test\untitled1\node_modules\ssh2\lib\protocol\handlers.misc.js:53:16)
    at Protocol.onPayload (E:\PycharmProjects\2023-03\asyncssh-test\untitled1\node_modules\ssh2\lib\protocol\Protocol.js:2025:10)
    at ChaChaPolyDecipherNative.decrypt (E:\PycharmProjects\2023-03\asyncssh-test\untitled1\node_modules\ssh2\lib\protocol\crypto.js:748:26)
    at Protocol.parsePacket [as _parse] (E:\PycharmProjects\2023-03\asyncssh-test\untitled1\node_modules\ssh2\lib\protocol\Protocol.js:1994:25)
    at Protocol.parse (E:\PycharmProjects\2023-03\asyncssh-test\untitled1\node_modules\ssh2\lib\protocol\Protocol.js:293:16)
    at Socket.<anonymous> (E:\PycharmProjects\2023-03\asyncssh-test\untitled1\node_modules\ssh2\lib\server.js:1207:17)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9) {
  code: 0
}
[540184.827275400] Socket ended
[540184.827275400] Socket closed
client closed
```

**Comment by mscdex** [comment]
The server is sending an invalid disconnection reason code. You can ignore it or not. Either way you might want to notify them about it so they can fix it.

**Comment by yangsengui** [comment]
I think it's not a problem of xshell, i have the same error when I use git bash. It can be just ignored, but I don't know whether it will be a side effect

**Comment by yangsengui** [comment]
may be it's beacuse the exit code of last command "exit" is treated as the disconnection reason of client since it's the last message from server, the return code of "exit" is 0 same as the unexpected disconnection reason.
![image](https://user-images.githubusercontent.com/59313293/229841552-e8f1b71d-cb98-463c-a248-657a32d38fcc.png)
![image](https://user-images.githubusercontent.com/59313293/229843499-89f4c11d-de2a-4437-ae55-52d158aaea4b.png)

**Comment by mscdex** [comment]
SSH disconnection messages are not related to shell or any other kind of sessions, they occur globally at the connection level.

Also, I just now realized you were implementing a server and not a client, but either way, sending a disconnect reason code of zero is incorrect.
