### ISSUE TITLE
can't compile by rollup when use pnpm

### ISSUE THREAD

**Issue by x-wink** [mscdex/ssh2#1304]
if I use pnpm install all deps then compile by rollup
I will get an error
```
[!] RollupError: Could not resolve "../build/Release/cpufeatures.node" from "../build/Release/cpufeatures.node?commonjs-external"
../build/Release/cpufeatures.node?commonjs-external
    at error (E:\WorkSpace\wink-sftp\node_modules\.pnpm\rollup@3.23.0\node_modules\rollup\dist\shared\rollup.js:278:30)
    at ModuleLoader.handleInvalidResolvedId (E:\WorkSpace\wink-sftp\node_modules\.pnpm\rollup@3.23.0\node_modules\rollup\dist\shared\rollup.js:24485:24)
    at E:\WorkSpace\wink-sftp\node_modules\.pnpm\rollup@3.23.0\node_modules\rollup\dist\shared\rollup.js:24447:26
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
but when I use npm it always work
---
I try to remove ssh2 in my project
then use pnpm install deps and compile by rollup it be ok
so I think this problem is cuase by ssh2 not rollup
maybe it's pnpm's problem

**Comment by mscdex** [comment]
If rollup works with npm and not pnpm, then I would say it's a pnpm problem.

**Comment by x-wink** [comment]
thanks for your reply
