### ISSUE TITLE
After updating from v1.11.0 the asynchronous hostVerifier causes "Error: Bad packet length"

### ISSUE THREAD

**Issue by zhshch2002** [mscdex/ssh2#1312]
I'm using ssh2 in an Electron project and everything works fine in 1.11.0. The following example is reproducible in NodeJS 18 and Electron 23.

```js
const {Client} = require('ssh2');

const conn = new Client();
conn.on('ready', () => {
    console.log('Client :: ready');
    conn.exec('uptime', (err, stream) => {
        if (err) throw err;
        stream.on('close', (code, signal) => {
            console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
            conn.end();
        }).on('data', (data) => {
            console.log('STDOUT: ' + data);
        }).stderr.on('data', (data) => {
            console.log('STDERR: ' + data);
        });
    });
}).connect({
    host: '192.168.3.42',
    port: 22,
    username: 'xxxxxxx',
    password: 'xxxxxxx',
    hostVerifier: (key, verify) => {
        console.log(key.toString("hex"));
        verify(true);
        // setTimeout(() => verify(true), 1000);
    },
});
```

everything normal, output:

```
0000000b73736xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx0941749a7c
Client :: ready
STDOUT:  07:42:57 up 3 days, 20:49,  0 users,  load average: 0.04, 0.05, 0.01

Stream :: close :: code: 0, signal: undefined
```

Things go wrong here:

```js
const {Client} = require('ssh2');

const conn = new Client();
conn.on('ready', () => {
    console.log('Client :: ready');
    conn.exec('uptime', (err, stream) => {
        if (err) throw err;
        stream.on('close', (code, signal) => {
            console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
            conn.end();
        }).on('data', (data) => {
            console.log('STDOUT: ' + data);
        }).stderr.on('data', (data) => {
            console.log('STDERR: ' + data);
        });
    });
}).connect({
    host: '192.168.3.42',
    port: 22,
    username: 'xxxxxx',
    password: 'xxxxxx',
    hostVerifier: (key, verify) => {
        console.log(key.toString("hex"));
        // verify(true);
        setTimeout(() => verify(true), 1000);
    },
});
```

throws:

```
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: Bad packet length
    at NullDecipher.decrypt (/home/xxxxx/.pnpm/ssh2@1.13.0/node_modules/ssh2/lib/protocol/crypto.js:570:17)
    at Protocol.parsePacket [as _parse] (/home/xxxxx/.pnpm/ssh2@1.13.0/node_modules/ssh2/lib/protocol/Protocol.js:2021:25)
    at Protocol.parse (/home/xxxxx/.pnpm/ssh2@1.13.0/node_modules/ssh2/lib/protocol/Protocol.js:306:16)
    at Socket.<anonymous> (/home/xxxxx/.pnpm/ssh2@1.13.0/node_modules/ssh2/lib/client.js:775:21)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
Emitted 'error' event on Client instance at:
    at Socket.<anonymous> (/home/xxxxx/.pnpm/ssh2@1.13.0/node_modules/ssh2/lib/client.js:777:20)
    at Socket.emit (node:events:513:28)
    [... lines matching original stack trace ...]
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

Node.js v18.15.0
```

**Comment by mscdex** [comment]
I am able to reproduce the error. It's due to OpenSSH sending a (encrypted) packet (EXT_INFO) immediately after it sends NEWKEYS but before we update the deciphering information.

Can you please verify this patch works for you?:

```patch
diff --git a/lib/protocol/kex.js b/lib/protocol/kex.js
index a70ad4a..1724ff1 100644
--- a/lib/protocol/kex.js
+++ b/lib/protocol/kex.js
@@ -532,7 +532,7 @@ const createKeyExchange = (() => {
       this._dhData = undefined;
       this._sig = undefined;
     }
-    finish() {
+    finish(scOnly) {
       if (this._finished)
         return false;
       this._finished = true;
@@ -783,9 +783,26 @@ const createKeyExchange = (() => {
           this._protocol._packetRW.write.finalize(packet, true)
         );
       }
-      trySendNEWKEYS(this);
 
-      const completeHandshake = () => {
+      if (isServer || !scOnly)
+        trySendNEWKEYS(this);
+
+      let hsCipherConfig;
+      let hsWrite;
+      const completeHandshake = (partial) => {
+        if (hsCipherConfig) {
+          trySendNEWKEYS(this);
+          hsCipherConfig.outbound.seqno = this._protocol._cipher.outSeqno;
+          this._protocol._cipher.free();
+          this._protocol._cipher = createCipher(hsCipherConfig);
+          this._protocol._packetRW.write = hsWrite;
+          hsCipherConfig = undefined;
+          hsWrite = undefined;
+          this._protocol._onHandshakeComplete(negotiated);
+
+          return false;
+        }
+
         if (!this.sessionID)
           this.sessionID = exchangeHash;
 
@@ -868,9 +885,8 @@ const createKeyExchange = (() => {
             macKey: (isServer ? scMacKey : csMacKey),
           },
         };
-        this._protocol._cipher && this._protocol._cipher.free();
-        this._protocol._decipher && this._protocol._decipher.free();
-        this._protocol._cipher = createCipher(config);
+        this._protocol._decipher.free();
+        hsCipherConfig = config;
         this._protocol._decipher = createDecipher(config);
 
         const rw = {
@@ -937,7 +953,8 @@ const createKeyExchange = (() => {
         }
         this._protocol._packetRW.read.cleanup();
         this._protocol._packetRW.write.cleanup();
-        this._protocol._packetRW = rw;
+        this._protocol._packetRW.read = rw.read;
+        hsWrite = rw.write;
 
         // Cleanup/reset various state
         this._public = null;
@@ -950,13 +967,16 @@ const createKeyExchange = (() => {
         this._dhData = undefined;
         this._sig = undefined;
 
-        this._protocol._onHandshakeComplete(negotiated);
-
+        if (!partial)
+          return completeHandshake();
         return false;
       };
+
+      if (isServer || scOnly)
+        this.finish = completeHandshake;
+
       if (!isServer)
-        return completeHandshake();
-      this.finish = completeHandshake;
+        return completeHandshake(scOnly);
     }
 
     start() {
@@ -1217,12 +1237,8 @@ const createKeyExchange = (() => {
           );
           this._receivedNEWKEYS = true;
           ++this._step;
-          if (this._protocol._server || this._hostVerified)
-            return this.finish();
 
-          // Signal to current decipher that we need to change to a new decipher
-          // for the next packet
-          return false;
+          return this.finish(!this._protocol._server && !this._hostVerified);
         default:
           return doFatalError(
             this._protocol,
```
