### ISSUE TITLE
`Handshake failed: no matching host key format` on `ssh-keyscan`

### ISSUE THREAD

**Issue by manelio** [mscdex/ssh2#1341]
Server crashes with error `Handshake failed: no matching host key format` and I can't find a way to capture the error before it crashes the server.

Simple code to reproduce the problem:

```
import { readFileSync } from 'fs';
import ssh2 from 'ssh2';
const { Server } = ssh2;
const hostKeys = [readFileSync('tls/server')];
new Server({
  hostKeys: hostKeys,
}, (client) => {})
.listen(2222, '0.0.0.0')
;
```

```
ssh-keyscan -p2222 localhost

# localhost:2222 SSH-2.0-ssh2js1.14.0
[localhost]:2222 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCV+I1wJ5cHUkoZNGpBkdh/ruW8H/+IqU7hu0ni4tCPo/HVQiNECy+06WwcEfwymzUlrjGzgepX/2jWtzW5L4QP/ePF07VJvFvXyrVjjwQV2K+SRKd5HLeXuwaAVh+r3Fe4i23JZlax24Hafrj5gJW2LLjqsvbP8YmvIaVzGKu92pRG0xMfEMjl1KsTzinE/flhqw+SYEZrPT78bhC0CLmhbEXbHUFSD8z0anuxpgoAEfpHx8Wcm9K4ap9xr4CXfFuZH6I1lQiZMeuGmr1Me6yNAQo06KjQ2jOpxuvy2X62uYJj2hB4rwLAcw3KPWm3re7RpYJPSBqoIixvlP5j833MUZWVzfeVFUK9OllbESuiQek3xixMKdrdLwP98FUq+AK7DMMl0JYsHd4+q8nJKXwMLg7q7qi+N39DvQaG4ofdLFLEtsXt1jxeiVxK5ka0NUQURbF7jVk+VLV+YvY+tDi6TneOMbrqT1Dcqw6Db4Wac7EkEH+Ayqb1orKtQhgQ9CE=
# localhost:2222 SSH-2.0-ssh2js1.14.0
# localhost:2222 SSH-2.0-ssh2js1.14.0
# localhost:2222 SSH-2.0-ssh2js1.14.0
# localhost:2222 SSH-2.0-ssh2js1.14.0

```

But

```
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: Handshake failed: no matching host key format
    at makeError (/home/manel/svc/xpose/node_modules/ssh2/lib/protocol/utils.js:142:15)
    at doFatalError (/home/manel/svc/xpose/node_modules/ssh2/lib/protocol/utils.js:184:13)
    at handleKexInit (/home/manel/svc/xpose/node_modules/ssh2/lib/protocol/kex.js:282:12)
    at Protocol.onKEXPayload (/home/manel/svc/xpose/node_modules/ssh2/lib/protocol/kex.js:1782:14)
    at NullDecipher.decrypt (/home/manel/svc/xpose/node_modules/ssh2/lib/protocol/crypto.js:612:26)
    at Protocol.parsePacket [as _parse] (/home/manel/svc/xpose/node_modules/ssh2/lib/protocol/Protocol.js:2021:25)
    at Protocol.parse (/home/manel/svc/xpose/node_modules/ssh2/lib/protocol/Protocol.js:306:16)
    at Socket.<anonymous> (/home/manel/svc/xpose/node_modules/ssh2/lib/server.js:1209:17)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
Emitted 'error' event on Client instance at:
    at Socket.<anonymous> (/home/manel/svc/xpose/node_modules/ssh2/lib/server.js:1211:16)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  level: 'handshake',
  fatal: true
}

Node.js v18.16.0
```

I traced the problem to server.js line 1205:

```
    cryptoInit.then(() => {
      proto.start();
      socket.on('data', (data) => {
        try {
          proto.parse(data, 0, data.length);
        } catch (ex) {
          this.emit('error', ex);
          try {
            if (isWritable(socket))
              socket.end();
          } catch {}
        }
      });
      socket.resume();
    }).catch((err) => {
```

I can't find a way to capture that `this.emit('error', ex);`

serverList and clientList output in kex.js is:

```
console.log(serverList)
console.log(clientList)
```

```
Client connected!
{
  clientList: [ 'rsa-sha2-512', 'rsa-sha2-256', 'ssh-rsa' ],
  serverList: [ 'rsa-sha2-512', 'rsa-sha2-256', 'ssh-rsa' ]
}
Client disconnected
Client connected!
{
  clientList: [
    'ecdsa-sha2-nistp256',
    'ecdsa-sha2-nistp384',
    'ecdsa-sha2-nistp521'
  ],
  serverList: [ 'rsa-sha2-512', 'rsa-sha2-256', 'ssh-rsa' ]
}
```

My main concern here is the ability for a client to crash the server.

**Comment by mscdex** [comment]
Like any other `EventEmitter` in node, you need to listen for the `'error'` event.

**Comment by manelio** [comment]
Lol. Shame on me.

Thanks!
