### ISSUE TITLE
"Instance unusable after fatal error" - Connection working for the first call, then failing

### ISSUE THREAD

**Issue by SquirrelCorporation** [mscdex/ssh2#1392]
Hi,
I am encountering a problem I cannot manage to fix.
Using a custom, basic agent to call "docker system dial-stdio" , and Using a Username and password or Username/Key -> the first call is working, but all others requests failed

Agent code:
```
export const getCustomAgent = (childLogger: any, opt: any) => {
  const conn = new Client();
  const cAgent = new Agent();
  // @ts-expect-error creating a new function
  cAgent.createConnection = function (options, fn) {
    conn
      .once('ready', function () {
        conn.exec('docker system dial-stdio', function (err, stream) {
          if (err) {
            handleError(err);
          }

          fn(null, stream);
          stream.addListener('error', (err) => {
            handleError(err);
          });
          stream.once('close', () => {
            conn.end();
            cAgent.destroy();
          });
        });
      })
      .on('error', (err) => {
        //childLogger.error(`Error connecting to ${opt.host}`);
        //childLogger.error(err);
        fn(err);
      })
      .connect(opt);

    conn.once('end', () => cAgent.destroy());
  };
  function handleError(err: any) {
    conn.end();
    cAgent.destroy();
    throw err;
  }
  return cAgent;
};
```

### Debug Logs

```
server-1   | Custom crypto binding not available
server-1   | Local ident: 'SSH-2.0-ssh2js1.15.0'
server-1   | Client: Trying 192.168.0.229 on port 22 ...
server-1   | Socket connected
server-1   | Remote ident: 'SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.7'
server-1   | Outbound: Sending KEXINIT
server-1   | Inbound: Handshake in progress
server-1   | Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512,ext-info-c,kex-strict-c-v00@openssh.com
server-1   | Handshake: (remote) KEX method: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,sntrup761x25519-sha512@openssh.com,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,kex-strict-s-v00@openssh.com
server-1   | Handshake: strict KEX mode enabled
server-1   | Handshake: KEX algorithm: curve25519-sha256@libssh.org
server-1   | Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
server-1   | Handshake: (remote) Host key format: rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
server-1   | Handshake: Host key format: ssh-ed25519
server-1   | Handshake: (local) C->S cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
server-1   | Handshake: (remote) C->S cipher: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
server-1   | Handshake: C->S Cipher: aes128-gcm@openssh.com
server-1   | Handshake: (local) S->C cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
server-1   | Handshake: (remote) S->C cipher: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
server-1   | Handshake: S->C cipher: aes128-gcm@openssh.com
server-1   | Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
server-1   | Handshake: (remote) C->S MAC: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
server-1   | Handshake: C->S MAC: <implicit>
server-1   | Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
server-1   | Handshake: (remote) S->C MAC: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
server-1   | Handshake: S->C MAC: <implicit>
server-1   | Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
server-1   | Handshake: (remote) C->S compression: none,zlib@openssh.com
server-1   | Handshake: C->S compression: none
server-1   | Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
server-1   | Handshake: (remote) S->C compression: none,zlib@openssh.com
server-1   | Handshake: S->C compression: none
server-1   | Outbound: Sending KEXECDH_INIT
server-1   | Received DH Reply
server-1   | Host accepted by default (no verification)
server-1   | Host accepted (verified)
server-1   | Outbound: Sending NEWKEYS
server-1   | Inbound: NEWKEYS
server-1   | Verifying signature ...
server-1   | Verified signature
server-1   | Handshake completed
server-1   | Outbound: Sending SERVICE_REQUEST (ssh-userauth)
server-1   | Inbound: Received EXT_INFO
server-1   | Inbound: Received SERVICE_ACCEPT (ssh-userauth)
server-1   | Outbound: Sending USERAUTH_REQUEST (none)
server-1   | Inbound: Received USERAUTH_FAILURE (publickey,password)
server-1   | Client: none auth failed
server-1   | Outbound: Sending USERAUTH_REQUEST (password)
server-1   | Inbound: Received USERAUTH_SUCCESS
server-1   | Outbound: Sending CHANNEL_OPEN (r:0, session)
server-1   | Inbound: GLOBAL_REQUEST (hostkeys-00@openssh.com)
server-1   | Outbound: Sending GLOBAL_REQUEST (hostkeys-prove-00@openssh.com)
server-1   | Inbound: CHANNEL_OPEN_CONFIRMATION (r:0, s:0)
server-1   | Outbound: Sending CHANNEL_REQUEST (r:0, exec: docker system dial-stdio)
server-1   | Inbound: REQUEST_SUCCESS
server-1   | Inbound: CHANNEL_WINDOW_ADJUST (r:0, 2097152)
server-1   | Inbound: CHANNEL_SUCCESS (r:0)
server-1   | Outbound: Sending CHANNEL_DATA (r:0, 79)
server-1   | Inbound: CHANNEL_DATA (r:0, 8971)
server-1   | Outbound: Sending CHANNEL_EOF (r:0)
server-1   | Inbound: CHANNEL_EOF (r:0)
server-1   | Inbound: CHANNEL_REQUEST (r:0, exit-status: 0)
server-1   | Inbound: CHANNEL_CLOSE (r:0)
server-1   | Outbound: Sending CHANNEL_CLOSE (r:0)
server-1   | Outbound: Sending DISCONNECT (11)
server-1   | Custom crypto binding not available
server-1   | Local ident: 'SSH-2.0-ssh2js1.15.0'
server-1   | Client: Trying 192.168.0.229 on port 22 ...
server-1   | Outbound: Sending DISCONNECT (11)
server-1   | Custom crypto binding not available
server-1   | Local ident: 'SSH-2.0-ssh2js1.15.0'
server-1   | Client: Trying 192.168.0.229 on port 22 ...
server-1   | Outbound: Sending DISCONNECT (11)
server-1   | Custom crypto binding not available
server-1   | Local ident: 'SSH-2.0-ssh2js1.15.0'
server-1   | Client: Trying 192.168.0.229 on port 22 ...
server-1   | Socket ended
server-1   | Socket connected
server-1   | Socket connected
server-1   | Socket connected
server-1   | Socket closed
server-1   | Outbound: Sending DISCONNECT (11)
server-1   | Custom crypto binding not available
server-1   | Local ident: 'SSH-2.0-ssh2js1.15.0'
server-1   | Client: Trying 192.168.0.229 on port 22 ...
server-1   | Socket ended
server-1   | Socket closed
server-1   | Outbound: Sending DISCONNECT (11)
server-1   | Socket connected
server-1   | Remote ident: 'SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.7'
server-1   | Outbound: Sending KEXINIT
server-1   | Socket ended
server-1   | Socket closed
server-1   | Custom crypto binding not available
server-1   | Local ident: 'SSH-2.0-ssh2js1.15.0'
server-1   | Client: Trying 192.168.0.229 on port 22 ...
server-1   | Socket connected
server-1   | Remote ident: 'SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.7'
server-1   | Outbound: Sending KEXINIT
server-1   | Inbound: Handshake in progress
server-1   | Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512,ext-info-c,kex-strict-c-v00@openssh.com
server-1   | Handshake: (remote) KEX method: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,sntrup761x25519-sha512@openssh.com,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,kex-strict-s-v00@openssh.com
server-1   | Handshake: strict KEX mode enabled
server-1   | Handshake: KEX algorithm: curve25519-sha256@libssh.org
server-1   | Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
server-1   | Handshake: (remote) Host key format: rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
server-1   | Handshake: Host key format: ssh-ed25519
server-1   | Handshake: (local) C->S cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
server-1   | Handshake: (remote) C->S cipher: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
server-1   | Handshake: C->S Cipher: aes128-gcm@openssh.com
server-1   | Handshake: (local) S->C cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
server-1   | Handshake: (remote) S->C cipher: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
server-1   | Handshake: S->C cipher: aes128-gcm@openssh.com
server-1   | Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
server-1   | Handshake: (remote) C->S MAC: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
server-1   | Handshake: C->S MAC: <implicit>
server-1   | Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
server-1   | Handshake: (remote) S->C MAC: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
server-1   | Handshake: S->C MAC: <implicit>
server-1   | Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
server-1   | Handshake: (remote) C->S compression: none,zlib@openssh.com
server-1   | Handshake: C->S compression: none
server-1   | Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
server-1   | Handshake: (remote) S->C compression: none,zlib@openssh.com
server-1   | Handshake: S->C compression: none
server-1   | Outbound: Sending KEXECDH_INIT
server-1   | Received DH Reply
server-1   | Host accepted by default (no verification)
server-1   | Host accepted (verified)
server-1   | Outbound: Sending NEWKEYS
server-1   | Inbound: NEWKEYS
server-1   | Verifying signature ...
server-1   | Verified signature
server-1   | Handshake completed
server-1   | Outbound: Sending SERVICE_REQUEST (ssh-userauth)
server-1   | Inbound: Received EXT_INFO
server-1   | Inbound: Received SERVICE_ACCEPT (ssh-userauth)
server-1   | Outbound: Sending USERAUTH_REQUEST (none)
server-1   | Inbound: Received USERAUTH_FAILURE (publickey,password)
server-1   | Client: none auth failed
server-1   | Outbound: Sending USERAUTH_REQUEST (password)
server-1   | Inbound: Received USERAUTH_SUCCESS
server-1   | Outbound: Sending CHANNEL_OPEN (r:0, session)
server-1   | Outbound: Sending CHANNEL_OPEN (r:1, session)
server-1   | Outbound: Sending CHANNEL_OPEN (r:2, session)
server-1   | Outbound: Sending CHANNEL_OPEN (r:3, session)
server-1   | Outbound: Sending CHANNEL_OPEN (r:4, session)
server-1   | Inbound: GLOBAL_REQUEST (hostkeys-00@openssh.com)
server-1   | Outbound: Sending GLOBAL_REQUEST (hostkeys-prove-00@openssh.com)
server-1   | Inbound: CHANNEL_OPEN_CONFIRMATION (r:0, s:0)
server-1   | Outbound: Sending CHANNEL_REQUEST (r:0, exec: docker system dial-stdio)
server-1   | Inbound: CHANNEL_OPEN_CONFIRMATION (r:1, s:1)
server-1   | Outbound: Sending CHANNEL_REQUEST (r:1, exec: docker system dial-stdio)
server-1   | Inbound: CHANNEL_OPEN_CONFIRMATION (r:2, s:2)
server-1   | Outbound: Sending CHANNEL_REQUEST (r:2, exec: docker system dial-stdio)
server-1   | Inbound: CHANNEL_OPEN_CONFIRMATION (r:3, s:3)
server-1   | Outbound: Sending CHANNEL_REQUEST (r:3, exec: docker system dial-stdio)
server-1   | Inbound: CHANNEL_OPEN_CONFIRMATION (r:4, s:4)
server-1   | Outbound: Sending CHANNEL_REQUEST (r:4, exec: docker system dial-stdio)
server-1   | Inbound: REQUEST_SUCCESS
server-1   | Inbound: CHANNEL_WINDOW_ADJUST (r:0, 2097152)
server-1   | Inbound: CHANNEL_SUCCESS (r:0)
server-1   | Inbound: CHANNEL_WINDOW_ADJUST (r:1, 2097152)
server-1   | Inbound: CHANNEL_SUCCESS (r:1)
server-1   | Inbound: CHANNEL_WINDOW_ADJUST (r:2, 2097152)
server-1   | Inbound: CHANNEL_SUCCESS (r:2)
server-1   | Inbound: CHANNEL_WINDOW_ADJUST (r:3, 2097152)
server-1   | Inbound: CHANNEL_SUCCESS (r:3)
server-1   | Inbound: CHANNEL_WINDOW_ADJUST (r:4, 2097152)
server-1   | Inbound: CHANNEL_SUCCESS (r:4)
server-1   | Socket closed
server-1   | Socket closed
server-1   | Inbound: CHANNEL_EOF (r:1)
server-1   | Inbound: CHANNEL_REQUEST (r:1, exit-status: 0)
server-1   | Inbound: CHANNEL_CLOSE (r:1)
server-1   | Inbound: CHANNEL_EOF (r:3)
server-1   | Inbound: CHANNEL_REQUEST (r:3, exit-status: 0)
server-1   | Inbound: CHANNEL_CLOSE (r:3)
server-1   | Inbound: CHANNEL_EOF (r:0)
server-1   | Inbound: CHANNEL_REQUEST (r:0, exit-status: 0)
server-1   | Inbound: CHANNEL_CLOSE (r:0)
server-1   | Inbound: CHANNEL_EOF (r:2)
server-1   | Inbound: CHANNEL_REQUEST (r:2, exit-status: 0)
server-1   | Inbound: CHANNEL_CLOSE (r:2)
server-1   | Inbound: CHANNEL_EOF (r:4)
server-1   | Inbound: CHANNEL_REQUEST (r:4, exit-status: 0)
server-1   | Inbound: CHANNEL_CLOSE (r:4)

```

**Comment by SquirrelCorporation** [comment]
After further investigation, and putting a logger in ` on('error', ` , I am getting an underlying error:
```
server-1   |     err: {
server-1   |       "type": "Error",
server-1   |       "message": "Bad packet length",
server-1   |       "stack":
server-1   |           Error: Bad packet length
server-1   |               at NullDecipher.decrypt (/server/node_modules/ssh2/lib/protocol/crypto.js:570:17)
server-1   |               at Protocol.parsePacket [as _parse] (/server/node_modules/ssh2/lib/protocol/Protocol.js:2028:25)
server-1   |               at Protocol.parse (/server/node_modules/ssh2/lib/protocol/Protocol.js:313:16)
server-1   |               at Socket.<anonymous> (/server/node_modules/ssh2/lib/client.js:775:21)
server-1   |               at Socket.emit (node:events:519:28)
server-1   |               at Socket.emit (node:domain:488:12)
server-1   |               at addChunk (node:internal/streams/readable:559:12)
server-1   |               at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
server-1   |               at Socket.Readable.push (node:internal/streams/readable:390:5)
server-1   |               at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
server-1   |     }

```

**Comment by SquirrelCorporation** [comment]
Thanks for the tip, it works, with the following code:

```
const cAgent = new ssh2.HTTPAgent(opt, { keepAlive: true });
  // @ts-expect-error creating a new function
  cAgent.createConnection = function (options, fn) {
    try {
      const conn = new Client();

      const handleError = (err: any) => {
        //   conn.end();
        //  cAgent.destroy();
        throw err;
      };
      const decorateHttpStream = (stream) => {
        stream.setKeepAlive = () => {};
        stream.setNoDelay = () => {};
        stream.setTimeout = () => {};
        stream.ref = () => {};
        stream.unref = () => {};
        stream.destroySoon = stream.destroy;
        return stream;
      };
      conn
        .once('ready', function () {
          conn.exec('docker system dial-stdio', function (err, stream) {
            if (err) {
              childLogger.error('Encountering an exec SSH error');
              childLogger.error(err);
              conn.end();
              cAgent.destroy();
              handleError(err);
            }
            stream.addListener('error', (err) => {
              childLogger.error('Encountering an stream SSH error');
              childLogger.error(err);
              conn.end();
              cAgent.destroy();
              handleError(err);
            });
            stream.once('close', () => {
              childLogger.error('Stream closed');
              conn.end();
              cAgent.destroy();
            });
            return fn(null, decorateHttpStream(stream));
          });
        })
        .on('error', (err) => {
          childLogger.error(`Error connecting to ${opt.host}`);
          childLogger.error(err);
          fn(err);
        })
        .once('end', () => {
          childLogger.error('Agent destroy');
          conn.end();
          cAgent.destroy();
        })
        .connect(opt);
    } catch (error) {
      childLogger.error('Uncatch error');
      childLogger.error(error);
      fn(error);
    }
  };
  return cAgent;
```
