### ISSUE TITLE
I can't connect Unhandled 'error' event

### ISSUE THREAD

**Issue by benzmuircroft** [mscdex/ssh2#152]
I get unhandled error, I don't know what to do as you have no docs for this...

putty command:

openssl rsa -in /home/engine/ssl.key -out /home/engine/ssl.key.rsa

node.js code:

``` javascript
var Connection = require('ssh2');

var conn = new Connection();
conn.on('ready', function() {
  console.log('Connection :: ready');
  conn.shell('uptime', function(err, stream) {
    if (err) throw err;
    stream.on('close', function() {
      console.log('Stream :: close');
      conn.end();
    }).on('data', function(data) {
      console.log('STDOUT: ' + data);
    }).stderr.on('data', function(data) {
      console.log('STDERR: ' + data);
    });
    stream.end('ls -l\nexit\n');
  });
}).connect({
  host: '127.0.0.1',
  port: 22,
  username: 'root',
  privateKey: require('fs').readFileSync('/home/engine/ssl.key.rsa')
});
```

then attempt to run:

node /home/engine/private_js/ssh.js

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
```

**Comment by edenzv** [comment]
Thanks, @mscdex good solution
