### ISSUE TITLE
gulp exits with 'Error in plugin' when ssh2 (gulp-sftp) is used with gulp-concat and gulp.watch

### ISSUE THREAD

**Issue by u01jmg3** [mscdex/ssh2#153]
``` js
gulp.task('compile:js:remote', function(){
    return gulp.src(srcJs, {base: src})
        .pipe(plumber({
            errorHandler: onError
        }))
        .pipe(removelogs())
        .pipe(uglify({outSourceMap: false}))
        .pipe(order([
            '**/**/jquery.js',
            '**/**/jquery.ui.js',
            '**/**/custom.js',
            '**/**/modernizr.js',
            '**/**/jquery.fancybox.js',
            '**/**/*.js'
        ]))
        .pipe(concat('all.min.js'))
        .pipe(gulp.dest(distScripts))
        .pipe(sftp({
            host: host,
            auth: auth,
            remotePath: remotePath + '/' + distScripts
        }))        
    ;
});
```

`compile:js:remote` is triggered after a change (`gulp.watch`) is made to source JavaScript. It should re-minify my code and upload the resulting file. However, `ssh2` is erroring out with the following. Only just introduced `gulp-concat` to this task but previously `ssh2` (`gulp-sftp`) was working without issue when I wasn't combining my JavaScript files. I've tried `{buffer: false}` but on the first run where files for this project (43 files) are uploaded `ssh2` (`gulp-sftp`) has no problem dealing with `all.min.js` (which is only 459KB). Previously created an issue for this here: https://github.com/gtg092x/gulp-sftp/issues/8#issuecomment-47936244

``` js
[14:17:33] Starting 'compile:js:remote'...
[14:17:37] Authenticating with private key.
[14:17:37] SFTP :: SFTP session closed

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error in plugin '←[36mgulp-sftp←[39m'
SFTP abrupt closure
    at SFTP.<anonymous> (C:\Users\com265\AppData\Roaming\npm\node_modules\gulp-s
ftp\index.js:148:44)
    at SFTP.emit (events.js:92:17)
    at ChannelStream.<anonymous> (C:\Users\com265\AppData\Roaming\npm\node_modul
es\gulp-sftp\node_modules\ssh2\lib\SFTP\SFTPv3.js:58:10)
    at ChannelStream.g (events.js:180:16)
    at ChannelStream.emit [as _emit] (events.js:117:20)
    at ChannelStream.emit (C:\Users\com265\AppData\Roaming\npm\node_modules\gulp
-sftp\node_modules\ssh2\lib\Channel.js:638:12)
    at Parser.<anonymous> (C:\Users\com265\AppData\Roaming\npm\node_modules\gulp
-sftp\node_modules\ssh2\lib\Channel.js:60:20)
    at Parser.g (events.js:180:16)
    at Parser.emit (events.js:92:17)
    at Parser.parsePacket (C:\Users\com265\AppData\Roaming\npm\node_modules\gulp
-sftp\node_modules\ssh2\lib\Parser.js:644:12)
```

**Comment by helloaivz** [comment]
use this https://www.npmjs.com/package/gulp-sftp-up4
