### ISSUE TITLE
Allow host-based authentication

### ISSUE THREAD

**Issue by sandrich** [mscdex/ssh2#193]
Hi

Any chance host-based authentication could be included?
Currently I get

```
Error: Authentication failure. Available authentication methods: publickey,gssapi-with-mic,password,hostbased
    at Connection._tryNextAuth (/opt/bis/node/node_modules/bis-package/node_modules/ssh2/lib/Connection.js:1010:13)
    at onUSERAUTH_FAILURE (/opt/bis/node/node_modules/bis-package/node_modules/ssh2/lib/Connection.js:2449:8)
    at Parser.<anonymous> (/opt/bis/node/node_modules/bis-package/node_modules/ssh2/lib/Connection.js:141:5)
    at Parser.emit (events.js:98:17)
    at Parser.parsePacket (/opt/bis/node/node_modules/bis-package/node_modules/ssh2/lib/Parser.js:488:12)
    at Parser.execute (/opt/bis/node/node_modules/bis-package/node_modules/ssh2/lib/Parser.js:249:14)
    at Socket.<anonymous> (/opt/bis/node/node_modules/bis-package/node_modules/ssh2/lib/Connection.js:536:18)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:748:14)
    at Socket.emit (events.js:92:17)
```

In Perl I would use the following

```
/usr/bin/ssh -t -o PreferredAuthentications=hostbased 2>/dev/null"
```

**Comment by yorkie** [comment]
@mscdex any example about using hostbased?

**Comment by mscdex** [comment]
@yorkie Just set `localHostname`, `localUsername`, and `privateKey`.

**Comment by yorkie** [comment]
Hey I'm actually not familiar with the Host-based authentication, the following settings is right?

```
{
  "localHostname": "127.0.0.1",
  "localUsername": "yorkie",
  "privateKey": fs.readFileSync("~/.ssh/id_rsa")
}
```

By the way, a little confusion about the `privateKey`, `ssh2` takes `config.privateKey.type` to get the type, but `fs.readFileSync()` doesn't return it.

**Comment by mscdex** [comment]
@yorkie That looks almost right, except `fs` does not expand tildes or shell variables, so that will result in an error. `privateKey` is parsed to an object that contains various properties, including those used by the authentication code.
