### ISSUE TITLE
[rewrite] Cannot read property 'outgoing' of undefined

### ISSUE THREAD

**Issue by mofux** [mscdex/ssh2#204]
From time to time, the module crashes with the following error:

```javascript
TypeError: Cannot read property 'outgoing' of undefined
    at send (/vagrant/modules/ssh-proxy/node_modules/ssh2-streams/lib/ssh.js:4568:29)
    at SSH2Stream.channelEOF (/vagrant/modules/ssh-proxy/node_modules/ssh2-streams/lib/ssh.js:747:10)
    at Channel.eof (/vagrant/modules/ssh-proxy/node_modules/ssh2/lib/Channel.js:284:35)
    at Channel.onFinish (/vagrant/modules/ssh-proxy/node_modules/ssh2/lib/Channel.js:245:10)
    at Channel.emit (events.js:92:17)
    at finishMaybe (_stream_writable.js:359:12)
    at endWritable (_stream_writable.js:366:3)
    at Channel.Writable.end (_stream_writable.js:344:5)
    at Client.onClientClose (/vagrant/modules/ssh-proxy/node_modules/ssh2/lib/Channel.js:270:12)
    at Client.g (events.js:180:16)
```

Looking at the code, this is caused if the sshstream connection is closed ("end" event), and in ```ssh2-streams/lib/ssh.js```, line ```175```, the self._state is set to ```undefined```.

Later on, channelEOF (line ```738```) is calling the send() method (line ```4566```), which expects the ```_state``` object to be present, but it got ```undefined``` before.

**Comment by mscdex** [comment]
This should be fixed now in `ssh2-streams`. Please try again with `npm install https://github.com/mscdex/ssh2/tarball/rewrite`.

**Comment by mofux** [comment]
I can confirm this has been fixed. Many thanks for your work on the ssh module, it's awesome!
