### ISSUE TITLE
TypeError: First argument needs to be a number, array or string

### ISSUE THREAD

**Issue by onairelav** [mscdex/ssh2#224]
Hello all,

I am having this error on the server 

buffer.js:188
        throw new TypeError('First argument needs to be a number, ' +
              ^
TypeError: First argument needs to be a number, array or string.
    at new Buffer (buffer.js:188:15)
    at onNEWKEYS (/root/proxy/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:2918:24)
    at SSH2Stream.<anonymous> (/root/proxy/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:181:35)
    at SSH2Stream.emit (events.js:117:20)
    at parsePacket (/root/proxy/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3351:10)
    at SSH2Stream._transform (/root/proxy/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:538:13)
    at SSH2Stream.Transform._read (_stream_transform.js:179:10)
    at SSH2Stream.Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)

########################################
below the CLIENT log
root@proxy:~/proxy# ssh -v  hba@127.0.0.1 -p 54830
OpenSSH_6.7p1 Debian-3, OpenSSL 1.0.1j 15 Oct 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to 127.0.0.1 [127.0.0.1] port 54830.
debug1: Connection established.
debug1: permanently_set_uid: 0/0
debug1: identity file /root/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.7p1 Debian-3
debug1: Remote protocol version 2.0, remote software version ssh2js0.0.2srv
debug1: no match: ssh2js0.0.2srv
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client aes128-ctr hmac-sha2-256 none
debug1: kex: client->server aes128-ctr hmac-sha2-256 none
debug1: sending SSH2_MSG_KEXDH_INIT
debug1: expecting SSH2_MSG_KEXDH_REPLY
debug1: Server host key: RSA 23:64:fe:5d:63:ec:0e:65:c9:49:8a:13:c4:d7:ae:d1
debug1: checking without port identifier
The authenticity of host '[127.0.0.1]:54830 ([127.0.0.1]:54830)' can't be established.
RSA key fingerprint is 23:64:fe:5d:63:ec:0e:65:c9:49:8a:13:c4:d7:ae:d1.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[127.0.0.1]:54830' (RSA) to the list of known hosts.
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: Roaming not allowed by server
debug1: SSH2_MSG_SERVICE_REQUEST sent
Connection closed by UNKNOWN

##################################
below the SERVER LOG

root@proxy:~/proxy# node  ssh-server.js
Listening on port 54830
[12608.54833453] DEBUG: Local ident: 'SSH-2.0-ssh2js0.0.2srv'
[12608.54833453] DEBUG: Parser: IN_INIT (waiting for identification begin)
[12608.54833453] DEBUG: Parser: IN_INIT (waiting for rest of identification)
[12608.54833453] DEBUG: Parser: IN_GREETING
[12608.54833453] DEBUG: Parser: IN_HEADER
[12608.54833453] DEBUG: Remote ident: 'SSH-2.0-OpenSSH_6.7p1 Debian-3'
[12608.54833453] DEBUG: Outgoing: Writing KEXINIT
Client connected!
[12608.54833453] DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
[12608.54833453] DEBUG: Parser: IN_PACKET
[12608.54833453] DEBUG: Parser: pktLen:1964,padLen:8,remainLen:1960
[12608.54833453] DEBUG: Parser: IN_PACKETDATA
[12608.54833453] DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXINIT
[12608.54833453] DEBUG: Comparing KEXINITs ...
[12608.54833453] DEBUG: (local) KEX algorithms: diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
[12608.54833453] DEBUG: (remote) KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
[12608.54833453] DEBUG: KEX algorithm: diffie-hellman-group14-sha1
[12608.54833453] DEBUG: (local) Host key formats: ssh-rsa,ssh-dss
[12608.54833453] DEBUG: (remote) Host key formats: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-rsa-cert-v00@openssh.com,ssh-dss-cert-v00@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,ssh-rsa,ssh-dss
[12608.54833453] DEBUG: Host key format: ssh-rsa
[12608.54833453] DEBUG: (local) Client->Server ciphers: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
[12608.54833453] DEBUG: (remote) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
[12608.54833453] DEBUG: Client->Server Cipher: aes128-ctr
[12608.54833453] DEBUG: (local) Server->Client ciphers: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
[12608.54833453] DEBUG: (remote) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
[12608.54833453] DEBUG: Server->Client Cipher: aes128-ctr
[12608.54833453] DEBUG: (local) Client->Server HMAC algorithms: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
[12608.54833453] DEBUG: (remote) Client->Server HMAC algorithms: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-md5-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
[12608.54833453] DEBUG: Client->Server HMAC algorithm: hmac-sha2-256
[12608.54833453] DEBUG: (local) Server->Client HMAC algorithms: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
[12608.54833453] DEBUG: (remote) Server->Client HMAC algorithms: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-md5-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
[12608.54833453] DEBUG: Server->Client HMAC algorithm: hmac-sha2-256
[12608.54833453] DEBUG: (local) Client->Server compression algorithms: none
[12608.54833453] DEBUG: (remote) Client->Server compression algorithms: none,zlib@openssh.com,zlib
[12608.54833453] DEBUG: Client->Server compression algorithm: none
[12608.54833453] DEBUG: (local) Server->Client compression algorithms: none
[12608.54833453] DEBUG: (remote) Server->Client compression algorithms: none,zlib@openssh.com,zlib
[12608.54833453] DEBUG: Server->Client compression algorithm: none
[12608.54833453] DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
[12608.54833453] DEBUG: Parser: IN_PACKET
[12608.54833453] DEBUG: Parser: pktLen:268,padLen:6,remainLen:264
[12608.54833453] DEBUG: Parser: IN_PACKETDATA
[12608.54833453] DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXDH_INIT
[12608.54833453] DEBUG: Outgoing: Writing KEXDH_REPLY
[12608.54833453] DEBUG: Outgoing: Writing NEWKEYS
[12608.54833453] DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
[12608.54833453] DEBUG: Parser: IN_PACKET
[12608.54833453] DEBUG: Parser: pktLen:12,padLen:10,remainLen:8
[12608.54833453] DEBUG: Parser: IN_PACKETDATA
[12608.54833453] DEBUG: Parser: IN_PACKETDATAAFTER, packet: NEWKEYS

buffer.js:188
        throw new TypeError('First argument needs to be a number, ' +
              ^
TypeError: First argument needs to be a number, array or string.
    at new Buffer (buffer.js:188:15)
    at onNEWKEYS (/root/proxy/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:2918:24)
    at SSH2Stream.<anonymous> (/root/proxy/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:181:35)
    at SSH2Stream.emit (events.js:117:20)
    at parsePacket (/root/proxy/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3351:10)
    at SSH2Stream._transform (/root/proxy/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:538:13)
    at SSH2Stream.Transform._read (_stream_transform.js:179:10)
    at SSH2Stream.Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
root@proxy:~/proxy#

**Comment by mscdex** [comment]
This should be fixed in mscdex/ssh2-streams@49898721296ab1c12c084c2f61bb5970f7f49d65.

**Comment by mscdex** [comment]
Reinstall `ssh2` to pick up the new `ssh2-streams` version.

**Comment by onairelav** [comment]
Hi, I will try and let you know. 

Valeriano Cossu
Thanks
