### ISSUE TITLE
Error: Unable to request agent forwarding

### ISSUE THREAD

**Issue by Toddses** [mscdex/ssh2#227]
See #136 

Using the latest release (0.4.3), I'm seeing this error again when I try to issue more than one command with agent forwarding. Here's the code.

```javascript
var Client = require('ssh2').Client;

var client = new Client();

client.on('ready', function() {
	console.log("Client :: ready");

	client.exec('ls -a', function (err, stream) {
		if (err) throw err;

		stream.on('close', function (code, signal) {
			console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
			client.end();
			cb();
		}).on('data', function (data) {
			console.log('STDOUT: ' + data);
		}).stderr.on('data', function (data) {
			console.log('STDERR: ' + data);
		});
	});
	client.exec('git ls-remote git@github.com:Toddses/capify-press.git', function (err, stream) {
		if (err) throw err;

		stream.on('close', function (code, signal) {
			console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
			client.end();
			cb();
		}).on('data', function (data) {
			console.log('STDOUT: ' + data);
		}).stderr.on('data', function (data) {
			console.log('STDERR: ' + data);
		});
	});
}).connect({
	host: this.host,
	port: 22,
	user: this.user,
	agent: process.env.SSH_AUTH_SOCK,
	agentForward: true
});
```

The output is 

```sh
Client :: ready

/var/www/apps/dploy/util/server.js:189
			if (err) throw err;
			               ^
Error: Unable to request agent forwarding
    at /var/www/apps/dploy/node_modules/ssh2/lib/client.js:1123:25
    at SSH2Stream.Channel.sshstream.once.once.on.on.on.on.on.self.emit.exitCode (/var/www/apps/dploy/node_modules/ssh2/lib/Channel.js:189:24)
    at SSH2Stream.emit (events.js:92:17)
    at parsePacket (/var/www/apps/dploy/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3155:10)
    at SSH2Stream._transform (/var/www/apps/dploy/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:554:13)
    at SSH2Stream.Transform._read [as __read] (_stream_transform.js:179:10)
    at SSH2Stream._read (/var/www/apps/dploy/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:213:15)
    at SSH2Stream.Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)

```

**Comment by mscdex** [comment]
Should be fixed in master now. Evidently this is another one of OpenSSH's "let's send a session-specific request for something that is connection-wide."

**Comment by Toddses** [comment]
Nice, that fixed it.
