### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by ecker00** [mscdex/ssh2#246]
With the latest version of ssh2 I get this error, when running this node script: http://hastebin.com/odomusiceh.js
It solved the problem to npm install ssh2@0.3.6 

**System**: Mac OS X 10.10.2

### Stack Trace

```
Connection :: connect
Connection :: ready
Stream :: exit :: code: 0, signal: undefined

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: stream.push() after EOF
    at readableAddChunk (_stream_readable.js:146:15)
    at SSH2Stream.Readable.push (_stream_readable.js:127:10)
    at SSH2Stream.Transform.push [as __push] (_stream_transform.js:140:32)
    at SSH2Stream.push (/private/tmp/testNJS/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:217:18)
    at send (/private/tmp/testNJS/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:4825:12)
    at SSH2Stream.channelClose (/private/tmp/testNJS/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:785:10)
    at Channel.close (/private/tmp/testNJS/node_modules/ssh2/lib/Channel.js:283:35)
    at SSH2Stream.<anonymous> (/private/tmp/testNJS/node_modules/ssh2/lib/Channel.js:188:14)
    at SSH2Stream.EventEmitter.emit (events.js:95:17)
    at parse_CHANNEL_REQUEST (/private/tmp/testNJS/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:4271:8)
```

**Comment by mscdex** [comment]
Fixed in mscdex/ssh2-streams@340048cb74.

Also, it looks like your code is from 0.2.x where only `data` events were emitted and with a second argument. In 0.3.x and newer, actual (separate) streams2 streams are used for stdout and stderr. Just something you should be aware of...
