### ISSUE TITLE
sftp.createWriteStream Home directory error

### ISSUE THREAD

**Issue by lukeadams** [mscdex/ssh2#286]
Opening an SFTP stream to the current user's home directory throws an error. (passing a path starting with a ~
Example:
```javascript
conn.on(
    'ready',
    function () {
        conn.sftp(
            function (err, sftp) {
               //ERROR THROWN HERE.                           ↓ notice the tilde
                var writeStream = sftp.createWriteStream( "~/idss3sk.txt" );

               //Write random garbage to the file ;)
                writeStream.write('elwfnfeoinwel');
                writeStream.end()
            }
        );
    }
);
//<insert conn.connect call to test>
```
Throws: 
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: No such file
    at SFTPStream._transform (/Users/lukeadams/Desktop/nodetest/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:354:27)
    at SFTPStream.Transform._read [as __read] (_stream_transform.js:179:10)
    at SFTPStream._read (/Users/lukeadams/Desktop/nodetest/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:160:15)
    at SFTPStream.Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at SFTPStream.Writable.write (_stream_writable.js:217:11)
    at Channel.ondata (_stream_readable.js:540:20)
    at Channel.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
```

**Comment by mscdex** [comment]
This is expected. I don't know of any SFTP server implementations that use a shell to do path normalization like that.

Also, you can catch the error by adding an `error` event handler.

**Comment by lukeadams** [comment]
That's fine. I haven't used SFTP that much, so I wasn't sure. Not a show stopper. I can just append /root to my path.
BTW: SSH2 has been great. Everything just works!

**Comment by mscdex** [comment]
FWIW typically SFTP sessions start in the user's home directory, so you might try something like `sftp.realpath('.', ...);` if you need to dynamically get the user's home directory.
