### ISSUE TITLE
SSH crashes when MaxAuthTries set in /etc/ssh/sshd_config and username/password wrong

### ISSUE THREAD

**Issue by cintolas** [mscdex/ssh2#305]
Edit your /etc/ssh/sshd_config file 
Add the line MaxAuthTries 3
Restart sshd

Run the following code
```javascript
var SSH = require('ssh2');

var ssh = new SSH();
ssh.connect({
	tryKeyboard:true,
	username:'xdemo',
	password:''
});

ssh.on('keyboard-interactive',function(name,instructions,lang,prompts,cb){
	cb(['badpassword']);
});
ssh.on('ready',function(){
	console.log('success');
});
ssh.on('error',function(e){
	console.log(e);
});
```

the node server crashes with the following.

Error: Too many authentication failures for xdemo
    at onDISCONNECT (/home/xdemo/FastX2/git/fastx2/fastx-client-js/server/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:2021:15)
    at SSH2Stream.<anonymous> (/home/xdemo/FastX2/git/fastx2/fastx-client-js/server/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:179:5)
    at SSH2Stream.EventEmitter.emit (events.js:106:17)
    at parsePacket (/home/xdemo/FastX2/git/fastx2/fastx-client-js/server/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3389:10)
    at SSH2Stream._transform (/home/xdemo/FastX2/git/fastx2/fastx-client-js/server/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:554:13)
    at SSH2Stream.Transform._read [as __read] (_stream_transform.js:179:10)
    at SSH2Stream._read (/home/xdemo/FastX2/git/fastx2/fastx-client-js/server/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:213:15)
    at SSH2Stream.Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:223:10)
    at writeOrBuffer (_stream_writable.js:213:5)

EXPECTED:  The ssh module should catch this as an error and send an onError event

**Comment by mscdex** [comment]
Are you still experience this with the latest version of `ssh2` (e.g. at least latest v0.4)?
