### ISSUE TITLE
Handling 'error' events coming from SSH2Stream

### ISSUE THREAD

**Issue by christopherstott** [mscdex/ssh2#310]
Hi! I'm sometimes seeing unhandled 'error' events thrown from SSH2Stream & I haven't figured out how to handle them. Do you have any advice?

- I'm listening to the 'ready', 'error', 'close', 'end' events on the connection object. 
- Then running a command like `connection.exec(command, options, function (err, stream) {` 
- then immediately listening to the 'close', 'data', 'error', stderr 'data' events on the stream object

It looks like the unhandled error may be getting thrown after connection.exec, but before the callback is returned with the stream (when listeners are attached).

Thanks!

```events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: protocol error: rcvd type 90
    at onDISCONNECT (/Users/chris/BB/BB/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:2034:15)
    at SSH2Stream.<anonymous> (/Users/chris/BB/BB/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:179:5)
    at SSH2Stream.emit (events.js:118:17)
    at parsePacket (/Users/chris/BB/BB/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3464:10)
    at SSH2Stream._transform (/Users/chris/BB/BB/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:555:13)
    at SSH2Stream.Transform._read [as __read] (_stream_transform.js:179:10)
    at SSH2Stream._read (/Users/chris/BB/BB/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:213:15)
    at SSH2Stream.Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at SSH2Stream.Writable.write (_stream_writable.js:217:11)
    at Socket.ondata (_stream_readable.js:540:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)```

**Comment by mscdex** [comment]
These errors should be emitted now on the connection object in master. Can you please try it?

I'm also interested in why the server is rejecting the channel open request (90). Can you post the code you're using?

**Comment by christopherstott** [comment]
Thanks! This resolved it for us
