### ISSUE TITLE
Server session exit code isn't correctly received by client

### ISSUE THREAD

**Issue by minesworld** [mscdex/ssh2#340]
The servers session data streamed isn't also received up to the end.

Test case (use my feature/bigdata-stream-tests branch):

echo 'maxNumber=100000 Exec( O:sODV)<->( O:wStream )' | DEBUG=1 node test/test-streaming.js -

logfile can be provided if not reproducible :-)

PS: tests for stream receive will come soon...

**Comment by minesworld** [comment]
Related issues might be 

https://github.com/mscdex/ssh2/issues/324
https://github.com/mscdex/ssh2/issues/277

**Comment by minesworld** [comment]
```
[INFO] http_parser: 2.5.0
[INFO] node: 4.2.1
[INFO] v8: 4.5.103.35
[INFO] uv: 1.7.5
[INFO] zlib: 1.2.8
[INFO] ares: 1.10.1-DEV
[INFO] icu: 56.1
[INFO] modules: 46
[INFO] openssl: 1.0.2d
[INFO] platform: darwin x64
[CREATE] created test maxNumber=100000 timeout=60 Exec( O:sODV)<->( O:wStream )
========================================================
[TEST] maxNumber=100000 timeout=60 Exec( O:sODV)<->( O:wStream )
========================================================
[CLIENT] DEBUG: Local ident: 'SSH-2.0-ssh2js0.0.18'
[CLIENT] DEBUG: Client: Trying 127.0.0.1 on port 53816 ...
[SERVER] [1697875.561887824] DEBUG: Local ident: 'SSH-2.0-ssh2js0.0.18srv'
[CLIENT] DEBUG: Client: Connected
[SERVER] [1697875.561887824] DEBUG: Parser: IN_INIT (waiting for identification begin)
[SERVER] [1697875.561887824] DEBUG: Parser: IN_INIT (waiting for rest of identification)
[SERVER] [1697875.561887824] DEBUG: Parser: IN_GREETING
[SERVER] [1697875.561887824] DEBUG: Parser: IN_HEADER
[SERVER] [1697875.561887824] DEBUG: Remote ident: 'SSH-2.0-ssh2js0.0.18'
[SERVER] [1697875.561887824] DEBUG: Outgoing: Writing KEXINIT
[EVENT] connection server(conn)
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
[CLIENT] DEBUG: Parser: IN_INIT
[CLIENT] DEBUG: Parser: IN_GREETING
[CLIENT] DEBUG: Parser: IN_HEADER
[CLIENT] DEBUG: Remote ident: 'SSH-2.0-ssh2js0.0.18srv'
[CLIENT] DEBUG: Outgoing: Writing KEXINIT
[CLIENT] DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
[CLIENT] DEBUG: Parser: IN_PACKET
[CLIENT] DEBUG: Parser: pktLen:772,padLen:6,remainLen:768
[CLIENT] DEBUG: Parser: IN_PACKETDATA
[CLIENT] DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXINIT
[CLIENT] DEBUG: Comparing KEXINITs ...
[CLIENT] DEBUG: (local) KEX algorithms: diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
[CLIENT] DEBUG: (remote) KEX algorithms: diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
[CLIENT] DEBUG: KEX algorithm: diffie-hellman-group14-sha1
[CLIENT] DEBUG: (local) Host key formats: ssh-rsa,ssh-dss
[CLIENT] DEBUG: (remote) Host key formats: ssh-rsa
[CLIENT] DEBUG: Host key format: ssh-rsa
[CLIENT] DEBUG: (local) Client->Server ciphers: aes256-ctr,aes192-ctr,aes128-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
[CLIENT] DEBUG: (remote) Client->Server ciphers: aes256-ctr,aes192-ctr,aes128-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
[CLIENT] DEBUG: Client->Server Cipher: aes256-ctr
[CLIENT] DEBUG: (local) Server->Client ciphers: aes256-ctr,aes192-ctr,aes128-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
[CLIENT] DEBUG: (remote) Server->Client ciphers: aes256-ctr,aes192-ctr,aes128-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
[CLIENT] DEBUG: Server->Client Cipher: aes256-ctr
[CLIENT] DEBUG: (local) Client->Server HMAC algorithms: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
[CLIENT] DEBUG: (remote) Client->Server HMAC algorithms: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
[CLIENT] DEBUG: Client->Server HMAC algorithm: hmac-md5
[CLIENT] DEBUG: (local) Server->Client HMAC algorithms: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
[CLIENT] DEBUG: (remote) Server->Client HMAC algorithms: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
[CLIENT] DEBUG: Server->Client HMAC algorithm: hmac-md5
[CLIENT] DEBUG: (local) Client->Server compression algorithms: none
[CLIENT] DEBUG: (remote) Client->Server compression algorithms: none
[CLIENT] DEBUG: Client->Server compression algorithm: none
[CLIENT] DEBUG: (local) Server->Client compression algorithms: none
[CLIENT] DEBUG: (remote) Server->Client compression algorithms: none
[CLIENT] DEBUG: Server->Client compression algorithm: none
[CLIENT] DEBUG: Outgoing: Writing KEXDH_INIT
[CLIENT] DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKET
[SERVER] [1697875.561887824] DEBUG: Parser: pktLen:852,padLen:6,remainLen:848
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKETDATA
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXINIT
[SERVER] [1697875.561887824] DEBUG: Comparing KEXINITs ...
[SERVER] [1697875.561887824] DEBUG: (local) KEX algorithms: diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
[SERVER] [1697875.561887824] DEBUG: (remote) KEX algorithms: diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
[SERVER] [1697875.561887824] DEBUG: KEX algorithm: diffie-hellman-group14-sha1
[SERVER] [1697875.561887824] DEBUG: (local) Host key formats: ssh-rsa,ssh-dss
[SERVER] [1697875.561887824] DEBUG: (remote) Host key formats: ssh-rsa,ssh-dss
[SERVER] [1697875.561887824] DEBUG: Host key format: ssh-rsa
[SERVER] [1697875.561887824] DEBUG: (local) Client->Server ciphers: aes256-ctr,aes192-ctr,aes128-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
[SERVER] [1697875.561887824] DEBUG: (remote) Client->Server ciphers: aes256-ctr,aes192-ctr,aes128-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
[SERVER] [1697875.561887824] DEBUG: Client->Server Cipher: aes256-ctr
[SERVER] [1697875.561887824] DEBUG: (local) Server->Client ciphers: aes256-ctr,aes192-ctr,aes128-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
[SERVER] [1697875.561887824] DEBUG: (remote) Server->Client ciphers: aes256-ctr,aes192-ctr,aes128-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
[SERVER] [1697875.561887824] DEBUG: Server->Client Cipher: aes256-ctr
[SERVER] [1697875.561887824] DEBUG: (local) Client->Server HMAC algorithms: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
[SERVER] [1697875.561887824] DEBUG: (remote) Client->Server HMAC algorithms: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
[SERVER] [1697875.561887824] DEBUG: Client->Server HMAC algorithm: hmac-md5
[SERVER] [1697875.561887824] DEBUG: (local) Server->Client HMAC algorithms: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
[SERVER] [1697875.561887824] DEBUG: (remote) Server->Client HMAC algorithms: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
[SERVER] [1697875.561887824] DEBUG: Server->Client HMAC algorithm: hmac-md5
[SERVER] [1697875.561887824] DEBUG: (local) Client->Server compression algorithms: none
[SERVER] [1697875.561887824] DEBUG: (remote) Client->Server compression algorithms: none
[SERVER] [1697875.561887824] DEBUG: Client->Server compression algorithm: none
[SERVER] [1697875.561887824] DEBUG: (local) Server->Client compression algorithms: none
[SERVER] [1697875.561887824] DEBUG: (remote) Server->Client compression algorithms: none
[SERVER] [1697875.561887824] DEBUG: Server->Client compression algorithm: none
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKET
[SERVER] [1697875.561887824] DEBUG: Parser: pktLen:268,padLen:6,remainLen:264
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKETDATA
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXDH_INIT
[SERVER] [1697875.561887824] DEBUG: Outgoing: Writing KEXDH_REPLY
[SERVER] [1697875.561887824] DEBUG: Outgoing: Writing NEWKEYS
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
[CLIENT] DEBUG: Parser: IN_PACKET
[CLIENT] DEBUG: Parser: pktLen:572,padLen:8,remainLen:568
[CLIENT] DEBUG: Parser: IN_PACKETDATA
[CLIENT] DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXDH_REPLY
[CLIENT] DEBUG: Checking host key format
[CLIENT] DEBUG: Checking signature format
[CLIENT] DEBUG: Verifying host fingerprint
[CLIENT] DEBUG: Host accepted by default (no verification)
[CLIENT] DEBUG: Verifying signature
[CLIENT] DEBUG: Outgoing: Writing NEWKEYS
[CLIENT] DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
[CLIENT] DEBUG: Parser: IN_PACKET
[CLIENT] DEBUG: Parser: pktLen:12,padLen:10,remainLen:8
[CLIENT] DEBUG: Parser: IN_PACKETDATA
[CLIENT] DEBUG: Parser: IN_PACKETDATAAFTER, packet: NEWKEYS
[CLIENT] DEBUG: Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
[CLIENT] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKET
[SERVER] [1697875.561887824] DEBUG: Parser: pktLen:12,padLen:10,remainLen:8
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKETDATA
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKETDATAAFTER, packet: NEWKEYS
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKET
[SERVER] [1697875.561887824] DEBUG: Parser: Decrypting
[SERVER] [1697875.561887824] DEBUG: Parser: pktLen:28,padLen:10,remainLen:16
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKETDATA
[SERVER] [1697875.561887824] DEBUG: Parser: Decrypting
[SERVER] [1697875.561887824] DEBUG: Parser: HMAC size:16
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKETDATAVERIFY
[SERVER] [1697875.561887824] DEBUG: Parser: Verifying MAC
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKETDATAAFTER, packet: SERVICE_REQUEST
[SERVER] [1697875.561887824] DEBUG: Outgoing: Writing SERVICE_ACCEPT (ssh-userauth)
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[CLIENT] DEBUG: Parser: IN_PACKET
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: pktLen:28,padLen:10,remainLen:16
[CLIENT] DEBUG: Parser: IN_PACKETDATA
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: HMAC size:16
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY
[CLIENT] DEBUG: Parser: Verifying MAC
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[CLIENT] DEBUG: Parser: IN_PACKETDATAAFTER, packet: SERVICE_ACCEPT
[CLIENT] DEBUG: Outgoing: Writing USERAUTH_REQUEST (password)
[CLIENT] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKET
[SERVER] [1697875.561887824] DEBUG: Parser: Decrypting
[SERVER] [1697875.561887824] DEBUG: Parser: pktLen:76,padLen:6,remainLen:64
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKETDATA
[SERVER] [1697875.561887824] DEBUG: Parser: Decrypting
[SERVER] [1697875.561887824] DEBUG: Parser: HMAC size:16
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKETDATAVERIFY
[SERVER] [1697875.561887824] DEBUG: Parser: Verifying MAC
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_REQUEST (password)
[EVENT] authentication server(ctx)
[SERVER] [1697875.561887824] DEBUG: Outgoing: Writing USERAUTH_SUCCESS
[EVENT] ready server()
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[CLIENT] DEBUG: Parser: IN_PACKET
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: pktLen:12,padLen:10,remainLen:0
[CLIENT] DEBUG: Parser: IN_PACKETDATA
[CLIENT] DEBUG: Parser: HMAC size:16
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY
[CLIENT] DEBUG: Parser: Verifying MAC
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[CLIENT] DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_SUCCESS
[EVENT] ready client()
[CLIENT] DEBUG: Outgoing: Writing CHANNEL_OPEN (0, session)
[CLIENT] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKET
[SERVER] [1697875.561887824] DEBUG: Parser: Decrypting
[SERVER] [1697875.561887824] DEBUG: Parser: pktLen:44,padLen:19,remainLen:32
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKETDATA
[SERVER] [1697875.561887824] DEBUG: Parser: Decrypting
[SERVER] [1697875.561887824] DEBUG: Parser: HMAC size:16
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKETDATAVERIFY
[SERVER] [1697875.561887824] DEBUG: Parser: Verifying MAC
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_OPEN (0, session)
[EVENT] session server(f,f)
[SERVER] [1697875.561887824] DEBUG: Outgoing: Writing CHANNEL_OPEN_CONFIRMATION (r:0, l:0)
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[CLIENT] DEBUG: Parser: IN_PACKET
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: pktLen:28,padLen:10,remainLen:16
[CLIENT] DEBUG: Parser: IN_PACKETDATA
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: HMAC size:16
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY
[CLIENT] DEBUG: Parser: Verifying MAC
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[CLIENT] DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_OPEN_CONFIRMATION
[CLIENT] DEBUG: Outgoing: Writing CHANNEL_REQUEST (0, exec)
[CLIENT] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKET
[SERVER] [1697875.561887824] DEBUG: Parser: Decrypting
[SERVER] [1697875.561887824] DEBUG: Parser: pktLen:44,padLen:16,remainLen:32
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKETDATA
[SERVER] [1697875.561887824] DEBUG: Parser: Decrypting
[SERVER] [1697875.561887824] DEBUG: Parser: HMAC size:16
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKETDATAVERIFY
[SERVER] [1697875.561887824] DEBUG: Parser: Verifying MAC
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_REQUEST (0, exec)
[EVENT] exec server.session(f,f,{ command: 'foo --bar' })
[SERVER] [1697875.561887824] DEBUG: Outgoing: Writing CHANNEL_SUCCESS (0)
[SERVER] [1697875.561887824] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[DATA] server.session.exec.stdout wStream push(2) .atEnd=false  #2
[DATA] server.session.exec.stdout wStream push(2) .atEnd=false  #4
[SERVER] [1697875.561887824] DEBUG: Outgoing: Writing CHANNEL_DATA (0)
[DATA] server.session.exec.stdout wStream push(2) .atEnd=false  #6
[SERVER] [1697875.561887824] DEBUG: Outgoing: Writing CHANNEL_DATA (0)


. . .


[DATA] server.session.exec.stdout wStream push(6) .atEnd=false  #588884
[DATA] server.session.exec.stdout wStream push(6) .atEnd=true  #588890
[DATA] server.session.exec.stdout wStream push(null) .atEnd=true  #588890
[EVENT] end server.session.exec.stdout wStream  #588890
[CHECK] server.session.exec.stderr wGDWonDrain:cb(undefined)
[CHECK] server end(1) => 1
[SERVER] [1697875.561887824] DEBUG: Outgoing: Writing CHANNEL_REQUEST (0, exit-status)
[SERVER] [1697875.561887824] DEBUG: Outgoing: Writing DISCONNECT (BY_APPLICATION)
[CLIENT] DEBUG: Parser: IN_PACKET
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: pktLen:12,padLen:6,remainLen:0
[CLIENT] DEBUG: Parser: IN_PACKETDATA
[CLIENT] DEBUG: Parser: HMAC size:16
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY
[CLIENT] DEBUG: Parser: Verifying MAC
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[CLIENT] DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_SUCCESS (0)
[CHECK] client.exec(e,s)
[CLIENT] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[CLIENT] DEBUG: Parser: IN_PACKET
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: pktLen:28,padLen:16,remainLen:16
[CLIENT] DEBUG: Parser: IN_PACKETDATA
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: HMAC size:16
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY
[CLIENT] DEBUG: Parser: Verifying MAC
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[CLIENT] DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
[CLIENT] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[CLIENT] DEBUG: Parser: IN_PACKET
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: pktLen:28,padLen:16,remainLen:16
[CLIENT] DEBUG: Parser: IN_PACKETDATA
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: HMAC size:16
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY
[CLIENT] DEBUG: Parser: Verifying MAC
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[CLIENT] DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
[CLIENT] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[CLIENT] DEBUG: Parser: IN_PACKET
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: pktLen:28,padLen:16,remainLen:16
[CLIENT] DEBUG: Parser: IN_PACKETDATA
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: HMAC size:16
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY
[CLIENT] DEBUG: Parser: Verifying MAC
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[CLIENT] DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
[CLIENT] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[CLIENT] DEBUG: Parser: IN_PACKET
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: pktLen:28,padLen:16,remainLen:16
[CLIENT] DEBUG: Parser: IN_PACKETDATA
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: HMAC size:16
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY
[CLIENT] DEBUG: Parser: Verifying MAC
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[CLIENT] DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
[CLIENT] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[CLIENT] DEBUG: Parser: IN_PACKET
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: pktLen:28,padLen:16,remainLen:16
[CLIENT] DEBUG: Parser: IN_PACKETDATA
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: HMAC size:16
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY
[CLIENT] DEBUG: Parser: Verifying MAC
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[CLIENT] DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
[CLIENT] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[CLIENT] DEBUG: Parser: IN_PACKET
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: pktLen:28,padLen:16,remainLen:16
[CLIENT] DEBUG: Parser: IN_PACKETDATA
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: HMAC size:16
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY
[CLIENT] DEBUG: Parser: Verifying MAC
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[CLIENT] DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
[CLIENT] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)


. . .


[CLIENT] DEBUG: Parser: IN_PACKETDATA
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: HMAC size:16
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY
[CLIENT] DEBUG: Parser: Verifying MAC
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[CLIENT] DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
[EVENT] data client.exec.stdout sODV (6) #64244
[CLIENT] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[CLIENT] DEBUG: Parser: IN_PACKET
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: pktLen:44,padLen:18,remainLen:32
[CLIENT] DEBUG: Parser: IN_PACKETDATA
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: HMAC size:16
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY
[CLIENT] DEBUG: Parser: Verifying MAC
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[CLIENT] DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_REQUEST (0, exit-status)
[EVENT] exit client.exec.channel({ '0': 100 })
[CLIENT] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[CLIENT] DEBUG: Parser: IN_PACKET
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: pktLen:28,padLen:14,remainLen:16
[CLIENT] DEBUG: Parser: IN_PACKETDATA
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: HMAC size:16
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY
[CLIENT] DEBUG: Parser: Verifying MAC
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[CLIENT] DEBUG: Parser: IN_PACKETDATAAFTER, packet: DISCONNECT (BY_APPLICATION)
[EVENT] end client()

/Users/mk/Developing/External/ssh2/test/test-streaming.js:677
  throw err;
  ^
AssertionError: [test-streaming/maxNumber=100000 timeout=60 Exec( O:sODV)<->( O:wStream )]: Wrong close args: undefined
    at Client.<anonymous> (/Users/mk/Developing/External/ssh2/test/test-streaming.js:429:14)
    at emitNone (events.js:67:13)
    at Client.emit (events.js:166:7)
    at Socket.<anonymous> (/Users/mk/Developing/External/ssh2/lib/client.js:217:10)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:903:12)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
```

**Comment by minesworld** [comment]
Hmm. looks that there is some error in the test code as the 

```
[EVENT] exit client.exec.channel({ '0': 100 })
```

suggest.

But still the ssh2 code doesn't transfer all data if

**Comment by minesworld** [comment]
There is an issue, but I;ve to change my test code to be more sure where it is exactly...
