### ISSUE TITLE
Channel emits finish event BEFORE all data is flushed / transmitted

### ISSUE THREAD

**Issue by minesworld** [mscdex/ssh2#344]
so calling connection.end() is not save and will result in data loss.

test case (checkout the latest feature/bigdata-stream-tests branch):

```
echo 'maxNumber=10000 Exec( O:vStream,E:vStream)<->( O:wStream,E:wStream )' | DEBUG=1 endWorkaround=1 exitOnSourceEnd=1 node test/test-streaming.js -
```

Log:

```
[DATA] server.session.exec.stderr wStream push(5) .atEnd=false  #48885
[DATA] server.session.exec.stderr wStream push(5) .atEnd=true  #48890
[DATA] server.session.exec.stderr wStream push(null) .atEnd=true  #48890
[EVENT] end server.session.exec.stdout wStream #48890
[FIX] exitOnSourceEnd server.session.exec.stdout
[CHECK] server.session.exec.stdout wStream:cb(null, finish)
[CHECK] server finish(1) => 1
[EVENT] end server.session.exec.stderr wStream #48890
[FIX] exitOnSourceEnd server.session.exec.stderr
[CHECK] server.session.exec.stderr wStream:cb(null, finish)
[CHECK] server finish(2) => 3
[CHECK] server.session.exec.exit(100)
[SERVER] [1726954.369783979] DEBUG: Outgoing: Writing CHANNEL_REQUEST (0, exit-status)
[CHECK] server close(3) => 3
[CHECK] server.session.exec.end()
[SERVER] [1726954.369783979] DEBUG: Outgoing: Writing CHANNEL_EOF (0)
[SERVER] [1726954.369783979] DEBUG: Outgoing: Writing CHANNEL_CLOSE (0)
[EVENT] finish server.session.exec.stream
[CHECK] server.end()
[SERVER] [1726954.369783979] DEBUG: Outgoing: Writing DISCONNECT (BY_APPLICATION)
[EVENT] finish server.session.exec.stdout wStream
[CHECK] server.session.exec.stdout wStream:cb(null, finish)
[CHECK] server finish(1) => 3
[CHECK] server.session.exec.exit(100)
[CHECK] server close(3) => 3
[CHECK] server.session.exec.end()
[FIX] endWorkaround server.session.exec.stdout wStream target
[CLIENT] DEBUG: Parser: IN_PACKET
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: pktLen:12,padLen:6,remainLen:0
```

The stream did push, but the channel didn't transmit it yet over to the client which results in

```
AssertionError: [test-streaming/maxNumber=10000 Exec( O:vStream,E:vStream)<->( O:wStream,E:wStream )]: client.exec.channel verifier client.exec.stderr is not .atEnd
    at Channel.<anonymous> (/Users/mk/Developing/External/ssh2/test/test-streaming.js:576:13)
    at emitNone (events.js:72:20)
    at Channel.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:903:12)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
```

So there is no reliable way to transmit all data and close the connection while sure that everything got transmitted...

**Comment by minesworld** [comment]
This seems to be an error specific to the Channels piped stream handling as 

```
echo 'maxNumber=10000 Exec( O:vStream,E:vStream)<->( O:wGDWonDrain,E:wGDWonDrain )' | DEBUG=1 endWorkaround=1 exitOnSourceEnd=1 node test/test-streaming.js -
```

seems to work correctly.

While 

```
echo 'maxNumber=10000 Exec( O:vStream,E:vStream)<->( O:wGDWonDrain,E:wStream )' | DEBUG=1 endWorkaround=1 exitOnSourceEnd=1 node test/test-streaming.js - >/dev/null
```

fails and 

```
echo 'maxNumber=10000 Exec( O:vStream,E:vStream)<->( O:wStream,E:wGDWonDrain )' | DEBUG=1 endWorkaround=1 exitOnSourceEnd=1 node test/test-streaming.js - >/dev/null
```

works. 

But in my eyes this is because stdout will be created and handled first...

**Comment by mscdex** [comment]
Can you please provide a standalone test for this?

**Comment by mscdex** [comment]
Closing this for now. If you can provide a minimal, standalone test, I would be glad to take a look at this.
