### ISSUE TITLE
Client Channel 'close' might give back different values then 'exit' event

### ISSUE THREAD

**Issue by minesworld** [mscdex/ssh2#347]
Failing test case:

```
echo 'maxNumber=1 Exec( I:wGDWonDrain )<->( I:sODV )' | DEBUG=1 endWorkaround=1 exitOnSourceEnd=1 disconnectOnFirstFinish=1 node test/test-streaming.js -
```

Logfile:

```
[INFO] http_parser: 2.5.0
[INFO] node: 4.2.1
[INFO] v8: 4.5.103.35
[INFO] uv: 1.7.5
[INFO] zlib: 1.2.8
[INFO] ares: 1.10.1-DEV
[INFO] icu: 56.1
[INFO] modules: 46
[INFO] openssl: 1.0.2d
[INFO] platform: darwin x64
[INFO] strictStreams2: undefined
[INFO] failOnBadIdentificationStarts: undefined
[INFO] exitOnSourceEnd: true
[INFO] endWorkaround: true
[INFO] disconnectOnFirstFinish: true
[INFO] strict: undefined
[CREATE] created test maxNumber=1 Exec( I:wGDWonDrain )<->( I:sODV )
========================================================
[TEST] maxNumber=1 Exec( I:wGDWonDrain )<->( I:sODV )
========================================================
[CLIENT] DEBUG: Local ident: 'SSH-2.0-ssh2js0.0.18'
[CLIENT] DEBUG: Client: Trying localhost on port 62534 ...
[SERVER] [1793423.524744458] DEBUG: Local ident: 'SSH-2.0-ssh2js0.0.18srv'
[CLIENT] DEBUG: Client: Connected
[SERVER] [1793423.524744458] DEBUG: Parser: IN_INIT (waiting for identification begin)
[SERVER] [1793423.524744458] DEBUG: Parser: IN_INIT (waiting for rest of identification)
[SERVER] [1793423.524744458] DEBUG: Parser: IN_GREETING
[SERVER] [1793423.524744458] DEBUG: Parser: IN_HEADER
[SERVER] [1793423.524744458] DEBUG: Remote ident: 'SSH-2.0-ssh2js0.0.18'
[SERVER] [1793423.524744458] DEBUG: Outgoing: Writing KEXINIT
[EVENT] connection server(conn)
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
[CLIENT] DEBUG: Parser: IN_INIT
[CLIENT] DEBUG: Parser: IN_GREETING
[CLIENT] DEBUG: Parser: IN_HEADER
[CLIENT] DEBUG: Remote ident: 'SSH-2.0-ssh2js0.0.18srv'
[CLIENT] DEBUG: Outgoing: Writing KEXINIT
[CLIENT] DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
[CLIENT] DEBUG: Parser: IN_PACKET
[CLIENT] DEBUG: Parser: pktLen:772,padLen:6,remainLen:768
[CLIENT] DEBUG: Parser: IN_PACKETDATA
[CLIENT] DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXINIT
[CLIENT] DEBUG: Comparing KEXINITs ...
[CLIENT] DEBUG: (local) KEX algorithms: diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
[CLIENT] DEBUG: (remote) KEX algorithms: diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
[CLIENT] DEBUG: KEX algorithm: diffie-hellman-group14-sha1
[CLIENT] DEBUG: (local) Host key formats: ssh-rsa,ssh-dss
[CLIENT] DEBUG: (remote) Host key formats: ssh-rsa
[CLIENT] DEBUG: Host key format: ssh-rsa
[CLIENT] DEBUG: (local) Client->Server ciphers: aes256-ctr,aes192-ctr,aes128-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
[CLIENT] DEBUG: (remote) Client->Server ciphers: aes256-ctr,aes192-ctr,aes128-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
[CLIENT] DEBUG: Client->Server Cipher: aes256-ctr
[CLIENT] DEBUG: (local) Server->Client ciphers: aes256-ctr,aes192-ctr,aes128-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
[CLIENT] DEBUG: (remote) Server->Client ciphers: aes256-ctr,aes192-ctr,aes128-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
[CLIENT] DEBUG: Server->Client Cipher: aes256-ctr
[CLIENT] DEBUG: (local) Client->Server HMAC algorithms: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
[CLIENT] DEBUG: (remote) Client->Server HMAC algorithms: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
[CLIENT] DEBUG: Client->Server HMAC algorithm: hmac-md5
[CLIENT] DEBUG: (local) Server->Client HMAC algorithms: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
[CLIENT] DEBUG: (remote) Server->Client HMAC algorithms: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
[CLIENT] DEBUG: Server->Client HMAC algorithm: hmac-md5
[CLIENT] DEBUG: (local) Client->Server compression algorithms: none
[CLIENT] DEBUG: (remote) Client->Server compression algorithms: none
[CLIENT] DEBUG: Client->Server compression algorithm: none
[CLIENT] DEBUG: (local) Server->Client compression algorithms: none
[CLIENT] DEBUG: (remote) Server->Client compression algorithms: none
[CLIENT] DEBUG: Server->Client compression algorithm: none
[CLIENT] DEBUG: Outgoing: Writing KEXDH_INIT
[CLIENT] DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKET
[SERVER] [1793423.524744458] DEBUG: Parser: pktLen:852,padLen:6,remainLen:848
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETDATA
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXINIT
[SERVER] [1793423.524744458] DEBUG: Comparing KEXINITs ...
[SERVER] [1793423.524744458] DEBUG: (local) KEX algorithms: diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
[SERVER] [1793423.524744458] DEBUG: (remote) KEX algorithms: diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
[SERVER] [1793423.524744458] DEBUG: KEX algorithm: diffie-hellman-group14-sha1
[SERVER] [1793423.524744458] DEBUG: (local) Host key formats: ssh-rsa,ssh-dss
[SERVER] [1793423.524744458] DEBUG: (remote) Host key formats: ssh-rsa,ssh-dss
[SERVER] [1793423.524744458] DEBUG: Host key format: ssh-rsa
[SERVER] [1793423.524744458] DEBUG: (local) Client->Server ciphers: aes256-ctr,aes192-ctr,aes128-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
[SERVER] [1793423.524744458] DEBUG: (remote) Client->Server ciphers: aes256-ctr,aes192-ctr,aes128-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
[SERVER] [1793423.524744458] DEBUG: Client->Server Cipher: aes256-ctr
[SERVER] [1793423.524744458] DEBUG: (local) Server->Client ciphers: aes256-ctr,aes192-ctr,aes128-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
[SERVER] [1793423.524744458] DEBUG: (remote) Server->Client ciphers: aes256-ctr,aes192-ctr,aes128-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
[SERVER] [1793423.524744458] DEBUG: Server->Client Cipher: aes256-ctr
[SERVER] [1793423.524744458] DEBUG: (local) Client->Server HMAC algorithms: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
[SERVER] [1793423.524744458] DEBUG: (remote) Client->Server HMAC algorithms: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
[SERVER] [1793423.524744458] DEBUG: Client->Server HMAC algorithm: hmac-md5
[SERVER] [1793423.524744458] DEBUG: (local) Server->Client HMAC algorithms: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
[SERVER] [1793423.524744458] DEBUG: (remote) Server->Client HMAC algorithms: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
[SERVER] [1793423.524744458] DEBUG: Server->Client HMAC algorithm: hmac-md5
[SERVER] [1793423.524744458] DEBUG: (local) Client->Server compression algorithms: none
[SERVER] [1793423.524744458] DEBUG: (remote) Client->Server compression algorithms: none
[SERVER] [1793423.524744458] DEBUG: Client->Server compression algorithm: none
[SERVER] [1793423.524744458] DEBUG: (local) Server->Client compression algorithms: none
[SERVER] [1793423.524744458] DEBUG: (remote) Server->Client compression algorithms: none
[SERVER] [1793423.524744458] DEBUG: Server->Client compression algorithm: none
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKET
[SERVER] [1793423.524744458] DEBUG: Parser: pktLen:268,padLen:5,remainLen:264
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETDATA
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXDH_INIT
[SERVER] [1793423.524744458] DEBUG: Outgoing: Writing KEXDH_REPLY
[SERVER] [1793423.524744458] DEBUG: Outgoing: Writing NEWKEYS
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
[CLIENT] DEBUG: Parser: IN_PACKET
[CLIENT] DEBUG: Parser: pktLen:572,padLen:7,remainLen:568
[CLIENT] DEBUG: Parser: IN_PACKETDATA
[CLIENT] DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXDH_REPLY
[CLIENT] DEBUG: Checking host key format
[CLIENT] DEBUG: Checking signature format
[CLIENT] DEBUG: Verifying host fingerprint
[CLIENT] DEBUG: Host accepted by default (no verification)
[CLIENT] DEBUG: Verifying signature
[CLIENT] DEBUG: Outgoing: Writing NEWKEYS
[CLIENT] DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
[CLIENT] DEBUG: Parser: IN_PACKET
[CLIENT] DEBUG: Parser: pktLen:12,padLen:10,remainLen:8
[CLIENT] DEBUG: Parser: IN_PACKETDATA
[CLIENT] DEBUG: Parser: IN_PACKETDATAAFTER, packet: NEWKEYS
[CLIENT] DEBUG: Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
[CLIENT] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKET
[SERVER] [1793423.524744458] DEBUG: Parser: pktLen:12,padLen:10,remainLen:8
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETDATA
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETDATAAFTER, packet: NEWKEYS
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKET
[SERVER] [1793423.524744458] DEBUG: Parser: Decrypting
[SERVER] [1793423.524744458] DEBUG: Parser: pktLen:28,padLen:10,remainLen:16
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETDATA
[SERVER] [1793423.524744458] DEBUG: Parser: Decrypting
[SERVER] [1793423.524744458] DEBUG: Parser: HMAC size:16
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETDATAVERIFY
[SERVER] [1793423.524744458] DEBUG: Parser: Verifying MAC
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETDATAAFTER, packet: SERVICE_REQUEST
[SERVER] [1793423.524744458] DEBUG: Outgoing: Writing SERVICE_ACCEPT (ssh-userauth)
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[CLIENT] DEBUG: Parser: IN_PACKET
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: pktLen:28,padLen:10,remainLen:16
[CLIENT] DEBUG: Parser: IN_PACKETDATA
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: HMAC size:16
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY
[CLIENT] DEBUG: Parser: Verifying MAC
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[CLIENT] DEBUG: Parser: IN_PACKETDATAAFTER, packet: SERVICE_ACCEPT
[CLIENT] DEBUG: Outgoing: Writing USERAUTH_REQUEST (password)
[CLIENT] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKET
[SERVER] [1793423.524744458] DEBUG: Parser: Decrypting
[SERVER] [1793423.524744458] DEBUG: Parser: pktLen:76,padLen:6,remainLen:64
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETDATA
[SERVER] [1793423.524744458] DEBUG: Parser: Decrypting
[SERVER] [1793423.524744458] DEBUG: Parser: HMAC size:16
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETDATAVERIFY
[SERVER] [1793423.524744458] DEBUG: Parser: Verifying MAC
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_REQUEST (password)
[EVENT] authentication server(ctx)
[SERVER] [1793423.524744458] DEBUG: Outgoing: Writing USERAUTH_SUCCESS
[EVENT] ready server()
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[CLIENT] DEBUG: Parser: IN_PACKET
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: pktLen:12,padLen:10,remainLen:0
[CLIENT] DEBUG: Parser: IN_PACKETDATA
[CLIENT] DEBUG: Parser: HMAC size:16
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY
[CLIENT] DEBUG: Parser: Verifying MAC
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[CLIENT] DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_SUCCESS
[EVENT] ready client()
[CLIENT] DEBUG: Outgoing: Writing CHANNEL_OPEN (0, session)
[CLIENT] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKET
[SERVER] [1793423.524744458] DEBUG: Parser: Decrypting
[SERVER] [1793423.524744458] DEBUG: Parser: pktLen:44,padLen:19,remainLen:32
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETDATA
[SERVER] [1793423.524744458] DEBUG: Parser: Decrypting
[SERVER] [1793423.524744458] DEBUG: Parser: HMAC size:16
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETDATAVERIFY
[SERVER] [1793423.524744458] DEBUG: Parser: Verifying MAC
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_OPEN (0, session)
[EVENT] session server(f,f)
[SERVER] [1793423.524744458] DEBUG: Outgoing: Writing CHANNEL_OPEN_CONFIRMATION (r:0, l:0)
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[CLIENT] DEBUG: Parser: IN_PACKET
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: pktLen:28,padLen:10,remainLen:16
[CLIENT] DEBUG: Parser: IN_PACKETDATA
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: HMAC size:16
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY
[CLIENT] DEBUG: Parser: Verifying MAC
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[CLIENT] DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_OPEN_CONFIRMATION
[CLIENT] DEBUG: Outgoing: Writing CHANNEL_REQUEST (0, exec)
[CLIENT] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKET
[SERVER] [1793423.524744458] DEBUG: Parser: Decrypting
[SERVER] [1793423.524744458] DEBUG: Parser: pktLen:44,padLen:16,remainLen:32
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETDATA
[SERVER] [1793423.524744458] DEBUG: Parser: Decrypting
[SERVER] [1793423.524744458] DEBUG: Parser: HMAC size:16
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETDATAVERIFY
[SERVER] [1793423.524744458] DEBUG: Parser: Verifying MAC
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_REQUEST (0, exec)
[EVENT] exec server.session(f,f,{ command: 'foo --bar' })
[SERVER] [1793423.524744458] DEBUG: Outgoing: Writing CHANNEL_SUCCESS (0)
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[CLIENT] DEBUG: Parser: IN_PACKET
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: pktLen:12,padLen:6,remainLen:0
[CLIENT] DEBUG: Parser: IN_PACKETDATA
[CLIENT] DEBUG: Parser: HMAC size:16
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY
[CLIENT] DEBUG: Parser: Verifying MAC
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[CLIENT] DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_SUCCESS (0)
[CHECK] client.exec(e,s)
[CLIENT] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[DATA] client.exec.stdin wGDWonDrain write(2) .atEnd=true  #2
[CLIENT] DEBUG: Outgoing: Writing CHANNEL_DATA (0)
[FIX] exitOnSourceEnd client.exec.stdin
[CHECK] client.exec.stdin wGDWonDrain:cb(null, finish)
[CHECK] client.exec.stdin.end()
[CLIENT] DEBUG: Outgoing: Writing CHANNEL_EOF (0)
[EVENT] finish client.exec.stdin wGDWonDrain
[CHECK] client.exec.stdin wGDWonDrain:cb(null, finish)
[CHECK] client.exec.stdin.end()
[FIX] endWorkaround client.exec.stdin wGDWonDrain stream
[FIX] endWorkaround client.exec.stdin wGDWonDrain write
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKET
[SERVER] [1793423.524744458] DEBUG: Parser: Decrypting
[SERVER] [1793423.524744458] DEBUG: Parser: pktLen:28,padLen:16,remainLen:16
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETDATA
[SERVER] [1793423.524744458] DEBUG: Parser: Decrypting
[SERVER] [1793423.524744458] DEBUG: Parser: HMAC size:16
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETDATAVERIFY
[SERVER] [1793423.524744458] DEBUG: Parser: Verifying MAC
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
[EVENT] data server.session.exec.stdin sODV (2) #0
[CHECK] server.session.exec.stdin sODV:cb(undefined)
[CHECK] server finish(4) => 4
[CHECK] server.session.exec.exit(100)
[SERVER] [1793423.524744458] DEBUG: Outgoing: Writing CHANNEL_REQUEST (0, exit-status)
[CHECK] server close(4) => 4
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKET
[SERVER] [1793423.524744458] DEBUG: Parser: Decrypting
[SERVER] [1793423.524744458] DEBUG: Parser: pktLen:12,padLen:6,remainLen:0
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETDATA
[SERVER] [1793423.524744458] DEBUG: Parser: HMAC size:16
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETDATAVERIFY
[SERVER] [1793423.524744458] DEBUG: Parser: Verifying MAC
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[SERVER] [1793423.524744458] DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_EOF (0)
[EVENT] finish server.session.exec.stream.stderr
[CHECK] server.end()
[SERVER] [1793423.524744458] DEBUG: Outgoing: Writing DISCONNECT (BY_APPLICATION)
[CLIENT] DEBUG: Parser: IN_PACKET
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: pktLen:44,padLen:18,remainLen:32
[CLIENT] DEBUG: Parser: IN_PACKETDATA
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: HMAC size:16
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY
[CLIENT] DEBUG: Parser: Verifying MAC
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[CLIENT] DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_REQUEST (0, exit-status)
[EVENT] exit client.exec.channel({ '0': 100 })
[CLIENT] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[CLIENT] DEBUG: Parser: IN_PACKET
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: pktLen:28,padLen:14,remainLen:16
[CLIENT] DEBUG: Parser: IN_PACKETDATA
[CLIENT] DEBUG: Parser: Decrypting
[CLIENT] DEBUG: Parser: HMAC size:16
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY
[CLIENT] DEBUG: Parser: Verifying MAC
[CLIENT] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[CLIENT] DEBUG: Parser: IN_PACKETDATAAFTER, packet: DISCONNECT (BY_APPLICATION)
[EVENT] end client()

/Users/mk/Developing/External/ssh2/test/test-streaming.js:933
  throw err;
  ^
AssertionError: [test-streaming/maxNumber=1 Exec( I:wGDWonDrain )<->( I:sODV )]: Wrong close args: undefined
    at Client.<anonymous> (/Users/mk/Developing/External/ssh2/test/test-streaming.js:690:14)
    at emitNone (events.js:67:13)
    at Client.emit (events.js:166:7)
    at Socket.<anonymous> (/Users/mk/Developing/External/ssh2/lib/client.js:217:10)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:903:12)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
```

Interestingly the exit event was delivered correctly  ```[EVENT] exit client.exec.channel({ '0': 100 })``` and in other test cases this didn't happen...

**Comment by mscdex** [comment]
Can you please provide a standalone test for this?

**Comment by mscdex** [comment]
Closing this for now. If you can provide a minimal, standalone test, I would be glad to take a look at this.
