### ISSUE TITLE
Unable to catch "The connection is closed by SSH Server"

### ISSUE THREAD

**Issue by Tiinusen** [mscdex/ssh2#378]
This might already be solved, but at the moment I have no clue how to catch this error.

```
Uncaught Error: The connection is closed by SSH Server

      at onDISCONNECT (node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:2032:15)
      at SSH2Stream.<anonymous> (node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:179:5)
      at parsePacket (node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3465:10)
      at SSH2Stream._transform (node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:555:13)
      at SSH2Stream.Transform._read (_stream_transform.js:167:10)
      at SSH2Stream._read (node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:213:15)
      at SSH2Stream.Transform._write (_stream_transform.js:155:12)
      at doWrite (_stream_writable.js:292:12)
```

**Comment by mscdex** [comment]
Like any EventEmitter in node, you just need to add an `error` event listener, in this case on the `ssh2` connection object.

**Comment by Tiinusen** [comment]
Thanks for the quick response, You were right. In my case it was a typo.
