### ISSUE TITLE
Channels readable push  afterFIN crash

### ISSUE THREAD

**Issue by 131** [mscdex/ssh2#386]
It seems like a dummy issue, it appends on a heavily loaded / busy server (300+ active hosts). I cannot give a very specific trace (but the following)

```
meeting-instance[23646]: Error: This socket has been ended by the other party
 meeting-instance[23646]: at Socket.writeAfterFIN [as write] (net.js:276:12)
 meeting-instance[23646]: at write (_stream_readable.js:583:24)
 meeting-instance[23646]: at flow (_stream_readable.js:592:7)
 meeting-instance[23646]: at Channel.pipeOnReadable (_stream_readable.js:624:5)
 meeting-instance[23646]: at Channel.EventEmitter.emit (events.js:92:17)
 meeting-instance[23646]: at emitReadable_ (_stream_readable.js:408:10)
 meeting-instance[23646]: at emitReadable (_stream_readable.js:404:5)
 meeting-instance[23646]: at readableAddChunk (_stream_readable.js:165:9)
 meeting-instance[23646]: at Channel.Readable.push (_stream_readable.js:127:10)
 meeting-instance[23646]: at SSH2Stream.<anonymous> (/var/www/domyks/ivscs/meeting-instance/node_modules/mas4h/node_modules/ssh2/lib/Channel.js:140:15)
```

```
{ http_parser: '1.0',
  node: '0.10.24',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.21',
  zlib: '1.2.3',
  modules: '11',
  openssl: '1.0.1e',
  npm: '1.3.21',
  ssh2: '0.4.13' }
```

**Comment by mscdex** [comment]
Is it possible you can try this on a newer version of node? At least the latest v0.10 (v0.10.41 as of this writing)?

**Comment by 131** [comment]
I'll try that. FYI My project use mas4h, a distributed revert ssh engine to access remote devices (based on revert ssh streams). Initial implementation was in openssh + php WS. Find the following graph with the load on a meeting instance (300+ active ssh lnk per instance)
http://sharing.activisu.com/storage/screenshots/1452873633.png

Using ssh2 implementation was just magic.

**Comment by 131** [comment]
Same thing with node 4.2.4 and another one on top of that
```
Jan 18 11:57:13 meeting-cluster-c0 meeting-instance[8322]: Error: This socket has been ended by the other party
Jan 18 11:57:13 meeting-cluster-c0 meeting-instance[8322]: at Socket.writeAfterFIN [as write] (net.js:268:12)
Jan 18 11:57:13 meeting-cluster-c0 meeting-instance[8322]: at Channel.ondata (_stream_readable.js:528:20)
Jan 18 11:57:13 meeting-cluster-c0 meeting-instance[8322]: at emitOne (events.js:77:13)
Jan 18 11:57:13 meeting-cluster-c0 meeting-instance[8322]: at Channel.emit (events.js:169:7)
Jan 18 11:57:13 meeting-cluster-c0 meeting-instance[8322]: at Channel.Readable.read (_stream_readable.js:360:10)
Jan 18 11:57:13 meeting-cluster-c0 meeting-instance[8322]: at flow (_stream_readable.js:743:26)
Jan 18 11:57:13 meeting-cluster-c0 meeting-instance[8322]: at resume_ (_stream_readable.js:723:3)
Jan 18 11:57:13 meeting-cluster-c0 meeting-instance[8322]: at doNTCallback2 (node.js:441:9)
Jan 18 11:57:13 meeting-cluster-c0 meeting-instance[8322]: at process._tickCallback (node.js:355:17)

```

**Comment by 131** [comment]
With a bit of refac on my side, the problem is now gone.
