### ISSUE TITLE
Unable to request pseudo terminal

### ISSUE THREAD

**Issue by dopatraman** [mscdex/ssh2#399]
My client is throwing this error:

```
Error: Unable to request a pseudo-terminal
    at C:\Users\pv\Proj\test\ssh-test\node_modules\ssh2\lib\client.js:1160:25
    at SSH2Stream.<anonymous> (C:\Users\pv\Proj\test\ssh-test\node_modules\ssh2\lib\Channel.js:179:24)
    at SSH2Stream.emit (events.js:104:17)
    at parsePacket (C:\Users\pv\Proj\test\ssh-test\node_modules\ssh2\node_modules\ssh2-streams\lib\ssh.js:3225:10)
    at SSH2Stream._transform (C:\Users\pv\Proj\test\ssh-test\node_modules\ssh2\node_modules\ssh2-streams\lib\ssh.js:552:13)
    at SSH2Stream.Transform._read [as __read] (_stream_transform.js:179:10)
    at SSH2Stream._read (C:\Users\pv\Proj\test\ssh-test\node_modules\ssh2\node_modules\ssh2-streams\lib\ssh.js:213:15)
    at SSH2Stream.Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
```

This is code of my client:

```
conn = new Client()
conn.on 'ready', ->
	console.log 'Client :: ready'
	conn.shell (err, stream) ->
		if err then throw err
		stream.on 'close', ->
			console.log 'Stream :: close'
			conn.end()
		.on 'data', (chunk) ->
			console.log 'STDOUT:', data
		.stderr.on 'data', (chunk) ->
			console.log 'STDERR:', data
		stream.end 'ls -l\nexit\n'
.connect
	host: '127.0.0.1'
	port: 57037
	username: 'dopa',
	privateKey: privateKey
```

Note that it is the same as the interactive shell example in the project's README. What am I doing wrong?

**Comment by mscdex** [comment]
Do you have pty (e.g. `/dev/pts`) and tty devices set up on the server?

**Comment by mscdex** [comment]
Assuming [this](http://stackoverflow.com/questions/35593598/) is also your question, I did not know you were also using the ssh2 server component. My answer is duplicated here for posterity:

You're not handling the `pty` session event. The default action when there is no event handler is to reject the request. So to allow all `pty` requests, add something like this:

```javascript
session.on 'pty', (accept, reject, info) ->
    accept()
```
