### ISSUE TITLE
sftp fastPut returns Error: No such file or directory on Windows 7

### ISSUE THREAD

**Issue by gitmft** [mscdex/ssh2#414]
My app works fine on mac but fails on windows 7 64 bit. below is the code an stack trace. Spent some time looking into the streams code based on trace stack. Note, there is no 'continue' event being fired.

SOURCE

```javascript
var stats = fs.statSync(fpath);
console.log("STATS: %j", stats);

var fpconfig = {
	concurrency: 1,
	debug: sftpDebug
};

sftpstream.fastPut(fpath, RD+TN, fpconfig, function(err) {
  if (err) {
    log(0, 'upload sftp fastPut ERROR: ' +fpath +' ' +err +' ' +rc +' ' +err.stack);
    return cb(err);
};
```

TRACE
2016-03-24T22:05:43.471Z: sftpDebug: DEBUG: Parser: IN_PACKETDATAAFTER, packet:
CHANNEL_DATA (0)
2016-03-24T22:05:43.473Z: upload sftp get stream resp:true
STATS: {"dev":275727805,"mode":33206,"nlink":1,"uid":0,"gid":0,"rdev":0,"ino":84
4424930133736,"size":8,"atime":"2016-03-24T22:05:12.953Z","mtime":"2016-03-24T22
:05:12.956Z","ctime":"2016-03-24T22:05:12.956Z","birthtime":"2016-03-24T22:05:12
.953Z"}
2016-03-24T22:05:43.474Z: sftpDebug: DEBUG: Parser: IN_PACKETBEFORE (expecting 1
6)
2016-03-24T22:05:43.475Z: sftpDebug: DEBUG[SFTP]: Outgoing: Writing OPEN
2016-03-24T22:05:43.475Z: sftpDebug: DEBUG: Outgoing: Writing CHANNEL_DATA (0)
2016-03-24T22:05:43.562Z: sftpDebug: DEBUG: Parser: IN_PACKET
2016-03-24T22:05:43.562Z: sftpDebug: DEBUG: Parser: Decrypting
2016-03-24T22:05:43.563Z: sftpDebug: DEBUG: Parser: pktLen:76,padLen:20,remainLe
n:64
2016-03-24T22:05:43.563Z: sftpDebug: DEBUG: Parser: IN_PACKETDATA
2016-03-24T22:05:43.563Z: sftpDebug: DEBUG: Parser: Decrypting
2016-03-24T22:05:43.564Z: sftpDebug: DEBUG: Parser: HMAC size:20
2016-03-24T22:05:43.564Z: sftpDebug: DEBUG: Parser: IN_PACKETDATAVERIFY
2016-03-24T22:05:43.564Z: sftpDebug: DEBUG: Parser: Verifying MAC
2016-03-24T22:05:43.564Z: sftpDebug: DEBUG: Parser: IN_PACKETDATAVERIFY (Valid H
MAC)
2016-03-24T22:05:43.564Z: sftpDebug: DEBUG: Parser: IN_PACKETDATAAFTER, packet:
CHANNEL_DATA (0)
2016-03-24T22:05:43.564Z: sftpDebug: DEBUG[SFTP]: Parser: Response: STATUS
2016-03-24T22:05:43.564Z: sftpDebug: DEBUG: Parser: IN_PACKETBEFORE (expecting 1
6)
2016-03-24T22:05:43.567Z: upload sftp fastPut ERROR: d:\tmp\watch-put\tmp\smalle
r.txt Error: No such file or directory true Error: No such file or directory
    at SFTPStream._transform (D:\tmp\watch-put\node_modules\ssh2\node_modules\ss
h2-streams\lib\sftp.js:384:27)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (D:\tmp\watch-put\node_modules\ssh2\node_modules\ssh2-st
reams\lib\sftp.js:170:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:287:5)
    at SFTPStream.Writable.write (_stream_writable.js:215:11)
    at Channel.ondata (_stream_readable.js:536:20)
    at emitOne (events.js:77:13)
    at Channel.emit (events.js:169:7)
2016-03-24T22:05:43.567Z: watcher upload ERROR: Error: No such file or directory

**Comment by mscdex** [comment]
It looks like the destination directory does not exist? Did you log `RD+TN` and verify that `dirname(RD+TN)` does exist on the server?

**Comment by gitmft** [comment]
Thank you , I didn't get this was an issue on server side path, assumed from the error it was due to local file system. Btw, the app I'm building is sort of a poor mans sftp dropbox using ssh2 sftp and chokidar to automatically upload files to sftp server. Stay tuned and thanks for all of your awesome work. I just saw today you did an sftp server which is grand for testing if nothing else.

**Comment by mscdex** [comment]
One way to tell whether it's a local file system error is if there are `syscall` and other properties attached to the error object. One thing that clued me in was that there was a `STATUS` response to the remote file open for writing, which indicates an error. Otherwise if the open was successful, you would've seen a `HANDLE` response instead.

Your project sounds pretty neat! :-)
