### ISSUE TITLE
error event handled but still raise an UncaughtExecption

### ISSUE THREAD

**Issue by mekalz** [mscdex/ssh2#430]
### ENV
- Node.js version: 0.10.35
- SSH2 version: 0.5.0 (https://github.com/mscdex/ssh2)
- Running on CentOS 7.0

### ISSUE
I use SSH2 to connect to a remote host on port 22, it works well, but if the remote host refused the connection, an 'error' event emitted by sshClient, the problem is even though I have handled this event, there is an UncaughtException thrown that crashed the node process;

#### Step 1

    // In file node_modules/ssh2/lib/client.js (line:295)
    err.level = 'client-socket';
    console.log(‘sock.on: error', JSON.stringify(err)); // I add this log for debugging
    self.emit('error', err);

And in my code, I tried like this:

    var SSHClient = require('ssh2').Client;
    var sshClient = new SSHClient();
    sshClient.on('error', function (error) {
         console.error(’sshClient.on: error', JSON.stringify(error));
         error.message = "this error is handled by callback of sshClient.on('error’): ” + error.message;
    });

then after running my app, in console it printed:

    sock.on: error {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","level":"client-socket"}
    sshClient.on: error {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","level":"client-socket"}
    
    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: this error is handled by callback of sshClient.on('error’): connect ECONNREFUSED
        at errnoException (net.js:905:11)
        at Object.afterConnect [as oncomplete] (net.js:896:19)

> The error.message is the one I modified in sshClient's error event handler, does that mean the error event catch by  sshClient error handler and the 'er' thrown globally are the same one?

----------
#### Step 2
Then I commented the line:295 in client.js, so it looks like this:

    err.level = 'client-socket';
    console.log(‘sock.on: error', JSON.stringify(err)); // I add this log for debugging
    // self.emit('error', err);

After running the app again, in console it only printed this message, and process is not crashed

    sock.on: error {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","level":"client-socket"}

I am so confused why the error raised an UncaughtException even though I have handled the error event and need help.

thanks for help!

**Comment by mscdex** [comment]
You must have another `error` event handler that is throwing, another ssh connection being made in parallel that is without an `error` handler, or something similar. I am not able to reproduce the problem, even with node v0.10.35.

Can you post all the code that uses `sshClient`?

**Comment by mekalz** [comment]
@mscdex thank you for help

My program may be a little complex, I use socket.io to connect to my server from browser, and then the Node.js app running on my server make a SSH connect to another remote host and run a command or bash script like "tail -f /some/log/file" or "grep keyword /some/log/file", after that, the Nose.js app send data via socket.io to browser.

It runs very well except the remote host refuses the SSH connect for some reason(e.g. authority).

The core code is as follow:
```
var util = require('util');
var SSHClient = require('ssh2').Client;

function createTailer(appName, tailerOptions, cb) {
  var host = tailerOptions.host;
  var path = tailerOptions.path;

  var cmdString = util.format('/export/servers/logbook-toolbox/tailer.sh -F %s', path);
  logger.info(util.format('Start tail for app %s on host %s with command: %s', appName, host, cmdString));

  execOnHost(host, cmdString, cb);
}

function execOnHost (host, cmdString, cb) {
  var sshClient = new SSHClient();
  sshClient.on('error', function (error) {
    var errorMsg = '';

    if (error.level) {
      errorMsg = util.format('error when SSH to %s: %s', host, error.message || '');
    }
    logger.error(util.format('ssh to host %s failed: %s', host, JSON.stringify(error)));
    error.message = errorMsg;

    sshClient.end();

    cb(error, null, null);
  });
  sshClient.on('ready', function () {
    sshClient.exec(cmdString, function (err, stream) {
      cb(err, stream, sshClient);
    });
  }).connect({
    host: host,
    port: 22,
    username: 'admin',
    privateKey: fs.readFileSync(property.rtlog.privateKeyFilePath)
  });
}

function LogFinder(appName, host, path, type, options) {
  var commander = {};
  var _this = this;

  this.appName = appName;
  this.host = host;
  this.path = path;
  this.type = type;
  this.options = options;

  var eventsEmitter = new events.EventEmitter();
  // Wrap for EventsEmitter
  this.on = function(event, cb) {
    eventsEmitter.on(event, cb);
  };

  this.stop = function (cb) {
    if (!cb) {
      cb = function(){};
    }
    if (commander.stream && commander.ssh) {
      try {
        commander.stream.end();
        commander.ssh.end();
        return cb(null, 'Commander stoped successfully')
      } catch (e) {
        logger.error(e, appName, host, path);
        var error = {
          code: 500,
          message: 'try to stop commander, but failed with error:' + e.message
        };
        logger.debug(error.message);
        return cb(error, {});
      }
    }
    var error = {
      code: 500,
      message: 'Commander not exist'
    }
    return cb(error, {});
  };

  this.destroy = function () {
    this.stop(function(){
      eventsEmitter.removeAllListeners();
    });
  };

  this.run = function (cb) {
    var error = {code: 500, message: 'Server error'};
    var tmpData = '';

    if (!appName || !host || !path || !options) {
      error = {code: 400, message: 'Arguments error!'};
      eventsEmitter.emit('error', error);
      return cb(error, {});
    }

    var info = {
      appName: appName,
      host: host,
      path: path
    };
    switch (type){
      case 'tail':
        createTailer(appName, options, onCreateCommander);
        break;
      case 'grep':
        createGreper(appName, options, onCreateCommander);
        break;
      case 'scroll':
        createScroller(appName, options, onCreateCommander);
        break;
      default:
        error.message = 'Unknown command type';
        eventsEmitter.emit('error', error);
        return cb(null, error.message);
    }
    function onCreateCommander (err, stream, ssh) {
      commander.stream = stream;
      commander.ssh = ssh;
      if (err) {
        return reportError(err);
      }

      stream.stdout.on('data', function (data) {
        data = data || '';
        if (tmpData) {
          data = Buffer.concat([tmpData, data]);
          tmpData = '';
        }
        var tData = cacheData(data);
        if(tData.tmpBuffer) {
          tmpData = tData.tmpBuffer;
        }
        data = tData.sendBuffer;
        data = options.isGBK ? iconv.decode(data, 'gbk') : data.toString();
        var stream = 'stdout';
        var dataBlock = {
          data: data,
          stream: stream,
          info: {
            appName: appName,
            host: host,
            path: path
          }
        };
        eventsEmitter.emit('data', dataBlock);
        var dataArr = data.split('\n');
        dataArr.forEach(function(msg){
          var row = {
            data: msg,
            stream: stream,
            info: {
              appName: appName,
              host: host,
              path: path
            }
          };
          eventsEmitter.emit('row', row);
        });
      });

      stream.stderr.on('data', function (data) {
        data = data || '';
        data = options.isGBK ? iconv.decode(data, 'gbk') : data.toString();
        var stream = 'stderr';
        var dataBlock = {
          data: data,
          stream: stream,
          info: {
            appName: appName,
            host: host,
            path: path
          }
        };
        eventsEmitter.emit('data', dataBlock);
        var dataArr = data.split('\n');
        dataArr.forEach(function(msg){
          var row = {
            data: msg,
            stream: stream,
            info: {
              appName: appName,
              host: host,
              path: path
            }
          };
          eventsEmitter.emit('row', row);
        });

        var errMsg = util.format('Got error from host %s when handling path %s: %s', host, path, data);
        logger.error(errMsg);
      });

      stream.on('exit', function(data) {
        var stream = 'stdinfo';
        var msg = 'search done';

        var row = {
          data: msg,
          stream: stream,
          info: {
            appName: appName,
            host: host,
            path: path
          }
        };

        ssh.end();

        eventsEmitter.emit('exit', row);

        var msg = util.format('Logfinder exit on host: %s, after finding in path: %s', host, path);
        logger.debug(msg);

        cb(null, row);
      });

      stream.on('error', function(err) {
        ssh.end();
        reportError(err);
      });

      function reportError (err) {
        err.message = err.message || 'Unknown error';
        var errMsg = util.format('app %s on host %s and path %s, %s', appName, host, path, err.message);
        logger.error('command error:', errMsg);

        eventsEmitter.emit('error', err);
        cb(err, {});
      }
    }
  }
}
```

What I do is make a LogFinder instance, and call its 'run' method:
```
var logFinder = new LogFinder(appName, host, path, type, options);
logFinder.on('error', function(error){
  // this callback is called as expected before the UncaughtException
  sioDataManager.send({
    event: processOption.events.error,
    content: error
  });
});
logFinder.on('data', function(data){
  sioDataManager.send({ // sioDataManager is a tool to cache data received from remote host
    event: processOption.events.result,
    content: data
  }, function(error) {
    if (error) {
      error.message += ', Stop remote process'
    }
    logger.error(error.message);
    logFinder.stop();
  });
});
logFinder.run(function(err, result){
   jobDone();
});
var jobDone = function() {
  sioDataManager.destroy();
  logFinder.destroy();
};
```

**Comment by mekalz** [comment]
@mscdex 
I will write a simple demo to see if I can reproduce this situation.

**Comment by mscdex** [comment]
A simple demo would be great.

Is it possible that `reportError()` is being called more than once? What if you temporarily comment out `eventsEmitter.removeAllListeners();`?

**Comment by mekalz** [comment]
I got it.
The problem is that the error emitted by function reportError was not being handled.
I change it like this:
```
function reportError (err) {
  err.message = err.message || 'Unknown error';
  var errMsg = util.format('app %s on host %s and path %s, %s', appName, host, path, err.message);
  logger.error('command error:', errMsg);
  if (cb) {
    cb(err, {});
  } else {
    // emit error only if no callback function passed in
    eventsEmitter.emit('error', err);
  }
}
```
@mscdex thank you for help;
