### ISSUE TITLE
Error: Failed to translate Buffer to a EC_POINT

### ISSUE THREAD

**Issue by Juul** [mscdex/ssh2#463]
When connecting with latest stable dropbear client (2016.74) to an ssh2 server I get this error.

My code:

```
var serv = new ssh2.Server({
  hostKeys: [fs.readFileSync(settings.keys.priv)]
}, function(client) {
  console.log('client connected!');
});

serv.listen(2222, 'localhost', function() {
  console.log("listening");
});
```

Output:

```
listening
client connected!
crypto.js:414
  var ret = this._handle.computeSecret(toBuf(key, inEnc));
                         ^

Error: Failed to translate Buffer to a EC_POINT
    at Error (native)
    at ECDH.dhComputeSecret [as computeSecret] (crypto.js:414:26)
    at KEXDH_REPLY (/home/juul/projects/meshing/remote_makenode/server/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:4860:26)
    at onKEXDH_INIT (/home/juul/projects/meshing/remote_makenode/server/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:2514:3)
    at SSH2Stream.<anonymous> (/home/juul/projects/meshing/remote_makenode/server/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:209:41)
    at emitOne (events.js:77:13)
    at SSH2Stream.emit (events.js:169:7)
    at parse_KEX (/home/juul/projects/meshing/remote_makenode/server/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:4055:12)
    at parsePacket (/home/juul/projects/meshing/remote_makenode/server/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3901:12)
    at SSH2Stream._transform (/home/juul/projects/meshing/remote_makenode/server/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:652:13)
```

**Comment by Juul** [comment]
I should note that this is using node v4.5.0

**Comment by Juul** [comment]
I enabled debug on the server. Here's the output:

```
listening
[debug] [34331.4445637] DEBUG: Local ident: 'SSH-2.0-ssh2js0.1.7srv'
[debug] [34331.4445637] DEBUG: Parser: IN_INIT (waiting for identification begin)
[debug] [34331.4445637] DEBUG: Parser: IN_INIT (waiting for rest of identification)
[debug] [34331.4445637] DEBUG: Parser: IN_GREETING
[debug] [34331.4445637] DEBUG: Parser: IN_HEADER
client connected!
[debug] [34331.4445637] DEBUG: Remote ident: 'SSH-2.0-dropbear_2016.74'
[debug] [34331.4445637] DEBUG: Outgoing: Writing KEXINIT
[debug] [34331.4445637] DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
[debug] [34331.4445637] DEBUG: Parser: IN_PACKET
[debug] [34331.4445637] DEBUG: Parser: pktLen:684,padLen:4,remainLen:680
[debug] [34331.4445637] DEBUG: Parser: IN_PACKETDATA
[debug] [34331.4445637] DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXINIT
[debug] [34331.4445637] DEBUG: Comparing KEXINITs ...
[debug] [34331.4445637] DEBUG: (local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1
[debug] [34331.4445637] DEBUG: (remote) KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,kexguess2@matt.ucc.asn.au
[debug] [34331.4445637] DEBUG: KEX algorithm: ecdh-sha2-nistp521
[debug] [34331.4445637] DEBUG: (local) Host key formats: ssh-rsa
[debug] [34331.4445637] DEBUG: (remote) Host key formats: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,ssh-dss
[debug] [34331.4445637] DEBUG: Host key format: ssh-rsa
[debug] [34331.4445637] DEBUG: (local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
[debug] [34331.4445637] DEBUG: (remote) Client->Server ciphers: aes128-ctr,aes256-ctr,aes128-cbc,aes256-cbc,twofish256-cbc,twofish-cbc,twofish128-cbc,3des-ctr,3des-cbc
[debug] [34331.4445637] DEBUG: Client->Server Cipher: aes128-ctr
[debug] [34331.4445637] DEBUG: (local) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
[debug] [34331.4445637] DEBUG: (remote) Server->Client ciphers: aes128-ctr,aes256-ctr,aes128-cbc,aes256-cbc,twofish256-cbc,twofish-cbc,twofish128-cbc,3des-ctr,3des-cbc
[debug] [34331.4445637] DEBUG: Server->Client Cipher: aes128-ctr
[debug] [34331.4445637] DEBUG: (local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
[debug] [34331.4445637] DEBUG: (remote) Client->Server HMAC algorithms: hmac-sha1-96,hmac-sha1,hmac-sha2-256,hmac-sha2-512,hmac-md5
[debug] [34331.4445637] DEBUG: Client->Server HMAC algorithm: hmac-sha1
[debug] [34331.4445637] DEBUG: (local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
[debug] [34331.4445637] DEBUG: (remote) Server->Client HMAC algorithms: hmac-sha1-96,hmac-sha1,hmac-sha2-256,hmac-sha2-512,hmac-md5
[debug] [34331.4445637] DEBUG: Server->Client HMAC algorithm: hmac-sha1
[debug] [34331.4445637] DEBUG: (local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
[debug] [34331.4445637] DEBUG: (remote) Client->Server compression algorithms: zlib@openssh.com,zlib,none
[debug] [34331.4445637] DEBUG: Client->Server compression algorithm: zlib@openssh.com
[debug] [34331.4445637] DEBUG: (local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
[debug] [34331.4445637] DEBUG: (remote) Server->Client compression algorithms: zlib@openssh.com,zlib,none
[debug] [34331.4445637] DEBUG: Server->Client compression algorithm: zlib@openssh.com
[debug] [34331.4445637] DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
[debug] [34331.4445637] DEBUG: Parser: IN_PACKET
[debug] [34331.4445637] DEBUG: Parser: pktLen:44,padLen:6,remainLen:40
[debug] [34331.4445637] DEBUG: Parser: IN_PACKETDATA
[debug] [34331.4445637] DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXECDH_INIT
crypto.js:414
  var ret = this._handle.computeSecret(toBuf(key, inEnc));
                         ^

Error: Failed to translate Buffer to a EC_POINT
    at Error (native)
    at ECDH.dhComputeSecret [as computeSecret] (crypto.js:414:26)
    at KEXDH_REPLY (/home/juul/projects/meshing/remote_makenode/server/node_modules/ssh2-streams/lib/ssh.js:4860:26)
    at onKEXDH_INIT (/home/juul/projects/meshing/remote_makenode/server/node_modules/ssh2-streams/lib/ssh.js:2514:3)
    at SSH2Stream.<anonymous> (/home/juul/projects/meshing/remote_makenode/server/node_modules/ssh2-streams/lib/ssh.js:209:41)
    at emitOne (events.js:77:13)
    at SSH2Stream.emit (events.js:169:7)
    at parse_KEX (/home/juul/projects/meshing/remote_makenode/server/node_modules/ssh2-streams/lib/ssh.js:4055:12)
    at parsePacket (/home/juul/projects/meshing/remote_makenode/server/node_modules/ssh2-streams/lib/ssh.js:3901:12)
    at SSH2Stream._transform (/home/juul/projects/meshing/remote_makenode/server/node_modules/ssh2-streams/lib/ssh.js:652:13)
```

**Comment by Juul** [comment]
If I set the following on the server:

```
    algorithms: {
        kex: ['diffie-hellman-group14-sha1']
    }
```

The server doesn't give an error but dropbear client disconnects with:

```
exited: Bad hostkey signature
```

**Comment by mscdex** [comment]
Does the regular OpenSSH client work just fine?

It's been awhile since I've used dropbear, so I will have to do some tests. Dropbear borrows (or at least they forked) from OpenSSH so I would expect both to work (mostly) the same.

**Comment by mscdex** [comment]
Also, can you share a minimal reproducible example I can use to test with?

**Comment by Juul** [comment]
Yeah it works fine with OpenSSH. Thanks for the quick reply! I put up instructions and code to reproduce the issue [right here](https://github.com/Juul/node-ssh2-dropbear-bug) :)

**Comment by mscdex** [comment]
Thanks for the repro repo!
