### ISSUE TITLE
uncaughtException: write EPIPE  - how to catch it?

### ISSUE THREAD

**Issue by Kurtas** [mscdex/ssh2#464]
Hello, 

 I'm getting this error ```uncaughtException: write EPIPE``` and I can't find way how to catch it.
I tried following code, but without success

```
ssh.on('error', e => logError(e))
ssh._sock.on('error', e => logError(e))
```

Thanks in advance

**Comment by mscdex** [comment]
What does the stack trace show?

Do you have a way to reliably reproduce the error?

**Comment by Kurtas** [comment]
I think that I can reproduce it. It happens on devices where I'm trying to get a lot of data.
Here is stack
```
2016-09-05T15:06:45.894Z - error: uncaughtException: write EPIPE 
{ date: 'Mon Sep 05 2016 17:06:45 GMT+0200 (CEST)',
  process: 
   { pid: 55884,
     uid: 1000,
     gid: 1000,
     cwd: '/home/kurtas/script',
     execPath: '/usr/local/bin/node',
     version: 'v6.2.2',
     argv: 
      [ '/usr/local/bin/node',
        '/home/kurtas/script/worker.js',
        '--instance=1' ],
     memoryUsage: { rss: 539774976, heapTotal: 503107584, heapUsed: 345642232 } },
  os: 
   { loadavg: [ 1.08544921875, 0.8134765625, 0.74658203125 ],
     uptime: 27691 },
  trace: 
   [ { column: 11,
       file: 'util.js',
       function: 'exports._errnoException',
       line: 1007,
       method: '_errnoException',
       native: false },
     { column: 14,
       file: 'net.js',
       function: 'WriteWrap.afterWrite',
       line: 793,
       method: 'afterWrite',
       native: false } ],
  stack: 
   [ 'Error: write EPIPE',
     '    at exports._errnoException (util.js:1007:11)',
     '    at WriteWrap.afterWrite (net.js:793:14)' ] }
```

**Comment by mscdex** [comment]
Can you try with the latest version of `ssh2` and let me know if it still occurs? If so, can you show how you're using `ssh2`?

**Comment by Kurtas** [comment]
Today I installed latest version of ```ssh2``` but now I'm immediately disconnected. Do you have any idea?

Here is debug log
```
DEBUG: Local ident: 'SSH-2.0-ssh2js0.1.7'
DEBUG: Client: Trying 10.95.147.3 on port 22 ...
DEBUG: Client: Connected
DEBUG: Parser: IN_INIT
DEBUG: Parser: IN_GREETING
DEBUG: Parser: IN_HEADER
DEBUG: Remote ident: 'SSH-2.0-Cisco-1.25'
DEBUG: Outgoing: Writing KEXINIT
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:340,padLen:5,remainLen:336
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXINIT
DEBUG: Comparing KEXINITs ...
DEBUG: (local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1
DEBUG: (remote) KEX algorithms: diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
DEBUG: KEX algorithm: diffie-hellman-group14-sha1
DEBUG: (local) Host key formats: ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
DEBUG: (remote) Host key formats: ssh-rsa
DEBUG: Host key format: ssh-rsa
DEBUG: (local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
DEBUG: (remote) Client->Server ciphers: aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc
DEBUG: No matching Client->Server cipher
DEBUG: Outgoing: Writing DISCONNECT (KEY_EXCHANGE_FAILED)
```

**Comment by mscdex** [comment]
The cipher list needs to be adjusted for older servers like this. The default settings changed in v0.5 to align with recent OpenSSH defaults (for security reasons). To manually set the list of ciphers to use for the connection:

```js
ssh.connect({
  algorithms: {
    cipher: ['aes128-ctr','aes192-ctr','aes256-ctr','aes128-gcm','aes128-gcm@openssh.com','aes256-gcm','aes256-gcm@openssh.com','aes-256-cbc']
  }
});
```

As far as emitting an actual error on handshake failure, that's on my todo list yet.

**Comment by Kurtas** [comment]
Hi, thanks you are really great!
I had to add more ```cipher``` settings & also ```kex``` but now it seems that it works. Also I don't see any ```EPIPE write``` errors ... 

Here is my current setting of algorithms
```
algorithms: {
  kex: ['ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group14-sha1', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group1-sha1'],
  cipher: ['aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm', 'aes128-gcm@openssh.com', 'aes256-gcm', 'aes256-gcm@openssh.com', 'aes256-cbc', 'aes192-cbc', 'aes128-cbc', 'blowfish-cbc', '3des-cbc', 'arcfour256', 'arcfour128', 'cast128-cbc', 'arcfour']
}
```

I will test it more, thanks once again!
