### ISSUE TITLE
Uncaught crypto signing errors when using privateKey

### ISSUE THREAD

**Issue by NathanRSmith** [mscdex/ssh2#465]
Hi, I ran across some uncaught errors when using private key authentication (ssh2@0.5.1). Using the public key:

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDPswXi+GDDofE1/cq1V/dVQtNiCtFKW/5wJl0HXHEjWn+cbK7956RSfkL6YZ4NLjzwNfm6XOJzFWkvulqZz+0U1yn3UytHs+IgwraX5vBtkm5tsuMMeE1wGSWcU5IrG2ZBF+6isZqSnL+ReYjEXmh/TFcaezoOUdGr10YIkhe+uSqFwRuTifbLhpXhU6Iwd2joWsVBU/MDwOVsk/ZKMgVn/RV0rs7t6LKKpXWnXGVtNBDmsBct2yyEGf8a+gE5MJW6kxe6ufbnza+AaHboyai+PZAbNJwwZRW22QyWfFSYpP9pCRqYLS9HnhA5buXJY+MCK05XSqCa0abf9yXtbs2P nathansmith@Nathans-MacBook-Pro.local
```

The following script will succeed in the first case, but raise an unhandled error (not provided to 'error' event handler) in the second.

```
var Client = require('ssh2').Client;

var pk = 
'-----BEGIN RSA PRIVATE KEY-----\n'+
'MIIEpQIBAAKCAQEAz7MF4vhgw6HxNf3KtVf3VULTYgrRSlv+cCZdB1xxI1p/nGyu\n'+
'/eekUn5C+mGeDS488DX5ulzicxVpL7pamc/tFNcp91MrR7PiIMK2l+bwbZJubbLj\n'+
'DHhNcBklnFOSKxtmQRfuorGakpy/kXmIxF5of0xXGns6DlHRq9dGCJIXvrkqhcEb\n'+
'k4n2y4aV4VOiMHdo6FrFQVPzA8DlbJP2SjIFZ/0VdK7O7eiyiqV1p1xlbTQQ5rAX\n'+
'LdsshBn/GvoBOTCVupMXurn2582vgGh26Mmovj2QGzScMGUVttkMlnxUmKT/aQka\n'+
'mC0vR54QOW7lyWPjAitOV0qgmtGm3/cl7W7NjwIDAQABAoIBAFxH0C+951BEXWV9\n'+
's1jLEqshG8YNxFtjcDLn+KFSoznv9Y7MgxtwlgPI8X1Jbe2xQ4X+lUwGBN7Y/nkk\n'+
'NSjtxwphZtXqb+pVs/yWRoZLJzunucSnnFVoBg/uPFWuk9zvOYlmVrKWcnT9i+fY\n'+
'tbl5sLgOdQzg/zRpidztssIQFti3o2jnpyrEGcepPWLkfCgqPfGmNv78BAIt/6iT\n'+
'zYDB4GMSq/LnPTIOFsIOvlkZg3RCcLWeAPRC+lvFQVY+M/uJL5WIbA5il1IMMKH7\n'+
'MULWpRO3lnb1JVrkZlBldK5uew6AN3tHDQOmg+C2JuIbOZ35J9dcnwsE+IptWWBj\n'+
'XiFRJCECgYEA8BeuufkslureqOycaPLMkqchMTue1OxbLJFvPN+dh/cW6Lng3b8+\n'+
'xAyzZrc0vccH/jl9WVHhIZ7TcKXDzSmmrtnZ/3m1c4gANGqIPwO+emL1ZzzkIKGd\n'+
'FrLeBZKP4TWry9kjg4cG1SKGpcB5ngJMPXUxMZNe74tC4Hk820PkFjcCgYEA3XXn\n'+
'ngRCgH9N1eKSD2daxxlBhTTSnTgjU+dDaDFQzPIhJCcS8HwyQBQmNTOSXXK9sShC\n'+
'fdXAsmiBby5WEBq/K5+cXeDG2ZlFLyPovEgTUrLgraw42PYs0+A8Ls7dFk7PuMez\n'+
'3G2gUPkY039JiyXKfcog9/dIRfbWCwzQ6s7TV2kCgYEArsme81cahhgg1zvCNokk\n'+
'M1Omz2/HFt2nFpAeOmPVDGnu7Kh9sxGKgTF53bpclBh0kjiKL99zFYXKCoUzQYYk\n'+
'CcEhemLBnYUSGRbBb5arMfAfFfR3Y+YkNaUsC0SCqILpOfMvbo57g+ipu7ufDlA/\n'+
'7rIFiUDvaVap7j909W+8egsCgYEAsuc/0DBixMmSyHl7QwRcmkC15HVSu32RVIOb\n'+
'ub01KAtmaH1EWJAMTCW64/mggOtjgI0kgeE/BSFVhsqo7eOdkhEj0db27OxbroRU\n'+
'zF1xdrpYtRRO7D6a4iLgm3OzuQS72+tASo8pFqDUxG6sq8NAvLOgRJE4ioSoT07w\n'+
'KvAgXRkCgYEAmWgcsX/BdNcKOteSDtPkys5NRtWCBz7Coxb+xXXoXz1FVegBolpY\n'+
't6OUDL7XIBDnCw6s3v3Hn9jky+k/iu4pppQsS70e7MdJMUrAk/ge7AmXstpGlGdA\n'+
'wXVePvXTIbU8VJOLunMyH5wpmMUiJbTX9v2o/yfpsH0ci4GaAeVtqpA=\n'+
'-----END RSA PRIVATE KEY-----\n';

// removed 3rd from last line
var badpk = 
'-----BEGIN RSA PRIVATE KEY-----\n'+
'MIIEpQIBAAKCAQEAz7MF4vhgw6HxNf3KtVf3VULTYgrRSlv+cCZdB1xxI1p/nGyu\n'+
'/eekUn5C+mGeDS488DX5ulzicxVpL7pamc/tFNcp91MrR7PiIMK2l+bwbZJubbLj\n'+
'DHhNcBklnFOSKxtmQRfuorGakpy/kXmIxF5of0xXGns6DlHRq9dGCJIXvrkqhcEb\n'+
'k4n2y4aV4VOiMHdo6FrFQVPzA8DlbJP2SjIFZ/0VdK7O7eiyiqV1p1xlbTQQ5rAX\n'+
'LdsshBn/GvoBOTCVupMXurn2582vgGh26Mmovj2QGzScMGUVttkMlnxUmKT/aQka\n'+
'mC0vR54QOW7lyWPjAitOV0qgmtGm3/cl7W7NjwIDAQABAoIBAFxH0C+951BEXWV9\n'+
's1jLEqshG8YNxFtjcDLn+KFSoznv9Y7MgxtwlgPI8X1Jbe2xQ4X+lUwGBN7Y/nkk\n'+
'NSjtxwphZtXqb+pVs/yWRoZLJzunucSnnFVoBg/uPFWuk9zvOYlmVrKWcnT9i+fY\n'+
'tbl5sLgOdQzg/zRpidztssIQFti3o2jnpyrEGcepPWLkfCgqPfGmNv78BAIt/6iT\n'+
'zYDB4GMSq/LnPTIOFsIOvlkZg3RCcLWeAPRC+lvFQVY+M/uJL5WIbA5il1IMMKH7\n'+
'MULWpRO3lnb1JVrkZlBldK5uew6AN3tHDQOmg+C2JuIbOZ35J9dcnwsE+IptWWBj\n'+
'XiFRJCECgYEA8BeuufkslureqOycaPLMkqchMTue1OxbLJFvPN+dh/cW6Lng3b8+\n'+
'xAyzZrc0vccH/jl9WVHhIZ7TcKXDzSmmrtnZ/3m1c4gANGqIPwO+emL1ZzzkIKGd\n'+
'FrLeBZKP4TWry9kjg4cG1SKGpcB5ngJMPXUxMZNe74tC4Hk820PkFjcCgYEA3XXn\n'+
'ngRCgH9N1eKSD2daxxlBhTTSnTgjU+dDaDFQzPIhJCcS8HwyQBQmNTOSXXK9sShC\n'+
'fdXAsmiBby5WEBq/K5+cXeDG2ZlFLyPovEgTUrLgraw42PYs0+A8Ls7dFk7PuMez\n'+
'3G2gUPkY039JiyXKfcog9/dIRfbWCwzQ6s7TV2kCgYEArsme81cahhgg1zvCNokk\n'+
'M1Omz2/HFt2nFpAeOmPVDGnu7Kh9sxGKgTF53bpclBh0kjiKL99zFYXKCoUzQYYk\n'+
'CcEhemLBnYUSGRbBb5arMfAfFfR3Y+YkNaUsC0SCqILpOfMvbo57g+ipu7ufDlA/\n'+
'7rIFiUDvaVap7j909W+8egsCgYEAsuc/0DBixMmSyHl7QwRcmkC15HVSu32RVIOb\n'+
'ub01KAtmaH1EWJAMTCW64/mggOtjgI0kgeE/BSFVhsqo7eOdkhEj0db27OxbroRU\n'+
'zF1xdrpYtRRO7D6a4iLgm3OzuQS72+tASo8pFqDUxG6sq8NAvLOgRJE4ioSoT07w\n'+
'KvAgXRkCgYEAmWgcsX/BdNcKOteSDtPkys5NRtWCBz7Coxb+xXXoXz1FVegBolpY\n'+
'wXVePvXTIbU8VJOLunMyH5wpmMUiJbTX9v2o/yfpsH0ci4GaAeVtqpA=\n'+
'-----END RSA PRIVATE KEY-----\n';

function go(pk) {
  var conn = new Client();
  conn.on('ready', function() {
    conn.exec('whoami; pwd;', function(err, stream) {
      if(err) {
        console.log('exec err');
        console.log(err);
        return;
      }

      stream.on('close', function(code, signal) {
            console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
            conn.end();
          }).on('data', function(data) {
            console.log('STDOUT: ' + data);
          }).stderr.on('data', function(data) {
            console.log('STDERR: ' + data);
          });
    })
  })
  .on('error', function(err) {
    console.log('caught connection err');
    console.log(err);
  })
  .connect({
    host: 'localhost',
    port: 32776,
    username: 'app-admin',
    privateKey: pk
  });
}

process.on('uncaughtException', function(err) {
  console.log('uncaught');
  console.log(err.stack);
  process.exit();
})


setTimeout(go.bind(null, pk), 0);
setTimeout(go.bind(null, badpk), 1000);
```

Output:

```
$ node fail.js
STDOUT: app-admin

STDOUT: /home/app-admin

Stream :: close :: code: 0, signal: undefined
uncaught
Error: error:0D07209B:asn1 encoding routines:ASN1_get_object:too long
    at Error (native)
    at Sign.sign (crypto.js:279:26)
    at /Users/nathansmith/dev/ssh-exploration/node_modules/ssh2/lib/client.js:559:31
    at SSH2Stream.authPK (/Users/nathansmith/dev/ssh-exploration/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:1596:3)
    at SSH2Stream.onUSERAUTH_PK_OK (/Users/nathansmith/dev/ssh-exploration/node_modules/ssh2/lib/client.js:536:14)
    at SSH2Stream.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at SSH2Stream.emit (events.js:166:7)
    at parse_USERAUTH (/Users/nathansmith/dev/ssh-exploration/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:4203:12)
    at parsePacket (/Users/nathansmith/dev/ssh-exploration/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3903:12)
```

I have been able to cause other crypto signing errors with other bad keys, but I believe a try catch around the `lib/client.js:559` area should be able to handle it appropriately.

**Comment by mscdex** [comment]
There is a general debate about this, but I lean more towards throwing for immediate errors (e.g. bad function arguments) and reserving `'error'` events for errors that happen after the next tick (e.g. a socket connection timeout), where throwing would not "work" at all.

**Comment by NathanRSmith** [comment]
Generally I would agree with you, but in this particular case it is not thrown synchronously:

Adjusting the bottom part of the script to print some timestamps and include a try-catch block:

```
process.on('uncaughtException', function(err) {
  console.log('uncaught',Date.now());
  console.log(err.stack);
  process.exit();
});

setTimeout(function() {
  console.log('pk',Date.now());
  go(pk);
}, 0);
setTimeout(function() {
  console.log('badpk',Date.now());
  try {
    go(badpk);
  }
  catch(err) {
    console.log('caught synchronously');
  }
}, 1000);
```

```
$ node fail.js
pk 1473360736269
STDOUT: app-admin

STDOUT: /home/app-admin

Stream :: close :: code: 0, signal: undefined
badpk 1473360737267
uncaught 1473360737289
Error: error:0D07209B:asn1 encoding routines:ASN1_get_object:too long
    at Error (native)
    at Sign.sign (crypto.js:279:26)
    at /Users/nathansmith/dev/Aunalytics/aunsight/aunsight-docker-dev/ssh-exploration/node_modules/ssh2/lib/client.js:559:31
    at SSH2Stream.authPK (/Users/nathansmith/dev/Aunalytics/aunsight/aunsight-docker-dev/ssh-exploration/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:1596:3)
    at SSH2Stream.onUSERAUTH_PK_OK (/Users/nathansmith/dev/Aunalytics/aunsight/aunsight-docker-dev/ssh-exploration/node_modules/ssh2/lib/client.js:536:14)
    at SSH2Stream.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at SSH2Stream.emit (events.js:166:7)
    at parse_USERAUTH (/Users/nathansmith/dev/Aunalytics/aunsight/aunsight-docker-dev/ssh-exploration/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:4203:12)
    at parsePacket (/Users/nathansmith/dev/Aunalytics/aunsight/aunsight-docker-dev/ssh-exploration/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3903:12)```

**Comment by mscdex** [comment]
Thanks for the repro!

**Comment by NathanRSmith** [comment]
Thanks for the fix!
