### ISSUE TITLE
Handle connection hopping to unreachable device

### ISSUE THREAD

**Issue by lynchs61** [mscdex/ssh2#477]
In your readme there's an example for connection hopping that executes the netcat command to open a connection to another device. I'm struggling to find a way to handle the case where the second device is unavailable. So for example, in your example below, how do I handle the case where `192.168.1.2` is unreachable. Right now it will just hang.

```javascript
conn1.exec('nc 192.168.1.2 22', function(err, stream) {
    if (err) {
      console.log('FIRST :: exec error: ' + err);
      return conn1.end();
    }
    conn2.connect({
      sock: stream,
      username: 'user2',
      password: 'password2',
    });
  });
````

**Comment by mscdex** [comment]
I don't think netcat has an option for *just* initial connection timeout.

Another alternative (if the server allows it) is to use `conn1.forwardOut()` which will create an outbound connection using ssh directly. Then pass the resulting stream (if no error) to `conn2.connect()`.

**Comment by lynchs61** [comment]
Thank you for your quick response! This doesn't seem to work. I get an error after I change exec to forwardOut. This is my actual example:

```
var Client = require('ssh2').Client;

var conn1 = new Client(),
    conn2 = new Client();

conn1.on('ready', function() {
    console.log('FIRST :: connection ready');
    conn1.forwardOut('nc 192.168.20.113 22', function(err, stream) {
        if (err) {
            console.log('FIRST :: exec error: ' + err);
            return conn1.end();
        }
        conn2.connect({
            sock: stream,
            username: 'root',
            password: 'mypassword'
        });
    });
}).connect({
    host: '10.101.139.200',
    username: 'root',
    password: 'mypassword'
});

conn2.on('ready', function() {
    console.log('SECOND :: connection ready');
    conn2.exec('uptime', function(err, stream) {
        if (err) {
            console.log('SECOND :: exec error: ' + err);
            return conn1.end();
        }
        stream.on('end', function() {
            conn1.end(); // close parent (and this) connection
        }).on('data', function(data) {
            console.log(data.toString());
        });
    });
});
```

It gives the following error.. Does this mean the server doesn't allow it? Why would it not allow it?
```
FIRST :: connection ready
buffer.js:771
  if (string.length > 0 && (length < 0 || offset < 0))
            ^

TypeError: Cannot read property 'length' of undefined
    at Buffer.write (buffer.js:771:13)
    at SSH2Stream.directTcpip (/home/slynch/WebstormProjects/testing/node_modules/ssh2-streams/lib/ssh.js:1128:7)
    at openChannel (/home/slynch/WebstormProjects/testing/node_modules/ssh2/lib/client.js:1130:21)
    at Client.forwardOut (/home/slynch/WebstormProjects/testing/node_modules/ssh2/lib/client.js:982:10)
    at Client.<anonymous> (/home/slynch/WebstormProjects/testing/test_connection_hopping.js:12:11)
    at emitNone (events.js:86:13)
    at Client.emit (events.js:185:7)
    at SSH2Stream.<anonymous> (/home/slynch/WebstormProjects/testing/node_modules/ssh2/lib/client.js:589:10)
    at SSH2Stream.g (events.js:286:16)
    at emitNone (events.js:86:13)
```

Does this mean the server doesn't allow this?

**Comment by mscdex** [comment]
Sorry, I did not mean you just literally replace the function name. It's a different function altogether. For example:

```js
conn1.forwardOut(
  // source address, can usually be any valid IP
  '127.0.0.1',
  // source port, this can any valid port number
  12345,
  // destination address, the second ssh server in your case
  '127.0.0.1',
  // destination port, standard ssh port unless it is something different
  22, function(err, stream) {
  if (err) {
    console.log('FIRST :: forwardOut error: ' + err);
    return conn1.end();
  }
  conn2.connect({
    sock: stream,
    username: 'root',
    password: 'mypassword'
  });
});
```

**Comment by lynchs61** [comment]
Ah. I didn't think about how to actually use it.
Thank you. This works great.
