### ISSUE TITLE
Getting an Error: Path not found. at SFTPStream._transform

### ISSUE THREAD

**Issue by talbotlawrence** [mscdex/ssh2#537]
This is a question and not an issue: I'm building an SFTP client web app for a school project.  I am trying to run code from the README.md file, but I'm getting this error message in the terminal (below).  I'm sure it's something simple like requiring this other node package in my file.  I'm just not sure how to include it:

```
Error: Path not found.
    at SFTPStream._transform (/path/lib/node_modules/ssh2-streams/lib/sftp.js:405:27)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/path/lib/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SFTPStream.Writable.write (_stream_writable.js:220:11)
    at Channel.ondata (_stream_readable.js:556:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
```

Here is the code below:
![image](https://cloud.githubusercontent.com/assets/456527/23865945/4f016308-07e5-11e7-8e30-ad0880afc32d.png)

**Comment by mscdex** [comment]
The SFTP server is telling you the path doesn't exist. You might try using an absolute path as IIRC there is no standardization on the base directory for relative paths (although I *think* OpenSSH's SFTP implementation uses the user's home directory).

**Comment by talbotlawrence** [comment]
Thank you!  Unfortunately, I'm still getting the error.  
What is odd is that it's saying the "ssh2-streams" path is not found, but I didn't think I had to require that package in order for the ssh2 package to work.

**Comment by mscdex** [comment]
The error message is coming from the SFTP server, it has nothing to do with node modules.

What (SFTP) server and server version is this with (you can find out by setting `debug: console.log` in the connection config and checking the server ident string near the top of the output)?

When you tried an absolute path, did you try something like `'/home/user/foo'`, assuming the file `'foo'` is in the user's home directory?
