### ISSUE TITLE
Handle `uncaughtException All configured authentication methods failed`

### ISSUE THREAD

**Issue by zer0Id0l** [mscdex/ssh2#543]
How do we handle `error` event for client connection errors? Trying to listen on `error` event for  client object doesn't help (code below). Is there another way to handle these errors? 

I am trying to handle error cases where client is unable to connect host for any reason(incorrect hostname, network issues, etc).
 
```
            var conn = new Client();
            conn.on('ready', function() {
                console.log('Client :: ready');
                conn.exec('tail -f /home/a.file', function(err, stream) {
                    console.log('Client :: executed command')
                    stream.on('data', function(code, signal) {
                        console.log('STREAM :: close :: code: ' + code + ', signal: ' + signal);
                        conn.end()
                    })
                });
            }).connect({
                host: host,
                port: ssh.port,
                username: ssh.username,
                privateKey: require('fs').readFileSync(ssh.privateKey)
            });
            conn.on('error', function(err) {
                console.log('Error during client obj creation, ' + err.message)
            })
```

Stack Trace :
```
Error: All configured authentication methods failed
    at tryNextAuth (/Users/rrsingh/git/kafkamon/node_modules/ssh2/lib/client.js:376:17)
    at SSH2Stream.onUSERAUTH_FAILURE (/Users/rrsingh/git/kafkamon/node_modules/ssh2/lib/client.js:587:5)
    at emitTwo (events.js:100:13)
    at SSH2Stream.emit (events.js:185:7)
    at parsePacket (/Users/rrsingh/git/kafkamon/node_modules/ssh2-streams/lib/ssh.js:3923:10)
    at SSH2Stream._transform (/Users/rrsingh/git/kafkamon/node_modules/ssh2-streams/lib/ssh.js:667:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/Users/rrsingh/git/kafkamon/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:287:5)
    at SSH2Stream.Writable.write (_stream_writable.js:215:11)
    at Socket.ondata (_stream_readable.js:536:20)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:529:20)
```

**Comment by mscdex** [comment]
That's where it's emitted. Are you using the latest version?

**Comment by mscdex** [comment]
I also just tried it locally and the `'error'` event handler catches that error as expected.

**Comment by zer0Id0l** [comment]
I am using `"ssh2": "^0.5.4"`

**Comment by mscdex** [comment]
What does `npm ls ssh2` show though?

**Comment by zer0Id0l** [comment]
npm ls ssh2
└── ssh2@0.5.4

I verified it in node modules too.

**Comment by zer0Id0l** [comment]
I did a cleanup of my node module packages and tried again, it works now. Thanks for quick response.
