### ISSUE TITLE
properly create a new empty file

### ISSUE THREAD

**Issue by sfeher-paymentus** [mscdex/ssh2#553]
I'm trying to create a empty lock file:

sftp.open(remoteFile, flags, (err, fd) => {
                        if (err) {
                            reject(err);
                        } else {
                            resolve(fd);
                        }
                    });

The file gets created, however the fd coming back looks like this:
{
  "type": "Buffer",
  "data": [   0,    0,    0,    0  ]
}

so closing the file throws:
"Error: No such file
    at SFTPStream._transform (node_modules\\ssh2-streams\\lib\\sftp.js:405:27)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (node_modules\\ssh2-streams\\lib\\sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at SFTPStream.Writable.write (_stream_writable.js:241:11)
    at Channel.ondata (_stream_readable.js:557:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Channel.Readable.push (_stream_readable.js:136:10)
    at SSH2Stream.<anonymous> (node_modules\\ssh2\\lib\\Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:191:7)
    at parsePacket (node_modules\\ssh2-streams\\lib\\ssh.js:3439:10)"

Debugging through the code (ssh2-streams/lib/sftp.js)

line 412:
} else if (pktType === RESPONSE.HANDLE) {
              /*
                string     handle
              */
              handle = readString(buffer, 4, this, callback);
              if (handle === false)
                return;
              cb(undefined, handle);

this is the only code path dealing with reading the handle.

Any ideas? Thanks.

**Comment by mscdex** [comment]
What `flags` are you passing? It sounds like you may be opening for reading instead of writing?

**Comment by sfeher-paymentus** [comment]
const remoteLckFileDescr = await sftp.openFileAsync(remoteLckFile, 'wx');

**Comment by mscdex** [comment]
Does the path leading up to the file in `remoteFile` exist (e.g. /foo and /foo/bar exist for `remoteFile = '/foo/bar/baz.lock'`)?

**Comment by sfeher-paymentus** [comment]
yes, '/foo/bar/baz.lock' is created fine with proper permissions.

The script creates the file successfully and is able to delete it a few lines later: [pseudocode]
let fDescriptor = async sftp.open('/foo/bar/baz.lock', 'wx', ... // works fine creating the file
// async sftpClose(fDescriptor) fails with "Error: No such file"
async sftp.unlink('/foo/bar/baz.lock'); // works fine

**Comment by mscdex** [comment]
Ah ok, I missed the part about it happening during *close*. I'm not sure what's happening then as I've never heard of that problem before. FWIW the error comes directly from the server.

Is this an OpenSSH server or something else (you can see the server's ident string in the debug output when setting `debug: console.log` in the connection config object)?
