### ISSUE TITLE
Getting Permission denied

### ISSUE THREAD

**Issue by mohanen** [mscdex/ssh2#574]
Im using sftp-upload module 

      var sftpOptions = {
        host: ip,
        username: 'ubuntu',
        path: sourcePath,
        remoteDir: "/" +  destinationPath,
        privateKey: fs.readFileSync('misc/test.pem')
      };
      console.log(appStatus);

      var sftp = new Sftp(sftpOptions);
      sftp.on('error', function(err) {
          console.log("sftp-upload error".red);
          console.log(err);
          return callback(err, appStatus, null);
        })
        .on('connect', function() {
          console.log('\nsftp connected'.green);
        })
        .on('uploading', function(pgs) {
          console.log('\nsftp Uploading', pgs.file);
          console.log(pgs.percent + '% completed');
        })
        .on('completed', function() {
          console.log('\n sftp Upload Completed'.green);
          return callback(null, appStatus, ip)
        })
        .upload();

This used to work but now stopped working and  getting this error 

{ Error: Permission denied
    at SFTP._parse (/home/mohanen/Desktop/WebApp/node_modules/ssh2/lib/SFTP/SFTPv3.js:986:23)
    at ChannelStream.<anonymous> (/home/mohanen/Desktop/WebApp/node_modules/ssh2/lib/SFTP/SFTPv3.js:49:12)
    at emitOne (events.js:96:13)
    at ChannelStream.emit (events.js:188:7)
    at ChannelStream.emit (/home/mohanen/Desktop/WebApp/node_modules/ssh2/lib/Channel.js:640:12)
    at Parser.<anonymous> (/home/mohanen/Desktop/WebApp/node_modules/ssh2/lib/Channel.js:95:20)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser.parsePacket (/home/mohanen/Desktop/WebApp/node_modules/ssh2/lib/Parser.js:607:12)
    at Parser.execute (/home/mohanen/Desktop/WebApp/node_modules/ssh2/lib/Parser.js:249:14) type: 'PERMISSION_DENIED', lang: '' }

**Comment by mscdex** [comment]
I don't know about how the `sftp-upload` operates, but that error message comes directly, as-is from the server, so there isn't anymore I can add to help determine the cause.

**Comment by mohanen** [comment]
my bad , its due to the destination end permission issue .

By the way, why doing a sftp via ssh2 is very slow.

**Comment by mscdex** [comment]
@mohanen It shouldn't be. Again, I don't know about `sftp-upload` but using `sftp.fastPut()` via `ssh2` matches OpenSSH's sftp client speed last I checked (it uses parallel reads and writes).
