### ISSUE TITLE
fastGet 1200 files.

### ISSUE THREAD

**Issue by zone44** [mscdex/ssh2#630]
I have 1200 files to fastGet.
If I force stop my loop at 1022 files it works.
If I force stop my loop at 1023 files it crashes:

Error: Failure
    at SFTPStream._transform (/home/blx/test4/node_modules/ssh2-streams/lib/sftp.js:410:27)
    at SFTPStream.Transform._read (_stream_transform.js:186:10)
    at SFTPStream._read (/home/blx/test4/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at SFTPStream.Writable.write (_stream_writable.js:290:11)
    at Channel.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Channel.emit (events.js:211:7)

**Comment by mscdex** [comment]
Sounds like you might be running into some server-imposed limit. Perhaps the remote user you're logged in as has an open file descriptor limit set to 1023/1024? I'm inclined to believe this because that is the default on Ubuntu at least (`ulimit -n`).

**Comment by zone44** [comment]
You are right ! ulimit returns 1024. Do you think I should I raise this limit on remote or on local server ? or both ? Sorry, I'm a real linux noob.

**Comment by mscdex** [comment]
If you're in control of the server you can change the soft and hard limits for the user in /etc/security/limits.conf. If not, you will just need to create a queue and process your downloads using that instead to get a hold on the number of concurrent transfers.

**Comment by hktalent** [comment]
@zone44 
'''
1、require('async')
Controlling Concurrency thread
2、my mac os
ulimit -n 65535
'''
