### ISSUE TITLE
Error when trying to transfer file

### ISSUE THREAD

**Issue by sachin0903** [mscdex/ssh2#640]
Hi,

I am trying to transfer the file via sftp and keep on getting following error:
Exception has occurred: Error
Error: Failure
    at SFTPStream._transform (..\sftp-client\node_modules\ssh2-streams\lib\sftp.js:411:27)
    at SFTPStream.Transform._read (_stream_transform.js:186:10)
    at SFTPStream._read (..\sftp-client\node_modules\ssh2-streams\lib\sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:385:12)
    at writeOrBuffer (_stream_writable.js:371:5)
    at SFTPStream.Writable.write (_stream_writable.js:288:11)
    at Channel.ondata (_stream_readable.js:642:20)
    at emitOne (events.js:115:13)
    at Channel.emit (events.js:210:7)

Here is the server and client code:
Server:
=================
```
var fs = require('fs');
 
var ssh2 = require('ssh2');
var OPEN_MODE = ssh2.SFTP_OPEN_MODE;
var STATUS_CODE = ssh2.SFTP_STATUS_CODE;
 
new ssh2.Server({
  hostKeys: [fs.readFileSync('./keys/host_rsa/id_rsa')]
}, function(client) {
  console.log('Client connected!');
 
  client.on('authentication', function(ctx) {
    if (ctx.method === 'password'
        && ctx.username === 'foo'
        && ctx.password === 'bar')
      ctx.accept();
    else
      ctx.reject();
  }).on('ready', function() {
    console.log('Client authenticated!');
 
    client.on('session', function(accept, reject) {
      var session = accept();
      session.on('sftp', function(accept, reject) {
        console.log('Client SFTP session');
        var openFiles = {};
        var handleCount = 0;
        var sftpStream = accept();
        let listSent = false;
        let names = [];
        sftpStream.on('OPEN', function(reqid, filename, flags, attrs) {
          // only allow opening /tmp/foo.txt for writing 
          if (filename !== '/tmp/foo.txt' || !(flags & OPEN_MODE.WRITE))
            return sftpStream.status(reqid, STATUS_CODE.FAILURE);
          // create a fake handle to return to the client, this could easily 
          // be a real file descriptor number for example if actually opening 
          // the file on the disk 
          var handle = new Buffer(4);
          openFiles[handleCount] = true;
          handle.writeUInt32BE(handleCount++, 0, true);
          sftpStream.handle(reqid, handle);
          console.log('Opening file for write')
        }).on('WRITE', function(reqid, handle, offset, data) {
          if (handle.length !== 4 || !openFiles[handle.readUInt32BE(0, true)])
            return sftpStream.status(reqid, STATUS_CODE.FAILURE);
          // fake the write 
          sftpStream.status(reqid, STATUS_CODE.OK);
          var inspected = require('util').inspect(data);
          console.log('Write to file at offset %d: %s', offset, inspected);
        }).on('CLOSE', function(reqid, handle) {
          var fnum;
          if (handle.length !== 4 || !openFiles[(fnum = handle.readUInt32BE(0, true))])
            return sftpStream.status(reqid, STATUS_CODE.FAILURE);
          delete openFiles[fnum];
          sftpStream.status(reqid, STATUS_CODE.OK);
          console.log('Closing file');
        }).on('OPENDIR',function(reqID,path)
          {
            var handle = new Buffer(4);
            handle.writeUInt32BE(handleCount++, 0, true);
            sftpStream.handle(reqID,handle);
            console.log(handle);
            console.log('Opening Read Directory for  --'+path);
            console.log(reqID);
            console.log(path);  

          }).on('READDIR',function(reqID,handle)
          {
           console.log('Read request')
           console.log(reqID);
            if(handle.length!==4)
            return sftpStream.status(reqID, STATUS_CODE.FAILURE,'There was failure')
            
                sftpStream.status(reqID, STATUS_CODE.OK,'Everything ok')
                sftpStream.name(reqID,names);     
              
              
          });
      });
    });
  }).on('end', function() {
    console.log('Client disconnected');
  });
}).listen(2323, '127.0.0.1', function() {
  console.log('Listening on port ' + this.address().port);
});
```

Client:
===============
```
conn.on('ready', function() {
  console.log('Client :: ready');
  conn.sftp(function(err, sftp) {
    if (err) throw err;
    var fs = require('fs');
        sftp.fastPut('c:\\sftp\\myRemoteFile.txt', '/myRemoteFile1.txt', function(err) {
            if(err){
                throw(err);
            } else {
                console.log('Done');
            }
        });
       
      });
}).connect({
  host: '127.0.0.1',
  port: 2323,
  username: 'foo',
  password: 'bar'
});
```

Can you please help.

**Comment by mscdex** [comment]
The example code you copied for the server is just that, it's an example, not a fully-fledged SFTP server. In this case the server is looking for a particular file name and failing otherwise. Also, the server implementation here does not actually write any file data sent to it.

**Comment by sachin0903** [comment]
Thanks a lot for your response.
do you have any example which can help me setting up sftp mock server to test functionality on my local environment.

**Comment by sachin0903** [comment]
Besides my earlier comment as you mentioned that code will just allow foo.txt to be processed, files with other name would be discarded. I even tried directory listing
