### ISSUE TITLE
Overwrite files with fastPut?

### ISSUE THREAD

**Issue by arkanos** [mscdex/ssh2#655]
Hi guys,

I currently have this code that works like a charm when uploading files:

```
var conn = new Client();
fs.readdir('./MP3', (err, files) =>
{
	if(err) throw err;
	conn.on('ready', () =>
	{
		conn.sftp((err, sftp) =>
		{
			async.eachLimit(files, 1, (file, cbFiles) =>
			{
				if(err) throw err;
				sftp.fastPut('./MP3/' + file, '/audios/' + file, (err) =>
				{
					console.log('/audios/' + file);
					if(err) throw err;
					fs.unlink('./MP3/' + file, (err) =>
					{
						if(err)
						{
							cbFiles(err);
						}
						cbFiles();
					});
				});
			}, (err) => {
				if(err)
				{
					log(err);
				} else {
					log('All calls uploaded.');
				}
				conn.close();
			});
		});
	})
	.on('error', (err) =>
	{
		console.log(err);
	})
	.connect(sftpOptions);
});
```

But when a file has been already uploaded and I try to upload a new one with the same name, I get the following exception:

```
Error: Permission denied
    at SFTPStream._transform (C:\Users\ruben.deig\Desktop\CS-01\playvox-calls\node_modules\ssh2-streams\lib\sftp.js:410:27)
    at SFTPStream.Transform._read (_stream_transform.js:186:10)
    at SFTPStream._read (C:\Users\ruben.deig\Desktop\CS-01\playvox-calls\node_modules\ssh2-streams\lib\sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at SFTPStream.Writable.write (_stream_writable.js:290:11)
    at Channel.ondata (_stream_readable.js:642:20)
    at emitOne (events.js:115:13)
    at Channel.emit (events.js:210:7)
```

I pressume, based on the behavior I can see on Filezilla client, that I get this error because there's a file already with that name and it asks me permission to overwrite the file. If that's the case, how can I force the file to be overwritten? I have the proper permissions in the sftp server.

Thanks

**Comment by mscdex** [comment]
The best you can do in that situation (although it's subject to race conditions) is to check for the destination file's existence on such an error. Those kinds of errors are sent by the server and there is no way for `ssh2` to know that it was "Permission denied" because the file exists and not because of an actual file/directory permissions issue.
