### ISSUE TITLE
failure at multiple downloads

### ISSUE THREAD

**Issue by neverlmore** [mscdex/ssh2#663]
When i'm trying to connect to a server and recursively list all the sub directories, checking for each one. if not a directory download that path.
the issue is, when am checking a directory with huge subdirectories(8-16) or files(20k)
i would receive this failure after trying to passing 2-3k files.
avg file size is (300kb). I thought it might be buffer related issue so i tried minimizing the number of concurrent download to 16 and chunk size to 32byte but didnt help at all

```
function main(path, sftp) {
        isDir(path, sftp).then(function (IsDir) {
            if (IsDir) {
                listDir(path, sftp).then(dir => {
                    dir.forEach(function (dir) {
                        main(dir, sftp);
                    })
                })
            }
            else {
                let folderName = fileName[0].match(/A.{13}/);
                let file = mainFolder + '/' + folderName[0] + fileName;
                sftp.stat(path, function (err, stat) {
                    overAllSize += stat.size;
                    if (err) console.log(err);
                });
                console.log(counter++, 'files', overAllSize / 1073741824, 'GB');
                createFolder(folderName[0])
                download(sftp, path, file, folderName[0])
            }
        });
    }

function download(sftp, remotePath, localPath) {
        sftp.fastGet(remotePath, localPath, {
            chunk: 163840, concurrency: 1024, step: function (totalTrans, chunk, total) {
                transferredSize += chunk;
                console.log(transferredSize / 1048576, 'MB transferred');
                if (transferredSize === overAllSize) {
                    console.log((Date.now() - timeNow) / 1000, 'Seconds to finish');
                    conn.end()
                }
            }
        }, function (err) {
            console.log( err);
        })
    }

    function listDir(path, sftp) {
        return new Promise(resolve => {
            sftp.readdir(path, function (err, dir) {
                resolve(dir)
            })
        }).then(function (dir) {
            return new Promise(resolve => {
                var paths = [];
                dir.forEach(function (item) {
                    paths.push(path + '/' + item.filename)
                });
                resolve(paths)
            })
        })
    }

```
```
{ Error: Failure
at SFTPStream._transform (/Users/Murad/Desktop/simon-hadoop-backend/node_modules/ssh2-streams/lib/sftp.js:410:27)
at SFTPStream.Transform._read (_stream_transform.js:185:10)
at SFTPStream._read (/Users/Murad/Desktop/backend/node_modules/ssh2-streams/lib/sftp.js:181:15)
at SFTPStream.Transform._write (_stream_transform.js:173:12)
at doWrite (_stream_writable.js:388:12)
at writeOrBuffer (_stream_writable.js:374:5)
at SFTPStream.Writable.write (_stream_writable.js:291:11)
at Channel.ondata (_stream_readable.js:642:20)
at Channel.emit (events.js:159:13)
at addChunk (_stream_readable.js:265:12) code: 4, lang: '' }

Process finished with exit code 130 (interrupted by signal 2: SIGINT)
```

**Comment by neverlmore** [comment]
since the code is async is there a limit to how many download

**Comment by neverlmore** [comment]
Solved! 
Making a queue and downloading no more than 20 files per second, seems to solve this issue.
