### ISSUE TITLE
ssh2 throwing with "TypeError: Cannot read property 'state' of undefined"

### ISSUE THREAD

**Issue by soichih** [mscdex/ssh2#667]
I started using conn.close() more often lately, and I see following exception time-to-time (and my app is crashing)

```
TypeError: Cannot read property 'state' of undefined
    at IncomingMessage.Channel.close (/app/node_modules/ssh2/lib/Channel.js:307:15)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at abortIncoming (_http_server.js:282:11)
    at Socket.socketOnEnd (_http_server.js:434:7)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

I am not sure if this an issue with ssh2, or if I am doing something wrong (maybe my app ends up trying to close the connection that's already closed, etc?)

**Comment by mscdex** [comment]
If this is still an issue with the latest `ssh2`/`ssh2-streams` can you post a simple code example that reproduces the issue?

**Comment by soichih** [comment]
I haven't seen this problem happening lately.
