### ISSUE TITLE
Unable to built connection to a remote sftp when i run code on Heroku environment.

### ISSUE THREAD

**Issue by vishavjeet** [mscdex/ssh2#679]
hi, since last update my code stopped working on Heroku environment. but working fine on my local Linux server development. it is showing the following error.

DEBUG: Local ident: 'SSH-2.0-ssh2js0.1.20'
DEBUG: Client: Trying 205.211.164.97 on port 24 ...
DEBUG: Client: Connected
{ Error: Timed out while waiting for handshake
at Timeout._onTimeout (/app/node_modules/ssh2/lib/client.js:687:19)
at ontimeout (timers.js:482:11)
at tryOnTimeout (timers.js:317:5)
at Timer.listOnTimeout (timers.js:277:5) level: 'client-timeout' }

**Comment by mscdex** [comment]
Whatever host you're trying to connect to is not sending anything after the TCP connection is made.

**Comment by vishavjeet** [comment]
If I am running the same code other than Heroku dyno (like local Linux development server or windows nodejs app on my local windows machine) it works fine for the same host. and the confusing thing for me is this code was working on Heroku dyno also up until 15 March. I have contacted Heroku support and they told they use the different file system (ephemeral filesystem). so can not generate keys on there dyno and store like typical Linux server. I don't know where exactly is the issue. any help would be much appreciated.

Thanks

**Comment by mscdex** [comment]
There's not much more I can really tell you. If the server is not sending anything at all, this module can't do anything. Perhaps there is some firewall or some other software blocking the network traffic? I have no idea. If it works everywhere else but Heroku, then you will need to escalate the issue with them.
