### ISSUE TITLE
Cannot `forwardIn` 2 connections on same server with same port

### ISSUE THREAD

**Issue by wibimaster** [mscdex/ssh2#691]
Hi, 
I thought that `forwardIn` was the same as "ssh -R" ; but I can do a `ssh -R a.mydomain.com` on port 8000 and a `ssh -R b.mydomain.com on port 8000`, but it fails when I try with `forwardIn` :

```javascript
var Client = require('ssh2').Client;
var net = require('net');

var serverCredentials = {
  // [...]
};
var forwards = [
  {
    distant: {
      host: 'a.domain.com',
      port: 8080
    },
    local: {
      host: 'test1.tld',
      port: 80
    }
  },
  {
    distant: {
      host: 'b.domain.com',
      port: 8080
    },
    local: {
      host: 'test2.tld',
      port: 80
    }
  }
];

let connection = new Client();
connection.connect(serverCredentials);

for (let idx in forwards) {
  let conf = forwards[idx];
  connection
    .on('ready', function() {
      console.log('Client :: ready');
      connection.forwardIn(conf.distant.host, conf.distant.port, function (error) {
        if (error) throw error;
        console.log('Listening for connections on server '+conf.distant.host+' on port '+conf.distant.port);
      });
    })
    .on('tcp connection', function(info, accept, reject) {
      let stream = accept();
      stream.pause()
      socket = net.connect(conf.local.port, conf.local.host, function () {
        stream.pipe(socket);
        socket.pipe(stream);
        stream.resume();
      });
    });
}

```

The output is :

```shell
Client :: ready
Client :: ready
Listening for connections on server a.domain.com on port 8080
/home/me/index.js:44
        if (error) throw error;
                   ^

Error: Unable to bind to b.domain.com:8080
    at /home/me/node_ssh/node_modules/ssh2/lib/client.js:941:21
    at SSH2Stream.<anonymous> (/home/me/node_modules/ssh2/lib/client.js:637:24)
    at emitNone (events.js:106:13)
    at SSH2Stream.emit (events.js:208:7)
    at parsePacket (/home/me/node_ssh/node_modules/ssh2-streams/lib/ssh.js:4006:10)
    at SSH2Stream._transform (/home/me/node_ssh/node_modules/ssh2-streams/lib/ssh.js:671:13)
    at SSH2Stream.Transform._read (_stream_transform.js:186:10)
    at SSH2Stream._read (/home/me/node_ssh/node_modules/ssh2-streams/lib/ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:397:12)
```

Is there a way to achieve this ?

Thanks !

**Comment by mscdex** [comment]
I'm assuming `a.domain.com` and `b.domain.com` resolve to different IP addresses on the remote server?

**Comment by wibimaster** [comment]
My bad, I never seen that if silently fail.
Not really silently, but it just show a little warning, and after that all MOTD appears :/

Thanks !
