### ISSUE TITLE
Error: Unknown message digest in Node version 10.0.1 but not 8.11.3

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [mscdex/ssh2#720]
The short is got a new workstation and forgot to check which version of node the servers are running. Ran into the below issue on my workstaion running node 10.0.1. Though it might be a dependency issue, after testing it appears to be an issue related to a change in node. Not sure if this is a bug in node itself or ssh2 running on Node 10.0.1. For now going to lock the project at Node 8.11.3. Let me know if you need anymore info or if I should open an issue with the node project. If I have some time I'll try and dig deeper into the problem. I'd really like to narrow down the node version that caused this break.

BTW, just want to add awesome work! We have been hammering ssh2 both client and server with 1000's of connections per day.
```
this.connection = new SSHClient()
...
// this is what the ssh config object looks like
/*
ssh = {
      "username": "****",
      "password": "***",
      "host": "****-proxy",
      "port": 22005
      "algorithms": {
        "serverHostKey": [
          "ssh-dss"
        ]
      }
    }
*/
this.connection.connect(ssh)

Error: Unknown message digest
    at new Verify (internal/crypto/sig.js:98:16)
    at Object.createVerify (crypto.js:133:10)
    at onKEXDH_REPLY (C:\Users\Michael Hobbs\WebstormProjects\sshim.js\node_modules\ssh2-streams\lib\ssh.js:2879:25)
    at SSH2Stream.<anonymous> (C:\Users\Michael Hobbs\WebstormProjects\sshim.js\node_modules\ssh2-streams\lib\ssh.js:217:45)
    at SSH2Stream.emit (events.js:182:13)
    at SSH2Stream.EventEmitter.emit (domain.js:442:20)
    at parse_KEXDH_REPLY (C:\Users\Michael Hobbs\WebstormProjects\sshim.js\node_modules\ssh2-streams\lib\ssh.js:4221:8)
    at parse_KEX (C:\Users\Michael Hobbs\WebstormProjects\sshim.js\node_modules\ssh2-streams\lib\ssh.js:4183:14)
    at parsePacket (C:\Users\Michael Hobbs\WebstormProjects\sshim.js\node_modules\ssh2-streams\lib\ssh.js:4018:12)
    at SSH2Stream._transform (C:\Users\Michael Hobbs\WebstormProjects\sshim.js\node_modules\ssh2-streams\lib\ssh.js:671:13)
```

**Comment by MichaelLeeHobbs** [comment]
Disregard this if you want. The core of the issue was the workstation setup script was missing ```-lts``` on ```choco install nodejs-lts``` I just assumed that the version I had was lts but when I went to downgrade I found out otherwise. 😳

**Comment by mscdex** [comment]
You need to upgrade your copy of `ssh2`/`ssh2-streams`.

**Comment by MichaelLeeHobbs** [comment]
This fixed the issue and passed all test! Disappointingly, I checked everything but this before I posted this issue. Thanks for the help. I'll make sure next time I check the project's dependencies **ALSO** before opening an issue.
