### ISSUE TITLE
Fails to work with Windows 10 built-in ssh

### ISSUE THREAD

**Issue by liximomo** [mscdex/ssh2#775]
[Since Windows 1809 update, Windows has a built-in Service for SSH agent.](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse),  I can't connect to my server no matter which key format (PuTTY, SSH2, SSH.COM) is used and with or without password on the private key.

```
[debug] Local ident: 'SSH-2.0-ssh2js0.3.1'
[debug] Client: Trying domain.net on port 22 ...
[debug] Client: Connected
[debug] Remote ident: 'SSH-2.0-OpenSSH_6.7p1 Debian-5+deb8u7'
[debug] Outgoing: Writing KEXINIT
[debug] DEBUG: Comparing KEXINITs ...
[debug] (local) KEX algorithms: ecdh-sha2-nistp521
[debug] (remote) KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
[debug] KEX algorithm: ecdh-sha2-nistp521
[debug] (local) Host key formats: ssh-rsa,ecdsa-sha2-nistp521
[debug] (remote) Host key formats: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ssh-ed25519
[debug] Host key format: ssh-rsa
[debug] (local) Client->Server ciphers: aes256-gcm,aes256-gcm@openssh.com
[debug] (remote) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com
[debug] Client->Server Cipher: aes256-gcm@openssh.com
[debug] (local) Server->Client ciphers: aes256-gcm,aes256-gcm@openssh.com
[debug] (remote) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com
[debug] Server->Client Cipher: aes256-gcm@openssh.com
[debug] (local) Client->Server HMAC algorithms: hmac-sha2-512
[debug] (remote) Client->Server HMAC algorithms: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[debug] Client->Server HMAC algorithm: hmac-sha2-512
[debug] (local) Server->Client HMAC algorithms: hmac-sha2-512
[debug] (remote) Server->Client HMAC algorithms: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[debug] Server->Client HMAC algorithm: hmac-sha2-512
[debug] (local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
[debug] (remote) Client->Server compression algorithms: none,zlib@openssh.com
[debug] Client->Server compression algorithm: none
[debug] (local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
[debug] (remote) Server->Client compression algorithms: none,zlib@openssh.com
[debug] Server->Client compression algorithm: none
[debug] Outgoing: Writing KEXECDH_INIT
[debug] DEBUG: Checking host key format
[debug] DEBUG: Checking signature format
[debug] DEBUG: Verifying host fingerprint
[debug] DEBUG: Host accepted by default (no verification)
[debug] DEBUG: Verifying signature
[debug] Outgoing: Writing NEWKEYS
[debug] Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
[debug] Outgoing: Writing DISCONNECT (BY_APPLICATION)
[error] Error: [troublezone.net]: Timed out while waiting for handshake
    at Client.module.exports._connectSSHClient.e.on.on.e
    at Client.emit (events.js:187:15)
    at Timeout._onTimeout
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
```

**Comment by mscdex** [comment]
Can you try with the latest `ssh2`?

**Comment by liximomo** [comment]
Thank you. It works.
