### ISSUE TITLE
The requested operation cannot be performed because there is a file transfer in progress.

### ISSUE THREAD

**Issue by bijoythomas** [mscdex/ssh2#791]
I'm running into a strange issue with one particular SFTP server. Any attempt to send more than one file on a single connection fails with the error message:

**The requested operation cannot be performed because there is a file transfer in progress.**

I do not see this issue with any of the other SFTP servers we use.

I am sending multiple files like below. Does code below send the files sequentially or in parallel on the same connection? 

```
conn.sftp(function(err, sftp) {
  let numberOfFiles = fileNames.length
  let numberOfFilesSent = 0 // keep track so we can end the connection
  for (var i = 0; i < numberOfFiles; i++) {
    let readStream = fs.createReadStream(fileNames[i])
    let writeStream = sftp.createWriteStream(outputFileNames[i])
    readStream.pipe(writeStream)
    writeStream.on('close', function() {
      numberOfFilesSent++
      if (numberOfFilesSent === numberOfFiles) {
        conn.end()
      }
    })
  }
}
```

**Comment by bijoythomas** [comment]
The debug output is below. I have taken out some of the lines in the middle for brevity.

```
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.1'
DEBUG: Client: Trying *********** on port 22 ...
DEBUG: Client: Connected
DEBUG: Parser: IN_INIT
DEBUG: Parser: IN_GREETING
DEBUG: Parser: IN_HEADER
DEBUG: Remote ident: 'SSH-2.0-SSHD'
DEBUG: Outgoing: Writing KEXINIT
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:540,padLen:8,remainLen:536
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXINIT
DEBUG: Comparing KEXINITs ...
DEBUG: (local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
DEBUG: (remote) KEX algorithms: diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256
DEBUG: KEX algorithm: diffie-hellman-group-exchange-sha256
DEBUG: (local) Host key formats: ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
DEBUG: (remote) Host key formats: ssh-rsa
DEBUG: Host key format: ssh-rsa
........ some more lines-----
DEBUG[SFTP]: Outgoing: Writing OPEN
DEBUG: Outgoing: Writing CHANNEL_DATA (0)
DEBUG[SFTP]: Outgoing: Writing OPEN
DEBUG: Outgoing: Writing CHANNEL_DATA (0)
DEBUG[SFTP]: Outgoing: Writing OPEN
DEBUG: Outgoing: Writing CHANNEL_DATA (0)
DEBUG[SFTP]: Outgoing: Writing OPEN
DEBUG: Outgoing: Writing CHANNEL_DATA (0)
DEBUG[SFTP]: Outgoing: Writing OPEN
DEBUG: Outgoing: Writing CHANNEL_DATA (0)
DEBUG[SFTP]: Outgoing: Writing OPEN
DEBUG: Outgoing: Writing CHANNEL_DATA (0)
DEBUG[SFTP]: Outgoing: Writing OPEN
DEBUG: Outgoing: Writing CHANNEL_DATA (0)
DEBUG[SFTP]: Outgoing: Writing OPEN
DEBUG: Outgoing: Writing CHANNEL_DATA (0)
DEBUG[SFTP]: Outgoing: Writing OPEN
DEBUG: Outgoing: Writing CHANNEL_DATA (0)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:28,padLen:4,remainLen:16
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
DEBUG[SFTP]: Parser: Response: HANDLE
DEBUG[SFTP]: Outgoing: Writing FSETSTAT
DEBUG: Outgoing: Writing CHANNEL_DATA (0)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:124,padLen:4,remainLen:112
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
DEBUG[SFTP]: Parser: Response: STATUS
events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: The requested operation cannot be performed because there is a file transfer in progress.
    at SFTPStream._transform (/var/www/vhosts/mvp/releases/current/node_modules/ssh2-streams/lib/sftp.js:412:27)
    at SFTPStream.Transform._read (_stream_transform.js:186:10)
    at SFTPStream._read (/var/www/vhosts/mvp/releases/current/node_modules/ssh2-streams/lib/sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at SFTPStream.Writable.write (_stream_writable.js:290:11)
    at Channel.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Channel.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Channel.Readable.push (_stream_readable.js:208:10)
    at SSH2Stream.<anonymous> (/var/www/vhosts/mvp/releases/current/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:116:13)
    at SSH2Stream.emit (events.js:211:7)
    at parsePacket (/var/www/vhosts/mvp/releases/current/node_modules/ssh2-streams/lib/ssh.js:3445:10)
    at SSH2Stream._transform (/var/www/vhosts/mvp/releases/current/node_modules/ssh2-streams/lib/ssh.js:671:13)
    at SSH2Stream.Transform._read (_stream_transform.js:186:10)
    at SSH2Stream._read (/var/www/vhosts/mvp/releases/current/node_modules/ssh2-streams/lib/ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:397:12)
```

Is the connection somehow being closed while the files are being transferred? Is there any way to see what operation was interfering with the transfer?

**Comment by mscdex** [comment]
> I am sending multiple files like below. Does code below send the files sequentially or in parallel on the same connection?

Parallel. Different servers may impose different limits. Also since you're upload files from disk, using `sftp.fastPut()` should be faster as it can send multiple file chunks at a time, compared to streams which send a chunk, wait for response, send next chunk, etc.

**Comment by bijoythomas** [comment]
Thank you for the response!

Yes, the process was exiting by default. Your `'error'` handler suggestion will be very helpful! 

 How does one configure a server to limit the number of transfers per connection? I've tried searching around for any material related to this but have not found anything so far.

**Comment by mscdex** [comment]
> How does one configure a server to limit the number of transfers per connection? I've tried searching around for any material related to this but have not found anything so far.

That's entirely dependent upon the server software/implementation.

> And how does one simulate the multiple transfers per connection from the regular `sftp` command. I tried `mput` and `put` with wildcards matching multiple files and they all seem to be transferred in sequence.

I don't believe the OpenSSH SFTP client has this ability.

**Comment by bijoythomas** [comment]
Ok. I'll dig around some more and see if I can find any more information. Thank you for your help and this useful module!
