### ISSUE TITLE
When I try to use ".connect" again, It doesn't work

### ISSUE THREAD

**Issue by Kisarigi** [mscdex/ssh2#796]
Here is my question, Only on server A I can connect server B. and both of server A and B I can only use ssh to connect.

```
//connect Server A 
conn.connect({
    host: '132.96.238.xxx',
    readyTimeout: 10000,
    username: 'xxx',
    password: 'xxx',
    algorithms:
        {
            kex: ['diffie-hellman-group1-sha1'],
            cipher: ['3des-cbc'],
        }
})
//on Server A try to connect Server B
    conn.connect({
    host: '1.37.28.xxx',
    readyTimeout: 20000,
    username: 'xxx',
    password: 'xxx',
    algorithms:
        {
            kex: ['diffie-hellman-group1-sha1'],
            cipher: ['3des-cbc'],
        }
})
```
The second ".connect" will show "Error: Timed out while waiting for handshake".

Well, I try another way , change the code to this :

```
//connect Server A 
conn.connect({
    host: '132.96.238.xxx',
    readyTimeout: 10000,
    username: 'xxx',
    password: 'xxx',
    algorithms:
        {
            kex: ['diffie-hellman-group1-sha1'],
            cipher: ['3des-cbc'],
        }
})

//on Server A try to connect Server B

 conn.shell(function(err, stream) {
         if (err) {
          throw err
         }
        stream.write('ssh  -c  3des-cbc   xxxx@1.37.28.xxx') 
        let data='';
        stream.on('data', function(chunk) {
            data += chunk;
        });
     
        stream.on('end',function(){
            console.log(data+'');
        });
        stream.on('error', function(err){
            console.log(err.stack);
        });
        stream.stderr.on('data', (chunk) => {
            console.log('err:  '+chunk);
        });


})

```
It really work, I connect Server B successful, but another question comes, I want to write many "stream.write("do some thing")"  on Server B, and I can't know when a "stream.write()"  be done.
I just want to get the whole return data in one time by use "stream.on('end')", and It didn't work.
"end event" seems never be emitted.

So I change the code to this , use "conn.exec()" instead of "conn.shell()"
```
//connect Server A 
conn.connect({
    host: '132.96.238.xxx',
    readyTimeout: 10000,
    username: 'xxx',
    password: 'xxx',
    algorithms:
        {
            kex: ['diffie-hellman-group1-sha1'],
            cipher: ['3des-cbc'],
        }
})
//on Server A try to connect Server B
conn.exec('ssh -T -c  3des-cbc  xxxxx@1.37.28.xxx,function (err,stream) {
    stream.on('end',function(){
            console.log('over');
        });
   stream.stderr.on('data', (chunk) => {
            console.log('err:  '+chunk);
        });
})
```
It failed to connect Server B with this : 

> err:  Host key verification failed.
> over
> 
The "end event" was emitted, but I connect Server B failed.

There are two questions.
1.Why the third code can not connect Server B , but the second code is OK?
2.When I use "conn.shell()", Can I know each "stream.write()" when it will be done? I want to get the whole return data in one time. Now I set a timer to use "stream.read()" to get the whole data instead of using "stream.on("data")". It's obviously not a good idea .

**Comment by mscdex** [comment]
If you're trying to connection hop, there's an example of doing that in the readme using just `ssh2`.

`.shell()` is designed for *interactive* sessions and not really for programmatic command execution. `.exec()` is designed for that kind of task because you have more control over the execution: you get only the command output and you know when there is no more output, you get the command's exit status code or signal, and `.exec()` is usually more lightweight on the server side.

Also, you didn't see `'end'` in the second code example because the interactive shell session was never ended. To do that you typically need to either need to send `'exit\n'` to the shell and it will close the session or you can abruptly call `stream.end()` to signal to the server that no more input will be sent, which should cause the session to end (otherwise you can use `stream.close()`).

**Comment by Kisarigi** [comment]
@mscdex 
Thank you ! 
After watching the hopping example in readme , I changed my code and It really worked.
But there is still a little question about how to consume data in right way. 
While using `.exec()` ,
```
 conn2.exec('dis cur interface g0/2/0', function(err, stream) {
            let data='';
            stream.on('data', function(chunk) {
              data += chunk;
              if(chunk.indexOf('return')!=-1){
                 console.log(data+'');
              }
           });
})
```
Like this, to get a whole data , the data  output is line by line, so I set a flag to judge it and concat these to a whole one.
Do we have an easy way to know when there is no more output?
I tried to use `stream.on('end')`, It didn't work.

```
conn2.exec('dis cur interface g0/2/0', function(err, stream) {
          let data='';
          stream.on('data', function(chunk) {
            data += chunk;
         });
         stream.on('end',function(){
           console.log(data)     //no output
         })
})
```
When I use `.exec()`, end event was not emitted.

**Comment by mscdex** [comment]
If whatever command you're executing is listening for input, you might have to close stdin by calling `stream.end()`.

You can also add `'close'` and `'exit'` event handlers to ensure those are getting called when the command finishes. Those events will received the exit code or signal if the command exited due to a signal. The difference between those two events is that `'close'` is guaranteed to be emitted when there will be no more `'data'` events, just like with node's child processes.

**Comment by Kisarigi** [comment]
@mscdex
I found that whatever command I input on Server B, It won't emit `end` or `close` event. Then I changed the code to this:
```
conn2.on('ready', function() {
    conn2.exec('display clock', function(err, stream) {
        let data='';
        if (err) {
            throw err;
        }
        stream.on('data', function(chunk) {
            data += chunk;
            console.log(chunk+'')
        });
        stream.on('pause',function(){
            console.log('stop');
        });
        stream.on('end',function(){
            console.log('end');
            console.log(data+'');
        });
        stream.on('close',function(){
            console.log('close')
            console.log(data+'');
        })
        stream.on('error', function(err){
            console.log(err.stack);
        });
        stream.stderr.on('data', (chunk) => {
            console.log('err:  '+chunk);
        });
        stream.end(); 
    });
});
```
   the program crashed with this:
```
Info: Please change the original password.

The password needs to be changed. Change now? [Y/N]: 
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: The connection is closed by SSH server

    at onDISCONNECT (/Users/kisarigi/WebstormProjects/untitled1/node_modules/_ssh2-streams@0.4.4@ssh2-streams/lib/ssh.js:2217:15)
    at SSH2Stream.<anonymous> (/Users/kisarigi/WebstormProjects/untitled1/node_modules/_ssh2-streams@0.4.4@ssh2-streams/lib/ssh.js:205:5)
    at SSH2Stream.emit (events.js:189:13)
    at parsePacket (/Users/kisarigi/WebstormProjects/untitled1/node_modules/_ssh2-streams@0.4.4@ssh2-streams/lib/ssh.js:3552:10)
    at SSH2Stream._transform (/Users/kisarigi/WebstormProjects/untitled1/node_modules/_ssh2-streams@0.4.4@ssh2-streams/lib/ssh.js:694:13)
    at SSH2Stream.Transform._read (_stream_transform.js:190:10)
    at SSH2Stream._read (/Users/kisarigi/WebstormProjects/untitled1/node_modules/_ssh2-streams@0.4.4@ssh2-streams/lib/ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at SSH2Stream.Writable.write (_stream_writable.js:294:11)
    at Channel.ondata (_stream_readable.js:667:20)
    at Channel.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Channel.Readable.push (_stream_readable.js:220:10)
    at SSH2Stream.<anonymous> (/Users/kisarigi/WebstormProjects/untitled1/node_modules/_ssh2@0.8.4@ssh2/lib/Channel.js:167:15)
    at SSH2Stream.emit (events.js:189:13)
    at parsePacket (/Users/kisarigi/WebstormProjects/untitled1/node_modules/_ssh2-streams@0.4.4@ssh2-streams/lib/ssh.js:3248:10)
    at SSH2Stream._transform (/Users/kisarigi/WebstormProjects/untitled1/node_modules/_ssh2-streams@0.4.4@ssh2-streams/lib/ssh.js:694:13)
    at SSH2Stream.Transform._read (_stream_transform.js:190:10)
    at SSH2Stream._read (/Users/kisarigi/WebstormProjects/untitled1/node_modules/_ssh2-streams@0.4.4@ssh2-streams/lib/ssh.js:253:15)
Emitted 'error' event at:
    at SSH2Stream.<anonymous> (/Users/kisarigi/WebstormProjects/untitled1/node_modules/_ssh2@0.8.4@ssh2/lib/client.js:358:10)
    at SSH2Stream.emit (events.js:194:15)
    at onDISCONNECT (/Users/kisarigi/WebstormProjects/untitled1/node_modules/_ssh2-streams@0.4.4@ssh2-streams/lib/ssh.js:2219:10)
    at SSH2Stream.<anonymous> (/Users/kisarigi/WebstormProjects/untitled1/node_modules/_ssh2-streams@0.4.4@ssh2-streams/lib/ssh.js:205:5)
    [... lines matching original stack trace ...]
    at SSH2Stream._transform (/Users/kisarigi/WebstormProjects/untitled1/node_modules/_ssh2-streams@0.4.4@ssh2-streams/lib/ssh.js:694:13)

Process finished with exit code 1
```
Then I use `conn2.end()` instead of 'stream.end()',  it emitted `end` and `close` successful, but        
 no output data because it just break off.
And I found that in Server A, it can emit `close` or `end` rightly while using `exec`.
Is there something wrong with Server B? Server A is just a jump server and Server B is a Huawei transmission device.

**Comment by mscdex** [comment]
Well that's most likely why the command never finishes, it appears to be prompting for input. So you'll need to `stream.write()` your input for the prompt (adding a `'\n'` at the end to simulate pressing the Enter key).

**Comment by Kisarigi** [comment]
@mscdex 
in the Server B(Huawei device), when I use `.exec('do anything')`, it won't emit end event. 
when I use '.shell()', the code is this:
```
conn4.shell(function(err, stream) {
        let data='';
        if (err) {
            throw err;
        }
        stream.on('data', function(chunk) {
            data += chunk;
            console.log(chunk+'')
        });
        stream.on('end',function(){
            console.log('end');
        });
        stream.on('close',function(){
            console.log('close')
        })
        stream.on('error', function(err){
            console.log(err.stack);
        });
        stream.stderr.on('data', (chunk) => {
            console.log('err:  '+chunk);
        });
        stream.write('dis cur  \n');
        stream.write('display clock \n');
        stream.end();
    });
```
       The `conn4.on('error')` was emitted and  
```
        stream.write('dis cur  \n');
        stream.write('display clock \n');

```
     those two line were not executed.
     the console showed:
```
Info: The max number of VTY users is 20, and the number
      of current VTY users on line is 1.

      The current login time is 2019-07-11 15:08:22+08:00.

Info:  First time access.  Failed: 0



<b2-s-gdgz-sj>
d
i
s
 
c
u
r
 
 
{ Error: The connection is closed by SSH server

    at onDISCONNECT (/Users/kisarigi/WebstormProjects/untitled1/node_modules/_ssh2-streams@0.4.4@ssh2-streams/lib/ssh.js:2217:15)
    at SSH2Stream.<anonymous> (/Users/kisarigi/WebstormProjects/untitled1/node_modules/_ssh2-streams@0.4.4@ssh2-streams/lib/ssh.js:205:5)
    at SSH2Stream.emit (events.js:189:13)
    at parsePacket (/Users/kisarigi/WebstormProjects/untitled1/node_modules/_ssh2-streams@0.4.4@ssh2-streams/lib/ssh.js:3552:10)
    at SSH2Stream._transform (/Users/kisarigi/WebstormProjects/untitled1/node_modules/_ssh2-streams@0.4.4@ssh2-streams/lib/ssh.js:694:13)
    at SSH2Stream.Transform._read (_stream_transform.js:190:10)
    at SSH2Stream._read (/Users/kisarigi/WebstormProjects/untitled1/node_modules/_ssh2-streams@0.4.4@ssh2-streams/lib/ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at SSH2Stream.Writable.write (_stream_writable.js:294:11)
    at Channel.ondata (_stream_readable.js:667:20)
    at Channel.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Channel.Readable.push (_stream_readable.js:220:10)
    at SSH2Stream.<anonymous> (/Users/kisarigi/WebstormProjects/untitled1/node_modules/_ssh2@0.8.4@ssh2/lib/Channel.js:167:15)
    at SSH2Stream.emit (events.js:189:13)
    at parsePacket (/Users/kisarigi/WebstormProjects/untitled1/node_modules/_ssh2-streams@0.4.4@ssh2-streams/lib/ssh.js:3248:10)
    at SSH2Stream._transform (/Users/kisarigi/WebstormProjects/untitled1/node_modules/_ssh2-streams@0.4.4@ssh2-streams/lib/ssh.js:694:13)
    at SSH2Stream.Transform._read (_stream_transform.js:190:10)
    at SSH2Stream._read (/Users/kisarigi/WebstormProjects/untitled1/node_modules/_ssh2-streams@0.4.4@ssh2-streams/lib/ssh.js:253:15) code: 2, level: 'protocol' }
end
close
```

**Comment by mscdex** [comment]
I'm not sure what to suggest, but if you can supply a test that doesn't rely on 3rd party resources (with the exception possibly being standard OpenSSH server installations), I'll be happy to look into it.
