### ISSUE TITLE
Getting error when client is disconnected

### ISSUE THREAD

**Issue by arthurvaverko** [mscdex/ssh2#809]
I'm getting the following error whenever i disconnect with winCSP client.
I have no clue about why or where to look ... :\ 

> events.js:167
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: write ECONNABORTED
>     at afterWriteDispatched (internal/stream_base_commons.js:78:25)
>     at writeGeneric (internal/stream_base_commons.js:73:3)
>     at Socket._writeGeneric (net.js:717:5)
>     at Socket._write (net.js:729:8)
>     at doWrite (_stream_writable.js:410:12)
>     at writeOrBuffer (_stream_writable.js:394:5)
>     at Socket.Writable.write (_stream_writable.js:294:11)
>     at SSH2Stream.ondata (_stream_readable.js:666:20)
>     at SSH2Stream.emit (events.js:182:13)
>     at addChunk (_stream_readable.js:283:12)
> Emitted 'error' event at:
>     at SSH2Stream.<anonymous> (D:\Sources\BECore\SftpApiServer\node_modules\ssh2\lib\server.js:309:10)
>     at SSH2Stream.emit (events.js:187:15)
>     at Socket.<anonymous> (D:\Sources\BECore\SftpApiServer\node_modules\ssh2\lib\server.js:205:17)
>     at Socket.emit (events.js:187:15)
>     at onwriteError (_stream_writable.js:425:12)
>     at onwrite (_stream_writable.js:456:5)
>     at _destroy (internal/streams/destroy.js:40:7)
>     at Socket._destroy (net.js:617:3)
>     at Socket.destroy (internal/streams/destroy.js:32:8)
>     at afterWriteDispatched (internal/stream_base_commons.js:78:17)

here is my code (typescript) :

```typescript
import * as constants from "constants";
import { readFileSync } from 'fs';
import * as log4js from "log4js";
import { Connection, Server, ServerConfig, Session, SFTP_STATUS_CODE } from 'ssh2';
import { Attributes, InputAttributes, SFTPStream } from 'ssh2-streams';
export class SftpApiProxyServer {

    private SftpServer: Server;
    private Logger: log4js.Logger;
    private SftpStream: SFTPStream;
    private Session: Session;
    private DirSent: boolean;

    constructor() {
        log4js.configure('./log4js.json');
        this.Logger = log4js.getLogger('SftpApiProxyServer');

        const serverConf: ServerConfig = {
            hostKeys: [readFileSync('C:\\Keys\\OTT-STG.pem')],
        };

        this.SftpServer = new Server(serverConf, (client) => this.ConfigureServer(client));
    }

    private getLongName(name: string): string {
        return `drwxrwxrwx 1 arthur 0 1 Jan 1 1970 ${name}`;
    }

    private getDirStats(): Attributes {
        return {
            gid: 0,
            mode: constants.S_IFDIR,
            uid: 0,
            size: 0,
            atime: 0,
            mtime: 0,
        };
    }

    public async Start(): Promise<void> {

        this.SftpServer.listen(22, '127.0.0.1', () => {
            this.Logger.info(`Listening on port ${this.SftpServer.address().port}`);
        });
    }

    private ConfigureServer(client: Connection): void {

        client.on('authentication', ctx => {
            this.Logger.info("auth started", ctx.username, ctx.method);
            
            switch (ctx.method) {
                case 'password':
                    this.Logger.info("password entered:", ctx.password);
                    return ctx.accept();
                    break;
                default:
                    this.Logger.info(`Received auth method:[${ctx.method}], its not supported, we support only: [password, keyboard-interactive]`);
                    ctx.reject(["password"])
            }

            ctx.accept();
        });

        client.on('end', () => {
            this.Logger.info("client disconnected...");
        })

        client.on('ready', () => {
            this.Logger.debug('Client authenticated!');
            client.on('session', (acceptSession, rejectSession) => {
                this.Session = acceptSession();
                this.Logger.debug('Session started!');
                this.Session.on('sftp', (acceptSftp, rejectSftp) => {
                    this.Logger.debug('Client SFTP session');
                    this.SftpStream = acceptSftp();

                    this.SftpStream.on('REALPATH', (reqId, path) => this.onRealPath(reqId, path));
                    this.SftpStream.on('SETSTAT', (reqId, path, attrs) => this.onSetStat(reqId, path, attrs));
                    this.SftpStream.on('OPENDIR', (reqId, path) => this.OpenDir(reqId, path));
                    this.SftpStream.on('FSETSTAT', (reqId, handle) => this.onFsetStat(reqId, handle));
                    this.SftpStream.on('READDIR', (reqId, handle) => this.onReadDir(reqId, handle));
                    this.SftpStream.on('STAT', (reqId, path) => this.onStat(reqId, path));
                    this.SftpStream.on('LSTAT', (reqId, path) => this.onLStat(reqId, path));
                    this.SftpStream.on('OPEN', (reqId, filename, flags, attrs) => this.onOpen(reqId, filename, flags, attrs));
                    this.SftpStream.on('READ', (reqId, handle, offset, length) => this.onRead(reqId, handle, offset, length));
                    this.SftpStream.on('CLOSE', (reqId, handle) => this.onClose(reqId, handle));
                });

            });

        });
    }

    private onClose(reqId: number, handle: Buffer): void {
        this.Logger.debug(`CLOSE req:[${reqId}], handle:[${handle}]`);
    }

    private onRead(reqId: number, handle: Buffer, offset: number, length: number): void {
        this.Logger.debug(`READ req:[${reqId}], handle:[${handle}], offset:[${offset}], length:[${length}]`);
    }

    private onOpen(reqId: number, filename: string, flags: number, attrs: InputAttributes): void {
        this.Logger.debug(`REALPATH req:[${reqId}], path:[${filename}], flags:[${flags}] attrs:[${attrs}]`);
        var handle = new Buffer(4);
        this.SftpStream.handle(reqId, handle);
        this.Logger.debug('Opening file for read')
    }

    private onLStat(reqId: number, path: string): void {
        this.Logger.debug(`LSTAT req:[${reqId}], path:[${path}]`);
        this.SftpStream.attrs(reqId, this.getDirStats());
    }

    private onStat(reqId: number, path: string): void {
        this.Logger.debug(`STAT req:[${reqId}], path:[${path}]`);
        this.SftpStream.attrs(reqId, this.getDirStats());
    }

    private onReadDir(reqId: number, handle: Buffer): void {
        this.Logger.debug(`READDIR req:[${reqId}], path:[${handle}]`);
        if (!this.DirSent) {
            this.Logger.debug(`Sending listing...`);
            this.SftpStream.name(reqId, [
                { filename: 'profile1', attrs: this.getDirStats(), longname: this.getLongName('profile1') },
                { filename: 'profile2', attrs: this.getDirStats(), longname: this.getLongName('profile2') },
            ]);
        } else {
            this.Logger.debug(`Sending EOF...`);
            this.SftpStream.status(reqId, SFTP_STATUS_CODE.EOF);
        }
        this.DirSent = true;
    }

    private onFsetStat(reqId: number, handle: Buffer): void {
        this.Logger.debug(`FSETSTAT req:[${reqId}], path:[${handle}]`);
    }

    private OpenDir(reqId: number, path: string): void {
        this.Logger.debug(`OPENDIR req:[${reqId}], path:[${path}]`);
        this.SftpStream.handle(reqId, Buffer.from('root_dir'));
    }

    private onSetStat(reqId: number, path: string, attrs: InputAttributes): void {
        this.Logger.debug(`SETSTAT req:[${reqId}], path:[${path}], attrs:[${attrs}]`);
    }

    private onRealPath(reqId: number, path: string): void {
        this.Logger.debug(`REALPATH req:[${reqId}], path:[${path}]`);

        this.SftpStream.name(reqId, [
            { attrs: this.getDirStats(), filename: '/', longname: this.getLongName('root') },
        ]);
    }

}

const s = new SftpApiProxyServer();
s.Start();
```

**Comment by elliot-nelson** [comment]
It looks like you never register an error handler when you set up your `client: Connection` object, e.g.:

```
client.on('error', error => {
    // do something.. log error.stack, return error to the requestor, whatever
});
```

If you register an error handler, then it should stop blowing up your process.

**Comment by arthurvaverko** [comment]
Thanks .. yes this is exactly what solved it .. 
Still don know why there is such an error when winscp is disconnected
