### ISSUE TITLE
Can't reach more than one jump host

### ISSUE THREAD

**Issue by cahobaut** [mscdex/ssh2#818]
I've difficulties to understand this package. I try to do more than I forwardOut but I face some errors :( .

`conn1.on('ready', function() {
        console.log('FIRST :: connection ready');
        conn1.forwardOut('127.0.0.1', 12345, '10.69.115.158', 22, function(err, stream){
                if (err){
                        console.log('FIRST :: forwardOut error: ' + err);
                        return conn1.end;
                }
                conn2.connect({
                        sock: stream,
                        username: 'login',
                        password:'password',
                });
        });
}).connect({
        host:'10.69.115.169',
        username:'login',
        password:'password',

});

conn2.on('ready', function() {
        console.log('SECOND :: connection ready');
        conn2.forwardOut('127.0.0.1', 12345, '10.67.241.94', 22, function (err, stream) {
                if (err){
                        console.log('SECOND :: forwardOut error: ' + err);
                        return conn1.end();
                }
                conn3.connect({
                        sock: stream,
                        username: 'login',
                        password: 'password',
                });
        });
});
conn3.on('ready', function() {
        console.log('THIRD :: connection ready');
        conn3.exec('ls', function(err, stream) {
                if (err){
                        console.log('THIRD :: exec error: ' + err);
                        return conn2.end();
                }
                stream.on('end', function(){
                        conn2.end();
                }).on('data', function() {
                        console.log(data.toString());
                });
        });
});`

 I Don't know how to do it . Any idea ?

Ps: Is there more documentation about it ?

thanks for help

**Comment by mscdex** [comment]
What error(s) do you get? What output is logged to the console?

**Comment by cahobaut** [comment]
I got this output :

`FIRST :: connection ready
SECOND :: connection ready
events.js:180
      throw er; // Unhandled 'error' event
      ^

Error: All configured authentication methods failed
    at doNextAuth (/home/alvin/globaldata/Alvin02v/node_modules/ssh2/lib/client.js:413:17)
    at tryNextAuth (/home/alvin/globaldata/Alvin02v/node_modules/ssh2/lib/client.js:484:5)
    at SSH2Stream.onUSERAUTH_FAILURE (/home/alvin/globaldata/Alvin02v/node_modules/ssh2/lib/client.js:597:5)
    at SSH2Stream.emit (events.js:203:13)
    at parsePacket (/home/alvin/globaldata/Alvin02v/node_modules/ssh2-streams/lib/ssh.js:3728:10)
    at SSH2Stream._transform (/home/alvin/globaldata/Alvin02v/node_modules/ssh2-streams/lib/ssh.js:694:13)
    at SSH2Stream.Transform._read (_stream_transform.js:189:10)
    at SSH2Stream._read (/home/alvin/globaldata/Alvin02v/node_modules/ssh2-streams/lib/ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:417:12)
Emitted 'error' event at:
    at doNextAuth (/home/alvin/globaldata/Alvin02v/node_modules/ssh2/lib/client.js:415:12)
    at tryNextAuth (/home/alvin/globaldata/Alvin02v/node_modules/ssh2/lib/client.js:484:5)
    [... lines matching original stack trace ...]
    at doWrite (_stream_writable.js:417:12) {
  level: 'client-authentication'
}
`

**Comment by cahobaut** [comment]
I Don't know if I've the right logic when I do it

**Comment by cahobaut** [comment]
Thank you for your help in my other issue. For this one I've this output:
`FIRST :: connection ready
SECOND :: connection ready
events.js:180
      throw er; // Unhandled 'error' event
      ^

Error: All configured authentication methods failed
    at doNextAuth (/home/alvin/globaldata/Alvin02v/node_modules/ssh2/lib/client.js:413:17)
    at tryNextAuth (/home/alvin/globaldata/Alvin02v/node_modules/ssh2/lib/client.js:484:5)
    at SSH2Stream.onUSERAUTH_FAILURE (/home/alvin/globaldata/Alvin02v/node_modules/ssh2/lib/client.js:597:5)
    at SSH2Stream.emit (events.js:203:13)
    at parsePacket (/home/alvin/globaldata/Alvin02v/node_modules/ssh2-streams/lib/ssh.js:3728:10)
    at SSH2Stream._transform (/home/alvin/globaldata/Alvin02v/node_modules/ssh2-streams/lib/ssh.js:694:13)
    at SSH2Stream.Transform._read (_stream_transform.js:189:10)
    at SSH2Stream._read (/home/alvin/globaldata/Alvin02v/node_modules/ssh2-streams/lib/ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:417:12)
Emitted 'error' event at:
    at doNextAuth (/home/alvin/globaldata/Alvin02v/node_modules/ssh2/lib/client.js:415:12)
    at tryNextAuth (/home/alvin/globaldata/Alvin02v/node_modules/ssh2/lib/client.js:484:5)
    [... lines matching original stack trace ...]
    at doWrite (_stream_writable.js:417:12) {
  level: 'client-authentication'
}
`
I Don't know if I've the use the right logic when I do it.

**Comment by cahobaut** [comment]
Is there a way to get more details about login logs?

**Comment by mscdex** [comment]
The third host is rejecting your authentication. Are you sure the username and password are correct? Perhaps a different authentication method is needed instead of just plain password (e.g. 'keyboard-interactive' or `privateKey`).

**Comment by cahobaut** [comment]
thanks you. username and password were wrong
