### ISSUE TITLE
Can't execute many commands on one connection

### ISSUE THREAD

**Issue by cahobaut** [mscdex/ssh2#825]
Hello mscdex, I've try to follow yours suggestions on others issues but I still can't execute more than one command on one connection. I've try to set it up using async.eachSeries

```js
var cmds= {
        cmd1:'ls',
        cmd2:'uptime',
        cmd3:'echo bonjour',
};


var conn = new Client();
conn.on('ready', function(){
        console.log('first conn :: ready');
        async.eachSeries(cmds, function iteratee(onecmd, callback){
                 conn.exec(onecmd, {pty: true}, function(err, stream){
                        if (err) throw err;
                        stream.on('close', function (code, signal) {
                                console.log('Streeam :: close :: code: '+code+', signal: ' + signal);
                                conn.end();
                                callback();
                        }).on('data', function(data) {
                                console.log('STDOUT: ' + data);
                        }).stderr.on('data', function(data) {
                                console.log('STDERR: '+ data);
                        });
                });
        });
}).connect({
        host: '1.1.1.1',
        username: 'login',
        password: 'pwd',
        debug: (debug) =>{
        console.log(debug);
        }
});
```

I get the next output

```
DEBUG: Local ident: 'SSH-2.0-ssh2js0.4.4'
DEBUG: Client: Trying 1.1.1.1 on port 22 ...
DEBUG: Client: Connected
DEBUG: Parser: IN_INIT
DEBUG: Parser: IN_GREETING
DEBUG: Parser: IN_HEADER
DEBUG: Remote ident: 'SSH-2.0-OpenSSH_5.3'
DEBUG: Outgoing: Writing KEXINIT
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:836,padLen:10,remainLen:832
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXINIT
DEBUG: Comparing KEXINITs ...
DEBUG: (local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
DEBUG: (remote) KEX algorithms: diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
DEBUG: KEX algorithm: diffie-hellman-group-exchange-sha256
DEBUG: (local) Host key formats: ssh-ed25519,ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
DEBUG: (remote) Host key formats: ssh-rsa,ssh-dss
DEBUG: Host key format: ssh-rsa
DEBUG: (local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
DEBUG: (remote) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
DEBUG: Client->Server Cipher: aes128-ctr
DEBUG: (local) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
DEBUG: (remote) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
DEBUG: Server->Client Cipher: aes128-ctr
DEBUG: (local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG: (remote) Client->Server HMAC algorithms: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
DEBUG: Client->Server HMAC algorithm: hmac-sha2-256
DEBUG: (local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG: (remote) Server->Client HMAC algorithms: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
DEBUG: Server->Client HMAC algorithm: hmac-sha2-256
DEBUG: (local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
DEBUG: (remote) Client->Server compression algorithms: none,zlib@openssh.com
DEBUG: Client->Server compression algorithm: none
DEBUG: (local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
DEBUG: (remote) Server->Client compression algorithms: none,zlib@openssh.com
DEBUG: Server->Client compression algorithm: none
DEBUG: Outgoing: Writing KEXDH_GEX_REQUEST
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:532,padLen:8,remainLen:528
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXDH_GEX_GROUP
DEBUG: Outgoing: Writing KEXDH_GEX_INIT
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:1084,padLen:10,remainLen:1080
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXDH_GEX_REPLY
DEBUG: Checking host key format
DEBUG: Checking signature format
DEBUG: Verifying host fingerprint
DEBUG: Host accepted by default (no verification)
DEBUG: Verifying signature
DEBUG: Outgoing: Writing NEWKEYS
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:12,padLen:10,remainLen:8
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: NEWKEYS
DEBUG: Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:28,padLen:10,remainLen:16
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: SERVICE_ACCEPT
DEBUG: Outgoing: Writing USERAUTH_REQUEST (none)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:44,padLen:19,remainLen:32
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_FAILURE
DEBUG: Client: none auth failed
DEBUG: Outgoing: Writing USERAUTH_REQUEST (password)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:12,padLen:10,remainLen:0
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_SUCCESS
first conn :: ready
DEBUG: Outgoing: Writing CHANNEL_OPEN (0, session)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:28,padLen:10,remainLen:16
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_OPEN_CONFIRMATION
DEBUG: Outgoing: Writing CHANNEL_REQUEST (0, pty-req)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:12,padLen:6,remainLen:0
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_SUCCESS (0)
DEBUG: Outgoing: Writing CHANNEL_REQUEST (0, exec)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:28,padLen:18,remainLen:16
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_WINDOW_ADJUST (0, 2097152)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:12,padLen:6,remainLen:0
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_SUCCESS (0)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:44,padLen:18,remainLen:32
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_REQUEST (0, exit-status)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:524,padLen:9,remainLen:512
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
STDOUT:[Output of ls command]
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:12,padLen:6,remainLen:0
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_EOF (0)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:12,padLen:6,remainLen:0
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_CLOSE (0)
DEBUG: Outgoing: Writing CHANNEL_CLOSE (0)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
Streeam :: close :: code: 0, signal: undefined
DEBUG: Outgoing: Writing DISCONNECT (BY_APPLICATION)
DEBUG: Outgoing: Writing CHANNEL_OPEN (1, session)
/home/alvin/globaldata/Alvin02v/Server2/ssh/testne.js:89
                        if (err) throw err;
                                 ^

Error: No response from server
    at Socket.<anonymous> (/home/alvin/globaldata/Alvin02v/node_modules/ssh2/lib/client.js:321:15)
    at Socket.emit (events.js:203:13)
    at TCP.<anonymous> (net.js:588:12)
```

**Comment by mscdex** [comment]
You're closing the connection too soon. Wait until all of your commands have completed first.

**Comment by cahobaut** [comment]
Can you suggest me on how to use Stream.on('close' because it's in the loop

**Comment by zxdong262** [comment]
@cahobaut Use async functions to abstract the process, it could be like this:

```js
function connect(config) {
  return new Promise((resolve, reject) => {
    const conn = new Client()
    conn
      .on('ready', () => {
        resolve(conn)
      })
      .on('error', reject)
      .connect(config)
  })
}

function exec(conn, cmd, config) {
  return new Promise((resolve, reject) => {
    conn.exec(cmd, config, function(err, stream) {
      if (err) {
        return reject(err)
      }
      stream.on('close', function (code, signal) {
        console.log('Streeam :: close :: code: '+code+', signal: ' + signal)
      }).on('data', function (data) {
        console.log('STDOUT: ' + data)
      }).stderr.on('data', function(data) {
        console.log('STDERR: '+ data)
      })
    })
  })
}

async function run() {
  const confConnect = {
    host: '1.1.1.1',
    username: 'login',
    password: 'pwd',
    debug: (debug) => {
      console.log(debug)
    }
  }
  
  const confExec = {
    pty: true
  }

  const cmds = {
    cmd1:'ls',
    cmd2:'uptime',
    cmd3:'echo bonjour'
  }

  const conn = await connect(confConnect)
  const keys = Object.keys(cmds)
  for (const key of keys) {
    const result = await exec(conn, cmd)
  }

  // all done, end it mannully
  conn.end()
}

// run it
run()
```

**Comment by wenlittleoil** [comment]
> @cahobaut Use async functions to abstract the process, it could be like this:
> 
> ```js
> function connect(config) {
>   return new Promise((resolve, reject) => {
>     const conn = new Client()
>     conn
>       .on('ready', () => {
>         resolve(conn)
>       })
>       .on('error', reject)
>       .connect(config)
>   })
> }
> 
> function exec(conn, cmd, config) {
>   return new Promise((resolve, reject) => {
>     conn.exec(cmd, config, function(err, stream) {
>       if (err) {
>         return reject(err)
>       }
>       stream.on('close', function (code, signal) {
>         console.log('Streeam :: close :: code: '+code+', signal: ' + signal)
>       }).on('data', function (data) {
>         console.log('STDOUT: ' + data)
>       }).stderr.on('data', function(data) {
>         console.log('STDERR: '+ data)
>       })
>     })
>   })
> }
> 
> async function run() {
>   const confConnect = {
>     host: '1.1.1.1',
>     username: 'login',
>     password: 'pwd',
>     debug: (debug) => {
>       console.log(debug)
>     }
>   }
>   
>   const confExec = {
>     pty: true
>   }
> 
>   const cmds = {
>     cmd1:'ls',
>     cmd2:'uptime',
>     cmd3:'echo bonjour'
>   }
> 
>   const conn = await connect(confConnect)
>   const keys = Object.keys(cmds)
>   for (const key of keys) {
>     const result = await exec(conn, cmds[key], confExec)
>   }
> 
>   // all done, end it manually
>   conn.end()
> }
> 
> // run it
> run()
> ```

Sorry for not understanding, The Promise returned by the function `exec` does not seem to be resolved.

**Comment by zxdong262** [comment]
> > @cahobaut Use async functions to abstract the process, it could be like this:
> > ```js
> > function connect(config) {
> >   return new Promise((resolve, reject) => {
> >     const conn = new Client()
> >     conn
> >       .on('ready', () => {
> >         resolve(conn)
> >       })
> >       .on('error', reject)
> >       .connect(config)
> >   })
> > }
> > 
> > function exec(conn, cmd, config) {
> >   return new Promise((resolve, reject) => {
> >     conn.exec(cmd, config, function(err, stream) {
> >       if (err) {
> >         return reject(err)
> >       }
> >       stream.on('close', function (code, signal) {
> >         console.log('Streeam :: close :: code: '+code+', signal: ' + signal)
> >       }).on('data', function (data) {
> >         console.log('STDOUT: ' + data)
> >       }).stderr.on('data', function(data) {
> >         console.log('STDERR: '+ data)
> >       })
> >     })
> >   })
> > }
> > 
> > async function run() {
> >   const confConnect = {
> >     host: '1.1.1.1',
> >     username: 'login',
> >     password: 'pwd',
> >     debug: (debug) => {
> >       console.log(debug)
> >     }
> >   }
> >   
> >   const confExec = {
> >     pty: true
> >   }
> > 
> >   const cmds = {
> >     cmd1:'ls',
> >     cmd2:'uptime',
> >     cmd3:'echo bonjour'
> >   }
> > 
> >   const conn = await connect(confConnect)
> >   const keys = Object.keys(cmds)
> >   for (const key of keys) {
> >     const result = await exec(conn, cmds[key], confExec)
> >   }
> > 
> >   // all done, end it manually
> >   conn.end()
> > }
> > 
> > // run it
> > run()
> > ```
> 
> Sorry for not understanding, The Promise returned by the function `exec` does not seem to be resolved.

Yes, I missed that, updated.

**Comment by mherb63** [comment]
Thank you.  This was very helpful.  I would suggest adding this to the main page as an example.  Of course, the` exec() `function needs the `resolve` on the `stream.on('close', ...`
