### ISSUE TITLE
throw ECONNRESET error when connecting Windows Server

### ISSUE THREAD

**Issue by sszzss** [mscdex/ssh2#850]
The example works fine for connecting Linux sshd server, but failed for windows server [https://github.com/PowerShell/openssh-portable](url).

``` javascript
var Client = require('ssh2').Client;

var conn = new Client();
conn.on('ready', function () {
    console.log('Client :: ready');
    conn.shell(function (err, stream) {
        if (err) throw err;
        stream.on('close', function () {
            console.log('Stream :: close');
            conn.end();
        }).on('data', function (data) {
            console.log('OUTPUT: ' + data);
        });
        stream.end('java -version\r\nexit\r\n');
    });
}).connect({
    host: '127.0.0.1',
    port: 9191,
    username: 'foo',
    privateKey: require('fs').readFileSync('id_rsa')
});
```
error
```
Stream :: close
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
Emitted 'error' event on Client instance at:
    at Socket.<anonymous> (D:\projects\deploy-tool\node_modules\ssh2\lib\client.js:307:10)
    at Socket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read',
  level: 'client-socket'
}
```

Any help would be appreciated!

**Comment by mscdex** [comment]
No idea, but you can trap these errors by adding an `'error'` event handler on `conn`.

**Comment by sszzss** [comment]
ok，I think maybe there is no better solution.
