### ISSUE TITLE
Connection Reset causes Express server to stop/crash

### ISSUE THREAD

**Issue by tukeshwar** [mscdex/ssh2#864]
My App is supposed to work in two different networks. 
I get the data from unix severs when I am connected to network1 and cache all data to be used when i switch to network 2, however as soon as I switch to network 2 after caching, express server stops with below error: 

> events.js:136
      throw er; // Unhandled 'error' event
      ^

> Error: read ECONNRESET 
at _errnoException (util.js:1031:13)
at TCP.onread (net.js:619:25)

I am trying to use node-ssh module as below:
`
      
        //return data from cache 

       var envCachedProps = propCacheObj.get(env);

	if(envCachedProps){
		console.log("return chached :>>"+env);

		res.status(200).set({'Access-Control-Allow-Origin': '*'});

		res.send(envCachedProps);

		return 0;
	}
	//if cache not present then get data from server
	node_ssh = require('node-ssh')
		ssh = new node_ssh()
		console.log("connectting");`
	
		ssh.connect({
		  host: hostname,
		  username: '8888',
		  privateKey: 'rsaKey'
		})
		.then(function() {
			console.log("Execute Command");
			ssh.execCommand("cd ....")
			.then(function(result) {
				//code for caching data here
				  res.status(200).set({'Access-Control-Allow-Origin': '*'});
				  res.send(result.stdout);
				  
			})
			
		})

		ssh.dispose();
	//res.send('humm...Something went wrong :( Please again or later');
`
Error is fine because TCP port is closed/reset but server should not stop. I could not find a way to gracefully catch this error and handle to keep sever running on network 2.

Please help and suggest if there is any way that I can keep server running when network is switched.

Kindly note that this is not the case until unless node-ssh module is invoked. In other cases server keeps running even though network is switched.

**Comment by tukeshwar** [comment]
Ahh.. finally find a solution by doing below 

`ssh=null;`
