### ISSUE TITLE
conn.end() triggers ECONNRESET error with Windows OpenSSH

### ISSUE THREAD

**Issue by codakin** [mscdex/ssh2#902]
I get the following error when conn.end() is executed:

```
events.js:298
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on Client instance at:
    at Socket.<anonymous> (C:\GML\tests\RunPowershellOverSSH\node_modules\ssh2\lib\client.js:307:10)
    at Socket.emit (events.js:321:20)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read',
  level: 'client-socket'
}
```

I connect to a Windows OpenSSH server I enabled using the process outlined here:
https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse

I used the sample below taken directly from the README to test.  I also have a Linux Ubuntu server running OpenSSH and did not encounter the error there with the same code sample.   Only in windows and only when the end() function is executed.

```
var Client = require('ssh2').Client;

var conn = new Client();
conn.on('ready', function() {
  console.log('Client :: ready');
  conn.sftp(function(err, sftp) {
    if (err) throw err;
    sftp.readdir('.', function(err, list) {
      if (err) throw err;
      console.dir(list);
      conn.end();
    });
  });
  
}).connect({
    host: '*****',
    port: 22,
    username: '*****',
    password: '*****'
});
```

**Comment by codakin** [comment]
As a workaround, I'm using the following solution to catch all uncaughtExceptions so the process doesn't crash unintentionally.

```
process.on('uncaughtException', function (err) {
    console.log('UNCAUGHT EXCEPTION - keeping process alive:', err); // err.message is "foobar"
});
```

https://stackoverflow.com/questions/29358054/catch-all-error-events-from-any-eventemitter-in-node

**Comment by mscdex** [comment]
A better workaround is to attach an `'error'` event handler on the client object instead.

**Comment by shaan1337** [comment]
I've got some reproduction steps for the issue here: https://github.com/shaan1337/ssh2_conn_reset_poc

It appears that the following is happening (after capturing the network traffic with wireshark):
1. We send a `DISCONNECT` message
2. We close the connection with a TCP `FIN` flag
3. The windows machine sends a TCP packet with the `RST` flag instead of the `FIN` flag (on linux, the `FIN` flag is correctly set)
4. This surfaces up as an `ECONNRESET` error

Something is clearly wrong with the way the openssh server on windows is closing the connection.

here's the full log for a run:
```
Diagnostics:
  pulumi:pulumi:Stack (ssh2_conn_reset_poc-dev):
    Waiting for 18.237.61.91:22..................................................................................................................................................
    Connected!
    --> DEBUG: Local ident: 'SSH-2.0-ssh2js0.4.10'
    --> DEBUG: Client: Trying 18.237.61.91 on port 22 ...
    --> DEBUG: Client: Connected
    --> DEBUG: Parser: IN_INIT
    --> DEBUG: Parser: IN_GREETING
    --> DEBUG: Parser: IN_HEADER
    --> DEBUG: Remote ident: 'SSH-2.0-OpenSSH_for_Windows_7.7'
    --> DEBUG: Outgoing: Writing KEXINIT
    --> DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
    --> DEBUG: Parser: IN_PACKET
    --> DEBUG: Parser: pktLen:1044,padLen:8,remainLen:1040
    --> DEBUG: Parser: IN_PACKETDATA
    --> DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXINIT
    --> DEBUG: Comparing KEXINITs ...
    --> DEBUG: (local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha1
    --> DEBUG: (remote) KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1
    --> DEBUG: KEX algorithm: ecdh-sha2-nistp256
    --> DEBUG: (local) Host key formats: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa
    --> DEBUG: (remote) Host key formats: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
    --> DEBUG: Host key format: ecdsa-sha2-nistp256
    --> DEBUG: (local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
    --> DEBUG: (remote) Client->Server ciphers: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
    --> DEBUG: Client->Server Cipher: aes128-ctr
    --> DEBUG: (local) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
    --> DEBUG: (remote) Server->Client ciphers: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
    --> DEBUG: Server->Client Cipher: aes128-ctr
    --> DEBUG: (local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
    --> DEBUG: (remote) Client->Server HMAC algorithms: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
    --> DEBUG: Client->Server HMAC algorithm: hmac-sha2-256
    --> DEBUG: (local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
    --> DEBUG: (remote) Server->Client HMAC algorithms: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
    --> DEBUG: Server->Client HMAC algorithm: hmac-sha2-256
    --> DEBUG: (local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
    --> DEBUG: (remote) Client->Server compression algorithms: none
    --> DEBUG: Client->Server compression algorithm: none
    --> DEBUG: (local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
    --> DEBUG: (remote) Server->Client compression algorithms: none
    --> DEBUG: Server->Client compression algorithm: none
    --> DEBUG: Outgoing: Writing KEXECDH_INIT
    --> DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
    --> DEBUG: Parser: IN_PACKET
    --> DEBUG: Parser: pktLen:292,padLen:8,remainLen:288
    --> DEBUG: Parser: IN_PACKETDATA
    --> DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXECDH_REPLY
    --> DEBUG: Checking host key format
    --> DEBUG: Checking signature format
    --> DEBUG: Verifying host fingerprint
    --> DEBUG: Host accepted by default (no verification)
    --> DEBUG: Verifying signature
    --> DEBUG: Outgoing: Writing NEWKEYS
    --> DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
    --> DEBUG: Parser: IN_PACKET
    --> DEBUG: Parser: pktLen:12,padLen:10,remainLen:8
    --> DEBUG: Parser: IN_PACKETDATA
    --> DEBUG: Parser: IN_PACKETDATAAFTER, packet: NEWKEYS
    --> DEBUG: Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
    --> DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
    --> DEBUG: Parser: IN_PACKET
    --> DEBUG: Parser: Decrypting
    --> DEBUG: Parser: pktLen:28,padLen:10,remainLen:16
    --> DEBUG: Parser: IN_PACKETDATA
    --> DEBUG: Parser: Decrypting
    --> DEBUG: Parser: HMAC size:32
    --> DEBUG: Parser: IN_PACKETDATAVERIFY
    --> DEBUG: Parser: Verifying MAC
    --> DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
    --> DEBUG: Parser: IN_PACKETDATAAFTER, packet: SERVICE_ACCEPT
    --> DEBUG: Outgoing: Writing USERAUTH_REQUEST (none)
    --> DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
    --> DEBUG: Parser: IN_PACKET
    --> DEBUG: Parser: Decrypting
    --> DEBUG: Parser: pktLen:60,padLen:14,remainLen:48
    --> DEBUG: Parser: IN_PACKETDATA
    --> DEBUG: Parser: Decrypting
    --> DEBUG: Parser: HMAC size:32
    --> DEBUG: Parser: IN_PACKETDATAVERIFY
    --> DEBUG: Parser: Verifying MAC
    --> DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
    --> DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_FAILURE
    --> DEBUG: Client: none auth failed
    --> DEBUG: Outgoing: Writing USERAUTH_REQUEST (password)
    --> DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
    --> DEBUG: Parser: IN_PACKET
    --> DEBUG: Parser: Decrypting
    --> DEBUG: Parser: pktLen:12,padLen:10,remainLen:0
    --> DEBUG: Parser: IN_PACKETDATA
    --> DEBUG: Parser: HMAC size:32
    --> DEBUG: Parser: IN_PACKETDATAVERIFY
    --> DEBUG: Parser: Verifying MAC
    --> DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
    --> DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_SUCCESS
    Client :: ready
    --> DEBUG: Outgoing: Writing CHANNEL_OPEN (0, session)
    --> DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
    --> DEBUG: Parser: IN_PACKET
    --> DEBUG: Parser: Decrypting
    --> DEBUG: Parser: pktLen:492,padLen:16,remainLen:480
    --> DEBUG: Parser: IN_PACKETDATA
    --> DEBUG: Parser: Decrypting
    --> DEBUG: Parser: HMAC size:32
    --> DEBUG: Parser: IN_PACKETDATAVERIFY
    --> DEBUG: Parser: Verifying MAC
    --> DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
    --> DEBUG: Parser: IN_PACKETDATAAFTER, packet: GLOBAL_REQUEST (hostkeys-00@openssh.com)
    --> DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
    --> DEBUG: Parser: IN_PACKET
    --> DEBUG: Parser: Decrypting
    --> DEBUG: Parser: pktLen:28,padLen:10,remainLen:16
    --> DEBUG: Parser: IN_PACKETDATA
    --> DEBUG: Parser: Decrypting
    --> DEBUG: Parser: HMAC size:32
    --> DEBUG: Parser: IN_PACKETDATAVERIFY
    --> DEBUG: Parser: Verifying MAC
    --> DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
    --> DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_OPEN_CONFIRMATION
    --> DEBUG: Outgoing: Writing CHANNEL_REQUEST (0, exec)
    --> DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
    --> DEBUG: Parser: IN_PACKET
    --> DEBUG: Parser: Decrypting
    --> DEBUG: Parser: pktLen:28,padLen:18,remainLen:16
    --> DEBUG: Parser: IN_PACKETDATA
    --> DEBUG: Parser: Decrypting
    --> DEBUG: Parser: HMAC size:32
    --> DEBUG: Parser: IN_PACKETDATAVERIFY
    --> DEBUG: Parser: Verifying MAC
    --> DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
    --> DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_WINDOW_ADJUST (0, 2097152)
    --> DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
    --> DEBUG: Parser: IN_PACKET
    --> DEBUG: Parser: Decrypting
    --> DEBUG: Parser: pktLen:12,padLen:6,remainLen:0
    --> DEBUG: Parser: IN_PACKETDATA
    --> DEBUG: Parser: HMAC size:32
    --> DEBUG: Parser: IN_PACKETDATAVERIFY
    --> DEBUG: Parser: Verifying MAC
    --> DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
    --> DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_SUCCESS (0)
    --> DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
    --> DEBUG: Parser: IN_PACKET
    --> DEBUG: Parser: Decrypting
    --> DEBUG: Parser: pktLen:28,padLen:16,remainLen:16
    --> DEBUG: Parser: IN_PACKETDATA
    --> DEBUG: Parser: Decrypting
    --> DEBUG: Parser: HMAC size:32
    --> DEBUG: Parser: IN_PACKETDATAVERIFY
    --> DEBUG: Parser: Verifying MAC
    --> DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
    --> DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
    STDOUT:
    --> DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
    --> DEBUG: Parser: IN_PACKET
    --> DEBUG: Parser: Decrypting
    --> DEBUG: Parser: pktLen:60,padLen:7,remainLen:48
    --> DEBUG: Parser: IN_PACKETDATA
    --> DEBUG: Parser: Decrypting
    --> DEBUG: Parser: HMAC size:32
    --> DEBUG: Parser: IN_PACKETDATAVERIFY
    --> DEBUG: Parser: Verifying MAC
    --> DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
    --> DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
    STDOUT: Microsoft Windows [Version 10.0.17763.1577]
    --> DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
    --> DEBUG: Parser: IN_PACKET
    --> DEBUG: Parser: Decrypting
    --> DEBUG: Parser: pktLen:28,padLen:16,remainLen:16
    --> DEBUG: Parser: IN_PACKETDATA
    --> DEBUG: Parser: Decrypting
    --> DEBUG: Parser: HMAC size:32
    --> DEBUG: Parser: IN_PACKETDATAVERIFY
    --> DEBUG: Parser: Verifying MAC
    --> DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
    --> DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
    STDOUT:
    --> DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
    --> DEBUG: Parser: IN_PACKET
    --> DEBUG: Parser: Decrypting
    --> DEBUG: Parser: pktLen:12,padLen:6,remainLen:0
    --> DEBUG: Parser: IN_PACKETDATA
    --> DEBUG: Parser: HMAC size:32
    --> DEBUG: Parser: IN_PACKETDATAVERIFY
    --> DEBUG: Parser: Verifying MAC
    --> DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
    --> DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_EOF (0)
    --> DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
    --> DEBUG: Parser: IN_PACKET
    --> DEBUG: Parser: Decrypting
    --> DEBUG: Parser: pktLen:44,padLen:18,remainLen:32
    --> DEBUG: Parser: IN_PACKETDATA
    --> DEBUG: Parser: Decrypting
    --> DEBUG: Parser: HMAC size:32
    --> DEBUG: Parser: IN_PACKETDATAVERIFY
    --> DEBUG: Parser: Verifying MAC
    --> DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
    --> DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_REQUEST (0, exit-status)
    --> DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
    --> DEBUG: Parser: IN_PACKET
    --> DEBUG: Parser: Decrypting
    --> DEBUG: Parser: pktLen:12,padLen:6,remainLen:0
    --> DEBUG: Parser: IN_PACKETDATA
    --> DEBUG: Parser: HMAC size:32
    --> DEBUG: Parser: IN_PACKETDATAVERIFY
    --> DEBUG: Parser: Verifying MAC
    --> DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
    --> DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_CLOSE (0)
    --> DEBUG: Outgoing: Writing CHANNEL_CLOSE (0)
    --> DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
    Stream :: close :: code: 0, signal: undefined
    --> DEBUG: Outgoing: Writing DISCONNECT (BY_APPLICATION)

    Error: read ECONNRESET
        at TCP.onStreamRead (internal/stream_base_commons.js:111:27)

    error: Running program '/home/shaan/Documents/Work/EventStore/ssh2_conn_reset_poc' failed with an unhandled exception:
    Error: read ECONNRESET
        at TCP.onStreamRead (internal/stream_base_commons.js:111:27)

```

**Comment by mscdex** [comment]
Yeah, there's nothing we can really do about that. The solution is to always add `'error'` event handlers and handle the error appropriately.
