### ISSUE TITLE
Can't start ssh session - Error: Handshake failed: no matching client->server HMAC

### ISSUE THREAD

**Issue by MonsieurBarti** [mscdex/ssh2#929]
Here is the code I use

```JS
let conn = new Client()
            conn.on('ready', () => {
                console.log('Client :: ready')
                conn.shell((err, stream) => {
                    if (err) return cb(err)
                    stream.on('close', () => {
                        console.log('Stream :: close')
                        conn.end()
                    }).on('data', (data) => {
                        return cb(null, data)
                    })
                    stream.end('docker ps -a --format "table {{.Names}}\t{{.Status}}"\nexit\n')
                })
            }).connect({
                host: '',
                port: ,
                username: '',
                privateKey: require('fs').readFileSync(''),
                algorithms: {
                    hmac: ['hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1']
                }
            })
```
Here is the result everytime :
```
Error: Handshake failed: no matching client->server HMAC
    at SSH2Stream.Transform._write (_stream_transform.js:179:12)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at SSH2Stream.Writable.write (_stream_writable.js:318:11)
    at Socket.ondata (_stream_readable.js:717:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
Emitted 'error' event on Client instance at:
    at SSH2Stream.<anonymous> (C:\Users\Monsieur Barti\Documents\Projects\Work\Immo-Sign\monitoring\node_modules\ssh2\lib\client.js:359:10)
    at SSH2Stream.emit (events.js:327:22)
    at check_KEXINIT (C:\Users\Monsieur Barti\Documents\Projects\Work\Immo-Sign\monitoring\node_modules\ssh2-streams\lib\ssh.js:2460:10)
    at check (C:\Users\Monsieur Barti\Documents\Projects\Work\Immo-Sign\monitoring\node_modules\ssh2-streams\lib\ssh.js:2281:9)
    [... lines matching original stack trace ...]
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  level: 'handshake'
}
```

**Comment by mscdex** [comment]
If the cipher being selected during the handshake is an AEAD cipher (e.g. aes-gcm), then this is a known issue. If not, the error indicates that the server does not support the HMACs you have set in your `algorithms`.

**Comment by MonsieurBarti** [comment]
The problem seems to come from the cipher indeed so what can I do if I want to open an ssh connection ?

**Comment by mscdex** [comment]
Until the bug is resolved, a matching HMAC has to be found.

**Comment by mscdex** [comment]
This should be fixed with `ssh2` v1.x.
