### ISSUE TITLE
ssh2@rewrite: Server keyboard-interactive auth crash

### ISSUE THREAD

**Issue by stephank** [mscdex/ssh2#940]
I'm building a small server that only accepts `publickey` auth, and was doing a simple test with an OpenSSH client. Without yet specifying a key file, the client fell through to `keyboard-interactive`, at which point the server crashed.

This is commit 9eba5e7e0bd9a2f3c995cea5eb22775fabdb8ec6 on `master`.

Client:

```
$ ssh -v -p 8022 localhost
OpenSSH_8.3p1, OpenSSL 1.1.1g  21 Apr 2020
[... output skipped]
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue:
debug1: Next authentication method: publickey
debug1: Trying private key: /Users/stephank/.ssh/id_rsa
debug1: Trying private key: /Users/stephank/.ssh/id_dsa
[... more attempts]
debug1: Next authentication method: keyboard-interactive
Connection closed by 127.0.0.1 port 8022
```

Server:

```
node_modules/ssh2/lib/server.js:99
    this.submethods = submethods.split(RE_KBINT_SUBMETHODS);
                                 ^

TypeError: submethods.split is not a function
    at new KeyboardAuthContext (node_modules/ssh2/lib/server.js:99:34)
    at USERAUTH_REQUEST (node_modules/ssh2/lib/server.js:1125:21)
    at 50 (node_modules/ssh2/lib/protocol/handlers.misc.js:305:16)
    at Protocol.onPayload (node_modules/ssh2/lib/protocol/Protocol.js:1945:10)
    at ChaChaPolyDecipherNative.decrypt (node_modules/ssh2/lib/protocol/crypto.js:751:26)
    at Protocol.parsePacket [as _parse] (node_modules/ssh2/lib/protocol/Protocol.js:1914:25)
    at Protocol.parse (node_modules/ssh2/lib/protocol/Protocol.js:287:16)
    at Socket.<anonymous> (node_modules/ssh2/lib/server.js:1235:13)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)
```

**Comment by mscdex** [comment]
This should be fixed now, thanks for the report!
