### ISSUE TITLE
ssh2@rewrite: Error handler is called multiple times

### ISSUE THREAD

**Issue by mofux** [mscdex/ssh2#972]
With the changes from https://github.com/mscdex/ssh2/commit/d3776f2af2e68e4485d2dbfe2f161008beb7e956 the error handler may now be called multiple times with different errors if the initial connection fails:

```javascript
const { Client } = require('ssh2');
const client = new Client();
client.on('error', (err) => console.log('Caught Error', err));
client.on('ready', () => console.log('ready'));
client.connect({
	host: 'unknown-host',
	username: 'test',
	password: 'test'
});
```

Result
```
Caught Error Error: getaddrinfo ENOTFOUND unknown-host                                                                                                                                                
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {                                                                                                                                   
  errno: 'ENOTFOUND',                                                                                                                                                                                 
  code: 'ENOTFOUND',                                                                                                                                                                                  
  syscall: 'getaddrinfo',                                                                                                                                                                             
  hostname: 'unknown-host',                                                                                                                                                                           
  level: 'client-socket'                                                                                                                                                                              
}                                                                                                                                                                                                     
Caught Error Error: Connection lost before handshake                                                                                                                                                  
    at makeError (/Users/user/Git/enter-client/node_modules/ssh2/lib/protocol/utils.js:142:15)                                                                                                        
    at onDone (/Users/user/Git/enter-client/node_modules/ssh2/lib/client.js:703:13)                                                                                                                   
    at Socket.<anonymous> (/Users/user/Git/enter-client/node_modules/ssh2/lib/client.js:729:7)                                                                                                        
    at Socket.emit (events.js:314:20)                                                                                                                                                                 
    at TCP.<anonymous> (net.js:675:12) {                                                                                                                                                              
  level: 'protocol',                                                                                                                                                                                  
  fatal: true                                                                                                                                                                                         
}    
```

This was causing me crashes because I've initially had a `client.once('error', ...)` handler, which only caught the first error, and when the second error arrived the handler would not be attached anymore and node would terminate. 

The fix for this is easy by using `on` instead of `once`, but it makes me wonder if it is desired to expose both errors to the user. Especially because the second error is triggered as a consequence of the first error (the hostname cannot be resolved, therefore the socket gets terminated by the lib, which triggers the second error).

**Comment by mscdex** [comment]
It seems like you referenced the wrong commit? d3776f2af2e68e4485d2dbfe2f161008beb7e956 only emits an error if data is received on the socket, which wouldn't be the case when the errors are a result of a connection not being made in the first place.

**Comment by mscdex** [comment]
I believe 459ab65de7f9ad0d7214d9f0035b188f794b653a should fix this particular issue.

**Comment by mofux** [comment]
It's working, thanks!
