### ISSUE TITLE
ssh > sftp doesn't work with OpenSSH 8.0?

### ISSUE THREAD

**Issue by soichih** [mscdex/ssh2#978]
Hello.

I've been troubleshooting an issue with opening sftp channel once I establish a ssh connection on a PSC bridges2 data transfer server (data.bridges2.psc.edu). This SSH server is configured to only allow transfer related command (no interactive login).

I used to be able to do this with the old data transfer node (data.bridges.psc.edu), but the new server doesn't allow me to do this for some reason. I've compared the debug output between the 2 servers and new server (on the right) receives CHANNEL_EOF when the ssh2/sftp client tries to request for sftp

![image](https://user-images.githubusercontent.com/923896/106617013-31a0d880-653c-11eb-9286-fffafda4308c.png)

And the error message from the new server says this.

```
╭─hayashis@haswell20 ~/test/ssh2 
╰─$ node bridges2.js > bridges2.log                                                                               130 ↵
/home/hayashis/syncthing/test/ssh2/bridges2.js:13
        if(err) throw err;
                ^

Error: Received exit code 255 while establishing SFTP session
    at Channel.onExit (/home/hayashis/syncthing/test/ssh2/node_modules/ssh2/lib/client.js:904:19)
    at Object.onceWrapper (events.js:422:26)
    at Channel.emit (events.js:315:20)
    at SSH2Stream.<anonymous> (/home/hayashis/syncthing/test/ssh2/node_modules/ssh2/lib/Channel.js:210:14)
    at SSH2Stream.emit (events.js:315:20)
    at parse_CHANNEL_REQUEST (/home/hayashis/syncthing/test/ssh2/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:4467:8)
    at parsePacket (/home/hayashis/syncthing/test/ssh2/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3768:12)
    at SSH2Stream._transform (/home/hayashis/syncthing/test/ssh2/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:701:13)
    at SSH2Stream.Transform._read (_stream_transform.js:205:10)
    at SSH2Stream._read (/home/hayashis/syncthing/test/ssh2/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:253:15) {
  code: 255,
  signal: undefined
}

```

The administrator of the system insists that there are no configuration differences. The new server uses OpenSSH v8, but I believe ssh2/sftp supports OpenSSH v8?

I am using the following test code.

```
const fs = require('fs');
const Client = require('ssh2').Client;

console.log("connecting");
let conn = new Client();
conn.on('ready', function(err) {
    if(err) {
        console.error("ready does have error!");
           throw err;
    }
    console.log("connected.. now opening sftp connection");
    conn.sftp((err, sftp)=>{
        if(err) throw err;
        console.log("got sftp");
        sftp.stat("/jet/home/shayashi", (err, stat)=>{
            console.dir(stat);
        });
    });
});
conn.connect({
    //host: "data.bridges.psc.edu", //old server.. OpenSSH v7.4 (still works)
    host: "data.bridges2.psc.edu", //new server.. OpenSSH 8.0 (doesn't work)
    username: "shayashi",
    agent: process.env["SSH_AUTH_SOCK"],

    keepaliveInterval: 5*1000,
    tryKeyboard: true, //needed by stampede2

    debug: console.log,
});

```

Do you have any suggestions on how to proceed with our troubleshooting?

**Comment by mscdex** [comment]
Are you able to connect with the OpenSSH sftp client successfully and perform an sftp operation?

**Comment by soichih** [comment]
I jus checked.. 

```
╭─hayashis@haswell20 ~ 
╰─$ sftp shayashi@data.bridges2.psc.edu                                                                           255 ↵
Connection closed.  
Connection closed
╭─hayashis@haswell20 ~ 
╰─$ sftp shayashi@data.bridges.psc.edu                                                                            255 ↵
Connected to data.bridges.psc.edu.
sftp> ls
abcd-spec    bin          dest         git          interact.sh  test         tmp          workdir      
sftp> exit
```

Thanks for suggesting this. I will relay this to PSC admins.
