### ISSUE TITLE
unknown channel type: direct-tcpip

### ISSUE THREAD

**Issue by murtaja92** [mscdex/ssh2#998]
Hello, thanks for this project im trying to portforward using ssh -R 443:localhost:80 tunnel.golive.cc http
my code 

```js
const conn = new Client();

  conn.on('ready', () => {
    console.log('Client :: ready');
    conn.forwardOut('127.0.0.1', 80, '127.0.0.1', 80, (err, stream) => {
      if (err) throw err;
      stream.on('close', () => {
        console.log('TCP :: CLOSED');
        conn.end();
      }).on('data', (data) => {
        console.log('TCP :: DATA: ' + data);
      })
    });
  }).connect({
    host: 'tunnel.golive.cc',
    port: 22,
    privateKey: require('fs').readFileSync("cer.key"),
    username: ""
  });
```

response 
```
Client :: ready
C:\PROJ\NAU\app.js:41
      if (err) throw err;
               ^

Error: (SSH) Channel open failure: unknown channel type: direct-tcpip
    at SSH2Stream.onFailure (C:\PROJ\NAU\node_modules\ssh2\lib\client.js:1205:13)
    at Object.onceWrapper (events.js:422:26)
    at SSH2Stream.emit (events.js:315:20)
    at parsePacket (C:\PROJ\NAU\node_modules\ssh2-streams\lib\ssh.js:3455:10)
    at SSH2Stream._transform (C:\PROJ\NAU\node_modules\ssh2-streams\lib\ssh.js:701:13)
    at SSH2Stream.Transform._read (internal/streams/transform.js:205:10)
    at SSH2Stream._read (C:\PROJ\NAU\node_modules\ssh2-streams\lib\ssh.js:253:15)
    at SSH2Stream.Transform._write (internal/streams/transform.js:193:12)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at SSH2Stream.Writable.write (internal/streams/writable.js:303:10) {
  reason: 'UNKNOWN_CHANNEL_TYPE',
  lang: 'en'
```

PLEASE HELP

**Comment by mscdex** [comment]
It means either the server doesn't understand outbound TCP/IP connection forwarding or it's denying such requests.

**Comment by murtaja92** [comment]
Thank you!
